import type { BiomeId,Element,EquipmentItem,EquipmentSlot,EquipmentStats,InventoryItem,MapManifest,MerchantState,PlayerEquipment,SpellPlan } from './contracts';
import { createRng } from './map';
import {generateScroll,scrollDefinition} from './scrolls';

type Prototype={id:string;name:string;slot:EquipmentSlot;biome:BiomeId;mechanicId:string;description:string;base:EquipmentStats};
const stats=(values:Partial<Omit<EquipmentStats,'elementPower'>>&{elementPower?:Partial<Record<Element,number>>}={}):EquipmentStats=>({elementPower:{...(values.elementPower??{})},castSpeed:values.castSpeed??0,areaPower:values.areaPower??0,damageReduction:values.damageReduction??0,moveSpeed:values.moveSpeed??0});
const PROTOTYPES:readonly Prototype[]=[
 {id:'rune-staff',name:'符文法杖',slot:'staff',biome:'ruins',mechanicId:'rock-affinity',description:'强化岩元素伤害',base:stats({elementPower:{rock:.1}})},{id:'echo-staff',name:'回响法杖',slot:'staff',biome:'ruins',mechanicId:'lightning-affinity',description:'强化雷元素伤害',base:stats({elementPower:{lightning:.1}})},{id:'ward-robe',name:'守卫法袍',slot:'robe',biome:'ruins',mechanicId:'damage-guard',description:'稳定降低受到的伤害',base:stats({damageReduction:.1})},{id:'path-robe',name:'巡礼法袍',slot:'robe',biome:'ruins',mechanicId:'swift-step',description:'提高移动速度',base:stats({moveSpeed:.1})},{id:'sigil-ring',name:'钥印戒指',slot:'ring',biome:'ruins',mechanicId:'area-focus',description:'扩大法术生效范围',base:stats({areaPower:.1})},{id:'rescue-ring',name:'援护戒指',slot:'ring',biome:'ruins',mechanicId:'quick-cast',description:'缩短法术释放前摇',base:stats({castSpeed:.08})},
 {id:'reed-staff',name:'芦苇法杖',slot:'staff',biome:'swamp',mechanicId:'water-affinity',description:'强化水元素伤害',base:stats({elementPower:{water:.13}})},{id:'spore-staff',name:'孢子法杖',slot:'staff',biome:'swamp',mechanicId:'life-affinity',description:'强化含生命元素法术的治疗',base:stats({elementPower:{life:.13}})},{id:'bog-robe',name:'涉沼法袍',slot:'robe',biome:'swamp',mechanicId:'swift-step',description:'提高移动速度',base:stats({moveSpeed:.12})},{id:'insulated-robe',name:'绝缘法袍',slot:'robe',biome:'swamp',mechanicId:'damage-guard',description:'稳定降低受到的伤害',base:stats({damageReduction:.12})},{id:'storm-ring',name:'雷蛙戒指',slot:'ring',biome:'swamp',mechanicId:'quick-cast',description:'缩短法术释放前摇',base:stats({castSpeed:.11})},{id:'root-ring',name:'活根戒指',slot:'ring',biome:'swamp',mechanicId:'area-focus',description:'扩大法术生效范围',base:stats({areaPower:.13})},
 {id:'cinder-staff',name:'烬火法杖',slot:'staff',biome:'volcano',mechanicId:'fire-affinity',description:'强化火元素伤害',base:stats({elementPower:{fire:.16}})},{id:'frostcore-staff',name:'霜核法杖',slot:'staff',biome:'volcano',mechanicId:'ice-affinity',description:'强化冰元素伤害',base:stats({elementPower:{ice:.15}})},{id:'obsidian-robe',name:'黑曜法袍',slot:'robe',biome:'volcano',mechanicId:'damage-guard',description:'稳定降低受到的伤害',base:stats({damageReduction:.14})},{id:'ash-robe',name:'灰行法袍',slot:'robe',biome:'volcano',mechanicId:'swift-step',description:'提高移动速度',base:stats({moveSpeed:.14})},{id:'magma-ring',name:'熔核戒指',slot:'ring',biome:'volcano',mechanicId:'area-focus',description:'扩大法术生效范围',base:stats({areaPower:.16})},{id:'cooling-ring',name:'冷却戒指',slot:'ring',biome:'volcano',mechanicId:'quick-cast',description:'缩短法术释放前摇',base:stats({castSpeed:.14})}
];
const ELEMENT_NAMES:Record<Element,string>={rock:'岩',fire:'火',ice:'冰',life:'生命',lightning:'雷',water:'水',shield:'盾'};

export function generateEquipment(seed:number,index:number,biome:BiomeId='ruins'):EquipmentItem{const random=createRng((seed^Math.imul(index+1,0x9e3779b1))>>>0),pool=PROTOTYPES.filter(p=>p.biome===biome),prototype=pool[Math.floor(random()*pool.length)]!,rarityRoll=random(),rarity=rarityRoll>.86?'rare':rarityRoll>.5?'uncommon':'common',affixCount=rarity==='rare'?2:rarity==='uncommon'?1:0,itemStats=cloneStats(prototype.base),affixes:string[]=[];for(let i=0;i<affixCount;i++){const value=.04+random()*.04;if(prototype.slot==='staff'){const element=Object.keys(itemStats.elementPower)[0] as Element;itemStats.elementPower[element]=(itemStats.elementPower[element]??0)+value;affixes.push(`${ELEMENT_NAMES[element]}共鸣 +${Math.round(value*100)}%`);}else if(prototype.slot==='robe'){const key=random()<.5?'damageReduction':'moveSpeed';itemStats[key]+=value;affixes.push(`${key==='damageReduction'?'坚韧':'轻盈'} +${Math.round(value*100)}%`);}else{const key=random()<.5?'castSpeed':'areaPower';itemStats[key]+=value;affixes.push(`${key==='castSpeed'?'咏唱':'广域'} +${Math.round(value*100)}%`);}}return{id:`item:${seed.toString(36)}:${index}`,prototypeId:prototype.id,name:prototype.name,slot:prototype.slot,rarity,stats:roundStats(itemStats),affixes,biome:prototype.biome,mechanicId:prototype.mechanicId,description:prototype.description};}
export function equipmentBonuses(equipment:PlayerEquipment){const result=stats();for(const item of Object.values(equipment))if(item){for(const [element,value] of Object.entries(item.stats.elementPower) as Array<[Element,number]>)result.elementPower[element]=(result.elementPower[element]??0)+value;result.castSpeed+=item.stats.castSpeed;result.areaPower+=item.stats.areaPower;result.damageReduction+=item.stats.damageReduction;result.moveSpeed+=item.stats.moveSpeed;}return roundStats(result);}
export function applyEquipmentToSpell(plan:SpellPlan,equipment:PlayerEquipment):SpellPlan{const bonus=equipmentBonuses(equipment),castSpeed=Math.min(.65,bonus.castSpeed),areaPower=Math.min(.5,bonus.areaPower),lifePower=bonus.elementPower.life??0;let next:SpellPlan={...plan,castMs:Math.max(40,Math.round(plan.castMs*(1-castSpeed))),effects:plan.effects.map(effect=>effect.type==='damage'?{...effect,amount:Math.round(effect.amount*(1+(bonus.elementPower[effect.element]??0)))}:effect.type==='heal'&&plan.elements.includes('life')?{...effect,amount:Math.round(effect.amount*(1+lifePower))}:effect)};if(!areaPower||plan.delivery==='global')return next;const scale=1+areaPower,effects=next.effects.map(effect=>effect.type==='environment'&&effect.radius!=null?{...effect,radius:Math.round(effect.radius*scale)}:effect);if(plan.delivery==='cone')next={...next,range:Math.round(next.range*scale),coneAngle:next.coneAngle*scale,effects};else if(plan.delivery==='beam'||plan.delivery==='projectile'||plan.delivery==='targeted'||plan.delivery==='area'||plan.delivery==='self')next={...next,radius:Math.round(next.radius*scale),effects};return next;}
export function createMerchant(map:MapManifest,stageIndex:number):MerchantState{const event=map.events.find(e=>e.kind==='merchant'),room=map.rooms.find(r=>r.id===event?.roomId)??map.rooms[1]!,stock:MerchantState['stock']=[0,1,2].map(i=>{const sourceBiome=i===2&&stageIndex>0?(stageIndex===1?'ruins':'swamp'):map.biome,item=generateEquipment(map.stageSeed^0x6d657263,stageIndex*10+i,sourceBiome);return{item,price:item.rarity==='rare'?95:item.rarity==='uncommon'?60:35};}),scroll=generateScroll(map.stageSeed,`merchant:${stageIndex}`,'merchant');if(scroll)stock.push({item:scroll,price:scrollDefinition(scroll.spellId)!.price});return{id:`merchant:${stageIndex}`,roomId:room.id,x:room.x+room.width/2,y:room.y+room.height/2,stock};}
export function canEquip(inventory:readonly InventoryItem[],itemId:string){return inventory.some(item=>item.id===itemId&&!isScrollLike(item));}
function isScrollLike(item:InventoryItem){return'kind'in item&&item.kind==='scroll';}
function cloneStats(value:EquipmentStats):EquipmentStats{return{...value,elementPower:{...value.elementPower}};}
function roundStats(value:EquipmentStats):EquipmentStats{return{...value,elementPower:Object.fromEntries(Object.entries(value.elementPower).map(([k,v])=>[k,Math.round(v*1000)/1000])),castSpeed:Math.round(value.castSpeed*1000)/1000,areaPower:Math.round(value.areaPower*1000)/1000,damageReduction:Math.round(value.damageReduction*1000)/1000,moveSpeed:Math.round(value.moveSpeed*1000)/1000};}
