import type { BiomeId,CatalystItem,Element,EquipmentAffix,EquipmentItem,EquipmentSlot,EquipmentStats,InventoryItem,MapManifest,MerchantState,PlayerEquipment,SpellPlan } from './contracts';
import { createRng } from './map';
import {generateScroll,scrollDefinition} from './scrolls';

type Prototype={id:string;name:string;slot:EquipmentSlot;biome:BiomeId;mechanicId:string;description:string;base:EquipmentStats};
const stats=(values:Partial<Omit<EquipmentStats,'elementPower'|'recipePower'>>&{elementPower?:Partial<Record<Element,number>>;recipePower?:Record<string,number>}={}):EquipmentStats=>({elementPower:{...(values.elementPower??{})},recipePower:{...(values.recipePower??{})},castSpeed:values.castSpeed??0,areaPower:values.areaPower??0,damageReduction:values.damageReduction??0,moveSpeed:values.moveSpeed??0,tenacity:values.tenacity??0,combatVision:values.combatVision??0});
const PROTOTYPES:readonly Prototype[]=[
 {id:'rune-staff',name:'符文法杖',slot:'staff',biome:'ruins',mechanicId:'rock-affinity',description:'强化岩元素伤害',base:stats({elementPower:{rock:.1}})},{id:'echo-staff',name:'回响法杖',slot:'staff',biome:'ruins',mechanicId:'lightning-affinity',description:'强化雷元素伤害',base:stats({elementPower:{lightning:.1}})},{id:'ward-robe',name:'守卫法袍',slot:'robe',biome:'ruins',mechanicId:'damage-guard',description:'稳定降低受到的伤害',base:stats({damageReduction:.1})},{id:'path-robe',name:'巡礼法袍',slot:'robe',biome:'ruins',mechanicId:'swift-step',description:'提高移动速度',base:stats({moveSpeed:.1})},{id:'sigil-ring',name:'钥印戒指',slot:'ring',biome:'ruins',mechanicId:'area-focus',description:'扩大法术生效范围',base:stats({areaPower:.1})},{id:'rescue-ring',name:'援护戒指',slot:'ring',biome:'ruins',mechanicId:'quick-cast',description:'缩短法术释放前摇',base:stats({castSpeed:.08})},
 {id:'reed-staff',name:'芦苇法杖',slot:'staff',biome:'swamp',mechanicId:'water-affinity',description:'强化水元素伤害',base:stats({elementPower:{water:.13}})},{id:'spore-staff',name:'孢子法杖',slot:'staff',biome:'swamp',mechanicId:'life-affinity',description:'强化含生命元素法术的治疗',base:stats({elementPower:{life:.13}})},{id:'bog-robe',name:'涉沼法袍',slot:'robe',biome:'swamp',mechanicId:'swift-step',description:'提高移动速度',base:stats({moveSpeed:.12})},{id:'insulated-robe',name:'绝缘法袍',slot:'robe',biome:'swamp',mechanicId:'damage-guard',description:'稳定降低受到的伤害',base:stats({damageReduction:.12})},{id:'storm-ring',name:'雷蛙戒指',slot:'ring',biome:'swamp',mechanicId:'quick-cast',description:'缩短法术释放前摇',base:stats({castSpeed:.11})},{id:'root-ring',name:'活根戒指',slot:'ring',biome:'swamp',mechanicId:'area-focus',description:'扩大法术生效范围',base:stats({areaPower:.13})},
 {id:'cinder-staff',name:'烬火法杖',slot:'staff',biome:'volcano',mechanicId:'fire-affinity',description:'强化火元素伤害',base:stats({elementPower:{fire:.16}})},{id:'frostcore-staff',name:'霜核法杖',slot:'staff',biome:'volcano',mechanicId:'ice-affinity',description:'强化冰元素伤害',base:stats({elementPower:{ice:.15}})},{id:'obsidian-robe',name:'黑曜法袍',slot:'robe',biome:'volcano',mechanicId:'damage-guard',description:'稳定降低受到的伤害',base:stats({damageReduction:.14})},{id:'ash-robe',name:'灰行法袍',slot:'robe',biome:'volcano',mechanicId:'swift-step',description:'提高移动速度',base:stats({moveSpeed:.14})},{id:'magma-ring',name:'熔核戒指',slot:'ring',biome:'volcano',mechanicId:'area-focus',description:'扩大法术生效范围',base:stats({areaPower:.16})},{id:'cooling-ring',name:'冷却戒指',slot:'ring',biome:'volcano',mechanicId:'quick-cast',description:'缩短法术释放前摇',base:stats({castSpeed:.14})}
];
const ELEMENT_NAMES:Record<Element,string>={rock:'岩',fire:'火',ice:'冰',life:'生命',lightning:'雷',water:'水',shield:'盾'};
const NON_SHIELD:Exclude<Element,'shield'>[]=['rock','fire','ice','life','lightning','water'];

function randomAffix(slot:EquipmentSlot,random:()=>number,base:EquipmentStats):EquipmentAffix{const level=random()>.82?2:1;if(slot==='staff'){if(random()<.24)return{id:'recipe-power',slot,level,value:.12*level,recipeId:['meteor','storm-chain','ice-lance','flamethrower'][Math.floor(random()*4)]!};const element=(Object.keys(base.elementPower)[0] as Element|undefined)??NON_SHIELD[Math.floor(random()*NON_SHIELD.length)]!;return{id:'element-power',slot,level,value:(.04+random()*.04)*level,element};}if(slot==='robe'){const roll=random();if(roll<.18)return{id:'stealth',slot,level:1,value:1};if(roll<.42)return{id:'tenacity',slot,level,value:.12*level};if(roll<.64)return{id:'element-immunity',slot,level:1,value:1,element:NON_SHIELD[Math.floor(random()*NON_SHIELD.length)]!,exclusiveGroup:'element-immunity'};if(roll<.82)return{id:'damage-reduction',slot,level,value:.04*level};return{id:'move-speed',slot,level,value:.04*level};}const roll=random();if(roll<.2)return{id:'beam-reflect',slot,level,value:level,exclusiveGroup:'beam-path'};if(roll<.38)return{id:'beam-pierce',slot,level:1,value:1,exclusiveGroup:'beam-path'};if(roll<.58)return{id:'combat-vision',slot,level,value:.08*level};if(roll<.79)return{id:'cast-speed',slot,level,value:.04*level};return{id:'area-power',slot,level,value:.05*level};}
function applyAffix(s:EquipmentStats,a:EquipmentAffix){if(a.id==='element-power'&&a.element)s.elementPower[a.element]=(s.elementPower[a.element]??0)+a.value;else if(a.id==='recipe-power'&&a.recipeId)s.recipePower[a.recipeId]=(s.recipePower[a.recipeId]??0)+a.value;else if(a.id==='tenacity')s.tenacity+=a.value;else if(a.id==='combat-vision')s.combatVision+=a.value;else if(a.id==='cast-speed')s.castSpeed+=a.value;else if(a.id==='area-power')s.areaPower+=a.value;else if(a.id==='damage-reduction')s.damageReduction+=a.value;else if(a.id==='move-speed')s.moveSpeed+=a.value;}
export function generateEquipment(seed:number,index:number,biome:BiomeId='ruins'):EquipmentItem{const random=createRng((seed^Math.imul(index+1,0x9e3779b1))>>>0),pool=PROTOTYPES.filter(p=>p.biome===biome),prototype=pool[Math.floor(random()*pool.length)]!,rarityRoll=random(),rarity=rarityRoll>.86?'rare':rarityRoll>.5?'uncommon':'common',affixCount=rarity==='rare'?2:rarity==='uncommon'?1:0,itemStats=cloneStats(prototype.base),affixes:EquipmentAffix[]=[];for(let i=0;i<affixCount;i++){const candidate=randomAffix(prototype.slot,random,itemStats);if(candidate.exclusiveGroup&&affixes.some(a=>a.exclusiveGroup===candidate.exclusiveGroup)){i--;continue;}affixes.push(candidate);applyAffix(itemStats,candidate);}const value=rarity==='rare'?95:rarity==='uncommon'?60:35;return{id:`item:${seed.toString(36)}:${index}`,prototypeId:prototype.id,name:prototype.name,slot:prototype.slot,rarity,stats:roundStats(itemStats),affixes,biome:prototype.biome,mechanicId:prototype.mechanicId,description:prototype.description,value,fusionGeneration:0,sourceItemValues:[value]};}
export function createCatalyst(seed:number,source:string):CatalystItem{return{id:`catalyst:${seed.toString(36)}:${source}`,kind:'catalyst',name:'稳定符文',description:'合成时保留全部合法词条'};}
export function isCatalyst(item:InventoryItem):item is CatalystItem{return'kind'in item&&item.kind==='catalyst';}
export function isEquipment(item:InventoryItem):item is EquipmentItem{return!('kind'in item);}
export function affixText(a:EquipmentAffix){if(a.id==='element-power')return`${ELEMENT_NAMES[a.element!]}共鸣 +${Math.round(a.value*100)}%`;if(a.id==='recipe-power')return`${a.recipeId}威力 +${Math.round(a.value*100)}%`;if(a.id==='stealth')return'隐身';if(a.id==='tenacity')return`韧性 +${Math.round(a.value*100)}%`;if(a.id==='element-immunity')return`${ELEMENT_NAMES[a.element!]}元素法袍`;if(a.id==='beam-reflect')return`射线反射 ${a.level}次`;if(a.id==='beam-pierce')return'射线穿透';if(a.id==='combat-vision')return`战斗视野 +${Math.round(a.value*100)}%`;const names={ 'cast-speed':'咏唱','area-power':'广域','damage-reduction':'坚韧','move-speed':'轻盈'};return`${names[a.id]} +${Math.round(a.value*100)}%`;}
export function hasAffix(item:EquipmentItem|null|undefined,id:EquipmentAffix['id']){return item?.affixes.find(a=>a.id===id);}
export function fuseEquipment(items:readonly EquipmentItem[],seed:number,stabilized=false):EquipmentItem|null{if((stabilized?items.length!==2:items.length!==3)||new Set(items.map(i=>i.slot)).size!==1)return null;const random=createRng(seed>>>0),legal:EquipmentAffix[]=[];for(const source of items)for(const affix of source.affixes){const existing=legal.find(a=>a.id===affix.id&&a.element===affix.element&&a.recipeId===affix.recipeId);if(existing){existing.level=Math.min(3,existing.level+affix.level);existing.value=Math.max(existing.value,affix.value);continue;}if(affix.exclusiveGroup&&legal.some(a=>a.exclusiveGroup===affix.exclusiveGroup))continue;legal.push({...affix});}let kept=legal.filter(()=>stabilized||random()<.7);if(!kept.length&&legal.length)kept=[legal[Math.floor(random()*legal.length)]!];kept=kept.slice(0,4);const base=stats();for(const element of NON_SHIELD)base.elementPower[element]=Math.max(...items.map(i=>i.stats.elementPower[element]??0))*1.2;for(const key of ['castSpeed','areaPower','damageReduction','moveSpeed','tenacity','combatVision'] as const)base[key]=Math.max(...items.map(i=>i.stats[key]))*1.2;for(const recipeId of new Set(items.flatMap(i=>Object.keys(i.stats.recipePower))))base.recipePower[recipeId]=Math.max(...items.map(i=>i.stats.recipePower[recipeId]??0))*1.2;const rarity=items.some(i=>i.rarity!=='common')?'rare':'uncommon',value=items.reduce((n,i)=>n+i.value,0),generation=Math.max(...items.map(i=>i.fusionGeneration))+1;return{id:`fusion:${seed.toString(36)}:${items.map(i=>i.id).join(':')}`,prototypeId:items[0]!.prototypeId,name:`熔铸${items[0]!.name}`,slot:items[0]!.slot,rarity,stats:roundStats(base),affixes:kept,biome:items[0]!.biome,mechanicId:'fusion',description:stabilized?'两件装备与稳定符文熔铸而成':'三件装备熔铸而成',value,fusionGeneration:generation,sourceItemValues:items.flatMap(i=>i.sourceItemValues)};}
export function sellPrice(item:InventoryItem){return isEquipment(item)?Math.floor(item.value*.5):0;}
export function equipmentBonuses(equipment:PlayerEquipment){const result=stats();for(const item of Object.values(equipment))if(item){for(const [element,value] of Object.entries(item.stats.elementPower) as Array<[Element,number]>)result.elementPower[element]=(result.elementPower[element]??0)+value;for(const [id,value] of Object.entries(item.stats.recipePower))result.recipePower[id]=(result.recipePower[id]??0)+value;result.castSpeed+=item.stats.castSpeed;result.areaPower+=item.stats.areaPower;result.damageReduction+=item.stats.damageReduction;result.moveSpeed+=item.stats.moveSpeed;result.tenacity+=item.stats.tenacity;result.combatVision+=item.stats.combatVision;}return roundStats(result);}
export function applyEquipmentToSpell(plan:SpellPlan,equipment:PlayerEquipment):SpellPlan{const bonus=equipmentBonuses(equipment),castSpeed=Math.min(.65,bonus.castSpeed),areaPower=Math.min(.5,bonus.areaPower),lifePower=bonus.elementPower.life??0,recipePower=bonus.recipePower[plan.id]??0,beamPierce=plan.delivery==='beam'?(hasAffix(equipment.ring,'beam-pierce')?.value??0):0;let next:SpellPlan={...plan,pierce:plan.pierce+beamPierce,castMs:Math.max(40,Math.round(plan.castMs*(1-castSpeed))),effects:plan.effects.map(effect=>effect.type==='damage'?{...effect,amount:Math.round(effect.amount*(1+(bonus.elementPower[effect.element]??0)+recipePower))}:effect.type==='heal'&&plan.elements.includes('life')?{...effect,amount:Math.round(effect.amount*(1+lifePower+recipePower))}:effect)};if(!areaPower||plan.delivery==='global')return next;const scale=1+areaPower,effects=next.effects.map(effect=>effect.type==='environment'&&effect.radius!=null?{...effect,radius:Math.round(effect.radius*scale)}:effect);if(plan.delivery==='cone')next={...next,range:Math.round(next.range*scale),coneAngle:next.coneAngle*scale,effects};else if(plan.delivery==='beam'||plan.delivery==='projectile'||plan.delivery==='targeted'||plan.delivery==='area'||plan.delivery==='self')next={...next,radius:Math.round(next.radius*scale),effects};return next;}
export function createMerchant(map:MapManifest,stageIndex:number):MerchantState{const event=map.events.find(e=>e.kind==='merchant'),room=map.rooms.find(r=>r.id===event?.roomId)??map.rooms[1]!,stock:MerchantState['stock']=[0,1,2].map(i=>{const sourceBiome=i===2&&stageIndex>0?(stageIndex===1?'ruins':'swamp'):map.biome,item=generateEquipment(map.stageSeed^0x6d657263,stageIndex*10+i,sourceBiome);return{item,price:item.value};}),scroll=generateScroll(map.stageSeed,`merchant:${stageIndex}`,'merchant');if(scroll)stock.push({item:scroll,price:scrollDefinition(scroll.spellId)!.price});if(createRng(map.stageSeed^0x73746162)()<.25)stock.push({item:createCatalyst(map.stageSeed,'merchant'),price:80});return{id:`merchant:${stageIndex}`,roomId:room.id,x:room.x+room.width/2,y:room.y+room.height/2,stock};}
export function canEquip(inventory:readonly InventoryItem[],itemId:string){return inventory.some(item=>item.id===itemId&&isEquipment(item));}
function cloneStats(value:EquipmentStats):EquipmentStats{return{...value,elementPower:{...value.elementPower},recipePower:{...value.recipePower}};}
function roundStats(value:EquipmentStats):EquipmentStats{return{...value,elementPower:Object.fromEntries(Object.entries(value.elementPower).filter(([,v])=>v>0).map(([k,v])=>[k,Math.round(v*1000)/1000])),recipePower:Object.fromEntries(Object.entries(value.recipePower).map(([k,v])=>[k,Math.round(v*1000)/1000])),castSpeed:Math.round(value.castSpeed*1000)/1000,areaPower:Math.round(value.areaPower*1000)/1000,damageReduction:Math.round(value.damageReduction*1000)/1000,moveSpeed:Math.round(value.moveSpeed*1000)/1000,tenacity:Math.round(value.tenacity*1000)/1000,combatVision:Math.round(value.combatVision*1000)/1000};}
