import { describe,expect,it } from 'vitest';
import type { Element,EquipmentItem,EquipmentSlot,EquipmentStats,PlayerEquipment,SpellPlan } from './contracts';
import { applyEquipmentToSpell,canEquip,createMerchant,equipmentBonuses,fuseEquipment,generateEquipment,sellPrice } from './equipment';
import { generateMap } from './map';

const emptyStats=():EquipmentStats=>({elementPower:{},recipePower:{},castSpeed:0,areaPower:0,damageReduction:0,moveSpeed:0,tenacity:0,combatVision:0});
const item=(slot:EquipmentSlot,stats:EquipmentStats):EquipmentItem=>({id:`test:${slot}`,prototypeId:`test-${slot}`,name:'测试装备',slot,rarity:'common',stats,affixes:[],biome:'ruins',mechanicId:'test',description:'test',value:35,fusionGeneration:0,sourceItemValues:[35]});
const equipment=(slot:EquipmentSlot,stats:EquipmentStats):PlayerEquipment=>({staff:null,robe:null,ring:null,[slot]:item(slot,stats)});
const plan=(delivery:SpellPlan['delivery'],values:Partial<SpellPlan>={}):SpellPlan=>({id:'test',name:'测试法术',elements:['fire','rock'],delivery,castMs:200,channel:false,range:600,radius:100,effects:[{type:'damage',element:'fire',amount:20},{type:'damage',element:'rock',amount:20},{type:'environment',kind:'steam',durationMs:1000,radius:80}],pierce:0,tickMs:100,recoveryMs:100,projectileSpeed:600,coneAngle:1,traits:[],...values});

describe('equipment economy',()=>{
 it('generates stable item prototypes and affixes from a seed',()=>{expect(generateEquipment(42,3)).toEqual(generateEquipment(42,3));expect(generateEquipment(42,3).id).not.toBe(generateEquipment(42,4).id);});
 it('keeps every generated stat inside its slot identity',()=>{for(const biome of ['ruins','swamp','volcano'] as const)for(let i=0;i<80;i++){const generated=generateEquipment(10,i,biome),s=generated.stats;expect(generated.biome).toBe(biome);if(generated.slot==='staff'){expect(Object.keys(s.elementPower)).toHaveLength(1);expect(s.castSpeed+s.areaPower+s.damageReduction+s.moveSpeed).toBe(0);}if(generated.slot==='robe'){expect(Object.keys(s.elementPower)).toHaveLength(0);expect(s.castSpeed+s.areaPower).toBe(0);}if(generated.slot==='ring'){expect(Object.keys(s.elementPower)).toHaveLength(0);expect(s.damageReduction+s.moveSpeed).toBe(0);}}});
 it('covers six staff affinities across the themed prototype pools',()=>{const affinities=new Set<Element>();for(const biome of ['ruins','swamp','volcano'] as const)for(let seed=1;seed<=200;seed++){const generated=generateEquipment(seed,seed%17,biome);if(generated.slot==='staff')Object.keys(generated.stats.elementPower).forEach(value=>affinities.add(value as Element));}expect(affinities).toEqual(new Set(['rock','lightning','water','life','fire','ice']));});
 it('combines element and robe bonuses',()=>{const staff=item('staff',{...emptyStats(),elementPower:{fire:.2}}),robe=item('robe',{...emptyStats(),damageReduction:.2,moveSpeed:.1}),bonuses=equipmentBonuses({staff,robe,ring:null});expect(bonuses.elementPower.fire).toBe(.2);expect(bonuses.damageReduction).toBe(.2);expect(bonuses.moveSpeed).toBe(.1);});
 it('only boosts matching damage components and life healing',()=>{const fire=applyEquipmentToSpell(plan('targeted'),equipment('staff',{...emptyStats(),elementPower:{fire:.5}}));expect(fire.effects.filter(e=>e.type==='damage').map(e=>e.amount)).toEqual([30,20]);const healing=applyEquipmentToSpell(plan('targeted',{elements:['life'],effects:[{type:'heal',amount:40}]}),equipment('staff',{...emptyStats(),elementPower:{life:.25}}));expect(healing.effects[0]).toEqual({type:'heal',amount:50});});
 it('applies smart area scaling and caps cast and area bonuses',()=>{const ring=equipment('ring',{...emptyStats(),castSpeed:.9,areaPower:.9});const cone=applyEquipmentToSpell(plan('cone'),ring);expect(cone.castMs).toBe(70);expect(cone.range).toBe(900);expect(cone.coneAngle).toBe(1.5);const beam=applyEquipmentToSpell(plan('beam'),ring);expect(beam.radius).toBe(150);expect(beam.range).toBe(600);const projectile=applyEquipmentToSpell(plan('projectile'),ring);expect(projectile.radius).toBe(150);expect(projectile.range).toBe(600);const global=applyEquipmentToSpell(plan('global'),ring);expect(global.radius).toBe(100);expect(global.effects[2]).toMatchObject({radius:80});});
 it('creates deterministic merchant stock and checks inventory ownership',()=>{const merchant=createMerchant(generateMap(7),0);expect(merchant.stock.length).toBeGreaterThanOrEqual(3);expect(createMerchant(generateMap(7),0)).toEqual(merchant);expect(canEquip([merchant.stock[0]!.item],merchant.stock[0]!.item.id)).toBe(true);});
 it('only fuses three matching slots and preserves every legal affix with a catalyst',()=>{const inputs=[1,2,3].map(i=>generateEquipment(44,i)).filter(v=>v.slot==='staff');while(inputs.length<3)inputs.push(item('staff',{...emptyStats(),elementPower:{fire:.1*inputs.length}}));expect(fuseEquipment([inputs[0]!,item('robe',emptyStats()),inputs[1]!],5)).toBeNull();const result=fuseEquipment(inputs.slice(0,3),5,true)!;expect(result.slot).toBe('staff');expect(result.fusionGeneration).toBe(1);expect(result.value).toBe(inputs.slice(0,3).reduce((n,v)=>n+v.value,0));expect(result.affixes.length).toBeLessThanOrEqual(4);expect(sellPrice(result)).toBe(Math.floor(result.value/2));});
});
