import type { BiomeId,EquipmentItem,EquipmentSlot,EquipmentStats,MapManifest,MerchantState,PlayerEquipment } from './contracts';
import { createRng } from './map';
type Prototype={id:string;name:string;slot:EquipmentSlot;biome:BiomeId;mechanicId:string;description:string;base:Partial<EquipmentStats>};
const PROTOTYPES:readonly Prototype[]=[
 {id:'rune-staff',name:'符文法杖',slot:'staff',biome:'ruins',mechanicId:'control-power',description:'控制法术同时强化伤害',base:{spellPower:.1}},{id:'echo-staff',name:'回响法杖',slot:'staff',biome:'ruins',mechanicId:'quick-cast',description:'连续施法更轻快',base:{castSpeed:.12}},{id:'ward-robe',name:'守卫法袍',slot:'robe',biome:'ruins',mechanicId:'ward',description:'护盾破裂后短暂减伤',base:{damageReduction:.11}},{id:'path-robe',name:'巡礼法袍',slot:'robe',biome:'ruins',mechanicId:'pathing',description:'穿越走廊时移动更快',base:{moveSpeed:.1}},{id:'sigil-ring',name:'钥印戒指',slot:'ring',biome:'ruins',mechanicId:'sigil',description:'目标房内提高法术威力',base:{spellPower:.07,castSpeed:.04}},{id:'rescue-ring',name:'援护戒指',slot:'ring',biome:'ruins',mechanicId:'rescue',description:'强化治疗与救援',base:{castSpeed:.08}},
 {id:'reed-staff',name:'芦苇法杖',slot:'staff',biome:'swamp',mechanicId:'wet-power',description:'对潮湿目标提高伤害',base:{spellPower:.13}},{id:'spore-staff',name:'孢子法杖',slot:'staff',biome:'swamp',mechanicId:'area-duration',description:'延长区域法术',base:{castSpeed:.11}},{id:'bog-robe',name:'涉沼法袍',slot:'robe',biome:'swamp',mechanicId:'mud-walk',description:'减轻泥地与毒水影响',base:{moveSpeed:.12}},{id:'insulated-robe',name:'绝缘法袍',slot:'robe',biome:'swamp',mechanicId:'grounding',description:'降低导电伤害',base:{damageReduction:.12}},{id:'storm-ring',name:'雷蛙戒指',slot:'ring',biome:'swamp',mechanicId:'chain-lightning',description:'强化潮湿感电反应',base:{spellPower:.09}},{id:'root-ring',name:'活根戒指',slot:'ring',biome:'swamp',mechanicId:'zone-heal',description:'区域中持续恢复',base:{moveSpeed:.06,damageReduction:.05}},
 {id:'cinder-staff',name:'烬火法杖',slot:'staff',biome:'volcano',mechanicId:'burn-burst',description:'燃烧叠层转化为爆发',base:{spellPower:.15}},{id:'frostcore-staff',name:'霜核法杖',slot:'staff',biome:'volcano',mechanicId:'overheat-break',description:'冰水岩更快削减过热',base:{castSpeed:.12}},{id:'obsidian-robe',name:'黑曜法袍',slot:'robe',biome:'volcano',mechanicId:'lava-guard',description:'降低熔岩与落石伤害',base:{damageReduction:.14}},{id:'ash-robe',name:'灰行法袍',slot:'robe',biome:'volcano',mechanicId:'safe-sprint',description:'转移安全区时加速',base:{moveSpeed:.14}},{id:'magma-ring',name:'熔核戒指',slot:'ring',biome:'volcano',mechanicId:'low-health-power',description:'低生命时提高威力',base:{spellPower:.1,damageReduction:.04}},{id:'cooling-ring',name:'冷却戒指',slot:'ring',biome:'volcano',mechanicId:'rune-channel',description:'更快激活冷却符文',base:{castSpeed:.1,moveSpeed:.05}}
];
const AFFIXES=[{name:'强能',stat:'spellPower' as const,min:.04,max:.1},{name:'咏唱',stat:'castSpeed' as const,min:.04,max:.1},{name:'坚韧',stat:'damageReduction' as const,min:.04,max:.08},{name:'轻盈',stat:'moveSpeed' as const,min:.04,max:.09}],ZERO:EquipmentStats={spellPower:0,castSpeed:0,damageReduction:0,moveSpeed:0};
export function generateEquipment(seed:number,index:number,biome:BiomeId='ruins'):EquipmentItem{const random=createRng((seed^Math.imul(index+1,0x9e3779b1))>>>0),pool=PROTOTYPES.filter(p=>p.biome===biome),prototype=pool[Math.floor(random()*pool.length)]!,rarityRoll=random(),rarity=rarityRoll>.86?'rare':rarityRoll>.5?'uncommon':'common',affixCount=rarity==='rare'?2:rarity==='uncommon'?1:0,stats={...ZERO,...prototype.base},affixes:string[]=[];for(const affix of shuffle([...AFFIXES],random).slice(0,affixCount)){const value=affix.min+(affix.max-affix.min)*random();stats[affix.stat]+=value;affixes.push(`${affix.name} +${Math.round(value*100)}%`);}return{id:`item:${seed.toString(36)}:${index}`,prototypeId:prototype.id,name:prototype.name,slot:prototype.slot,rarity,stats:roundStats(stats),affixes,biome:prototype.biome,mechanicId:prototype.mechanicId,description:prototype.description};}
export function equipmentBonuses(equipment:PlayerEquipment){const result={...ZERO};for(const item of Object.values(equipment))if(item)for(const key of Object.keys(result)as Array<keyof EquipmentStats>)result[key]+=item.stats[key];return roundStats(result);}
export function createMerchant(map:MapManifest,stageIndex:number):MerchantState{const event=map.events.find(e=>e.kind==='merchant'),room=map.rooms.find(r=>r.id===event?.roomId)??map.rooms[1]!,stock=[0,1,2].map(i=>{const sourceBiome=i===2&&stageIndex>0?(stageIndex===1?'ruins':'swamp'):map.biome,item=generateEquipment(map.stageSeed^0x6d657263,stageIndex*10+i,sourceBiome);return{item,price:item.rarity==='rare'?95:item.rarity==='uncommon'?60:35};});return{id:`merchant:${stageIndex}`,roomId:room.id,x:room.x+room.width/2,y:room.y+room.height/2,stock};}
export function canEquip(inventory:readonly EquipmentItem[],itemId:string){return inventory.some(item=>item.id===itemId);}
function roundStats(stats:EquipmentStats){return Object.fromEntries(Object.entries(stats).map(([k,v])=>[k,Math.round(v*1000)/1000])) as EquipmentStats;}function shuffle<T>(values:T[],random:()=>number){for(let i=values.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[values[i],values[j]]=[values[j]!,values[i]!];}return values;}
