import { describe,expect,it } from 'vitest';
import { generateMap,isWalkable,mapFingerprint,moveWithinMap,roomAt } from './map';

describe('deterministic map generation',()=>{
 it('repeats exactly for the same seed and changes for another seed',()=>{expect(mapFingerprint(generateMap(42))).toBe(mapFingerprint(generateMap(42)));expect(mapFingerprint(generateMap(42))).not.toBe(mapFingerprint(generateMap(43)));});
 it('creates a connected non-overlapping room graph inside the world',()=>{const map=generateMap(9981),seen=new Set([map.rooms[0]!.id]),queue=[map.rooms[0]!.id];while(queue.length){const id=queue.shift()!,room=map.rooms.find(r=>r.id===id)!;for(const next of room.connections)if(!seen.has(next)){seen.add(next);queue.push(next);}}expect(seen.size).toBe(map.rooms.length);expect(map.rooms).toHaveLength(16);for(const room of map.rooms){expect(room.x).toBeGreaterThanOrEqual(0);expect(room.y).toBeGreaterThanOrEqual(0);expect(room.x+room.width).toBeLessThanOrEqual(map.width);expect(room.y+room.height).toBeLessThanOrEqual(map.height);}for(let i=0;i<map.rooms.length;i++)for(let j=i+1;j<map.rooms.length;j++){const a=map.rooms[i]!,b=map.rooms[j]!;expect(a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y).toBe(false);}});
 it('keeps movement inside rooms and corridors',()=>{const map=generateMap(7),spawn=map.spawn;expect(roomAt(map,spawn)?.id).toBe('room-0');expect(isWalkable(map,spawn)).toBe(true);expect(moveWithinMap(map,spawn,{x:-100,y:-100})).toEqual(spawn);for(const corridor of map.corridors){const a=map.rooms.find(r=>r.id===corridor.fromRoomId)!,b=map.rooms.find(r=>r.id===corridor.toRoomId)!,from={x:a.x+a.width/2,y:a.y+a.height/2},to={x:b.x+b.width/2,y:b.y+b.height/2};for(let step=0;step<=40;step++){const t=step/40;expect(isWalkable(map,{x:from.x+(to.x-from.x)*t,y:from.y+(to.y-from.y)*t})).toBe(true);}}});
 it('distinguishes center entry from the full player body entering',()=>{const map=generateMap(5),room=map.rooms[0]!,nearDoor={x:room.x+2,y:room.y+room.height/2};expect(roomAt(map,nearDoor)?.id).toBe(room.id);expect(roomAt(map,nearDoor,24)).toBeUndefined();expect(roomAt(map,{x:room.x+24,y:nearDoor.y},24)?.id).toBe(room.id);});
});
