import { describe,expect,it } from 'vitest';
import { generateMap,isWalkable,mapFingerprint,moveWithinMap,roomAt } from './map';

describe('deterministic multi-cell map generation',()=>{
 it('repeats exactly for the same seed and changes for another seed',()=>{expect(mapFingerprint(generateMap(42))).toBe(mapFingerprint(generateMap(42)));expect(mapFingerprint(generateMap(42))).not.toBe(mapFingerprint(generateMap(43)));});
 it('creates connected, non-overlapping room graphs for many seeds',()=>{for(let seed=1;seed<=80;seed++){const map=generateMap(seed),seen=new Set([map.rooms[0]!.id]),queue=[map.rooms[0]!.id],occupied=new Set<string>();while(queue.length){const id=queue.shift()!,room=map.rooms.find(r=>r.id===id)!;for(const next of room.connections)if(!seen.has(next)){seen.add(next);queue.push(next);}}expect(seen.size).toBe(map.rooms.length);expect(map.rooms).toHaveLength(14);expect(map.corridors.length).toBeGreaterThanOrEqual(15);for(const room of map.rooms){expect(room.x).toBeGreaterThanOrEqual(0);expect(room.y).toBeGreaterThanOrEqual(0);expect(room.x+room.width).toBeLessThanOrEqual(map.width);expect(room.y+room.height).toBeLessThanOrEqual(map.height);for(let y=room.gridY;y<room.gridY+room.gridHeight;y++)for(let x=room.gridX;x<room.gridX+room.gridWidth;x++){const key=`${x},${y}`;expect(occupied.has(key)).toBe(false);occupied.add(key);}}}});
 it('contains standard, wide and tall rooms at the expanded scale',()=>{const map=generateMap(9981),kinds=new Set(map.rooms.map(room=>room.templateKind)),standard=map.rooms.find(room=>room.templateKind==='standard')!;expect(kinds).toEqual(new Set(['standard','wide','tall']));expect(standard.width*standard.height).toBeGreaterThanOrEqual(900*650);expect(map.rooms.filter(room=>room.gridWidth*room.gridHeight>1).length).toBeGreaterThanOrEqual(4);});
 it('keeps every corridor continuously walkable for the full player body',()=>{const map=generateMap(7);for(const corridor of map.corridors){if(corridor.width>=corridor.height){const y=corridor.y+corridor.height/2;for(let x=corridor.x+24;x<=corridor.x+corridor.width-24;x+=20)expect(isWalkable(map,{x,y})).toBe(true);}else{const x=corridor.x+corridor.width/2;for(let y=corridor.y+24;y<=corridor.y+corridor.height-24;y+=20)expect(isWalkable(map,{x,y})).toBe(true);}}});
 it('keeps movement inside walkable geometry and detects full-body entry',()=>{const map=generateMap(5),spawn=map.spawn,room=map.rooms[0]!,nearDoor={x:room.x+2,y:room.y+room.height/2};expect(isWalkable(map,spawn)).toBe(true);expect(moveWithinMap(map,spawn,{x:-100,y:-100})).toEqual(spawn);expect(roomAt(map,nearDoor)?.id).toBe(room.id);expect(roomAt(map,nearDoor,24)).toBeUndefined();});
});
