import { describe,expect,it } from 'vitest';
import { generateMap } from './map';
import { bossAddCap,bossAddSlots,completedSigils,createStageProgress,puzzleRunes } from './progression';

describe('stage progression',()=>{
 it('places distinct objectives and prioritizes large rooms for combat duties',()=>{const map=generateMap(44),stage=createStageProgress(map,0),ids=stage.objectives.map(o=>o.roomId),bossRoom=map.rooms.find(r=>r.id===stage.boss.roomId)!,eliteRoom=map.rooms.find(r=>r.id===stage.objectives[0]!.roomId)!,altarRoom=map.rooms.find(r=>r.id===stage.objectives[1]!.roomId)!;expect(new Set(ids).size).toBe(3);expect(ids).not.toContain('room-0');expect(ids).not.toContain(stage.boss.roomId);expect(bossRoom.gridWidth*bossRoom.gridHeight).toBe(2);expect(eliteRoom.gridWidth*eliteRoom.gridHeight).toBe(2);expect(altarRoom.gridWidth*altarRoom.gridHeight).toBe(2);expect(stage.objectives.map(o=>o.kind)).toEqual(['elite','altar','puzzle']);});
 it('requires two completed objectives',()=>{const stage=createStageProgress(generateMap(8),0);expect(completedSigils(stage)).toBe(0);stage.objectives[0]!.status='completed';stage.objectives[1]!.status='completed';expect(completedSigils(stage)).toBe(stage.requiredSigils);});
 it('configures a distinct cooperative boss mechanic in every biome',()=>{const stages=[0,1,2].map(i=>createStageProgress(generateMap(8,i),i));expect(stages.map(s=>s.biome)).toEqual(['ruins','swamp','volcano']);expect(stages.map(s=>s.boss.mechanics[0]!.kind)).toEqual(['rune-pillar','purifier','cooling-rune']);expect(stages[1]!.boss.mechanics).toHaveLength(3);expect(stages[2]!.boss.mechanics.filter(m=>m.active)).toHaveLength(2);});
 it('places all puzzle runes inside their objective room',()=>{const map=generateMap(9),stage=createStageProgress(map,0),objective=stage.objectives.find(o=>o.kind==='puzzle')!,room=map.rooms.find(r=>r.id===objective.roomId)!;for(const rune of puzzleRunes(map,room.id)){expect(rune.x).toBeGreaterThan(room.x);expect(rune.x).toBeLessThan(room.x+room.width);expect(rune.y).toBeGreaterThan(room.y);expect(rune.y).toBeLessThan(room.y+room.height);}});
 it('caps and only replenishes boss adds up to each biome limit',()=>{expect([1,2,3,4].map(n=>bossAddCap(0,n))).toEqual([3,3,4,5]);expect([1,2,3,4].map(n=>bossAddCap(1,n))).toEqual([3,4,5,6]);expect([1,2,3,4].map(n=>bossAddCap(2,n))).toEqual([4,4,5,6]);expect(bossAddSlots(1,4,6,3)).toBe(0);expect(bossAddSlots(1,4,4,3)).toBe(2);});
});
