import { describe,expect,it } from 'vitest'; import { ELEMENTS } from './contracts'; import { POSITION_MODIFIERS,beamPower,canQueueLightning,reactDamage,resolveSpell,resolveStatusApplication } from './spells';
const wet={kind:'wet' as const,intensity:1,stacks:1,sourceId:'rain',expiresAt:999999};
describe('spell resolver',()=>{
 it('prefers ordered exact recipes',()=>{expect(resolveSpell(['fire','life'])?.id).toBe('flame-beam');expect(resolveSpell(['life','fire'])?.id).toBe('mixed:life-fire')});
 it('uses independent effects for every element and modifier slot',()=>{for(const slot of [2,3,4] as const)for(const element of ELEMENTS)expect(POSITION_MODIFIERS[slot][element]).toBeTypeOf('function');const base=resolveSpell(['rock'])!,second=resolveSpell(['rock','rock'])!,third=resolveSpell(['rock','fire','rock'])!,fourth=resolveSpell(['rock','fire','ice','rock'])!;expect(second.radius).toBeGreaterThan(base.radius);expect(third.castMs).toBeGreaterThan(base.castMs);expect(fourth.traits).toContain('shockwave')});
 it('resolves meteor and rain signatures',()=>{expect(resolveSpell(['fire','rock','rock','fire'])?.id).toBe('meteor');expect(resolveSpell(['fire','water','water','fire'])?.delivery).toBe('global')});
 it('derives data-driven telegraphs and channel update policy',()=>{expect(resolveSpell(['fire','rock','rock','fire'])?.presentation?.telegraph).toBe('target-circle');expect(resolveSpell(['rock'])?.presentation?.telegraph).toBe('none');expect(resolveSpell(['water'])?.presentation?.channelUpdateMs).toBe(48);});
 it('applies wet damage reactions',()=>{expect(reactDamage([wet],'fire',20)).toEqual({amount:30,reaction:'蒸发'});expect(reactDamage([wet],'lightning',20).amount).toBe(29)});
 it('requires a queued shield before lightning while wet',()=>{expect(canQueueLightning([], [wet])).toBe(false);expect(canQueueLightning(['shield'],[wet])).toBe(true)});
 it('decays beams after the grace period and keeps a floor',()=>{expect(beamPower(1500)).toBe(1);expect(beamPower(4000)).toBeCloseTo(.55);expect(beamPower(9000)).toBe(.55)});
 it('resolves all new ordered recipes before positional modifiers',()=>{expect(resolveSpell(['ice','shield','shield','ice'])?.id).toBe('ice-wall');expect(resolveSpell(['lightning','water','lightning','shield'])?.id).toBe('storm-field');expect(resolveSpell(['life','lightning','life'])?.traits).toContain('chain-heal');expect(resolveSpell(['rock','shield','lightning','rock'])?.id).toBe('gravity-well');expect(resolveSpell(['fire','shield','fire'])?.id).toBe('fire-ring');expect(resolveSpell(['ice','ice','rock'])?.id).toBe('ice-lance');expect(resolveSpell(['water','rock','water'])?.id).toBe('tidal-wave');expect(resolveSpell(['life','shield','life','shield'])?.id).toBe('life-barrier')});
 it('closes the wet, burning, chilled and frozen status loop',()=>{const at=10000,burn={kind:'burning' as const,intensity:1,stacks:2,sourceId:'fire',expiresAt:at+4000},chill={kind:'chilled' as const,intensity:1,stacks:1,sourceId:'ice',expiresAt:at+4000};expect(resolveStatusApplication([burn],{...wet,expiresAt:at+4000},at).statuses.some(s=>s.kind==='burning')).toBe(false);expect(resolveStatusApplication([wet],burn,at).statuses.some(s=>s.kind==='burning')).toBe(false);const two=resolveStatusApplication([chill],chill,at).statuses;const frozen=resolveStatusApplication(two,chill,at);expect(frozen.froze).toBe(true);expect(frozen.statuses.some(s=>s.kind==='frozen')).toBe(true);expect(resolveStatusApplication(two,chill,at,at+2000).froze).toBe(false)});
 it('lets elemental wards reject their matching negative status',()=>{const at=10000,ward=(kind:'fire-ward'|'frost-ward'|'water-ward')=>({kind,intensity:1,stacks:1,sourceId:'ward',expiresAt:at+5000});expect(resolveStatusApplication([ward('fire-ward')],{kind:'burning',intensity:1,stacks:1,sourceId:'fire',expiresAt:at+1000},at).statuses.some(s=>s.kind==='burning')).toBe(false);expect(resolveStatusApplication([ward('frost-ward')],{kind:'chilled',intensity:1,stacks:1,sourceId:'ice',expiresAt:at+1000},at).statuses.some(s=>s.kind==='chilled')).toBe(false);expect(resolveStatusApplication([ward('water-ward')],{...wet,expiresAt:at+1000},at).statuses.some(s=>s.kind==='wet')).toBe(false)});
});
