import { mainCanvas,mainContext } from 'littlejsengine';
import { ELEMENTS,ELEMENT_SLOTS,WORLD_HEIGHT,WORLD_WIDTH,type ActiveBeam,type ActiveCast,type ActiveProjectile,type AimState,type ControlEffect,type EnemyAttackKind,type EnemyKind,type EnemyState,type EnvironmentState,type EquipmentItem,type FloatingText,type GameState,type HazardState,type HostProjectile,type LootEntity,type MapManifest,type MerchantState,type PendingCast,type PlayerActivity,type PlayerRealtimeFrame,type Point,type RegionEncounter,type SharedSpellVisual,type SpellEffect,type SpellPlan,type SpellVisual,type StageProgress,type StatusInstance,type WorldEventState } from '../game/contracts';
import { ZERO_CONTROL,advanceControl,angleTo,applyControl,beamTargets,canAct,circleContains,clippedRay,coneContains,createPending,distance,furthestReachable,normalize,spellDirection,turnToward } from '../game/combat';
import { generateMap,isWalkable,moveWithinMap,roomAt } from '../game/map';
import { activeSimulationRooms,createRegionEncounters,shouldActivateEncounter } from '../game/regions';
import { completedSigils,createStageProgress,puzzleRunes } from '../game/progression';
import { createMerchant,equipmentBonuses,generateEquipment } from '../game/equipment';
import { steeringTimedOut,steerToward } from '../game/navigation';
import { BACKGROUND_INTERVAL_MS,REALTIME_HEARTBEAT_MS,REALTIME_INTERVAL_MS,interpolateRealtime } from '../game/realtime';
import { RECIPES,beamPower,canQueueLightning,isRecipeId,reactDamage,resolvePlayerSpell,resolveSpell,resolveStatusApplication } from '../game/spells';
import {SCROLLS,generateScroll,isScroll} from '../game/scrolls';
import {UiMessageQueue,computeHudLayout,contains,hudBlocksWorld,type HudLayout,type UiMessageCategory} from '../ui/hud';

type View={x:number;y:number;w:number;h:number;scale:number};type RemoteMotion={previous:PlayerRealtimeFrame;current:PlayerRealtimeFrame;receivedAt:number};type Button={element:(typeof ELEMENTS)[number];x:number;y:number;r:number};type UiAction={x:number;y:number;w:number;h:number;kind:'toggle-inventory'|'toggle-spellbook'|'equip'|'drop'|'pickup'|'want'|'buy';itemId?:string;entityId?:string};
const labels={rock:'岩',fire:'火',ice:'冰',life:'命',lightning:'雷',water:'水',shield:'盾'} as const;
const colors={rock:'#aa8b68',fire:'#ff5c45',ice:'#77e6ff',life:'#79df78',lightning:'#c596ff',water:'#469cff',shield:'#ffd952'} as const;

export class MagickaScene{
 private state:GameState|null=null;
 private map:MapManifest=generateMap(1);private explored=new Set<string>();private reportedRoom='';
 private local={x:WORLD_WIDTH/2,y:WORLD_HEIGHT/2,z:0,hp:100,downed:false,kills:0,statuses:[] as StatusInstance[],elements:[] as (typeof ELEMENTS)[number][],controls:{...ZERO_CONTROL}};
 private moveTarget:Point|null=null;private moveHeading:number|null=null;private moveStuckSince=0;private moveBestDistance=Infinity;private aim:AimState|null=null;private pending:PendingCast|null=null;private beam:ActiveBeam|null=null;private recoveryUntil=0;private localFreezeImmuneUntil=0;
 private shots:ActiveProjectile[]=[];private visuals:SpellVisual[]=[];private floats:FloatingText[]=[];
 private hostEnemies=new Map<string,EnemyState>();private hostProjectiles=new Map<string,HostProjectile>();private hostEnvironments=new Map<string,EnvironmentState>();
 private hostHazards=new Map<string,HazardState>();private hostEvents=new Map<string,WorldEventState>();
 private hostEncounters=new Map<string,RegionEncounter>();
 private hostStage:StageProgress|null=null;private stageAdvanceAt=0;
 private hostLoot=new Map<string,LootEntity>();private hostMerchants=new Map<string,MerchantState>();private inventoryOpen=false;private spellbookOpen=false;private uiActions:UiAction[]=[];
 private actingAsHost=false;private remoteMotion=new Map<string,RemoteMotion>();private remoteCasts=new Map<string,ActiveCast>();
 private seen=new Set<string>();private pendingDamage=new Map<string,{enemyId:string;amount:number;expectedHp:number}>();private threatSeen=new Set<string>();
 private previous=performance.now();private publishAt=0;private realtimeAt=0;private realtimeHeartbeatAt=0;private lastRealtimeKey='';private realtimeSeq=0;private worldAt=0;private seq=0;private worldSeq=0;private eventSeq=0;private weatherAt=0;
 private ratio=1;private view:View={x:0,y:0,w:0,h:0,scale:1};private hud:HudLayout=computeHudLayout(1280,720);private messages=new UiMessageQueue();private buttons:Button[]=[];private disposers:Array<()=>void>=[];

 init(){this.disposers.push(parti.onState(s=>this.receive(s as GameState)),parti.onEvent('magicka:realtime-frame',p=>this.onRealtimeFrame(p as PlayerRealtimeFrame)),parti.onEvent('magicka:spell-cast',p=>this.onSpellCast(p as ActiveCast)),parti.onEvent('magicka:enemy-damage',p=>this.onEnemyDamage(p as Record<string,unknown>)),parti.onEvent('magicka:player-effect',p=>this.onPlayerEffect(p as Record<string,unknown>)),parti.onEvent('magicka:spell-visual',p=>this.onSpellVisual(p as SharedSpellVisual)),parti.onEvent('magicka:environment',p=>this.onEnvironment(p as EnvironmentState)),parti.onEvent('magicka:projectile-hit',p=>{const id=String((p as {projectileId?:unknown}).projectileId??'');this.hostProjectiles.delete(id);}),parti.onEvent('magicka:loot-dropped',p=>this.onLootDropped(p as LootEntity)),parti.onEvent('magicka:loot-picked',p=>this.hostLoot.delete(String((p as {lootId?:unknown}).lootId??''))),parti.onEvent('magicka:loot-wants',p=>{const raw=p as {lootId?:unknown;wants?:unknown},loot=this.hostLoot.get(String(raw.lootId??''));if(loot&&Array.isArray(raw.wants))loot.wants=raw.wants.map(String);}),parti.onEvent('magicka:merchant-sold',p=>{const raw=p as {merchantId?:unknown;itemId?:unknown},merchant=this.hostMerchants.get(String(raw.merchantId??''));if(merchant)merchant.stock=merchant.stock.filter(entry=>entry.item.id!==String(raw.itemId??''));}));mainCanvas.addEventListener('pointerdown',this.pointerDown);mainCanvas.addEventListener('pointermove',this.pointerMove);mainCanvas.addEventListener('pointerup',this.pointerUp);mainCanvas.addEventListener('pointercancel',this.pointerUp);window.addEventListener('keydown',this.key);parti.ready();}

 update(){
  const now=performance.now(),dt=Math.min(.04,Math.max(.001,(now-this.previous)/1000));this.previous=now;this.ratio=mainCanvas.width/Math.max(1,mainCanvas.clientWidth);this.view=this.computeView();if(this.state?.phase!=='running')return;
  this.local.controls=advanceControl(this.local.controls,dt,now);this.local.z=this.local.controls.z;const controlled=this.movePlayer({x:clamp(this.local.x+this.local.controls.vx*dt,20,WORLD_WIDTH-20),y:clamp(this.local.y+this.local.controls.vy*dt,20,WORLD_HEIGHT-20)});this.local.x=controlled.x;this.local.y=controlled.y;this.expire(now);this.discoverCurrentRoom();
  if(!canAct(this.local.controls,now)){this.interruptCast('施法被打断');}else this.updateCasting(now,dt);
  if(!this.local.downed&&canAct(this.local.controls,now)&&this.moveTarget&&!this.aim&&!this.beam){const d=distance(this.local,this.moveTarget),haste=this.local.statuses.find(s=>s.kind==='haste')?.intensity??0,speed=260*(1+this.bonuses().moveSpeed+haste)*(now<this.local.controls.slowedUntil?this.local.controls.slowScale:1),step=speed*dt,result=steerToward(this.map,this.local,this.moveTarget,step,this.moveHeading,p=>this.canPlayerOccupy(p));this.local.x=result.position.x;this.local.y=result.position.y;this.moveHeading=result.heading;const remaining=distance(this.local,this.moveTarget),progress=result.distanceGain>.15||remaining<this.moveBestDistance-2;if(progress){this.moveBestDistance=Math.min(this.moveBestDistance,remaining);this.moveStuckSince=0;}else if(!this.moveStuckSince)this.moveStuckSince=now;if(d<=step||remaining<3||steeringTimedOut(this.moveStuckSince,now))this.clearMoveTarget();}
  this.updatePlayerProjectiles(dt,now);if(this.isHost()){this.updateRegionEncounters();this.updateStageProgress();this.simulateHost(dt,now);}this.simulateThreats(now);this.simulateWeather(now);this.simulateHazards(now);this.simulateWorldEvents();this.visuals=this.visuals.filter(v=>v.endsAt>now);this.floats=this.floats.filter(v=>v.endsAt>now);
  this.publishRealtime(now);if(now>=this.publishAt){this.publishAt=now+100;void parti.action('publishPlayer',{sequence:++this.seq,...this.local});}
  if(this.isHost()&&this.hostStage&&now>=this.worldAt){this.worldAt=now+100;void parti.action('syncWorld',{sequence:++this.worldSeq,enemies:[...this.hostEnemies.values()],projectiles:[...this.hostProjectiles.values()],environments:[...this.hostEnvironments.values()],hazards:[...this.hostHazards.values()],events:[...this.hostEvents.values()],encounters:[...this.hostEncounters.values()],stage:this.hostStage,loot:[...this.hostLoot.values()],merchants:[...this.hostMerchants.values()]});}
 }
 private currentActivity(now:number):PlayerActivity{const plan=this.aim?.plan??this.pending?.plan??this.beam?.plan??this.resolveEquippedSpell(this.local.elements),phase=this.local.downed?'downed':!canAct(this.local.controls,now)?'stunned':this.beam?'channeling':this.pending?'windup':this.aim?'aiming':now<this.recoveryUntil?'recovery':this.local.elements.length?'selecting':'idle',castId=this.pending?.id??this.beam?.id??null;return{phase,elements:plan?[...plan.elements]:[...this.local.elements],spellId:plan?.id??null,castId,phaseStartedAt:this.pending?.releasedAt??this.beam?.startedAt??this.aim?.startedAt??now,phaseEndsAt:this.pending?.triggersAt??(phase==='recovery'?this.recoveryUntil:null)};}
 private publishRealtime(now:number){if(now<this.realtimeAt)return;const hidden=document.visibilityState!=='visible',interval=hidden?BACKGROUND_INTERVAL_MS:REALTIME_INTERVAL_MS,activity=this.currentActivity(now),key=JSON.stringify([Math.round(this.local.x),Math.round(this.local.y),Math.round(this.local.z),activity.phase,activity.elements,activity.spellId,activity.castId]),changed=key!==this.lastRealtimeKey;if(!changed&&now<this.realtimeHeartbeatAt){this.realtimeAt=now+interval;return;}this.realtimeAt=now+interval;this.realtimeHeartbeatAt=now+REALTIME_HEARTBEAT_MS;this.lastRealtimeKey=key;void parti.action('publishRealtimeFrame',{sequence:++this.realtimeSeq,sentAt:Date.now(),x:this.local.x,y:this.local.y,z:this.local.z,activity});}

 private updateCasting(now:number,dt:number){
  if(this.aim?.plan.delivery==='beam'&&now>=this.aim.startedAt+this.aim.plan.castMs){const a=this.aim,id=this.id('beam');this.beam={id,plan:a.plan,angle:a.angle,targetAngle:angleTo(this.local,a.target),startedAt:now,nextDamageAt:now,pointerId:a.pointerId};this.reportCast(id,a.plan,'committed',this.local,a.target,0);this.reportCast(id,a.plan,'channeling',this.local,a.target,1);this.aim=null;}
  if(this.beam){this.beam.angle=turnToward(this.beam.angle,this.beam.targetAngle,Math.PI*2.5*dt);if(now>=this.beam.nextDamageAt){this.beam.nextDamageAt=now+this.beam.plan.tickMs;this.tickBeam(this.beam,now);}}
  if(this.pending&&now>=this.pending.triggersAt){const cast=this.pending;this.pending=null;this.executeSpell(cast.id,cast.plan,cast.origin,cast.target,now);this.recoveryUntil=now+cast.plan.recoveryMs;}
 }

 private beginAt(target:Point,pointerId:number){
  if(this.local.downed)return;const plan=this.resolveEquippedSpell(this.local.elements);if(!plan){if(isWalkable(this.map,target)){this.moveTarget={...target};this.moveHeading=null;this.moveStuckSince=0;this.moveBestDistance=distance(this.local,target);}else this.notify('无法到达遗迹墙外');return;}if(this.pending||this.beam||performance.now()<this.recoveryUntil){this.notify('当前法术尚未结束');return;}if(!canAct(this.local.controls,performance.now()))return;this.clearMoveTarget();this.aim={plan,pointerId,target:{...target},startedAt:performance.now(),angle:angleTo(this.local,target)};
 }
 private finishAim(pointerId:number){
  const now=performance.now();if(this.beam?.pointerId===pointerId){this.reportCast(this.beam.id,this.beam.plan,'ended',this.local,this.beamEnd(this.beam.angle,this.beam.plan.range),99);this.recoveryUntil=now+this.beam.plan.recoveryMs;this.beam=null;this.local.elements=[];return;}if(!this.aim||this.aim.pointerId!==pointerId)return;const aim=this.aim;this.aim=null;if(aim.plan.delivery==='beam'){this.notify('射线吟唱取消');return;}const pending=createPending(this.id('cast'),aim,now);pending.origin={x:this.local.x,y:this.local.y};this.pending=pending;this.reportCast(pending.id,pending.plan,'committed',pending.origin,pending.target,0);this.local.elements=[];
 }
 private interruptCast(message:string){if(!this.pending&&!this.aim&&!this.beam)return;const cast=this.pending??this.beam;if(cast)this.reportCast(cast.id,cast.plan,'cancelled',this.local,'target'in cast?cast.target:this.beamEnd(cast.angle,cast.plan.range),99);this.pending=null;this.aim=null;this.beam=null;this.notify(message);}

 private executeSpell(castId:string,plan:SpellPlan,origin:Point,target:Point,now:number){this.reportCast(castId,plan,'resolved',origin,target,1);this.discoverRecipe(plan);
  this.publishSpellVisual(plan,origin,target,plan.delivery==='cone'?'cone':plan.delivery==='projectile'?'projectile':plan.delivery==='self'?'heal':'impact',420);
  const angle=angleTo(origin,target),environmentTarget=plan.delivery==='self'||plan.delivery==='global'?origin:target;if(plan.traits.includes('water-pool'))this.createEnvironment('water-pool',environmentTarget,Math.max(80,plan.radius),4000);if(plan.traits.includes('overflow-heal')){const healing=plan.effects.filter(e=>e.type==='heal').reduce((n,e)=>n+e.amount,0);if(healing)this.createEnvironment('overflow-heal',environmentTarget,Math.max(70,plan.radius),3000,Math.max(1,Math.round(healing*.25)));}if(plan.traits.includes('self-ward'))this.applySelf([{type:'status',status:'shielded',intensity:1,durationMs:3000}],origin);if(plan.delivery==='projectile'){const d=normalize(origin,target);this.shots.push({id:this.id('shot'),ownerId:parti.playerId??'',spellId:plan.id,element:plan.elements[0]!,x:origin.x,y:origin.y,vx:d.x*plan.projectileSpeed,vy:d.y*plan.projectileSpeed,radius:plan.radius,remainingPierce:plan.pierce,expiresAt:now+plan.range/Math.max(1,plan.projectileSpeed)*1000,effects:plan.effects,traits:plan.traits,hitIds:[]});return;}
  if(plan.delivery==='cone'){const hits=this.enemies().filter(e=>coneContains(origin,angle,plan.range,plan.coneAngle/2,e,e.radius));for(const e of hits)this.damageEnemy(e,plan,origin,now);this.visuals.push({id:this.id('visual'),kind:'cone',origin,target,radius:plan.range,angle,color:plan.elements[0]!,startedAt:now,endsAt:now+260});return;}
  if(plan.delivery==='targeted'||plan.delivery==='area'){if(plan.effects.some(e=>e.type==='teleport'))this.applySelf(plan.effects,target);else{const hits=this.enemies().filter(e=>circleContains(target,plan.radius,e,e.radius));if(plan.id==='scroll-annihilation'&&hits.length+this.playersInArea(target,plan.radius).length!==1){this.notify('湮灭术需要范围内恰好一个目标');return;}for(const e of hits)this.damageEnemy(e,plan,origin,now);this.applyPlayers(plan,target,origin);}this.visuals.push({id:this.id('visual'),kind:'impact',origin,target,radius:plan.radius,angle,color:plan.elements[0]!,startedAt:now,endsAt:now+420});}
  if(plan.delivery==='global'){for(const e of this.enemies())this.damageEnemy(e,plan,origin,now);this.applyPlayersGlobal(plan,origin);}
  if(plan.delivery==='self')this.applySelf(plan.effects,origin);
  for(const effect of plan.effects)if(effect.type==='environment')this.createEnvironment(effect.kind,environmentTarget,effect.radius??plan.radius,effect.durationMs);
 }
 private tickBeam(beam:ActiveBeam,now:number){this.discoverRecipe(beam.plan);const power=beamPower(now-beam.startedAt),plan=this.scaleSpell(beam.plan,power),target=this.beamEnd(beam.angle,plan.range),max=distance(this.local,target);this.publishSpellVisual(plan,this.local,target,'beam',Math.max(180,plan.tickMs+80));const targets=beamTargets(this.local,beam.angle,plan.radius,this.enemies(),plan.pierce,max);for(const {enemy}of targets)this.damageEnemy(enemy,plan,this.local,now);}
 private publishSpellVisual(plan:SpellPlan,origin:Point,target:Point,kind:SpellVisual['kind'],durationMs:number){void parti.action('reportSpellVisual',{eventId:this.id('spell-visual'),kind,origin:{x:origin.x,y:origin.y},target:{x:target.x,y:target.y},radius:kind==='cone'?plan.range:plan.radius,angle:angleTo(origin,target),coneAngle:plan.coneAngle,color:plan.elements[0],durationMs});}
 private scaleSpell(plan:SpellPlan,power:number):SpellPlan{return{...plan,radius:plan.radius*power,effects:plan.effects.map(e=>e.type==='damage'||e.type==='heal'?{...e,amount:Math.max(1,Math.round(e.amount*power))}:e.type==='status'?{...e,durationMs:Math.max(100,Math.round(e.durationMs*power))}:e.type==='control'?{...e,control:{...e.control,strength:e.control.strength*power,durationMs:Math.max(80,Math.round(e.control.durationMs*power))}}:e)};}
 private discoverRecipe(plan:SpellPlan){if(isRecipeId(plan.id)&&!this.state?.discoveredRecipeIds.includes(plan.id))void parti.action('discoverRecipe',{recipeId:plan.id});}
 private createEnvironment(kind:EnvironmentState['kind'],target:Point,radius:number,durationMs:number,power?:number){const wallNow=Date.now(),room=roomAt(this.map,target),center=kind==='blizzard'&&room?{x:room.x+room.width/2,y:room.y+room.height/2}:target,effectiveRadius=kind==='rain'?9999:kind==='blizzard'&&room?Math.hypot(room.width,room.height)/2:radius,env:EnvironmentState={id:this.id('env'),kind,x:center.x,y:center.y,radius:effectiveRadius,startedAt:wallNow,endsAt:wallNow+durationMs,sourcePlayerId:parti.playerId??undefined,lastTickAt:0,power};void parti.action('reportEnvironment',env);}
 private reportCast(castId:string,plan:SpellPlan,phase:ActiveCast['phase'],origin:Point,target:Point,revision:number){void parti.action('reportSpellCast',{castId,spellId:plan.id,elements:plan.elements,phase,origin:{x:origin.x,y:origin.y},target:{x:target.x,y:target.y},revision});}
 private updatePlayerProjectiles(dt:number,now:number){for(const s of this.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;if(!isWalkable(this.map,s,Math.max(4,s.radius/2))){s.expiresAt=0;continue;}for(const e of this.enemies()){if(s.hitIds.includes(e.id)||!circleContains(s,s.radius,e,e.radius))continue;s.hitIds.push(e.id);this.damageEnemy(e,{...resolveSpell([s.element])!,id:s.spellId,effects:s.effects,traits:s.traits},s,now);if(s.remainingPierce--<=0){s.expiresAt=0;break;}}}this.shots=this.shots.filter(s=>s.expiresAt>now&&s.x>=0&&s.x<=WORLD_WIDTH&&s.y>=0&&s.y<=WORLD_HEIGHT);}

 private damageEnemy(enemy:EnemyState,plan:SpellPlan,origin:Point,now:number,triggerTraits=true){
  const wasFrozen=enemy.statuses.some(s=>s.kind==='frozen'),shocked=enemy.statuses.some(s=>s.kind==='shocked');let amount=0,reaction='';for(const effect of plan.effects){if(effect.type==='damage'){const result=reactDamage(enemy.statuses,effect.element,effect.amount);amount+=result.amount;if(result.reaction){reaction=result.reaction;enemy.statuses=enemy.statuses.filter(s=>s.kind!==(result.reaction==='碎裂'?'frozen':'wet'));}}else if(effect.type==='heal')amount+=enemy.tags?.includes('undead')?effect.amount:-Math.min(effect.amount,enemy.maxHp-enemy.hp);else if(effect.type==='current-health-damage')amount+=Math.max(0,enemy.hp-Math.max(1,Math.ceil(enemy.hp*(1-(this.isBoss(enemy)?effect.bossRatio??effect.ratio:effect.ratio)))));else if(effect.type==='set-health')amount+=enemy.hp-Math.max(1,Math.round(enemy.maxHp*effect.ratio));else if(effect.type==='cleanse'){enemy.statuses=[];enemy.controls={...enemy.controls,slowedUntil:0,slowScale:1,stunnedUntil:0};}}if(shocked&&amount>0&&!plan.id.startsWith('scroll-')){amount=Math.round(amount*1.15);enemy.statuses=enemy.statuses.filter(s=>s.kind!=='shocked');reaction=reaction||'感电';}if(!amount&&!plan.effects.some(e=>e.type==='status'||e.type==='control'||e.type==='cleanse'))return;const direction=spellDirection(origin,enemy),controls=plan.effects.flatMap(e=>e.type==='control'?[e.control]:[]),statuses=this.effectStatuses(plan.effects,this.id('status'));
  if(amount>0&&!plan.id.startsWith('scroll-')&&['ruin-guardian','bog-heart','forge-titan'].includes(enemy.kind)&&this.hostStage){const required=this.hostStage.boss.mechanics.filter(m=>m.active);for(const mechanic of required)if(this.connectedPlayers().some(p=>distance(p,mechanic)<=55))mechanic.progress=mechanic.target;enemy.mechanicState=required.every(m=>m.progress>=m.target)?'vulnerable':'shielded';if(enemy.mechanicState==='shielded'){amount=Math.max(1,Math.round(amount*.2));reaction=reaction||'机制护盾';}}enemy.hp=clamp(enemy.hp-amount,0,enemy.maxHp);enemy.flashUntil=now+160;enemy.revision+=1;for(const s of statuses)this.applyEnemyStatus(enemy,s,Date.now());for(const c of controls)enemy.controls=applyControl(enemy.controls,c,direction,now);const eventId=this.id('hit');this.seen.add(eventId);this.pendingDamage.set(eventId,{enemyId:enemy.id,amount,expectedHp:enemy.hp});this.addFloat(enemy.x,enemy.y-30,amount<0?`+${-amount}`:`${amount}${reaction?` ${reaction}`:''}`,colors[plan.elements[0]!]);if(amount)void parti.action('reportEnemyDamage',{eventId,worldSequence:this.state?.worldSequence??0,enemyId:enemy.id,sourcePlayerId:parti.playerId,spellId:plan.id,amount,statuses:enemy.statuses,controls,direction});if(triggerTraits)this.triggerSpellTraits(plan,enemy,origin,now,wasFrozen);if(enemy.hp<=0){if(this.isHost())this.handleEnemyDeath(enemy);this.hostEnemies.delete(enemy.id);this.local.kills+=1;this.notify('怪物击败');}}
 private applyEnemyStatus(enemy:EnemyState,next:StatusInstance,wallNow:number){const result=resolveStatusApplication(enemy.statuses,next,wallNow,enemy.freezeImmuneUntil);enemy.statuses=result.statuses;if(result.froze){enemy.controls=applyControl(enemy.controls,{kind:'stun',strength:1,durationMs:1500},{x:0,y:0},performance.now());enemy.freezeImmuneUntil=wallNow+3500;}}
 private triggerSpellTraits(plan:SpellPlan,enemy:EnemyState,_origin:Point,now:number,wasFrozen:boolean){let ratio=0,radius=0,element=plan.elements[0]!;if(plan.traits.includes('shockwave')){ratio=.3;radius=90;element='rock';}else if(plan.traits.includes('ember-burst')){ratio=.35;radius=95;element='fire';}else if(plan.traits.includes('ice-shards')&&wasFrozen){ratio=.3;radius=120;element='ice';}if(ratio){const base=plan.effects.filter(e=>e.type==='damage').reduce((n,e)=>n+e.amount,0),splash={...plan,traits:[],effects:[{type:'damage' as const,element,amount:Math.max(1,Math.round(base*ratio))}]};for(const other of this.enemies())if(other.id!==enemy.id&&circleContains(enemy,radius,other,other.radius))this.damageEnemy(other,splash,enemy,now,false);}if(plan.traits.includes('chain')){const chain={...plan,traits:[],effects:plan.effects.map(e=>e.type==='damage'?{...e,amount:Math.max(1,Math.round(e.amount*.55))}:e).filter(e=>e.type==='damage')};for(const other of this.enemies().filter(e=>e.id!==enemy.id).sort((a,b)=>distance(enemy,a)-distance(enemy,b)).slice(0,2))if(distance(enemy,other)<=260)this.damageEnemy(other,chain,enemy,now,false);}}
 private playersInArea(target:Point,radius:number){const roomId=roomAt(this.map,this.local)?.id;return Object.values(this.state?.players??{}).filter(p=>p.connected&&roomAt(this.map,p)?.id===roomId&&circleContains(target,radius,p,24));}
 private applyPlayers(plan:SpellPlan,target:Point,origin:Point){for(const p of this.playersInArea(target,plan.radius)){if(p.id===parti.playerId)this.applySelf(plan.effects,origin);else void parti.action('reportPlayerEffect',{eventId:this.id('player-effect'),targetPlayerId:p.id,effects:plan.effects,direction:spellDirection(origin,p)});}}
 private applyPlayersGlobal(plan:SpellPlan,origin:Point){const roomId=roomAt(this.map,this.local)?.id;for(const p of Object.values(this.state?.players??{})){if(!p.connected||roomAt(this.map,p)?.id!==roomId)continue;if(p.id===parti.playerId)this.applySelf(plan.effects,origin);else void parti.action('reportPlayerEffect',{eventId:this.id('player-effect'),targetPlayerId:p.id,effects:plan.effects,direction:spellDirection(origin,p)});}}
 private applySelf(effects:SpellEffect[],origin:Point){for(const e of effects){if(e.type==='heal')this.local.hp=Math.min(100,this.local.hp+e.amount);else if(e.type==='revive'){if(this.local.downed){this.local.hp=Math.max(1,Math.round(100*e.healthRatio));this.local.downed=false;}}else if(e.type==='current-health-damage'){if(!this.local.downed)this.takeRawDamage(Math.max(0,this.local.hp-Math.max(1,Math.ceil(this.local.hp*(1-e.ratio)))));}else if(e.type==='set-health'){if(!this.local.downed)this.local.hp=Math.max(1,Math.round(100*e.ratio));}else if(e.type==='cleanse'){this.local.statuses=[];this.local.controls={...this.local.controls,slowedUntil:0,slowScale:1,stunnedUntil:0};}else if(e.type==='teleport'){const d=Math.min(e.maxRange,distance(this.local,origin)),angle=angleTo(this.local,origin),wanted={x:this.local.x+Math.cos(angle)*d,y:this.local.y+Math.sin(angle)*d},land=furthestReachable(this.local,wanted,p=>this.spellPathValid(p));if(distance(this.local,land)<2)this.notify('前方没有安全的瞬移空间');else{this.local.x=land.x;this.local.y=land.y;this.clearMoveTarget();}}else if(e.type==='status')this.addStatus(e.status,e.intensity,e.durationMs,'self');else if(e.type==='control')this.local.controls=applyControl(this.local.controls,e.control,spellDirection(origin,this.local),performance.now());}}

 private simulateHost(dt:number,now:number){
  const wallNow=Date.now(),players=Object.values(this.state?.players??{}).filter(p=>p.connected&&!p.downed),activeRooms=activeSimulationRooms(this.hostEncounters.values(),this.occupiedRooms());
  for(const enemy of this.hostEnemies.values()){if(!activeRooms.has(enemy.roomId))continue;enemy.controls=advanceControl(enemy.controls,dt,now);this.placeEnemy(enemy,enemy.x+enemy.controls.vx*dt,enemy.y+enemy.controls.vy*dt);enemy.statuses=enemy.statuses.filter(s=>s.expiresAt==null||s.expiresAt>wallNow);const roomPlayers=players.filter(p=>roomAt(this.map,p)?.id===enemy.roomId),target=roomPlayers.sort((a,b)=>distance(enemy,a)-distance(enemy,b))[0];if(!target){enemy.attack=null;continue;}enemy.targetId=target.id;if(!canAct(enemy.controls,now)){enemy.attack=null;continue;}if(enemy.attack){if(wallNow>=enemy.attack.firesAt)this.fireEnemyAttack(enemy,enemy.attack,target,wallNow);if(wallNow>=enemy.attack.firesAt+180)enemy.attack=null;continue;}if(wallNow<enemy.nextAttackAt)continue;const d=distance(enemy,target),speed=(enemy.kind==='chaser'?145:enemy.kind==='shooter'?95:enemy.kind==='ruin-guardian'?85:115)*(now<enemy.controls.slowedUntil?enemy.controls.slowScale:1),attack=this.chooseAttack(enemy,d);if(attack){enemy.attack={kind:attack,targetId:target.id,startedAt:wallNow,firesAt:wallNow+(attack==='melee'?350:attack==='water-slam'?420:520)};continue;}const desired=enemy.kind==='shooter'?300:enemy.kind==='water-fiend'?d>330?260:70:enemy.kind==='ruin-guardian'?110:65,sign=d>desired+25?1:d<desired-25?-1:0;if(sign){const v=normalize(enemy,target);this.placeEnemy(enemy,enemy.x+v.x*speed*dt*sign,enemy.y+v.y*speed*dt*sign);}}
  for(const[id,p]of this.hostProjectiles){if(!activeRooms.has(p.roomId))continue;const next={x:p.x+p.vx*dt,y:p.y+p.vy*dt};if(!isWalkable(this.map,next,Math.max(4,p.radius/2))){this.hostProjectiles.delete(id);continue;}p.x=next.x;p.y=next.y;}for(const[id,p]of this.hostProjectiles)if(p.expiresAt<=wallNow)this.hostProjectiles.delete(id);const raining=[...this.hostEnvironments.values()].some(e=>e.kind==='rain'&&e.endsAt>wallNow);for(const enemy of this.hostEnemies.values()){if(raining)this.applyEnemyStatus(enemy,{kind:'wet',intensity:1,stacks:1,sourceId:'rain',expiresAt:wallNow+2200},wallNow);const burning=enemy.statuses.find(s=>s.kind==='burning');if(burning&&wallNow-(enemy.lastStatusTickAt??0)>=1000){enemy.lastStatusTickAt=wallNow;enemy.hp=Math.max(0,enemy.hp-burning.stacks*2);enemy.revision++;}}
  for(const env of this.hostEnvironments.values()){if(wallNow-(env.lastTickAt??0)<(env.kind==='lightning-barrage'?500:800))continue;env.lastTickAt=wallNow;for(const enemy of this.hostEnemies.values()){if(!circleContains(env,env.radius,enemy,enemy.radius))continue;if(env.kind==='steam')enemy.hp=Math.max(0,enemy.hp-3);else if(env.kind==='water-pool')this.applyEnemyStatus(enemy,{kind:'wet',intensity:1,stacks:1,sourceId:env.id,expiresAt:wallNow+2200},wallNow);else if(env.kind==='ice-wall'){this.applyEnemyStatus(enemy,{kind:'chilled',intensity:1,stacks:1,sourceId:env.id,expiresAt:wallNow+2500},wallNow);enemy.controls=applyControl(enemy.controls,{kind:'slow',strength:.3,durationMs:900},{x:0,y:0},now);}else if(env.kind==='storm-field')enemy.hp=Math.max(0,enemy.hp-Math.round(enemy.statuses.some(s=>s.kind==='wet')?15:10));else if(env.kind==='fire-ring'){enemy.hp=Math.max(0,enemy.hp-8);this.applyEnemyStatus(enemy,{kind:'burning',intensity:1,stacks:1,sourceId:env.id,expiresAt:wallNow+3500},wallNow);}else if(env.kind==='gravity-well'){const pull=normalize(enemy,env);enemy.controls=applyControl(enemy.controls,{kind:'knockback',strength:160,durationMs:500},pull,now);}else if(env.kind==='life-barrier')enemy.hp=Math.min(enemy.maxHp,enemy.hp+6);else if(env.kind==='overflow-heal')enemy.hp=Math.min(enemy.maxHp,enemy.hp+(env.power??1));else if(env.kind==='lightning-barrage')enemy.hp=Math.max(0,enemy.hp-24);else if(env.kind==='blizzard'){this.applyEnemyStatus(enemy,{kind:'chilled',intensity:1,stacks:1,sourceId:env.id,expiresAt:wallNow+1800},wallNow);enemy.controls=applyControl(enemy.controls,{kind:'slow',strength:.55,durationMs:900},{x:0,y:0},now);}enemy.revision++;}}
  for(const[id,e]of this.hostEnvironments)if(e.endsAt<=wallNow){if(e.kind==='gravity-well')for(const enemy of this.hostEnemies.values())if(circleContains(e,e.radius,enemy,enemy.radius)){enemy.hp=Math.max(0,enemy.hp-35);enemy.revision++;}this.hostEnvironments.delete(id);}for(const enemy of [...this.hostEnemies.values()])if(enemy.hp<=0){this.handleEnemyDeath(enemy);this.hostEnemies.delete(enemy.id);}
 }
 private updateStageProgress(){if(!this.hostStage){this.hostStage=createStageProgress(this.map,this.state?.stageIndex??0);this.stageAdvanceAt=0;}const stage=this.hostStage,players=this.connectedPlayerRooms(),wallNow=Date.now(),partySize=Math.max(1,players.length);if(!this.hostMerchants.size){const merchant=createMerchant(this.map,stage.index),blocked=new Set([...stage.objectives.map(o=>o.roomId),stage.boss.roomId]),room=this.map.rooms.find(r=>r.id!=='room-0'&&!blocked.has(r.id));if(room){merchant.roomId=room.id;merchant.x=room.x+room.width/2;merchant.y=room.y+room.height/2;}this.hostMerchants.set(merchant.id,merchant);}for(const merchant of this.hostMerchants.values()){const encounter=this.hostEncounters.get(merchant.roomId);if(encounter){encounter.status='cleared';encounter.enemyCount=0;}}for(const objective of stage.objectives){const encounter=this.hostEncounters.get(objective.roomId);if(encounter){encounter.kind='sealed';if(objective.kind==='puzzle'){encounter.status='cleared';encounter.enemyCount=0;}else encounter.enemyCount=objective.kind==='elite'?partySize*3+2:partySize*2;}if(objective.status==='dormant'){const ready=objective.kind==='puzzle'?players.some(id=>id===objective.roomId):players.length>0&&players.every(id=>id===objective.roomId);if(!ready)continue;objective.status='active';objective.startedAt=wallNow;if(objective.kind!=='puzzle'&&encounter){encounter.status='active';encounter.activatedAt=wallNow;this.spawnEncounter(encounter);}this.notify(objective.kind==='elite'?'精英挑战开始':objective.kind==='altar'?'守护祭坛：抵御两轮敌人':'符文机关已激活');continue;}if(objective.status!=='active')continue;if(objective.kind==='puzzle'){const rune=puzzleRunes(this.map,objective.roomId)[objective.progress];if(rune&&this.connectedPlayers().some(p=>distance(p,rune)<=42)){objective.progress+=1;this.notify(`符文 ${objective.progress}/${objective.target}`);}if(objective.progress>=objective.target)this.completeObjective(objective,encounter);continue;}const alive=[...this.hostEnemies.values()].some(e=>e.roomId===objective.roomId);if(alive)continue;if(objective.kind==='altar'&&objective.progress+1<objective.target){objective.progress+=1;if(encounter){encounter.status='active';this.spawnEncounter(encounter);}this.notify(`祭坛守护 ${objective.progress}/${objective.target}`);}else{objective.progress=objective.target;this.completeObjective(objective,encounter);}}
  if(stage.boss.status==='locked'&&completedSigils(stage)>=stage.requiredSigils){stage.boss.status='available';this.notify('钥印共鸣：遗迹守卫入口已开放');}
  const bossEncounter=this.hostEncounters.get(stage.boss.roomId);if(bossEncounter){bossEncounter.kind='sealed';bossEncounter.enemyCount=0;if(stage.boss.status==='locked'||stage.boss.status==='available')bossEncounter.status='dormant';}
  if(stage.boss.status==='available'&&players.length>0&&players.every(id=>id===stage.boss.roomId))this.startBoss(stage,bossEncounter,partySize);
  if(stage.boss.status==='active')this.updateBoss(stage,bossEncounter,partySize,wallNow);
  if(stage.portal?.active&&wallNow>=this.stageAdvanceAt){const allInside=this.connectedPlayers().every(p=>distance(p,stage.portal!)<=55);if(allInside){this.stageAdvanceAt=wallNow+750;if(stage.index===2)void parti.action('completeRun',{eventId:`victory:${this.state?.runSeed}`});else void parti.action('advanceStage',{eventId:`advance:${this.state?.runSeed}:${stage.index}`});}}
 }
 private completeObjective(objective:StageProgress['objectives'][number],encounter?:RegionEncounter){objective.status='completed';objective.progress=objective.target;if(encounter){encounter.status='cleared';encounter.clearedAt=Date.now();}this.notify(`获得钥印 · ${completedSigils(this.hostStage!)}/${this.hostStage!.requiredSigils}`);}
 private startBoss(stage:StageProgress,encounter:RegionEncounter|undefined,partySize:number){const room=this.map.rooms.find(r=>r.id===stage.boss.roomId);if(!room)return;stage.status='boss';stage.boss.status='active';stage.boss.phase=1;stage.boss.nextMechanicAt=Date.now()+7000;const id=`boss:${stage.index}:${room.id}`;stage.boss.enemyId=id;if(encounter){encounter.status='active';encounter.activatedAt=Date.now();}const hp=Math.round((650+partySize*260)*(stage.index===0?1:stage.index===1?1.2:1.4)),kind:EnemyKind=stage.index===0?'ruin-guardian':stage.index===1?'bog-heart':'forge-titan';this.hostEnemies.set(id,{id,roomId:room.id,kind,x:room.x+room.width/2,y:room.y+room.height/2,hp,maxHp:hp,radius:58,targetId:null,nextAttackAt:Date.now()+1200,attack:null,statuses:[],controls:{...ZERO_CONTROL},flashUntil:0,revision:0,behaviorPhase:1,mechanicState:'shielded'});this.notify(stage.index===0?'遗迹守卫苏醒':stage.index===1?'腐沼之心苏醒':'熔炉泰坦启动');}
 private updateBoss(stage:StageProgress,encounter:RegionEncounter|undefined,partySize:number,wallNow:number){const bossId=stage.boss.enemyId,boss=bossId?this.hostEnemies.get(bossId):undefined;if(!boss){stage.boss.status='defeated';stage.status='complete';stage.completedAt=wallNow;if(encounter){encounter.status='cleared';encounter.clearedAt=wallNow;}for(const[id,e]of this.hostEnemies)if(e.roomId===stage.boss.roomId)this.hostEnemies.delete(id);const room=this.map.rooms.find(r=>r.id===stage.boss.roomId)!;stage.portal={roomId:room.id,x:room.x+room.width/2,y:room.y+room.height/2,active:true};this.notify(stage.index===2?'熔炉泰坦已击败 · 集合完成远征':'Boss 已击败 · 全员进入传送门');return;}const nextPhase=boss.hp<=boss.maxHp*.33?3:boss.hp<=boss.maxHp*.66?2:1;if(nextPhase>stage.boss.phase){stage.boss.phase=nextPhase;boss.behaviorPhase=nextPhase;this.spawnBossAdds(stage.boss.roomId,partySize);this.notify(`Boss 进入第 ${nextPhase} 阶段`);}if(wallNow>=stage.boss.nextMechanicAt){stage.boss.nextMechanicAt=wallNow+Math.max(4500,8000-stage.boss.phase*900);this.spawnBossAdds(stage.boss.roomId,stage.boss.phase);this.activateBossHazards(stage);}}
 private spawnBossAdds(roomId:string,count:number){const encounter:RegionEncounter={roomId,kind:'sealed',status:'active',enemyCount:Math.min(4,count),activatedAt:Date.now(),clearedAt:null};this.spawnEncounter(encounter);}
 private connectedPlayers(){return Object.values(this.state?.players??{}).filter(p=>p.connected).map(p=>p.id===parti.playerId?{...p,x:this.local.x,y:this.local.y}:p);}
 private updateRegionEncounters(){if(!this.hostEncounters.size){const size=Object.values(this.state?.players??{}).filter(p=>p.connected).length;for(const encounter of createRegionEncounters(this.map,size))this.hostEncounters.set(encounter.roomId,encounter);}const playerRooms=this.connectedPlayerRooms(),wallNow=Date.now(),controlled=new Set([...(this.hostStage?.objectives.map(o=>o.roomId)??[]),...(this.hostStage?[this.hostStage.boss.roomId]:[]),...this.hostMerchants.values()].map(v=>typeof v==='string'?v:v.roomId));for(const encounter of this.hostEncounters.values()){if(controlled.has(encounter.roomId))continue;if(shouldActivateEncounter(encounter,playerRooms)){encounter.status='active';encounter.activatedAt=wallNow;this.spawnEncounter(encounter);if(encounter.kind==='sealed')this.notify('全员就位：封锁遭遇开始');}else if(encounter.status==='active'&&![...this.hostEnemies.values()].some(e=>e.roomId===encounter.roomId)){encounter.status='cleared';encounter.clearedAt=wallNow;for(const[id,p]of this.hostProjectiles)if(p.roomId===encounter.roomId)this.hostProjectiles.delete(id);if(encounter.kind==='sealed')this.notify('区域已清理，封锁解除');}}}
 private connectedPlayerRooms(){return Object.values(this.state?.players??{}).filter(p=>p.connected).map(p=>{const position=p.id===parti.playerId?this.local:p;return roomAt(this.map,position,24)?.id??null;});}
 private occupiedRooms(){const result=new Set<string>();for(const p of Object.values(this.state?.players??{})){if(!p.connected||p.downed)continue;const position=p.id===parti.playerId?this.local:p,room=roomAt(this.map,position);if(room)result.add(room.id);}return result;}
 private spawnEncounter(encounter:RegionEncounter){const room=this.map.rooms.find(r=>r.id===encounter.roomId);if(!room)return;const pools:Record<MapManifest['biome'],EnemyKind[]>={ruins:['chaser','shooter','water-fiend','shield-guard'],swamp:['mud-stalker','spore-pod','bog-witch','vine-hunter'],volcano:['lava-hound','ash-mage','obsidian-beetle','flame-construct']},elitePools:Record<MapManifest['biome'],EnemyKind[]>={ruins:['reflect-warden','resonance-priest'],swamp:['plague-mother','thunder-frog'],volcano:['core-colossus','magnet-priest']};for(let i=0;i<encounter.enemyCount;i++){const n=++this.eventSeq,elite=encounter.enemyCount>=5&&i===0,kind=(elite?elitePools[this.map.biome]:pools[this.map.biome])[(i+n)%(elite?2:4)]!,angle=(i/Math.max(1,encounter.enemyCount))*Math.PI*2,range=Math.min(room.width,room.height)*.27,x=room.x+room.width/2+Math.cos(angle)*range,y=room.y+room.height/2+Math.sin(angle)*range,id=`enemy:${encounter.roomId}:${Date.now().toString(36)}:${n}`,hp=Math.round((elite?180:kind==='chaser'||kind==='mud-stalker'||kind==='lava-hound'?75:100)*(1+Math.min(3,this.connectedPlayers().length-1)*.28));this.hostEnemies.set(id,{id,roomId:encounter.roomId,kind,x,y,hp,maxHp:hp,radius:elite?40:30,targetId:null,nextAttackAt:Date.now()+800+i*90,attack:null,statuses:[],controls:{...ZERO_CONTROL},flashUntil:0,revision:0,elite});}}
 private placeEnemy(enemy:EnemyState,x:number,y:number){const room=this.map.rooms.find(r=>r.id===enemy.roomId);if(!room)return;enemy.x=clamp(x,room.x+enemy.radius,room.x+room.width-enemy.radius);enemy.y=clamp(y,room.y+enemy.radius,room.y+room.height-enemy.radius);}
 private chooseAttack(e:EnemyState,d:number):EnemyAttackKind|null{const melee=['chaser','shield-guard','mud-stalker','vine-hunter','lava-hound','obsidian-beetle','core-colossus'],water=['water-fiend','bog-witch','thunder-frog','plague-mother'],boss=['ruin-guardian','bog-heart','forge-titan'];if(melee.includes(e.kind))return d<=105?'melee':null;if(boss.includes(e.kind))return d<=145?'melee':d>=210&&d<=540?(e.kind==='bog-heart'?'water-bolt':'bolt'):null;if(water.includes(e.kind))return d<=110?'water-slam':d>=180&&d<=430?'water-bolt':null;return d>=170&&d<=460?'bolt':d<=90?'melee':null;}
 private fireEnemyAttack(enemy:EnemyState,attack:NonNullable<EnemyState['attack']>,target:{x:number;y:number},now:number){const key=`${enemy.id}:${attack.firesAt}`;if(this.threatSeen.has(key))return;this.threatSeen.add(key);enemy.nextAttackAt=now+(enemy.kind==='chaser'?1150:enemy.kind==='shooter'?1800:1500);if(attack.kind==='bolt'||attack.kind==='water-bolt'){const v=normalize(enemy,target),speed=attack.kind==='bolt'?360:300,id=this.id('enemy-shot');this.hostProjectiles.set(id,{id,roomId:enemy.roomId,kind:attack.kind,sourceId:enemy.id,x:enemy.x,y:enemy.y,vx:v.x*speed,vy:v.y*speed,radius:attack.kind==='bolt'?12:18,damage:attack.kind==='bolt'?14:10,expiresAt:Date.now()+3500,control:attack.kind==='water-bolt'?{kind:'slow',strength:.65,durationMs:1800}:undefined});}}

 private simulateThreats(now:number){if(this.local.downed)return;const wallNow=Date.now();for(const e of this.enemies()){const a=e.attack;if(!a||a.targetId!==parti.playerId||wallNow<a.firesAt||wallNow>a.firesAt+180)continue;const id=`attack:${e.id}:${a.firesAt}`;if(this.threatSeen.has(id))continue;if((a.kind==='melee'&&distance(e,this.local)<=105)||(a.kind==='water-slam'&&distance(e,this.local)<=125)){this.threatSeen.add(id);this.takeDamage(a.kind==='melee'?16:12);const dir=normalize(e,this.local);this.local.controls=applyControl(this.local.controls,{kind:'knockback',strength:a.kind==='melee'?240:340,durationMs:300},dir,now);}}
  for(const p of this.enemyProjectiles()){const id=`projectile:${p.id}`;if(this.threatSeen.has(id)||!circleContains(p,p.radius,this.local,24))continue;this.threatSeen.add(id);this.takeDamage(p.damage);if(p.control)this.local.controls=applyControl(this.local.controls,p.control,normalize(p,this.local),now);if(p.kind==='water-bolt')this.addStatus('wet',1,4000,p.id);this.hostProjectiles.delete(p.id);void parti.action('reportProjectileHit',{projectileId:p.id});}}
 private simulateWeather(now:number){if(now<this.weatherAt)return;this.weatherAt=now+500;const burning=this.local.statuses.find(s=>s.kind==='burning');if(burning)this.takeDamage(burning.stacks*2);for(const env of this.environments()){if(env.kind==='blizzard'&&roomAt(this.map,env)?.id!==roomAt(this.map,this.local)?.id)continue;if(env.kind==='rain')this.addStatus('wet',1,2400,env.id);else if(!circleContains(env,env.radius,this.local,24))continue;else if(env.kind==='steam')this.takeDamage(3);else if(env.kind==='water-pool')this.addStatus('wet',1,2200,env.id);else if(env.kind==='ice-wall')this.addStatus('chilled',1,2400,env.id);else if(env.kind==='storm-field')this.takeDamage(this.local.statuses.some(s=>s.kind==='wet')?15:10);else if(env.kind==='fire-ring')this.addStatus('burning',1,3000,env.id);else if(env.kind==='gravity-well')this.local.controls=applyControl(this.local.controls,{kind:'knockback',strength:140,durationMs:800},normalize(this.local,env),now);else if(env.kind==='life-barrier'){this.local.hp=Math.min(100,this.local.hp+6);this.addStatus('shielded',1,1200,env.id);}else if(env.kind==='overflow-heal')this.local.hp=Math.min(100,this.local.hp+(env.power??1));else if(env.kind==='lightning-barrage')this.takeDamage(24);else if(env.kind==='blizzard'){this.addStatus('chilled',1,1800,env.id);this.local.controls=applyControl(this.local.controls,{kind:'slow',strength:.55,durationMs:900},{x:0,y:0},now);}}}
 private simulateHazards(now:number){if(now<this.weatherAt-700)return;const wallNow=Date.now(),roomId=roomAt(this.map,this.local)?.id;for(const h of this.hostHazards.values()){if(h.roomId!==roomId)continue;if(this.isHost()&&(h.kind==='vent'||h.kind==='falling-rock')){const cycle=(wallNow+Math.abs(hash(h.id)))%6000,hPhase=cycle<3600?'idle':cycle<4800?'warning':'active';if(h.phase!==hPhase){h.phase=hPhase;h.revision++;}}if(!circleContains(h,h.radius,this.local,24))continue;if(h.kind==='shallow-water'||h.kind==='conductive-water')this.addStatus('wet',1,2200,h.id);else if(h.kind==='mud')this.local.controls=applyControl(this.local.controls,{kind:'slow',strength:.62,durationMs:1000},{x:0,y:0},now);else if(h.kind==='poison-water')this.takeDamage(3);else if(h.kind==='lava')this.addStatus('burning',1,2400,h.id),this.takeDamage(5);else if((h.kind==='vent'||h.kind==='falling-rock')&&h.phase==='active')this.takeDamage(9);}}
 private simulateWorldEvents(){for(const event of this.hostEvents.values()){if(event.status!=='available')continue;const nearby=this.connectedPlayers().some(p=>distance(event,p)<=70);if(!nearby)continue;if((event.kind==='chest'||event.kind==='cursed-chest')&&this.isHost()){const base=generateEquipment(this.map.stageSeed,Math.abs(hash(`${event.id}:base`)),this.map.biome);this.hostLoot.set(`loot:${event.id}:base`,{id:`loot:${event.id}:base`,x:event.x-20,y:event.y,roomId:event.roomId,item:base,wants:[],droppedByPlayerId:null,ownerPriorityUntil:0});const scroll=generateScroll(this.map.stageSeed,event.id,event.kind);if(scroll)this.hostLoot.set(`loot:${event.id}:scroll`,{id:`loot:${event.id}:scroll`,x:event.x+20,y:event.y,roomId:event.roomId,item:scroll,wants:[],droppedByPlayerId:null,ownerPriorityUntil:0});event.status='completed';event.revision++;this.notify(scroll?'宝箱中发现了卷轴':'宝箱已经开启');}else if(distance(event,this.local)<=70&&event.kind==='healing-spring'&&this.local.hp<100){this.local.hp=Math.min(100,this.local.hp+25);event.status='completed';event.revision++;this.notify('恢复泉恢复了生命');}else if(distance(event,this.local)<=70&&event.kind==='element-shrine'){this.addStatus('shielded',1,12000,event.id);event.status='completed';event.revision++;this.notify('元素祭坛赐予护盾');}}}
 private activateBossHazards(stage:StageProgress){const roomHazards=[...this.hostHazards.values()].filter(h=>h.roomId===stage.boss.roomId);for(const hazard of roomHazards){hazard.phase='warning';hazard.startsAt=Date.now();hazard.endsAt=Date.now()+2400;hazard.revision++;}this.notify(stage.index===0?'符文柱共鸣，落石将至':stage.index===1?'毒水扩散，净化台启动':'高热爆发，转移至安全区');}
 private takeDamage(amount:number){const shield=this.local.statuses.find(s=>s.kind==='shielded');if(shield){shield.stacks-=1;if(shield.stacks<=0)this.local.statuses=this.local.statuses.filter(s=>s!==shield);this.notify('护盾吸收伤害');return;}amount=Math.max(1,Math.round(amount*(1-clamp(this.bonuses().damageReduction,0,.6))));this.local.hp=Math.max(0,this.local.hp-amount);this.addFloat(this.local.x,this.local.y-35,`-${amount}`,'#ff6b75');if(!this.local.hp){this.local.downed=true;this.interruptCast('你倒下了');this.clearMoveTarget();}}
 private takeRawDamage(amount:number){amount=Math.max(0,Math.round(amount));this.local.hp=Math.max(1,this.local.hp-amount);if(amount)this.addFloat(this.local.x,this.local.y-35,`-${amount}`,'#ff6b75');}

 private receive(state:GameState){
  const old=this.state?.phase,oldSeed=this.state?.runSeed,oldStage=this.state?.stageIndex,seedChanged=oldSeed!==state.runSeed||oldStage!==state.stageIndex;this.state=state;this.remoteCasts=new Map(Object.values(state.activeCasts).filter(c=>c.sourcePlayerId!==parti.playerId&&c.phase==='committed').map(c=>[c.castId,{...c,origin:{...c.origin},target:{...c.target}}]));
  if(seedChanged){this.map=generateMap(state.runSeed,state.stageIndex);this.explored.clear();this.reportedRoom='';this.hostStage=null;this.hostHazards=new Map(this.map.hazards.map(h=>[h.id,{...h}]));this.hostEvents=new Map(this.map.events.map(e=>[e.id,{...e}]));this.stageAdvanceAt=0;}
  for(const id of state.exploredRoomIds)this.explored.add(id);const isHostNow=this.isHost(),becameHost=isHostNow&&!this.actingAsHost;this.actingAsHost=isHostNow;this.worldSeq=Math.max(this.worldSeq,state.worldSequence);
  for(const[id,p]of this.pendingDamage){const authoritative=state.enemies[p.enemyId];if(!authoritative||(p.amount>=0?authoritative.hp<=p.expectedHp:authoritative.hp>=p.expectedHp))this.pendingDamage.delete(id);}const me=this.me();if(!me)return;
  if((old!=='running'&&state.phase==='running')||(seedChanged&&state.phase==='running')){this.local={x:me.x,y:me.y,z:0,hp:me.hp,downed:me.downed,kills:me.kills,statuses:[],elements:[],controls:{...ZERO_CONTROL}};this.clearMoveTarget();this.hostEnemies.clear();this.hostProjectiles.clear();this.hostEnvironments.clear();this.hostEncounters.clear();this.hostLoot.clear();this.hostMerchants.clear();this.hostHazards=new Map(this.map.hazards.map(h=>[h.id,{...h}]));this.hostEvents=new Map(this.map.events.map(e=>[e.id,{...e}]));this.seen.clear();this.threatSeen.clear();this.messages.clear();this.notify('点击场地开始移动','tip',0,3200,'movement-tip');this.discoverCurrentRoom();}
  if(!isHostNow){const pendingByEnemy=new Map<string,number>();for(const p of this.pendingDamage.values())pendingByEnemy.set(p.enemyId,(pendingByEnemy.get(p.enemyId)??0)+p.amount);const entries=Object.values(state.enemies).map(e=>[e.id,{...e,hp:e.hp-(pendingByEnemy.get(e.id)??0)}] as const).filter(([,e])=>e.hp>0);this.hostEnemies=new Map(entries);this.loadSharedWorld(state);}
  else if(becameHost){this.hostEnemies=new Map(Object.values(state.enemies).filter(e=>e.hp>0).map(e=>[e.id,{...e}]));this.loadSharedWorld(state);}
 }
 private loadSharedWorld(state:GameState){this.hostProjectiles=new Map(Object.values(state.projectiles).map(p=>[p.id,{...p}]));this.hostEnvironments=new Map(Object.values(state.environments).map(e=>[e.id,{...e}]));this.hostHazards=new Map((Object.values(state.hazards).length?Object.values(state.hazards):this.map.hazards).map(e=>[e.id,{...e}]));this.hostEvents=new Map((Object.values(state.events).length?Object.values(state.events):this.map.events).map(e=>[e.id,{...e}]));this.hostEncounters=new Map(Object.values(state.encounters).map(e=>[e.roomId,{...e}]));this.hostLoot=new Map(Object.values(state.loot).map(e=>[e.id,{...e,wants:[...e.wants]}]));this.hostMerchants=new Map(Object.values(state.merchants).map(e=>[e.id,{...e,stock:[...e.stock]}]));this.hostStage=state.stage;}
 private discoverCurrentRoom(){const room=roomAt(this.map,this.local);if(!room)return;this.explored.add(room.id);if(room.id===this.reportedRoom)return;this.reportedRoom=room.id;void parti.action('exploreRoom',{roomId:room.id});}
 private clearMoveTarget(){this.moveTarget=null;this.moveHeading=null;this.moveStuckSince=0;this.moveBestDistance=Infinity;}
 private canPlayerOccupy(target:Point){if(!isWalkable(this.map,target,24)||this.environments().some(e=>e.kind==='ice-wall'&&circleContains(e,e.radius,target,24)))return false;const room=roomAt(this.map,this.local),encounter=room?this.hostEncounters.get(room.id):undefined;if(!room||encounter?.kind!=='sealed'||encounter.status!=='active')return true;return roomAt(this.map,target,24)?.id===room.id;}
 private spellPathValid(target:Point){const startRoom=roomAt(this.map,this.local),targetRoom=roomAt(this.map,target,8);return Boolean(startRoom&&targetRoom?.id===startRoom.id&&isWalkable(this.map,target,8)&&!this.environments().some(e=>e.kind==='ice-wall'&&circleContains(e,e.radius,target,8)));}
 private beamEnd(angle:number,range=1600){return clippedRay(this.local,angle,range,p=>this.spellPathValid(p));}
 private isBoss(enemy:EnemyState){return['ruin-guardian','bog-heart','forge-titan'].includes(enemy.kind);}
 private movePlayer(target:Point){const moved=moveWithinMap(this.map,this.local,target),room=roomAt(this.map,this.local),encounter=room?this.hostEncounters.get(room.id):undefined;if(!room||encounter?.kind!=='sealed'||encounter.status!=='active')return moved;const radius=24;if(moved.x>=room.x+radius&&moved.x<=room.x+room.width-radius&&moved.y>=room.y+radius&&moved.y<=room.y+room.height-radius)return moved;return{x:this.local.x,y:this.local.y};}
 private onEnemyDamage(raw:Record<string,unknown>){const id=String(raw.eventId??'');if(!id||this.seen.has(id))return;this.seen.add(id);const enemy=this.hostEnemies.get(String(raw.enemyId));if(!enemy)return;enemy.hp=clamp(enemy.hp-(Number(raw.amount)||0),0,enemy.maxHp);enemy.flashUntil=performance.now()+160;enemy.revision+=1;const incoming=(Array.isArray(raw.statuses)?raw.statuses:[])as StatusInstance[];if(incoming.length)enemy.statuses=incoming.map(s=>({...s}));const direction=validPoint(raw.direction)?raw.direction:{x:0,y:0};for(const c of (Array.isArray(raw.controls)?raw.controls:[])as ControlEffect[])enemy.controls=applyControl(enemy.controls,c,direction,performance.now());if(enemy.hp<=0){if(this.isHost())this.handleEnemyDeath(enemy);this.hostEnemies.delete(enemy.id);}}
 private onPlayerEffect(raw:Record<string,unknown>){if(raw.targetPlayerId!==parti.playerId)return;const id=String(raw.eventId??'');if(this.seen.has(id))return;this.seen.add(id);const direction=validPoint(raw.direction)?raw.direction:{x:0,y:0};this.applySelf((Array.isArray(raw.effects)?raw.effects:[])as SpellEffect[],direction);}
 private onSpellVisual(shared:SharedSpellVisual){if(shared.sourcePlayerId===parti.playerId||this.seen.has(shared.eventId))return;this.seen.add(shared.eventId);const now=performance.now();this.visuals.push({id:shared.eventId,kind:shared.kind,origin:{...shared.origin},target:{...shared.target},radius:shared.radius,angle:shared.angle,coneAngle:shared.coneAngle,color:shared.color,startedAt:now,endsAt:now+shared.durationMs});}
 private onRealtimeFrame(frame:PlayerRealtimeFrame){const id=frame.playerId;if(!id||id===parti.playerId)return;const current=this.remoteMotion.get(id);if(current&&frame.sequence<=current.current.sequence)return;const fallback=current?.current??frame;this.remoteMotion.set(id,{previous:fallback,current:frame,receivedAt:performance.now()});const player=this.state?.players[id];if(player){player.x=frame.x;player.y=frame.y;player.z=frame.z;player.activity=frame.activity;player.elements=[...frame.activity.elements];player.realtimeSequence=frame.sequence;}}
 private onSpellCast(cast:ActiveCast){if(cast.sourcePlayerId===parti.playerId)return;const old=this.remoteCasts.get(cast.castId);if(old&&cast.revision<=old.revision)return;if(cast.phase==='cancelled'||cast.phase==='ended'||cast.phase==='resolved')this.remoteCasts.delete(cast.castId);else this.remoteCasts.set(cast.castId,{...cast,origin:{...cast.origin},target:{...cast.target}});}
 private remotePosition<T extends Point&{z:number}>(id:string,fallback:T):T{const motion=this.remoteMotion.get(id);if(!motion)return fallback;const position=interpolateRealtime(motion.previous,motion.current,motion.receivedAt,performance.now());return{...fallback,...position} as T;}
 private drawRemoteCasts(){for(const cast of this.remoteCasts.values()){if(cast.phase!=='committed')continue;const player=this.state?.players[cast.sourcePlayerId],plan=player?resolveSpell(player.activity.elements):null;if(!plan||plan.presentation?.telegraph==='none')continue;const remaining=Math.max(0,cast.resolveAt-Date.now()),pulse=1+Math.sin(performance.now()/80)*.05,color=remaining<250?'#ff665f':'#ffcc66';if(plan.presentation?.telegraph==='target-circle')this.circle(cast.target,plan.radius*pulse,color,false);}}
 private onEnvironment(env:EnvironmentState){if(this.isHost())this.hostEnvironments.set(env.id,{...env});}
 private onLootDropped(loot:LootEntity){if(this.isHost())this.hostLoot.set(loot.id,{...loot,wants:[...loot.wants]});}
 private handleEnemyDeath(enemy:EnemyState){const dropRoll=Math.abs(hash(enemy.id))%100,boss=this.isBoss(enemy),count=boss?2:enemy.elite?1:dropRoll<12?1:0;for(let i=0;i<count;i++){const item=generateEquipment(this.map.stageSeed,Math.abs(hash(`${enemy.id}:item:${i}`)),this.map.biome),loot:LootEntity={id:`loot:${enemy.id}:${i}`,x:enemy.x+i*35,y:enemy.y,roomId:enemy.roomId,item,wants:[],droppedByPlayerId:null,ownerPriorityUntil:0};this.hostLoot.set(loot.id,loot);}const scroll=generateScroll(this.map.stageSeed,enemy.id,boss?'boss':'elite');if((boss||enemy.elite)&&scroll){const loot:LootEntity={id:`loot:${enemy.id}:scroll`,x:enemy.x+count*35,y:enemy.y,roomId:enemy.roomId,item:scroll,wants:[],droppedByPlayerId:null,ownerPriorityUntil:0};this.hostLoot.set(loot.id,loot);}const recipients=this.connectedPlayers().filter(p=>roomAt(this.map,p)?.id===enemy.roomId).map(p=>p.id);void parti.action('awardGold',{eventId:`reward:${enemy.id}`,playerIds:recipients,amount:boss?50:enemy.elite?20:8});}

 render(){const c=mainContext,w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio;this.hud=computeHudLayout(w,h);c.save();c.setTransform(this.ratio,0,0,this.ratio,0,0);c.clearRect(0,0,w,h);c.fillStyle='#100d17';c.fillRect(0,0,w,h);this.buttons=[];this.uiActions=[];c.save();c.beginPath();c.rect(this.view.x,this.view.y,this.view.w,this.view.h);c.clip();this.drawArena();c.restore();this.drawHud(w);this.drawEconomyUi(w,h);this.drawSpellbook(w,h);if(this.inventoryOpen||this.spellbookOpen)this.drawMenuButtons();if(!this.state)this.overlay(w,h,'连接远征','');else if(this.state.phase==='lobby')this.drawLobby(w,h);else if(this.state.phase==='gameover')this.drawGameOver(w,h);else if(this.state.phase==='victory')this.drawVictory(w,h);c.restore();}
 private drawArena(){const c=mainContext,now=performance.now();c.fillStyle='#0d0b12';c.fillRect(this.view.x,this.view.y,this.view.w,this.view.h);this.drawMap();this.drawStageMarkers();this.drawWorldEconomy();this.drawRemoteCasts();for(const env of this.environments()){if(env.kind==='rain'){c.fillStyle='rgba(70,140,255,.14)';c.fillRect(this.view.x,this.view.y,this.view.w,this.view.h);}else this.circle(env,env.radius,'rgba(220,220,230,.25)',true);}for(const s of this.shots)this.circle(s,s.radius,colors[s.element],true);for(const p of this.enemyProjectiles())this.circle(p,p.radius,p.kind==='water-bolt'?'#55bfff':'#e3a4ff',true);for(const v of this.visuals)this.drawVisual(v,now);for(const e of this.enemies())this.drawEnemy(e,now);for(const p of Object.values(this.state?.players??{})){const pos=p.id===parti.playerId?this.local:this.remotePosition(p.id,p);this.drawPlayer(pos,p.id===parti.playerId?'#ffe06a':'#78b7ff',p.name,p.activity);}this.drawAim(now);for(const f of this.floats){const age=(now-f.startedAt)/(f.endsAt-f.startedAt),p=this.toScreen({x:f.x,y:f.y-age*45});this.text(f.text,p.x,p.y,14,f.color,'center');}}
 private drawMap(){const c=mainContext;for(const corridor of this.map.corridors){if(!this.explored.has(corridor.fromRoomId)&&!this.explored.has(corridor.toRoomId))continue;const p=this.toScreen(corridor);c.fillStyle='#4b3b43';c.fillRect(p.x,p.y,corridor.width*this.view.scale,corridor.height*this.view.scale);}for(const room of this.map.rooms){if(!this.explored.has(room.id))continue;const p=this.toScreen(room);c.fillStyle='#443239';c.fillRect(p.x,p.y,room.width*this.view.scale,room.height*this.view.scale);c.strokeStyle='#9a6849';c.lineWidth=4;c.strokeRect(p.x,p.y,room.width*this.view.scale,room.height*this.view.scale);c.strokeStyle='rgba(211,167,111,.12)';c.lineWidth=1;for(let x=80;x<room.width;x+=80){const a=this.toScreen({x:room.x+x,y:room.y}),b=this.toScreen({x:room.x+x,y:room.y+room.height});c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}for(let y=80;y<room.height;y+=80){const a=this.toScreen({x:room.x,y:room.y+y}),b=this.toScreen({x:room.x+room.width,y:room.y+y});c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}const encounter=this.hostEncounters.get(room.id),lockedBoss=this.hostStage?.boss.roomId===room.id&&this.hostStage.boss.status==='locked';if(!lockedBoss&&encounter?.kind==='sealed'&&encounter.status!=='cleared'){const active=encounter.status==='active';c.strokeStyle=active?'#ff665f':'#d8a84e';c.lineWidth=active?8:4;c.strokeRect(p.x,p.y,room.width*this.view.scale,room.height*this.view.scale);this.text(active?'封锁战斗':'全员进入后触发',p.x+room.width*this.view.scale/2,p.y+28,15,active?'#ffb0a8':'#ffe09a','center');}}}
 private drawStageMarkers(){const stage=this.hostStage;if(!stage)return;const labels={elite:'精英钥印',altar:'守护祭坛',puzzle:'符文机关'} as const;for(const objective of stage.objectives){if(!this.explored.has(objective.roomId))continue;const room=this.map.rooms.find(r=>r.id===objective.roomId)!;const center={x:room.x+room.width/2,y:room.y+room.height/2};if(objective.kind==='puzzle'){for(const rune of puzzleRunes(this.map,room.id)){const done=rune.index<objective.progress;this.circle(rune,30,done?'#62df8a':rune.index===objective.progress?'#ffe268':'#6f6878',done);}}else this.circle(center,objective.status==='completed'?32:46,objective.status==='completed'?'#62df8a':'#e7bd55',objective.status==='completed');const p=this.toScreen({x:center.x,y:center.y-65});this.text(`${labels[objective.kind]} ${objective.status==='completed'?'✓':objective.kind==='altar'&&objective.status==='active'?`${objective.progress}/${objective.target}`:''}`,p.x,p.y,14,objective.status==='completed'?'#9effb6':'#ffe09a','center');}
  const bossRoom=this.map.rooms.find(r=>r.id===stage.boss.roomId);if(bossRoom&&this.explored.has(bossRoom.id)){const center={x:bossRoom.x+bossRoom.width/2,y:bossRoom.y+bossRoom.height/2},p=this.toScreen({x:center.x,y:center.y-82});if(stage.boss.status!=='active'&&stage.boss.status!=='defeated')this.circle(center,58,stage.boss.status==='available'?'#ff6b5e':'#51464f',false);this.text(stage.boss.status==='locked'?'Boss封印中':stage.boss.status==='available'?'全员进入以挑战Boss':stage.boss.status==='active'?`遗迹守卫 · 阶段 ${stage.boss.phase}`:'Boss已击败',p.x,p.y,15,stage.boss.status==='available'?'#ffb0a8':'#ddd','center');}
  if(stage.portal?.active){const pulse=56+Math.sin(performance.now()/180)*7;this.circle(stage.portal,pulse,'rgba(130,105,255,.55)',true);this.circle(stage.portal,70,'#b8a5ff',false);const p=this.toScreen({x:stage.portal.x,y:stage.portal.y-90});this.text('全员进入传送门',p.x,p.y,17,'#e5dcff','center');}}
 private drawWorldEconomy(){for(const loot of this.hostLoot.values()){if(!this.explored.has(loot.roomId))continue;this.circle(loot,18,isScroll(loot.item)?'#f0c75e':loot.item.rarity==='rare'?'#c88cff':loot.item.rarity==='uncommon'?'#70d996':'#e0d5bc',true);const p=this.toScreen({x:loot.x,y:loot.y-28});this.text(`${loot.item.name}${loot.wants.length?` · ${loot.wants.length}人想要`:''}`,p.x,p.y,11,'#fff','center');}for(const merchant of this.hostMerchants.values()){if(!this.explored.has(merchant.roomId))continue;this.circle(merchant,38,'#55b9a7',true);const p=this.toScreen({x:merchant.x,y:merchant.y-52});this.text('遗迹商人',p.x,p.y,14,'#aaffef','center');}}
 private drawEconomyUi(w:number,h:number){const me=this.me();if(!me||this.state?.phase!=='running')return;const c=mainContext,{inventoryButton,spellbookButton}=this.hud;cbox(c,inventoryButton.x,inventoryButton.y,inventoryButton.w,inventoryButton.h,this.inventoryOpen?'rgba(118,84,60,.94)':'rgba(32,25,40,.82)');this.text(`背包 ${me.inventory.length}/9`,inventoryButton.x+inventoryButton.w/2,inventoryButton.y+inventoryButton.h/2+5,11,'#fff','center');this.uiActions.push({...inventoryButton,kind:'toggle-inventory'});cbox(c,spellbookButton.x,spellbookButton.y,spellbookButton.w,spellbookButton.h,this.spellbookOpen?'rgba(93,71,120,.94)':'rgba(32,25,40,.82)');this.text('法术书',spellbookButton.x+spellbookButton.w/2,spellbookButton.y+spellbookButton.h/2+5,11,'#fff','center');this.uiActions.push({...spellbookButton,kind:'toggle-spellbook'});if(!this.inventoryOpen)return;const panelW=Math.min(560,w-16),panelH=Math.min(430,h-16),x=(w-panelW)/2,y=(h-panelH)/2,rowH=panelH<410?48:56,rowGap=4;cbox(c,0,0,w,h,'rgba(8,6,12,.48)');cbox(c,x,y,panelW,panelH,'rgba(20,16,28,.97)');this.text(`金币 ${me.gold} · 战斗中不可换装`,x+16,y+25,13,'#ffe09a');const slots=[me.equipment.staff,me.equipment.robe,me.equipment.ring],slotNames=['法杖','法袍','戒指'];for(let i=0;i<3;i++){const bx=x+10+i*(panelW-20)/3,bw=(panelW-32)/3,item=slots[i];cbox(c,bx,y+34,bw,40,'#2d2736');this.text(`${slotNames[i]}：${item?.name??'空'}`,bx+5,y+59,10,item?'#fff':'#888');if(item){this.uiActions.push({x:bx+bw-32,y:y+35,w:30,h:38,kind:'drop',itemId:item.id});this.text('丢',bx+bw-17,y+59,10,'#ffb0a8','center');}}
  const cellW=(panelW-32)/3;for(let i=0;i<9;i++){const item=me.inventory[i],col=i%3,row=Math.floor(i/3),bx=x+10+col*(cellW+6),by=y+80+row*(rowH+rowGap);cbox(c,bx,by,cellW,rowH,item?'#373043':'#211d28');if(!item){this.text('空',bx+7,by+rowH/2+4,10,'#666');continue;}this.text(item.name,bx+5,by+18,11,isScroll(item)?'#f3d477':item.rarity==='rare'?'#d3a2ff':item.rarity==='uncommon'?'#83e2a1':'#eee');this.text(isScroll(item)?`卷轴 · ${Math.max(0,Math.ceil(((me.scrollCooldowns[item.spellId]??0)-Date.now())/1000))}s`:item.affixes[0]??this.itemStats(item),bx+5,by+36,9,'#bbb');if(!isScroll(item))this.uiActions.push({x:bx,y:by,w:cellW-32,h:rowH,kind:'equip',itemId:item.id});this.uiActions.push({x:bx+cellW-32,y:by,w:32,h:rowH,kind:'drop',itemId:item.id});this.text('丢',bx+cellW-16,by+rowH/2+4,10,'#ffb0a8','center');}
  const nearbyLoot=[...this.hostLoot.values()].filter(loot=>distance(this.local,loot)<=120),merchant=[...this.hostMerchants.values()].find(v=>distance(this.local,v)<=140);let sideY=y+80+3*(rowH+rowGap)+4,available=Math.max(0,Math.floor((y+panelH-sideY-6)/36));for(const loot of nearbyLoot.slice(0,Math.min(3,available))){cbox(c,x+10,sideY,panelW-20,32,'#403749');this.text(`掉落：${loot.item.name}`,x+18,sideY+21,11,'#fff');this.uiActions.push({x:x+panelW-142,y:sideY,w:66,h:32,kind:'want',entityId:loot.id},{x:x+panelW-74,y:sideY,w:64,h:32,kind:'pickup',entityId:loot.id});this.text(loot.wants.includes(parti.playerId??'')?'取消':'想要',x+panelW-109,sideY+21,10,'#ffe09a','center');this.text('拾取',x+panelW-42,sideY+21,10,'#aaffc2','center');sideY+=36;available--;}
  if(merchant&&available>0){for(const entry of merchant.stock.slice(0,available)){cbox(c,x+10,sideY,panelW-20,32,'#25423d');this.text(`${entry.item.name} · ${entry.price}金币`,x+18,sideY+21,11,'#d8fff6');this.uiActions.push({x:x+panelW-86,y:sideY,w:76,h:32,kind:'buy',entityId:merchant.id,itemId:entry.item.id});this.text('购买',x+panelW-48,sideY+21,10,'#fff','center');sideY+=36;}}}
 private drawSpellbook(w:number,h:number){if(!this.spellbookOpen||this.state?.phase!=='running')return;const c=mainContext,pw=Math.min(700,w-16),ph=Math.min(520,h-16),x=(w-pw)/2,y=(h-ph)/2,me=this.me();cbox(c,0,0,w,h,'rgba(8,6,12,.48)');cbox(c,x,y,pw,ph,'rgba(18,14,27,.97)');this.text(`法术书 · 特殊组合 ${this.state.discoveredRecipeIds.length}/${RECIPES.length}`,x+18,y+30,18,'#ffe8a8');this.text('特殊组合通过释放发现；携带卷轴立即解锁强化组合',x+18,y+51,11,'#bdb3c9');let row=0,rowH=ph<430?42:48;for(const recipe of RECIPES){if(!this.state.discoveredRecipeIds.includes(recipe.id))continue;const plan=resolveSpell(recipe.pattern)!;const damage=plan.effects.filter(e=>e.type==='damage').reduce((n,e)=>n+e.amount,0),heal=plan.effects.filter(e=>e.type==='heal').reduce((n,e)=>n+e.amount,0),yy=y+78+row*rowH;if(yy>y+ph-20)break;cbox(c,x+12,yy-20,pw-24,rowH-5,row%2?'#272032':'#30263b');this.text(`${plan.name}  ${recipe.pattern.map(e=>labels[e]).join(' → ')}`,x+22,yy-1,13,'#fff');this.text(`${plan.delivery}${damage?` · 伤害 ${damage}`:''}${heal?` · 治疗 ${heal}`:''}${plan.radius?` · 范围 ${Math.round(plan.radius)}`:''}`,x+22,yy+15,10,'#b9d9ff');row++;}for(const scroll of SCROLLS){const count=me?.inventory.filter(item=>isScroll(item)&&item.spellId===scroll.spellId).length??0;if(!count)continue;const yy=y+78+row*rowH;if(yy>y+ph-20)break;cbox(c,x+12,yy-20,pw-24,rowH-5,'#493d26');this.text(`卷轴 · ${scroll.name} ×${count}  ${scroll.pattern.map(e=>labels[e]).join(' → ')}`,x+22,yy-1,13,'#f3d477');this.text(`${scroll.description} · 冷却20秒`,x+22,yy+15,10,'#e6d5a2');row++;}if(!row)this.text('尚未发现特殊配方或携带卷轴。',x+pw/2,y+ph/2,14,'#aaa','center');}
 private drawMenuButtons(){const c=mainContext,{inventoryButton,spellbookButton}=this.hud,me=this.me();cbox(c,inventoryButton.x,inventoryButton.y,inventoryButton.w,inventoryButton.h,this.inventoryOpen?'rgba(118,84,60,.98)':'rgba(32,25,40,.94)');this.text(this.inventoryOpen?'关闭':`背包 ${me?.inventory.length??0}/9`,inventoryButton.x+inventoryButton.w/2,inventoryButton.y+inventoryButton.h/2+5,11,'#fff','center');cbox(c,spellbookButton.x,spellbookButton.y,spellbookButton.w,spellbookButton.h,this.spellbookOpen?'rgba(93,71,120,.98)':'rgba(32,25,40,.94)');this.text(this.spellbookOpen?'关闭':'法术书',spellbookButton.x+spellbookButton.w/2,spellbookButton.y+spellbookButton.h/2+5,11,'#fff','center');}
 private itemStats(item:EquipmentItem){const parts:string[]=[];if(item.stats.spellPower)parts.push(`威力+${Math.round(item.stats.spellPower*100)}%`);if(item.stats.castSpeed)parts.push(`施法+${Math.round(item.stats.castSpeed*100)}%`);if(item.stats.damageReduction)parts.push(`减伤+${Math.round(item.stats.damageReduction*100)}%`);if(item.stats.moveSpeed)parts.push(`移速+${Math.round(item.stats.moveSpeed*100)}%`);return parts.join(' ')||'基础装备';}
 private drawAim(now:number){const state=this.aim;if(state){const origin=this.toScreen(this.local),angle=angleTo(this.local,state.target),color=colors[state.plan.elements[0]!];mainContext.strokeStyle=color;mainContext.fillStyle=`${color}33`;mainContext.lineWidth=3;if(state.plan.delivery==='cone'){mainContext.beginPath();mainContext.moveTo(origin.x,origin.y);mainContext.arc(origin.x,origin.y,state.plan.range*this.view.scale,angle-state.plan.coneAngle/2,angle+state.plan.coneAngle/2);mainContext.closePath();mainContext.fill();mainContext.stroke();}else if(state.plan.delivery==='targeted'||state.plan.delivery==='area'){this.circle(state.target,state.plan.radius,color,false);}else if(state.plan.delivery==='projectile'){const end=this.toScreen(state.target);mainContext.beginPath();mainContext.moveTo(origin.x,origin.y);mainContext.lineTo(end.x,end.y);mainContext.stroke();}else if(state.plan.delivery==='beam'){const end=this.toScreen(this.beamEnd(angle,state.plan.range));mainContext.beginPath();mainContext.moveTo(origin.x,origin.y);mainContext.lineTo(end.x,end.y);mainContext.stroke();const progress=clamp((now-state.startedAt)/state.plan.castMs,0,1);this.text(`吟唱 ${Math.round(progress*100)}%`,origin.x,origin.y-45,13,'#fff','center');}}
  if(this.pending&&(this.pending.plan.delivery==='targeted'||this.pending.plan.delivery==='area')){const pulse=1+Math.sin(now/80)*.05;this.circle(this.pending.target,this.pending.plan.radius*pulse,'#ffcc66',false);}if(this.beam){const power=beamPower(now-this.beam.startedAt),width=this.beam.plan.radius*power,blocked=this.beamEnd(this.beam.angle,this.beam.plan.range),max=distance(this.local,blocked),hits=beamTargets(this.local,this.beam.angle,width,this.enemies(),this.beam.plan.pierce,max),end=hits.length?{x:this.local.x+Math.cos(this.beam.angle)*hits.at(-1)!.along,y:this.local.y+Math.sin(this.beam.angle)*hits.at(-1)!.along}:blocked,a=this.toScreen(this.local),b=this.toScreen(end);mainContext.strokeStyle=colors[this.beam.plan.elements[0]!];mainContext.lineWidth=Math.max(3,width*2*this.view.scale);mainContext.beginPath();mainContext.moveTo(a.x,a.y);mainContext.lineTo(b.x,b.y);mainContext.stroke();}}
 private drawVisual(v:SpellVisual,now:number){const alpha=clamp((v.endsAt-now)/(v.endsAt-v.startedAt),0,1),color=colors[v.color];mainContext.globalAlpha=alpha;if(v.kind==='cone'){const o=this.toScreen(v.origin),half=(v.coneAngle??1.04)/2;mainContext.fillStyle=color;mainContext.beginPath();mainContext.moveTo(o.x,o.y);mainContext.arc(o.x,o.y,v.radius*this.view.scale,v.angle-half,v.angle+half);mainContext.closePath();mainContext.fill();}else if(v.kind==='beam'){const a=this.toScreen(v.origin),b=this.toScreen(v.target);mainContext.strokeStyle=color;mainContext.lineWidth=Math.max(5,v.radius*this.view.scale);mainContext.beginPath();mainContext.moveTo(a.x,a.y);mainContext.lineTo(b.x,b.y);mainContext.stroke();}else if(v.kind==='projectile'){const progress=clamp((now-v.startedAt)/(v.endsAt-v.startedAt),0,1),position={x:v.origin.x+(v.target.x-v.origin.x)*progress,y:v.origin.y+(v.target.y-v.origin.y)*progress};this.circle(position,Math.max(8,v.radius),color,true);}else this.circle(v.target,v.radius,color,true);mainContext.globalAlpha=1;}
 private drawEnemy(e:EnemyState,now:number){const c=mainContext,p=this.toScreen({x:e.x,y:e.y-e.controls.z}),r=e.radius*this.view.scale;c.strokeStyle=now<e.flashUntil?'#fff':e.kind==='water-fiend'?'#54baff':e.kind==='shooter'?'#d298ff':'#ff745f';c.lineWidth=5;c.strokeRect(p.x-r,p.y-r,r*2,r*2);c.fillStyle='#210d16';c.fillRect(p.x-r,p.y-r-11,r*2,6);c.fillStyle='#ff5868';c.fillRect(p.x-r,p.y-r-11,r*2*clamp(e.hp/e.maxHp,0,1),6);this.text(e.kind,p.x,p.y+4,11,'#fff','center');if(e.attack){const wallNow=Date.now(),t=clamp((e.attack.firesAt-wallNow)/(e.attack.firesAt-e.attack.startedAt),0,1);c.strokeStyle='#ffdf65';c.lineWidth=4;c.beginPath();c.arc(p.x,p.y,r+8,-Math.PI/2,-Math.PI/2+(1-t)*Math.PI*2);c.stroke();}this.drawStatuses(e.statuses,p.x,p.y+r+20);}
 private drawPlayer(p:{x:number;y:number;z:number;hp:number;downed:boolean;statuses?:StatusInstance[]},color:string,name:string,activity?:PlayerActivity){const c=mainContext,ground=this.toScreen(p),s=this.toScreen({x:p.x,y:p.y-p.z}),r=25*this.view.scale;c.fillStyle='rgba(0,0,0,.3)';c.beginPath();c.ellipse(ground.x,ground.y+r*.8,r,r*.35,0,0,Math.PI*2);c.fill();c.fillStyle=p.downed?'#555':color;c.fillRect(s.x-r,s.y-r,r*2,r*2);c.strokeStyle='#fff';c.lineWidth=2;c.strokeRect(s.x-r,s.y-r,r*2,r*2);const phase=activity&&activity.phase!=='idle'?` · ${{selecting:'选元素',aiming:'瞄准',windup:'前摇',channeling:'引导',recovery:'后摇',interrupted:'打断',downed:'倒地',stunned:'眩晕',idle:''}[activity.phase]}`:'';this.text(`${name}${phase}`,s.x,s.y-r-12,12,'#fff','center');if(activity?.elements.length)this.text(activity.elements.map(e=>labels[e]).join('+'),s.x,s.y-r-28,10,'#ffe9a8','center');c.fillStyle='#220b13';c.fillRect(s.x-r,s.y+r+5,r*2,5);c.fillStyle='#62e77b';c.fillRect(s.x-r,s.y+r+5,r*2*clamp(p.hp/100,0,1),5);this.drawStatuses(p.statuses??[],s.x,s.y+r+20);}
 private drawStatuses(statuses:StatusInstance[],x:number,y:number){const names:Record<StatusInstance['kind'],string>={wet:'潮湿',burning:'燃烧',chilled:'减速',frozen:'冻结',shocked:'感电',shielded:'护盾','fire-ward':'防火','frost-ward':'防冻','water-ward':'防潮',haste:'加速'};this.text(statuses.map(s=>names[s.kind]).join(' '),x,y,10,'#d9efff','center');}
 private drawHud(w:number){if(this.state?.phase!=='running')return;const c=mainContext,{status,message,minimap,elementPanel,elementCenters,compact}=this.hud,current=roomAt(this.map,this.local),encounter=current?this.hostEncounters.get(current.id):undefined,remaining=current?[...this.hostEnemies.values()].filter(e=>e.roomId===current.id).length:0,playerRooms=this.connectedPlayerRooms(),inside=current?playerRooms.filter(id=>id===current.id).length:0,sigils=this.hostStage?completedSigils(this.hostStage):0;
  cbox(c,status.x,status.y,status.w,status.h,'rgba(18,14,27,.78)');this.text(`HP ${this.local.hp}`,status.x+10,status.y+19,compact?12:13,'#fff');this.text(`击杀 ${this.local.kills}`,status.x+status.w-10,status.y+19,compact?10:11,'#d7cedd','right');c.fillStyle='#25101a';c.fillRect(status.x+10,status.y+27,status.w-20,8);c.fillStyle=this.local.hp<30?'#ff5968':'#62df7c';c.fillRect(status.x+10,status.y+27,(status.w-20)*clamp(this.local.hp/100,0,1),8);const statusNames:Record<StatusInstance['kind'],string>={wet:'潮湿',burning:'燃烧',chilled:'减速',frozen:'冻结',shocked:'感电',shielded:'护盾','fire-ward':'防火','frost-ward':'防冻','water-ward':'防潮',haste:'加速'},activeStatuses=this.local.statuses.slice(0,4).map(s=>statusNames[s.kind]);this.text(activeStatuses.join(' · ')||`钥印 ${sigils}/2 · 探索 ${this.explored.size}/${this.map.rooms.length}`,status.x+10,status.y+(compact?55:61),compact?9:10,activeStatuses.length?'#cdeeff':'#aaa');
  this.drawMinimap(minimap.x,minimap.y,minimap.w,minimap.h);cbox(c,elementPanel.x,elementPanel.y,elementPanel.w,elementPanel.h,'rgba(18,14,27,.74)');const plan=this.resolveEquippedSpell(this.local.elements),castStatus=this.beam?'持续施法':this.pending?'吟唱中':performance.now()<this.recoveryUntil?'施法后摇':this.aim?.plan.delivery==='beam'?'吟唱射线':this.local.elements.length?'准备完成':'选择元素或点击场地移动';this.text(`${castStatus}${this.local.elements.length?` · ${this.local.elements.map(e=>labels[e]).join('+')}`:''}${plan?` · ${plan.name}`:''}`,w/2,elementPanel.y+18,compact?10:12,'#fff','center');for(let i=0;i<elementCenters.length;i++){const button=elementCenters[i]!,element=ELEMENTS[i]!,r=button.r-3;this.buttons.push({element,x:button.x,y:button.y,r:button.r});c.fillStyle=colors[element];c.beginPath();c.arc(button.x,button.y,r,0,Math.PI*2);c.fill();c.strokeStyle='#f5e8d0';c.lineWidth=2;c.stroke();this.text(labels[element],button.x,button.y+(compact?5:6),compact?16:18,'#17111f','center');}
  const queued=this.messages.current(),context=encounter?.status==='active'?`${encounter.kind==='sealed'?'封锁遭遇':'游荡敌人'} · 剩余 ${remaining}`:encounter?.kind==='sealed'&&encounter.status==='dormant'?`集合区域 · 完整进入 ${inside}/${playerRooms.length}`:`钥印 ${sigils}/2 · 探索 ${this.explored.size}/${this.map.rooms.length}`,display=queued?(queued.count>1?`${queued.text} ×${queued.count}`:queued.text):context,category=queued?.category??'system',messageColor=category==='warning'?'rgba(105,34,42,.9)':category==='objective'?'rgba(74,57,27,.9)':'rgba(18,14,27,.82)';cbox(c,message.x,message.y,message.w,message.h,messageColor);this.text(display,message.x+message.w/2,message.y+message.h/2+(compact?4:5),compact?11:13,'#fff','center');}
 private drawMinimap(x:number,y:number,w:number,h:number){const c=mainContext,s=Math.min(w/this.map.width,h/this.map.height),ox=x+(w-this.map.width*s)/2,oy=y+(h-this.map.height*s)/2;c.fillStyle='rgba(9,7,12,.76)';c.fillRect(x,y,w,h);for(const corridor of this.map.corridors)if(this.explored.has(corridor.fromRoomId)||this.explored.has(corridor.toRoomId)){c.fillStyle='#70555d';c.fillRect(ox+corridor.x*s,oy+corridor.y*s,Math.max(1,corridor.width*s),Math.max(1,corridor.height*s));}for(const room of this.map.rooms)if(this.explored.has(room.id)){const encounter=this.hostEncounters.get(room.id);c.fillStyle=encounter?.kind==='sealed'&&encounter.status==='active'?'#ef5b5b':encounter?.kind==='sealed'&&encounter.status==='dormant'?'#d8a84e':encounter?.status==='cleared'?'#55745e':'#a47762';c.fillRect(ox+room.x*s,oy+room.y*s,Math.max(2,room.width*s),Math.max(2,room.height*s));}for(const player of Object.values(this.state?.players??{})){if(!player.connected)continue;const p=player.id===parti.playerId?this.local:player;c.fillStyle=player.id===parti.playerId?'#ffe06a':'#78b7ff';c.beginPath();c.arc(ox+p.x*s,oy+p.y*s,2.5,0,Math.PI*2);c.fill();}c.strokeStyle='rgba(168,145,180,.72)';c.lineWidth=1;c.strokeRect(x+.5,y+.5,w-1,h-1);}
 private drawLobby(w:number,h:number){this.overlay(w,h,'元素远征','1–4 人合作 Roguelike');const ready=this.me()?.ready;cbox(mainContext,w/2-120,h/2+15,240,60,ready?'#355843':'#704a36');this.text(ready?'等待其他玩家':'点击准备',w/2,h/2+52,20,'#fff','center');}
 private drawGameOver(w:number,h:number){this.overlay(w,h,'全员倒地',`团队击杀 ${Object.values(this.state?.players??{}).reduce((n,p)=>n+p.kills,0)}`);this.text(this.isHost()?'点击任意位置返回大厅':'等待房主重新开始',w/2,h/2+70,17,'#ddd','center');}
 private drawVictory(w:number,h:number){const summary=this.state?.victorySummary,minutes=Math.floor((summary?.durationMs??0)/60000),seconds=Math.floor(((summary?.durationMs??0)%60000)/1000);this.overlay(w,h,'远征胜利',`用时 ${minutes}:${seconds.toString().padStart(2,'0')} · 击杀 ${summary?.totalKills??0} · 金币 ${summary?.totalGold??0}`);this.text('远古遗迹 → 腐化沼泽 → 熔火火山 已全部净化',w/2,h/2+58,16,'#ffe89a','center');}
 private overlay(w:number,h:number,title:string,sub:string){mainContext.fillStyle='rgba(8,6,12,.78)';mainContext.fillRect(0,0,w,h);this.text(title,w/2,h/2-36,34,'#fff','center');this.text(sub,w/2,h/2+2,17,'#ccc','center');}

 private bonuses(){return equipmentBonuses(this.me()?.equipment??{staff:null,robe:null,ring:null});}
 private resolveEquippedSpell(elements:readonly (typeof ELEMENTS)[number][]):SpellPlan|null{const me=this.me(),plan=resolvePlayerSpell(elements,me?.inventory??[],me?.scrollCooldowns??{},Date.now());if(!plan)return null;const bonus=this.bonuses();return{...plan,castMs:Math.max(40,Math.round(plan.castMs*(1-clamp(bonus.castSpeed,0,.65)))),effects:plan.effects.map(effect=>effect.type==='damage'?{...effect,amount:Math.round(effect.amount*(1+bonus.spellPower))}:effect.type==='heal'?{...effect,amount:Math.round(effect.amount*(1+bonus.spellPower))}:effect)};}
 private selectElement(element:(typeof ELEMENTS)[number]){if(this.local.downed||this.local.elements.length>=ELEMENT_SLOTS)return;if(element==='lightning'&&!canQueueLightning(this.local.elements,this.local.statuses)){this.local.elements=[];this.addStatus('shocked',1,1200,'self');this.local.controls=applyControl(this.local.controls,{kind:'stun',strength:1,durationMs:600},{x:0,y:0},performance.now());this.takeDamage(12);return;}this.local.elements.push(element);}
 private addStatus(kind:StatusInstance['kind'],intensity:number,duration:number,sourceId:string){const now=performance.now();if(kind==='shocked'&&this.local.statuses.some(s=>s.kind==='wet'))this.interruptCast('潮湿导电：施法被打断');const result=resolveStatusApplication(this.local.statuses,{kind,intensity,stacks:1,sourceId,expiresAt:now+duration},now,this.localFreezeImmuneUntil);this.local.statuses=result.statuses;if(result.froze){this.local.controls=applyControl(this.local.controls,{kind:'stun',strength:1,durationMs:1500},{x:0,y:0},now);this.localFreezeImmuneUntil=now+3500;}}
 private expire(now:number){this.local.statuses=this.local.statuses.filter(s=>s.expiresAt==null||s.expiresAt>now);}
 private effectStatuses(effects:SpellEffect[],sourceId:string){return effects.flatMap(e=>e.type==='status'?[{kind:e.status,intensity:e.intensity,stacks:1,sourceId,expiresAt:Date.now()+e.durationMs}]:[]);}
 private addFloat(x:number,y:number,text:string,color:string){const now=performance.now();this.floats.push({id:this.id('float'),x,y,text,color,startedAt:now,endsAt:now+850});}
 private id(prefix:string){return`${prefix}:${parti.playerId}:${Date.now().toString(36)}:${++this.eventSeq}`;}
 private notify(s:string,category?:UiMessageCategory,priority?:number,durationMs?:number,dedupeKey?:string){const warning=/倒下|打断|危险|落石|毒水|高热|无法|取消/.test(s),objective=/钥印|祭坛|符文|Boss|守卫|泰坦|封锁|区域|传送门|挑战/.test(s),combat=s==='怪物击败';this.messages.push({text:s,category:category??(warning?'warning':objective?'objective':combat?'combat':'system'),priority:priority??(warning?3:objective?2:1),durationMs,dedupeKey:dedupeKey??(combat?'enemy-defeated':undefined)});}

 private pointerDown=(ev:PointerEvent)=>{const p=this.screenPoint(ev);if(this.state?.phase==='lobby'){const w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio;if(Math.abs(p.x-w/2)<120&&Math.abs(p.y-h/2-45)<30)void parti.action('setReady',{ready:true});return;}if(this.state?.phase==='gameover'){if(this.isHost())void parti.action('restart');return;}const action=this.uiActions.find(a=>contains(a,p));if(action){this.handleUiAction(action);return;}if(this.inventoryOpen||this.spellbookOpen)return;const button=this.buttons.find(b=>distance(p,b)<=b.r);if(button){this.selectElement(button.element);return;}if(hudBlocksWorld(this.hud,p))return;const world=this.toWorld(p);if(world)this.beginAt(world,ev.pointerId);};
 private pointerMove=(ev:PointerEvent)=>{const p=this.toWorld(this.screenPoint(ev));if(!p)return;if(this.aim?.pointerId===ev.pointerId){this.aim.target=p;this.aim.angle=angleTo(this.local,p);}if(this.beam?.pointerId===ev.pointerId)this.beam.targetAngle=angleTo(this.local,p);};
 private pointerUp=(ev:PointerEvent)=>this.finishAim(ev.pointerId);
 private key=(ev:KeyboardEvent)=>{if(ev.key.toLowerCase()==='i'){this.inventoryOpen=!this.inventoryOpen;this.spellbookOpen=false;return;}if(ev.key.toLowerCase()==='b'){this.spellbookOpen=!this.spellbookOpen;this.inventoryOpen=false;return;}const n=Number(ev.key);if(n>=1&&n<=7)this.selectElement(ELEMENTS[n-1]!);else if(ev.key==='Backspace')this.local.elements.pop();else if(ev.key==='Escape'){if(this.inventoryOpen)this.inventoryOpen=false;else if(this.spellbookOpen)this.spellbookOpen=false;else this.local.elements=[];}};
 private handleUiAction(action:UiAction){if(action.kind==='toggle-inventory'){this.inventoryOpen=!this.inventoryOpen;this.spellbookOpen=false;return;}if(action.kind==='toggle-spellbook'){this.spellbookOpen=!this.spellbookOpen;this.inventoryOpen=false;return;}if(action.kind==='equip'){if(this.enemies().length){this.notify('战斗中无法更换装备');return;}void parti.action('equipItem',{itemId:action.itemId});}else if(action.kind==='drop')void parti.action('dropItem',{itemId:action.itemId});else if(action.kind==='pickup')void parti.action('pickupLoot',{lootId:action.entityId});else if(action.kind==='want')void parti.action('toggleLootWant',{lootId:action.entityId});else if(action.kind==='buy')void parti.action('buyItem',{merchantId:action.entityId,itemId:action.itemId});}
 private computeView():View{const w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio,scale=clamp(Math.min(w/1050,h/680),.62,1.15);return{x:0,y:0,w,h,scale};}
 private screenPoint(e:PointerEvent){const r=mainCanvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}private toWorld(p:Point):Point|null{if(p.x<this.view.x||p.x>this.view.x+this.view.w||p.y<this.view.y||p.y>this.view.y+this.view.h)return null;return{x:this.camera().x+(p.x-this.view.x-this.view.w/2)/this.view.scale,y:this.camera().y+(p.y-this.view.y-this.view.h/2)/this.view.scale};}private toScreen(p:Point){const camera=this.camera();return{x:this.view.x+this.view.w/2+(p.x-camera.x)*this.view.scale,y:this.view.y+this.view.h/2+(p.y-camera.y)*this.view.scale};}
 private camera(){const halfW=this.view.w/Math.max(.01,this.view.scale)/2,halfH=this.view.h/Math.max(.01,this.view.scale)/2;return{x:clamp(this.local.x,halfW,Math.max(halfW,this.map.width-halfW)),y:clamp(this.local.y,halfH,Math.max(halfH,this.map.height-halfH))};}
 private circle(p:Point,r:number,color:string,fill:boolean){const s=this.toScreen(p);mainContext.beginPath();mainContext.arc(s.x,s.y,r*this.view.scale,0,Math.PI*2);fill?(mainContext.fillStyle=color,mainContext.fill()):(mainContext.strokeStyle=color,mainContext.lineWidth=3,mainContext.stroke());}
 private enemies(){const roomId=roomAt(this.map,this.local)?.id;return[...this.hostEnemies.values()].filter(e=>e.roomId===roomId);}private enemyProjectiles(){const roomId=roomAt(this.map,this.local)?.id,all=this.isHost()?[...this.hostProjectiles.values()]:Object.values(this.state?.projectiles??{});return all.filter(p=>p.roomId===roomId);}private environments(){return this.isHost()?[...this.hostEnvironments.values()]:Object.values(this.state?.environments??{});}private me(){return parti.playerId?this.state?.players[parti.playerId]:undefined;}private isHost(){return Boolean(parti.playerId&&this.state?.hostId===parti.playerId);}private text(s:string,x:number,y:number,size:number,color:string,align:CanvasTextAlign='left'){mainContext.fillStyle=color;mainContext.font=`600 ${size}px ui-monospace,monospace`;mainContext.textAlign=align;mainContext.textBaseline='alphabetic';mainContext.fillText(s,x,y);}
}
function clamp(n:number,a:number,b:number){return Math.max(a,Math.min(b,n));}function cbox(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string){c.fillStyle=color;c.fillRect(x,y,w,h);}function validPoint(v:unknown):v is Point{const p=v as Point|null;return Boolean(p&&Number.isFinite(p.x)&&Number.isFinite(p.y));}
function hash(value:string){let result=2166136261;for(let i=0;i<value.length;i++){result^=value.charCodeAt(i);result=Math.imul(result,16777619);}return result|0;}
