import { mainCanvas,mainContext } from 'littlejsengine';
import { ELEMENTS,ELEMENT_SLOTS,HUD_HEIGHT,WORLD_HEIGHT,WORLD_WIDTH,type ActiveBeam,type ActiveProjectile,type AimState,type ControlEffect,type EnemyAttackKind,type EnemyState,type EnvironmentState,type FloatingText,type GameState,type HostProjectile,type PendingCast,type Point,type SpellEffect,type SpellPlan,type SpellVisual,type StatusInstance } from '../game/contracts';
import { ZERO_CONTROL,advanceControl,angleTo,applyControl,beamTargets,canAct,circleContains,coneContains,createPending,distance,enemyCap,normalize,rayToBoundary,spellDirection,turnToward } from '../game/combat';
import { applyStatus,canQueueLightning,reactDamage,resolveSpell } from '../game/spells';

type View={x:number;y:number;w:number;h:number;scale:number};type Button={element:(typeof ELEMENTS)[number];x:number;y:number;r:number};
const labels={rock:'岩',fire:'火',ice:'冰',life:'命',lightning:'雷',water:'水',shield:'盾'} as const;
const colors={rock:'#aa8b68',fire:'#ff5c45',ice:'#77e6ff',life:'#79df78',lightning:'#c596ff',water:'#469cff',shield:'#ffd952'} as const;

export class MagickaScene{
 private state:GameState|null=null;
 private local={x:WORLD_WIDTH/2,y:WORLD_HEIGHT/2,z:0,hp:100,downed:false,kills:0,statuses:[] as StatusInstance[],elements:[] as (typeof ELEMENTS)[number][],controls:{...ZERO_CONTROL}};
 private moveTarget:Point|null=null;private aim:AimState|null=null;private pending:PendingCast|null=null;private beam:ActiveBeam|null=null;private recoveryUntil=0;
 private shots:ActiveProjectile[]=[];private visuals:SpellVisual[]=[];private floats:FloatingText[]=[];
 private hostEnemies=new Map<string,EnemyState>();private hostProjectiles=new Map<string,HostProjectile>();private hostEnvironments=new Map<string,EnvironmentState>();
 private seen=new Set<string>();private pendingDamage=new Map<string,{enemyId:string;amount:number;expectedHp:number}>();private threatSeen=new Set<string>();
 private previous=performance.now();private publishAt=0;private worldAt=0;private spawnAt=0;private seq=0;private worldSeq=0;private eventSeq=0;private weatherAt=0;private flash='';private flashUntil=0;
 private ratio=1;private view:View={x:0,y:0,w:0,h:0,scale:1};private buttons:Button[]=[];private disposers:Array<()=>void>=[];

 init(){this.disposers.push(parti.onState(s=>this.receive(s as GameState)),parti.onEvent('magicka:enemy-damage',p=>this.onEnemyDamage(p as Record<string,unknown>)),parti.onEvent('magicka:player-effect',p=>this.onPlayerEffect(p as Record<string,unknown>)),parti.onEvent('magicka:environment',p=>this.onEnvironment(p as EnvironmentState)),parti.onEvent('magicka:projectile-hit',p=>{const id=String((p as {projectileId?:unknown}).projectileId??'');this.hostProjectiles.delete(id);}));mainCanvas.addEventListener('pointerdown',this.pointerDown);mainCanvas.addEventListener('pointermove',this.pointerMove);mainCanvas.addEventListener('pointerup',this.pointerUp);mainCanvas.addEventListener('pointercancel',this.pointerUp);window.addEventListener('keydown',this.key);parti.ready();}

 update(){
  const now=performance.now(),dt=Math.min(.04,Math.max(.001,(now-this.previous)/1000));this.previous=now;this.ratio=mainCanvas.width/Math.max(1,mainCanvas.clientWidth);this.view=this.computeView();if(this.state?.phase!=='running')return;
  this.local.controls=advanceControl(this.local.controls,dt,now);this.local.z=this.local.controls.z;this.local.x=clamp(this.local.x+this.local.controls.vx*dt,20,WORLD_WIDTH-20);this.local.y=clamp(this.local.y+this.local.controls.vy*dt,135,WORLD_HEIGHT-55);this.expire(now);
  if(!canAct(this.local.controls,now)){this.interruptCast('施法被打断');}else this.updateCasting(now,dt);
  if(!this.local.downed&&canAct(this.local.controls,now)&&this.moveTarget&&!this.aim&&!this.beam){const d=distance(this.local,this.moveTarget),speed=260*(now<this.local.controls.slowedUntil?this.local.controls.slowScale:1),step=speed*dt;if(d<=step){this.local.x=this.moveTarget.x;this.local.y=this.moveTarget.y;this.moveTarget=null;}else{const v=normalize(this.local,this.moveTarget);this.local.x+=v.x*step;this.local.y+=v.y*step;}}
  this.updatePlayerProjectiles(dt,now);if(this.isHost())this.simulateHost(dt,now);this.simulateThreats(now);this.simulateWeather(now);this.visuals=this.visuals.filter(v=>v.endsAt>now);this.floats=this.floats.filter(v=>v.endsAt>now);
  if(now>=this.publishAt){this.publishAt=now+100;void parti.action('publishPlayer',{sequence:++this.seq,...this.local});}
  if(this.isHost()&&now>=this.worldAt){this.worldAt=now+100;void parti.action('syncWorld',{sequence:++this.worldSeq,enemies:[...this.hostEnemies.values()],projectiles:[...this.hostProjectiles.values()],environments:[...this.hostEnvironments.values()]});}
 }

 private updateCasting(now:number,dt:number){
  if(this.aim?.plan.delivery==='beam'&&now>=this.aim.startedAt+this.aim.plan.castMs){const a=this.aim;this.beam={id:this.id('beam'),plan:a.plan,angle:a.angle,targetAngle:angleTo(this.local,a.target),startedAt:now,nextDamageAt:now,pointerId:a.pointerId};this.aim=null;}
  if(this.beam){this.beam.angle=turnToward(this.beam.angle,this.beam.targetAngle,Math.PI*2.5*dt);if(now>=this.beam.nextDamageAt){this.beam.nextDamageAt=now+this.beam.plan.tickMs;this.tickBeam(this.beam,now);}}
  if(this.pending&&now>=this.pending.triggersAt){const cast=this.pending;this.pending=null;this.executeSpell(cast.plan,cast.origin,cast.target,now);this.recoveryUntil=now+cast.plan.recoveryMs;}
 }

 private beginAt(target:Point,pointerId:number){
  if(this.local.downed)return;const plan=resolveSpell(this.local.elements);if(!plan){this.moveTarget=target;return;}if(this.pending||this.beam||performance.now()<this.recoveryUntil){this.notify('当前法术尚未结束');return;}if(!canAct(this.local.controls,performance.now()))return;this.moveTarget=null;this.aim={plan,pointerId,target:{...target},startedAt:performance.now(),angle:angleTo(this.local,target)};
 }
 private finishAim(pointerId:number){
  const now=performance.now();if(this.beam?.pointerId===pointerId){this.recoveryUntil=now+this.beam.plan.recoveryMs;this.beam=null;this.local.elements=[];return;}if(!this.aim||this.aim.pointerId!==pointerId)return;const aim=this.aim;this.aim=null;if(aim.plan.delivery==='beam'){this.notify('射线吟唱取消');return;}const pending=createPending(this.id('cast'),aim,now);pending.origin={x:this.local.x,y:this.local.y};this.pending=pending;this.local.elements=[];
 }
 private interruptCast(message:string){if(!this.pending&&!this.aim&&!this.beam)return;this.pending=null;this.aim=null;this.beam=null;this.notify(message);}

 private executeSpell(plan:SpellPlan,origin:Point,target:Point,now:number){
  const angle=angleTo(origin,target);if(plan.delivery==='projectile'){const d=normalize(origin,target);this.shots.push({id:this.id('shot'),ownerId:parti.playerId??'',spellId:plan.id,element:plan.elements[0]!,x:origin.x,y:origin.y,vx:d.x*plan.projectileSpeed,vy:d.y*plan.projectileSpeed,radius:plan.radius,remainingPierce:plan.pierce,expiresAt:now+plan.range/Math.max(1,plan.projectileSpeed)*1000,effects:plan.effects,hitIds:[]});return;}
  if(plan.delivery==='cone'){const hits=this.enemies().filter(e=>coneContains(origin,angle,plan.range,plan.coneAngle/2,e,e.radius));for(const e of hits)this.damageEnemy(e,plan,origin,now);this.visuals.push({id:this.id('visual'),kind:'cone',origin,target,radius:plan.range,angle,color:plan.elements[0]!,startedAt:now,endsAt:now+260});return;}
  if(plan.delivery==='targeted'||plan.delivery==='area'){for(const e of this.enemies().filter(e=>circleContains(target,plan.radius,e,e.radius)))this.damageEnemy(e,plan,origin,now);this.applyPlayers(plan,target,origin);this.visuals.push({id:this.id('visual'),kind:'impact',origin,target,radius:plan.radius,angle,color:plan.elements[0]!,startedAt:now,endsAt:now+420});}
  if(plan.delivery==='self')this.applySelf(plan.effects,origin);
  if(plan.delivery==='global'||plan.delivery==='area')for(const effect of plan.effects)if(effect.type==='environment'){const env:EnvironmentState={id:this.id('env'),kind:effect.kind,x:target.x,y:target.y,radius:effect.kind==='rain'?9999:effect.radius??plan.radius,startedAt:Date.now(),endsAt:Date.now()+effect.durationMs};void parti.action('reportEnvironment',env);}
 }
 private tickBeam(beam:ActiveBeam,now:number){const targets=beamTargets(this.local,beam.angle,beam.plan.radius,this.enemies(),beam.plan.pierce);for(const {enemy}of targets)this.damageEnemy(enemy,beam.plan,this.local,now);}
 private updatePlayerProjectiles(dt:number,now:number){for(const s of this.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;for(const e of this.enemies()){if(s.hitIds.includes(e.id)||!circleContains(s,s.radius,e,e.radius))continue;s.hitIds.push(e.id);this.damageEnemy(e,{...resolveSpell([s.element])!,id:s.spellId,effects:s.effects},s,now);if(s.remainingPierce--<=0){s.expiresAt=0;break;}}}this.shots=this.shots.filter(s=>s.expiresAt>now&&s.x>=0&&s.x<=WORLD_WIDTH&&s.y>=100&&s.y<=WORLD_HEIGHT);}

 private damageEnemy(enemy:EnemyState,plan:SpellPlan,origin:Point,now:number){
  let amount=0,reaction='';for(const effect of plan.effects)if(effect.type==='damage'){const result=reactDamage(enemy.statuses,effect.element,effect.amount);amount+=result.amount;if(result.reaction)reaction=result.reaction;}if(amount<=0)return;const direction=spellDirection(origin,enemy),controls=plan.effects.flatMap(e=>e.type==='control'?[e.control]:[]),statuses=this.effectStatuses(plan.effects,this.id('status'));
  enemy.hp-=amount;enemy.flashUntil=now+160;enemy.revision+=1;for(const s of statuses)enemy.statuses=applyStatus(enemy.statuses,s,Date.now());for(const c of controls)enemy.controls=applyControl(enemy.controls,c,direction,now);const eventId=this.id('hit');this.seen.add(eventId);this.pendingDamage.set(eventId,{enemyId:enemy.id,amount,expectedHp:enemy.hp});this.addFloat(enemy.x,enemy.y-30,`${amount}${reaction?` ${reaction}`:''}`,colors[plan.elements[0]!]);void parti.action('reportEnemyDamage',{eventId,worldSequence:this.state?.worldSequence??0,enemyId:enemy.id,sourcePlayerId:parti.playerId,spellId:plan.id,amount,statuses,controls,direction});if(enemy.hp<=0){this.hostEnemies.delete(enemy.id);this.local.kills+=1;this.notify('怪物击败');}}
 private applyPlayers(plan:SpellPlan,target:Point,origin:Point){for(const p of Object.values(this.state?.players??{})){if(!circleContains(target,plan.radius,p,24))continue;if(p.id===parti.playerId)this.applySelf(plan.effects,origin);else{const effects=plan.effects.filter(e=>e.type!=='damage');if(effects.length)void parti.action('reportPlayerEffect',{eventId:this.id('player-effect'),targetPlayerId:p.id,effects,direction:spellDirection(origin,p)});}}}
 private applySelf(effects:SpellEffect[],origin:Point){for(const e of effects){if(e.type==='heal'){this.local.hp=Math.min(100,this.local.hp+e.amount);if(this.local.downed&&this.local.hp>=25)this.local.downed=false;}else if(e.type==='status')this.addStatus(e.status,e.intensity,e.durationMs,'self');else if(e.type==='control')this.local.controls=applyControl(this.local.controls,e.control,spellDirection(origin,this.local),performance.now());}}

 private simulateHost(dt:number,now:number){
  const wallNow=Date.now(),connected=Object.values(this.state?.players??{}).filter(p=>p.connected),players=connected.filter(p=>!p.downed),cap=enemyCap(connected.length);if(now>=this.spawnAt&&this.hostEnemies.size<cap){const elapsed=wallNow-(this.state?.startedAt??wallNow);this.spawnAt=now+Math.max(700,1800-elapsed/50);this.spawnEnemy();}
  for(const enemy of this.hostEnemies.values()){enemy.controls=advanceControl(enemy.controls,dt,now);enemy.x=clamp(enemy.x+enemy.controls.vx*dt,25,WORLD_WIDTH-25);enemy.y=clamp(enemy.y+enemy.controls.vy*dt,135,WORLD_HEIGHT-55);enemy.statuses=enemy.statuses.filter(s=>s.expiresAt==null||s.expiresAt>wallNow);const target=players.slice().sort((a,b)=>distance(enemy,a)-distance(enemy,b))[0];if(!target)continue;enemy.targetId=target.id;if(!canAct(enemy.controls,now)){enemy.attack=null;continue;}if(enemy.attack){if(wallNow>=enemy.attack.firesAt)this.fireEnemyAttack(enemy,enemy.attack,target,wallNow);if(wallNow>=enemy.attack.firesAt+180)enemy.attack=null;continue;}if(wallNow<enemy.nextAttackAt)continue;const d=distance(enemy,target),speed=(enemy.kind==='chaser'?145:enemy.kind==='shooter'?95:115)*(now<enemy.controls.slowedUntil?enemy.controls.slowScale:1);const attack=this.chooseAttack(enemy,d);if(attack){enemy.attack={kind:attack,targetId:target.id,startedAt:wallNow,firesAt:wallNow+(attack==='melee'?350:attack==='water-slam'?420:520)};continue;}const desired=enemy.kind==='shooter'?300:enemy.kind==='water-fiend'?d>330?260:70:65;const sign=d>desired+25?1:d<desired-25?-1:0;if(sign){const v=normalize(enemy,target);enemy.x=clamp(enemy.x+v.x*speed*dt*sign,25,WORLD_WIDTH-25);enemy.y=clamp(enemy.y+v.y*speed*dt*sign,135,WORLD_HEIGHT-55);}}
  for(const p of this.hostProjectiles.values()){p.x+=p.vx*dt;p.y+=p.vy*dt;}for(const[id,p]of this.hostProjectiles)if(p.expiresAt<=Date.now()||p.x<0||p.x>WORLD_WIDTH||p.y<100||p.y>WORLD_HEIGHT)this.hostProjectiles.delete(id);const raining=[...this.hostEnvironments.values()].some(e=>e.kind==='rain'&&e.endsAt>Date.now());for(const e of this.hostEnemies.values())if(raining)e.statuses=applyStatus(e.statuses,{kind:'wet',intensity:1,stacks:1,sourceId:'rain',expiresAt:Date.now()+2200},Date.now());for(const[id,e]of this.hostEnvironments)if(e.endsAt<=Date.now())this.hostEnvironments.delete(id);
 }
 private chooseAttack(e:EnemyState,d:number):EnemyAttackKind|null{if(e.kind==='chaser')return d<=90?'melee':null;if(e.kind==='shooter')return d>=190&&d<=430?'bolt':null;return d<=105?'water-slam':d>=190&&d<=390?'water-bolt':null;}
 private fireEnemyAttack(enemy:EnemyState,attack:NonNullable<EnemyState['attack']>,target:{x:number;y:number},now:number){const key=`${enemy.id}:${attack.firesAt}`;if(this.threatSeen.has(key))return;this.threatSeen.add(key);enemy.nextAttackAt=now+(enemy.kind==='chaser'?1150:enemy.kind==='shooter'?1800:1500);if(attack.kind==='bolt'||attack.kind==='water-bolt'){const v=normalize(enemy,target),speed=attack.kind==='bolt'?360:300,id=this.id('enemy-shot');this.hostProjectiles.set(id,{id,kind:attack.kind,sourceId:enemy.id,x:enemy.x,y:enemy.y,vx:v.x*speed,vy:v.y*speed,radius:attack.kind==='bolt'?12:18,damage:attack.kind==='bolt'?14:10,expiresAt:Date.now()+3500,control:attack.kind==='water-bolt'?{kind:'slow',strength:.65,durationMs:1800}:undefined});}}
 private spawnEnemy(){const n=++this.eventSeq,kind=n%6===0?'water-fiend':n%3===0?'shooter':'chaser',x=n%2?55:WORLD_WIDTH-55,id=`enemy:${Date.now().toString(36)}:${n}`,hp=kind==='chaser'?75:100;this.hostEnemies.set(id,{id,kind,x,y:170+(n*91)%(WORLD_HEIGHT-300),hp,maxHp:hp,radius:kind==='chaser'?28:35,targetId:null,nextAttackAt:Date.now()+800,attack:null,statuses:[],controls:{...ZERO_CONTROL},flashUntil:0,revision:0});}

 private simulateThreats(now:number){if(this.local.downed)return;const wallNow=Date.now();for(const e of this.enemies()){const a=e.attack;if(!a||a.targetId!==parti.playerId||wallNow<a.firesAt||wallNow>a.firesAt+180)continue;const id=`attack:${e.id}:${a.firesAt}`;if(this.threatSeen.has(id))continue;if((a.kind==='melee'&&distance(e,this.local)<=105)||(a.kind==='water-slam'&&distance(e,this.local)<=125)){this.threatSeen.add(id);this.takeDamage(a.kind==='melee'?16:12);const dir=normalize(e,this.local);this.local.controls=applyControl(this.local.controls,{kind:'knockback',strength:a.kind==='melee'?240:340,durationMs:300},dir,now);}}
  for(const p of this.enemyProjectiles()){const id=`projectile:${p.id}`;if(this.threatSeen.has(id)||!circleContains(p,p.radius,this.local,24))continue;this.threatSeen.add(id);this.takeDamage(p.damage);if(p.control)this.local.controls=applyControl(this.local.controls,p.control,normalize(p,this.local),now);if(p.kind==='water-bolt')this.addStatus('wet',1,4000,p.id);this.hostProjectiles.delete(p.id);void parti.action('reportProjectileHit',{projectileId:p.id});}}
 private simulateWeather(now:number){if(now<this.weatherAt)return;this.weatherAt=now+800;for(const env of this.environments()){if(env.kind==='rain')this.addStatus('wet',1,2400,env.id);else if(circleContains(env,env.radius,this.local,24))this.takeDamage(3);}}
 private takeDamage(amount:number){const shield=this.local.statuses.find(s=>s.kind==='shielded');if(shield){shield.stacks-=1;if(shield.stacks<=0)this.local.statuses=this.local.statuses.filter(s=>s!==shield);this.notify('护盾吸收伤害');return;}this.local.hp=Math.max(0,this.local.hp-amount);this.addFloat(this.local.x,this.local.y-35,`-${amount}`,'#ff6b75');if(!this.local.hp){this.local.downed=true;this.interruptCast('你倒下了');this.moveTarget=null;}}

 private receive(state:GameState){const old=this.state?.phase;this.state=state;this.worldSeq=Math.max(this.worldSeq,state.worldSequence);for(const[id,p]of this.pendingDamage){const authoritative=state.enemies[p.enemyId];if(!authoritative||authoritative.hp<=p.expectedHp)this.pendingDamage.delete(id);}const me=this.me();if(!me)return;if(old!=='running'&&state.phase==='running'){this.local={x:me.x,y:me.y,z:0,hp:100,downed:false,kills:0,statuses:[],elements:[],controls:{...ZERO_CONTROL}};this.hostEnemies.clear();this.hostProjectiles.clear();this.hostEnvironments.clear();this.seen.clear();this.threatSeen.clear();this.spawnAt=0;}if(!this.isHost()){const pendingByEnemy=new Map<string,number>();for(const p of this.pendingDamage.values())pendingByEnemy.set(p.enemyId,(pendingByEnemy.get(p.enemyId)??0)+p.amount);const entries=Object.values(state.enemies).map(e=>[e.id,{...e,hp:e.hp-(pendingByEnemy.get(e.id)??0)}] as const).filter(([,e])=>e.hp>0);this.hostEnemies=new Map(entries);this.hostProjectiles=new Map(Object.values(state.projectiles).map(e=>[e.id,{...e}]));this.hostEnvironments=new Map(Object.values(state.environments).map(e=>[e.id,{...e}]));}else{for(const e of Object.values(state.enemies))if(!this.hostEnemies.has(e.id))this.hostEnemies.set(e.id,{...e});for(const p of Object.values(state.projectiles))if(!this.hostProjectiles.has(p.id))this.hostProjectiles.set(p.id,{...p});for(const e of Object.values(state.environments))if(!this.hostEnvironments.has(e.id))this.hostEnvironments.set(e.id,{...e});}}
 private onEnemyDamage(raw:Record<string,unknown>){const id=String(raw.eventId??'');if(!id||this.seen.has(id))return;this.seen.add(id);const enemy=this.hostEnemies.get(String(raw.enemyId));if(!enemy)return;enemy.hp-=Number(raw.amount)||0;enemy.flashUntil=performance.now()+160;enemy.revision+=1;for(const s of (Array.isArray(raw.statuses)?raw.statuses:[])as StatusInstance[])enemy.statuses=applyStatus(enemy.statuses,s,Date.now());const direction=validPoint(raw.direction)?raw.direction:{x:0,y:0};for(const c of (Array.isArray(raw.controls)?raw.controls:[])as ControlEffect[])enemy.controls=applyControl(enemy.controls,c,direction,performance.now());if(enemy.hp<=0)this.hostEnemies.delete(enemy.id);}
 private onPlayerEffect(raw:Record<string,unknown>){if(raw.targetPlayerId!==parti.playerId)return;const id=String(raw.eventId??'');if(this.seen.has(id))return;this.seen.add(id);const direction=validPoint(raw.direction)?raw.direction:{x:0,y:0};for(const e of (Array.isArray(raw.effects)?raw.effects:[])as SpellEffect[]){if(e.type==='status')this.addStatus(e.status,e.intensity,e.durationMs,String(raw.sourcePlayerId));else if(e.type==='heal'){this.local.hp=Math.min(100,this.local.hp+e.amount);if(this.local.downed&&this.local.hp>=25)this.local.downed=false;}else if(e.type==='control')this.local.controls=applyControl(this.local.controls,e.control,direction,performance.now());}}
 private onEnvironment(env:EnvironmentState){if(this.isHost())this.hostEnvironments.set(env.id,{...env});}

 render(){const c=mainContext,w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio;c.save();c.setTransform(this.ratio,0,0,this.ratio,0,0);c.clearRect(0,0,w,h);c.fillStyle='#100d17';c.fillRect(0,0,w,h);this.buttons=[];c.save();c.beginPath();c.rect(this.view.x,this.view.y,this.view.w,this.view.h);c.clip();this.drawArena();c.restore();this.drawHud(w,h);if(!this.state)this.overlay(w,h,'连接训练场','');else if(this.state.phase==='lobby')this.drawLobby(w,h);else if(this.state.phase==='gameover')this.drawGameOver(w,h);if(performance.now()<this.flashUntil){c.fillStyle='rgba(20,10,25,.85)';c.fillRect(w/2-170,50,340,40);this.text(this.flash,w/2,76,17,'#fff','center');}c.restore();}
 private drawArena(){const c=mainContext,now=performance.now();c.fillStyle='#36202d';c.fillRect(this.view.x,this.view.y,this.view.w,this.view.h);c.strokeStyle='#9a6849';c.lineWidth=4;c.strokeRect(this.view.x+2,this.view.y+2,this.view.w-4,this.view.h-4);for(const env of this.environments()){if(env.kind==='rain'){c.fillStyle='rgba(70,140,255,.14)';c.fillRect(this.view.x,this.view.y,this.view.w,this.view.h);}else this.circle(env,env.radius,'rgba(220,220,230,.25)',true);}for(const s of this.shots)this.circle(s,s.radius,colors[s.element],true);for(const p of this.enemyProjectiles())this.circle(p,p.radius,p.kind==='water-bolt'?'#55bfff':'#e3a4ff',true);for(const v of this.visuals)this.drawVisual(v,now);for(const e of this.enemies())this.drawEnemy(e,now);for(const p of Object.values(this.state?.players??{})){const pos=p.id===parti.playerId?this.local:p;this.drawPlayer(pos,p.id===parti.playerId?'#ffe06a':'#78b7ff',p.name);}this.drawAim(now);for(const f of this.floats){const age=(now-f.startedAt)/(f.endsAt-f.startedAt),p=this.toScreen({x:f.x,y:f.y-age*45});this.text(f.text,p.x,p.y,14,f.color,'center');}}
 private drawAim(now:number){const state=this.aim;if(state){const origin=this.toScreen(this.local),angle=angleTo(this.local,state.target),color=colors[state.plan.elements[0]!];mainContext.strokeStyle=color;mainContext.fillStyle=`${color}33`;mainContext.lineWidth=3;if(state.plan.delivery==='cone'){mainContext.beginPath();mainContext.moveTo(origin.x,origin.y);mainContext.arc(origin.x,origin.y,state.plan.range*this.view.scale,angle-state.plan.coneAngle/2,angle+state.plan.coneAngle/2);mainContext.closePath();mainContext.fill();mainContext.stroke();}else if(state.plan.delivery==='targeted'||state.plan.delivery==='area'){this.circle(state.target,state.plan.radius,color,false);}else if(state.plan.delivery==='projectile'){const end=this.toScreen(state.target);mainContext.beginPath();mainContext.moveTo(origin.x,origin.y);mainContext.lineTo(end.x,end.y);mainContext.stroke();}else if(state.plan.delivery==='beam'){const end=this.toScreen(rayToBoundary(this.local,angle));mainContext.beginPath();mainContext.moveTo(origin.x,origin.y);mainContext.lineTo(end.x,end.y);mainContext.stroke();const progress=clamp((now-state.startedAt)/state.plan.castMs,0,1);this.text(`吟唱 ${Math.round(progress*100)}%`,origin.x,origin.y-45,13,'#fff','center');}}
  if(this.pending&&(this.pending.plan.delivery==='targeted'||this.pending.plan.delivery==='area')){const pulse=1+Math.sin(now/80)*.05;this.circle(this.pending.target,this.pending.plan.radius*pulse,'#ffcc66',false);}if(this.beam){const hits=beamTargets(this.local,this.beam.angle,this.beam.plan.radius,this.enemies(),this.beam.plan.pierce),end=hits.length?{x:this.local.x+Math.cos(this.beam.angle)*hits.at(-1)!.along,y:this.local.y+Math.sin(this.beam.angle)*hits.at(-1)!.along}:rayToBoundary(this.local,this.beam.angle),a=this.toScreen(this.local),b=this.toScreen(end);mainContext.strokeStyle=colors[this.beam.plan.elements[0]!];mainContext.lineWidth=Math.max(3,this.beam.plan.radius*2*this.view.scale);mainContext.beginPath();mainContext.moveTo(a.x,a.y);mainContext.lineTo(b.x,b.y);mainContext.stroke();}}
 private drawVisual(v:SpellVisual,now:number){const alpha=clamp((v.endsAt-now)/(v.endsAt-v.startedAt),0,1),color=colors[v.color];mainContext.globalAlpha=alpha;if(v.kind==='cone'){const o=this.toScreen(v.origin);mainContext.fillStyle=color;mainContext.beginPath();mainContext.moveTo(o.x,o.y);mainContext.arc(o.x,o.y,v.radius*this.view.scale,v.angle-.52,v.angle+.52);mainContext.closePath();mainContext.fill();}else this.circle(v.target,v.radius,color,true);mainContext.globalAlpha=1;}
 private drawEnemy(e:EnemyState,now:number){const c=mainContext,p=this.toScreen({x:e.x,y:e.y-e.controls.z}),r=e.radius*this.view.scale;c.strokeStyle=now<e.flashUntil?'#fff':e.kind==='water-fiend'?'#54baff':e.kind==='shooter'?'#d298ff':'#ff745f';c.lineWidth=5;c.strokeRect(p.x-r,p.y-r,r*2,r*2);c.fillStyle='#210d16';c.fillRect(p.x-r,p.y-r-11,r*2,6);c.fillStyle='#ff5868';c.fillRect(p.x-r,p.y-r-11,r*2*clamp(e.hp/e.maxHp,0,1),6);this.text(e.kind,p.x,p.y+4,11,'#fff','center');if(e.attack){const wallNow=Date.now(),t=clamp((e.attack.firesAt-wallNow)/(e.attack.firesAt-e.attack.startedAt),0,1);c.strokeStyle='#ffdf65';c.lineWidth=4;c.beginPath();c.arc(p.x,p.y,r+8,-Math.PI/2,-Math.PI/2+(1-t)*Math.PI*2);c.stroke();}this.drawStatuses(e.statuses,p.x,p.y+r+20);}
 private drawPlayer(p:{x:number;y:number;z:number;hp:number;downed:boolean;statuses?:StatusInstance[]},color:string,name:string){const c=mainContext,ground=this.toScreen(p),s=this.toScreen({x:p.x,y:p.y-p.z}),r=25*this.view.scale;c.fillStyle='rgba(0,0,0,.3)';c.beginPath();c.ellipse(ground.x,ground.y+r*.8,r,r*.35,0,0,Math.PI*2);c.fill();c.fillStyle=p.downed?'#555':color;c.fillRect(s.x-r,s.y-r,r*2,r*2);c.strokeStyle='#fff';c.lineWidth=2;c.strokeRect(s.x-r,s.y-r,r*2,r*2);this.text(name,s.x,s.y-r-12,12,'#fff','center');c.fillStyle='#220b13';c.fillRect(s.x-r,s.y+r+5,r*2,5);c.fillStyle='#62e77b';c.fillRect(s.x-r,s.y+r+5,r*2*clamp(p.hp/100,0,1),5);this.drawStatuses(p.statuses??[],s.x,s.y+r+20);}
 private drawStatuses(statuses:StatusInstance[],x:number,y:number){const names:Record<StatusInstance['kind'],string>={wet:'潮湿',burning:'燃烧',chilled:'减速',frozen:'冻结',shocked:'感电',shielded:'护盾'};this.text(statuses.map(s=>names[s.kind]).join(' '),x,y,10,'#d9efff','center');}
 private drawHud(w:number,h:number){const c=mainContext;c.fillStyle='#17111f';c.fillRect(0,0,w,62);c.fillRect(0,h-HUD_HEIGHT,w,HUD_HEIGHT);this.text(`HP ${this.local.hp}   击杀 ${this.local.kills}`,22,36,18,'#fff');this.text(`怪物 ${this.enemies().length}/${enemyCap(Object.values(this.state?.players??{}).filter(p=>p.connected).length)}`,w-22,36,17,'#ddd','right');const gap=Math.min(92,(w-30)/7),start=w/2-gap*3;for(let i=0;i<7;i++){const x=start+i*gap,y=h-49,r=Math.min(35,gap*.4),element=ELEMENTS[i]!;this.buttons.push({element,x,y,r:r+7});c.fillStyle=colors[element];c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();c.strokeStyle='#f5e8d0';c.lineWidth=3;c.stroke();this.text(labels[element],x,y+7,20,'#17111f','center');}const plan=resolveSpell(this.local.elements),status=this.beam?'持续施法':this.pending?'吟唱中':performance.now()<this.recoveryUntil?'施法后摇':this.aim?.plan.delivery==='beam'?'吟唱射线':this.local.elements.length?'准备完成':'点击场地移动';this.text(`${status}  ${this.local.elements.map(e=>labels[e]).join(' + ')}${plan?` · ${plan.name}`:''}`,w/2,h-95,15,'#fff','center');}
 private drawLobby(w:number,h:number){this.overlay(w,h,'元素训练场','1–4 人无尽合作训练');const ready=this.me()?.ready;cbox(mainContext,w/2-120,h/2+15,240,60,ready?'#355843':'#704a36');this.text(ready?'等待其他玩家':'点击准备',w/2,h/2+52,20,'#fff','center');}
 private drawGameOver(w:number,h:number){this.overlay(w,h,'全员倒地',`团队击杀 ${Object.values(this.state?.players??{}).reduce((n,p)=>n+p.kills,0)}`);this.text(this.isHost()?'点击任意位置返回大厅':'等待房主重新开始',w/2,h/2+70,17,'#ddd','center');}
 private overlay(w:number,h:number,title:string,sub:string){mainContext.fillStyle='rgba(8,6,12,.78)';mainContext.fillRect(0,0,w,h);this.text(title,w/2,h/2-36,34,'#fff','center');this.text(sub,w/2,h/2+2,17,'#ccc','center');}

 private selectElement(element:(typeof ELEMENTS)[number]){if(this.local.downed||this.local.elements.length>=ELEMENT_SLOTS)return;if(element==='lightning'&&!canQueueLightning(this.local.elements,this.local.statuses)){this.local.elements=[];this.addStatus('shocked',1,1200,'self');this.local.controls=applyControl(this.local.controls,{kind:'stun',strength:1,durationMs:600},{x:0,y:0},performance.now());this.takeDamage(12);return;}this.local.elements.push(element);}
 private addStatus(kind:StatusInstance['kind'],intensity:number,duration:number,sourceId:string){if(kind==='shocked'&&this.local.statuses.some(s=>s.kind==='wet'))this.interruptCast('潮湿导电：施法被打断');this.local.statuses=applyStatus(this.local.statuses,{kind,intensity,stacks:1,sourceId,expiresAt:performance.now()+duration},performance.now());}
 private expire(now:number){this.local.statuses=this.local.statuses.filter(s=>s.expiresAt==null||s.expiresAt>now);}
 private effectStatuses(effects:SpellEffect[],sourceId:string){return effects.flatMap(e=>e.type==='status'?[{kind:e.status,intensity:e.intensity,stacks:1,sourceId,expiresAt:Date.now()+e.durationMs}]:[]);}
 private addFloat(x:number,y:number,text:string,color:string){const now=performance.now();this.floats.push({id:this.id('float'),x,y,text,color,startedAt:now,endsAt:now+850});}
 private id(prefix:string){return`${prefix}:${parti.playerId}:${Date.now().toString(36)}:${++this.eventSeq}`;}
 private notify(s:string){this.flash=s;this.flashUntil=performance.now()+1800;}

 private pointerDown=(ev:PointerEvent)=>{const p=this.screenPoint(ev);if(this.state?.phase==='lobby'){const w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio;if(Math.abs(p.x-w/2)<120&&Math.abs(p.y-h/2-45)<30)void parti.action('setReady',{ready:true});return;}if(this.state?.phase==='gameover'){if(this.isHost())void parti.action('restart');return;}const button=this.buttons.find(b=>distance(p,b)<=b.r);if(button){this.selectElement(button.element);return;}const world=this.toWorld(p);if(world)this.beginAt(world,ev.pointerId);};
 private pointerMove=(ev:PointerEvent)=>{const p=this.toWorld(this.screenPoint(ev));if(!p)return;if(this.aim?.pointerId===ev.pointerId){this.aim.target=p;this.aim.angle=angleTo(this.local,p);}if(this.beam?.pointerId===ev.pointerId)this.beam.targetAngle=angleTo(this.local,p);};
 private pointerUp=(ev:PointerEvent)=>this.finishAim(ev.pointerId);
 private key=(ev:KeyboardEvent)=>{const n=Number(ev.key);if(n>=1&&n<=7)this.selectElement(ELEMENTS[n-1]!);else if(ev.key==='Backspace')this.local.elements.pop();else if(ev.key==='Escape')this.local.elements=[];};
 private computeView():View{const w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio-HUD_HEIGHT-62,scale=Math.min(w/WORLD_WIDTH,h/WORLD_HEIGHT);return{x:(w-WORLD_WIDTH*scale)/2,y:62+(h-WORLD_HEIGHT*scale)/2,w:WORLD_WIDTH*scale,h:WORLD_HEIGHT*scale,scale};}
 private screenPoint(e:PointerEvent){const r=mainCanvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}private toWorld(p:Point):Point|null{if(p.x<this.view.x||p.x>this.view.x+this.view.w||p.y<this.view.y||p.y>this.view.y+this.view.h)return null;return{x:(p.x-this.view.x)/this.view.scale,y:(p.y-this.view.y)/this.view.scale};}private toScreen(p:Point){return{x:this.view.x+p.x*this.view.scale,y:this.view.y+p.y*this.view.scale};}
 private circle(p:Point,r:number,color:string,fill:boolean){const s=this.toScreen(p);mainContext.beginPath();mainContext.arc(s.x,s.y,r*this.view.scale,0,Math.PI*2);fill?(mainContext.fillStyle=color,mainContext.fill()):(mainContext.strokeStyle=color,mainContext.lineWidth=3,mainContext.stroke());}
 private enemies(){return[...this.hostEnemies.values()];}private enemyProjectiles(){return this.isHost()?[...this.hostProjectiles.values()]:Object.values(this.state?.projectiles??{});}private environments(){return this.isHost()?[...this.hostEnvironments.values()]:Object.values(this.state?.environments??{});}private me(){return parti.playerId?this.state?.players[parti.playerId]:undefined;}private isHost(){return Boolean(parti.playerId&&this.state?.hostId===parti.playerId);}private text(s:string,x:number,y:number,size:number,color:string,align:CanvasTextAlign='left'){mainContext.fillStyle=color;mainContext.font=`600 ${size}px ui-monospace,monospace`;mainContext.textAlign=align;mainContext.textBaseline='alphabetic';mainContext.fillText(s,x,y);}
}
function clamp(n:number,a:number,b:number){return Math.max(a,Math.min(b,n));}function cbox(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string){c.fillStyle=color;c.fillRect(x,y,w,h);}function validPoint(v:unknown):v is Point{const p=v as Point|null;return Boolean(p&&Number.isFinite(p.x)&&Number.isFinite(p.y));}
