import { mainCanvas,mainContext } from 'littlejsengine';
import { ELEMENTS,ELEMENT_SLOTS,HUD_HEIGHT,WORLD_HEIGHT,WORLD_WIDTH,type Element,type EnemyState,type EnvironmentState,type GameState,type SpellEffect,type SpellPlan,type StatusInstance } from '../game/contracts';
import { applyStatus,canQueueLightning,reactDamage,resolveSpell } from '../game/spells';

type Point={x:number;y:number}; type View={x:number;y:number;w:number;h:number;scale:number}; type Button={element:Element;x:number;y:number;r:number};
const labels:Record<Element,string>={rock:'岩',fire:'火',ice:'冰',life:'命',lightning:'雷',water:'水',shield:'盾'};
const colors:Record<Element,string>={rock:'#aa8b68',fire:'#ff5c45',ice:'#77e6ff',life:'#79df78',lightning:'#c596ff',water:'#469cff',shield:'#ffd952'};

export class MagickaScene{
 private state:GameState|null=null; private local={x:WORLD_WIDTH/2,y:WORLD_HEIGHT/2,hp:100,downed:false,kills:0,statuses:[] as StatusInstance[],elements:[] as Element[]};
 private target:Point|null=null; private casting:{plan:SpellPlan;target:Point;started:number;lastTick:number;pointer:number}|null=null;
 private hostEnemies=new Map<string,EnemyState>(); private hostEnvironments=new Map<string,EnvironmentState>(); private seen=new Set<string>();
 private previous=performance.now();private publishAt=0;private worldAt=0;private spawnAt=0;private seq=0;private worldSeq=0;private eventSeq=0;private hurtAt=0;private weatherAt=0;private flash='';private flashUntil=0;
 private ratio=1;private view:View={x:0,y:0,w:0,h:0,scale:1};private buttons:Button[]=[];private disposers:Array<()=>void>=[];
 init(){
  this.disposers.push(parti.onState(s=>this.receive(s as GameState)),parti.onEvent('magicka:enemy-damage',p=>this.onEnemyDamage(p as Record<string,unknown>)),parti.onEvent('magicka:player-effect',p=>this.onPlayerEffect(p as Record<string,unknown>)),parti.onEvent('magicka:environment',p=>this.onEnvironment(p as EnvironmentState)));
  mainCanvas.addEventListener('pointerdown',this.pointerDown);mainCanvas.addEventListener('pointermove',this.pointerMove);mainCanvas.addEventListener('pointerup',this.pointerUp);mainCanvas.addEventListener('pointercancel',this.pointerUp);window.addEventListener('keydown',this.key);parti.ready();
 }
 update(){
  const now=performance.now(),dt=Math.min(.04,Math.max(.001,(now-this.previous)/1000));this.previous=now;this.ratio=mainCanvas.width/Math.max(1,mainCanvas.clientWidth);this.view=this.computeView();if(this.state?.phase!=='running')return;
  this.expire(now);if(!this.local.downed&&this.target&&!this.casting){const dx=this.target.x-this.local.x,dy=this.target.y-this.local.y,d=Math.hypot(dx,dy),step=260*dt;if(d<=step){this.local.x=this.target.x;this.local.y=this.target.y;this.target=null;}else{this.local.x+=dx/d*step;this.local.y+=dy/d*step;}}
  if(this.isHost())this.simulateHost(dt,now);this.simulateThreats(now);this.simulateWeather(now);
  if(this.casting?.plan.channel&&now-this.casting.started>=this.casting.plan.castMs&&now>=this.casting.lastTick+240){this.casting.lastTick=now;this.releaseSpell(this.casting.plan,this.casting.target,true);}
  if(now>=this.publishAt){this.publishAt=now+100;void parti.action('publishPlayer',{sequence:++this.seq,...this.local});}
  if(this.isHost()&&now>=this.worldAt){this.worldAt=now+100;void parti.action('syncWorld',{sequence:++this.worldSeq,enemies:[...this.hostEnemies.values()],environments:[...this.hostEnvironments.values()]});}
 }
 render(){
  const c=mainContext,w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio;c.save();c.setTransform(this.ratio,0,0,this.ratio,0,0);c.clearRect(0,0,w,h);c.fillStyle='#100d17';c.fillRect(0,0,w,h);this.buttons=[];
  c.save();c.beginPath();c.rect(this.view.x,this.view.y,this.view.w,this.view.h);c.clip();this.drawArena();c.restore();this.drawHud(w,h);
  if(!this.state)this.overlay(w,h,'连接训练场','');else if(this.state.phase==='lobby')this.drawLobby(w,h);else if(this.state.phase==='gameover')this.drawGameOver(w,h);
  if(performance.now()<this.flashUntil){c.fillStyle='rgba(20,10,25,.85)';c.fillRect(w/2-170,50,340,40);this.text(this.flash,w/2,76,17,'#fff','center');}c.restore();
 }
 private receive(state:GameState){const old=this.state?.phase;this.state=state;this.worldSeq=Math.max(this.worldSeq,state.worldSequence);const me=this.me();if(!me)return;if(old!=='running'&&state.phase==='running'){this.local={x:me.x,y:me.y,hp:100,downed:false,kills:0,statuses:[],elements:[]};this.hostEnemies.clear();this.hostEnvironments.clear();this.seen.clear();this.spawnAt=0;}if(!this.isHost()){this.hostEnemies=new Map(Object.values(state.enemies).map(e=>[e.id,{...e}]));this.hostEnvironments=new Map(Object.values(state.environments).map(e=>[e.id,{...e}]));}else{for(const e of Object.values(state.enemies))if(!this.hostEnemies.has(e.id))this.hostEnemies.set(e.id,{...e});for(const e of Object.values(state.environments))if(!this.hostEnvironments.has(e.id))this.hostEnvironments.set(e.id,{...e});}}
 private simulateHost(dt:number,now:number){
  const elapsed=Date.now()-(this.state?.startedAt??Date.now()),cap=Math.min(32,8+Math.floor(elapsed/20000)+Object.keys(this.state?.players??{}).length*3);
  if(now>=this.spawnAt&&this.hostEnemies.size<cap){this.spawnAt=now+Math.max(650,1750-elapsed/40);const n=this.eventSeq++,kind=n%7===0?'water-fiend':n%4===0?'shooter':'chaser';const edge=n%2?60:WORLD_WIDTH-60,id=`enemy:${Date.now().toString(36)}:${n}`;this.hostEnemies.set(id,{id,kind,x:edge,y:190+(n*97)%(WORLD_HEIGHT-330),hp:kind==='chaser'?65:90,maxHp:kind==='chaser'?65:90,radius:kind==='chaser'?27:34,targetId:null,attackAt:Date.now()+900,statuses:[]});}
  const players=Object.values(this.state?.players??{}).filter(p=>p.connected&&!p.downed);for(const e of this.hostEnemies.values()){const target=players.sort((a,b)=>dist(e,a)-dist(e,b))[0];if(!target)continue;e.targetId=target.id;const dx=target.x-e.x,dy=target.y-e.y,d=Math.max(1,Math.hypot(dx,dy));const speed=e.kind==='shooter'&&d<330?-70:e.kind==='shooter'?90:e.kind==='water-fiend'?105:145;e.x=clamp(e.x+dx/d*speed*dt,25,WORLD_WIDTH-25);e.y=clamp(e.y+dy/d*speed*dt,145,WORLD_HEIGHT-65);}
  const raining=[...this.hostEnvironments.values()].some(e=>e.kind==='rain'&&e.endsAt>Date.now());for(const enemy of this.hostEnemies.values()){enemy.statuses=enemy.statuses.filter(s=>s.expiresAt==null||s.expiresAt>Date.now());if(raining)enemy.statuses=applyStatus(enemy.statuses,{kind:'wet',intensity:1,stacks:1,sourceId:'rain',expiresAt:Date.now()+2200},Date.now());}for(const[id,e]of this.hostEnvironments)if(e.endsAt<=Date.now())this.hostEnvironments.delete(id);
 }
 private simulateThreats(now:number){if(this.local.downed||now<this.hurtAt)return;for(const e of this.enemies()){const d=Math.hypot(e.x-this.local.x,e.y-this.local.y),hit=e.kind==='shooter'?d>210&&d<390&&Date.now()>=e.attackAt:d<e.radius+25;if(hit){this.hurtAt=now+850;this.takeDamage(e.kind==='water-fiend'?9:e.kind==='shooter'?13:16);if(e.kind==='water-fiend')this.addStatus('wet',1,4500,e.id);if(this.isHost()&&e.kind==='shooter')e.attackAt=Date.now()+1700;break;}}}
 private simulateWeather(now:number){if(now<this.weatherAt)return;this.weatherAt=now+800;for(const env of this.environments()){if(env.kind==='rain')this.addStatus('wet',1,2400,env.id);else if(Math.hypot(env.x-this.local.x,env.y-this.local.y)<=env.radius)this.takeDamage(3);}}
 private takeDamage(amount:number){const shield=this.local.statuses.find(s=>s.kind==='shielded');if(shield){shield.stacks-=1;if(shield.stacks<=0)this.local.statuses=this.local.statuses.filter(s=>s!==shield);this.notify('护盾吸收伤害');return;}this.local.hp=Math.max(0,this.local.hp-amount);if(!this.local.hp){this.local.downed=true;this.casting=null;this.target=null;this.notify('你倒下了，等待生命法术救援');}}
 private beginAt(p:Point,pointer:number){if(this.local.downed)return;const plan=resolveSpell(this.local.elements);if(!plan){this.target=p;return;}this.target=null;this.casting={plan,target:p,started:performance.now(),lastTick:0,pointer};if(plan.delivery==='self'&&plan.castMs===0)this.finishCast();}
 private finishCast(){const cast=this.casting;if(!cast)return;const age=performance.now()-cast.started;if(age<cast.plan.castMs){this.notify('吟唱未完成');this.casting=null;return;}if(!cast.plan.channel)this.releaseSpell(cast.plan,cast.target,false);this.local.elements=[];this.casting=null;}
 private releaseSpell(plan:SpellPlan,target:Point,tick:boolean){
  const castId=`${parti.playerId}:${Date.now().toString(36)}:${++this.eventSeq}`,enemies=this.hitEnemies(plan,target);for(const enemy of enemies){let amount=0;for(const effect of plan.effects)if(effect.type==='damage')amount+=reactDamage(enemy.statuses,effect.element,effect.amount).amount*(tick?.25:1);if(amount>0)void parti.action('reportEnemyDamage',{eventId:`${castId}:${enemy.id}`,enemyId:enemy.id,sourcePlayerId:parti.playerId,spellId:plan.id,amount,statuses:this.effectStatuses(plan.effects,castId)});}
  const affectsSelf=plan.delivery==='self'||this.hitsPoint(plan,target,this.local);for(const effect of plan.effects){if(effect.type==='status'&&affectsSelf)this.addStatus(effect.status,effect.intensity,effect.durationMs,castId);if(effect.type==='heal'&&affectsSelf)this.local.hp=Math.min(100,this.local.hp+effect.amount);}
  for(const player of Object.values(this.state?.players??{})){if(player.id===parti.playerId||!this.hitsPoint(plan,target,player))continue;const effects=plan.effects.filter(e=>e.type==='status'||e.type==='heal'||e.type==='impulse');if(effects.length)void parti.action('reportPlayerEffect',{eventId:`${castId}:${player.id}`,targetPlayerId:player.id,effects});}
  for(const effect of plan.effects)if(effect.type==='environment'){const env:EnvironmentState={id:`env:${castId}`,kind:effect.kind,x:target.x,y:target.y,radius:effect.kind==='rain'?9999:effect.radius??plan.radius,startedAt:Date.now(),endsAt:Date.now()+effect.durationMs};void parti.action('reportEnvironment',env);}
 }
 private hitEnemies(plan:SpellPlan,target:Point){const all=this.enemies().filter(e=>this.hitsPoint(plan,target,e));if(plan.delivery==='beam'){all.sort((a,b)=>dist(this.local,a)-dist(this.local,b));return all.slice(0,1);}return all;}
 private hitsPoint(plan:SpellPlan,target:Point,p:{x:number;y:number;radius?:number}){const r=(p.radius??22)+plan.radius;if(plan.delivery==='self')return Math.hypot(p.x-this.local.x,p.y-this.local.y)<=r;if(plan.delivery==='global')return true;if(plan.delivery==='beam'||plan.delivery==='cone'||plan.delivery==='projectile')return segmentDistance(p,this.local,target)<=r&&dist(this.local,p)<=plan.range;return Math.hypot(p.x-target.x,p.y-target.y)<=r;}
 private effectStatuses(effects:SpellEffect[],sourceId:string){return effects.flatMap(e=>e.type==='status'?[{kind:e.status,intensity:e.intensity,stacks:1,sourceId,expiresAt:Date.now()+e.durationMs}]:[]);}
 private onEnemyDamage(raw:Record<string,unknown>){const id=String(raw.eventId??'');if(!id||this.seen.has(id))return;this.seen.add(id);const enemy=this.hostEnemies.get(String(raw.enemyId))??this.state?.enemies[String(raw.enemyId)];if(!enemy)return;enemy.hp-=Number(raw.amount)||0;for(const status of (Array.isArray(raw.statuses)?raw.statuses:[])as StatusInstance[])enemy.statuses=applyStatus(enemy.statuses,status,Date.now());if(enemy.hp<=0){if(this.isHost())this.hostEnemies.delete(enemy.id);if(raw.sourcePlayerId===parti.playerId){this.local.kills+=1;this.notify('怪物击败');}}if(this.seen.size>1000)this.seen.clear();}
 private onPlayerEffect(raw:Record<string,unknown>){if(raw.targetPlayerId!==parti.playerId)return;const id=String(raw.eventId??'');if(this.seen.has(id))return;this.seen.add(id);for(const e of (Array.isArray(raw.effects)?raw.effects:[])as SpellEffect[]){if(e.type==='status')this.addStatus(e.status,e.intensity,e.durationMs,String(raw.sourcePlayerId));if(e.type==='heal'){this.local.hp=Math.min(100,this.local.hp+e.amount);if(this.local.downed&&this.local.hp>=25){this.local.downed=false;this.notify('你被生命法术救起');}}}}
 private onEnvironment(env:EnvironmentState){if(!this.isHost())return;this.hostEnvironments.set(env.id,{...env});}
 private addStatus(kind:StatusInstance['kind'],intensity:number,duration:number,sourceId:string){if(kind==='shocked'&&this.local.statuses.some(s=>s.kind==='wet')){this.casting=null;this.local.elements=[];this.notify('潮湿导电：施法被打断');}this.local.statuses=applyStatus(this.local.statuses,{kind,intensity,stacks:1,sourceId,expiresAt:performance.now()+duration},performance.now());}
 private expire(now:number){this.local.statuses=this.local.statuses.filter(s=>s.expiresAt==null||s.expiresAt>now);}
 private selectElement(element:Element){if(this.local.downed||this.local.elements.length>=ELEMENT_SLOTS)return;if(element==='lightning'&&!canQueueLightning(this.local.elements,this.local.statuses)){this.local.elements=[];this.addStatus('shocked',1,1200,'self');this.takeDamage(12);return;}this.local.elements.push(element);}
 private pointerDown=(ev:PointerEvent)=>{const p=this.screenPoint(ev);if(this.state?.phase==='lobby'){const w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio;if(Math.abs(p.x-w/2)<120&&Math.abs(p.y-h/2-45)<30)void parti.action('setReady',{ready:true});return;}if(this.state?.phase==='gameover'){if(this.isHost())void parti.action('restart');return;}const button=this.buttons.find(b=>Math.hypot(p.x-b.x,p.y-b.y)<=b.r);if(button){this.selectElement(button.element);return;}const world=this.toWorld(p);if(world)this.beginAt(world,ev.pointerId);};
 private pointerMove=(ev:PointerEvent)=>{if(this.casting?.pointer!==ev.pointerId)return;const p=this.toWorld(this.screenPoint(ev));if(p)this.casting.target=p;};
 private pointerUp=(ev:PointerEvent)=>{if(this.casting?.pointer===ev.pointerId)this.finishCast();};
 private key=(ev:KeyboardEvent)=>{const n=Number(ev.key);if(n>=1&&n<=7)this.selectElement(ELEMENTS[n-1]!);else if(ev.key==='Backspace')this.local.elements.pop();else if(ev.key==='Escape')this.local.elements=[];};
 private drawArena(){const c=mainContext;c.fillStyle='#36202d';c.fillRect(this.view.x,this.view.y,this.view.w,this.view.h);c.strokeStyle='#9a6849';c.lineWidth=4;c.strokeRect(this.view.x+2,this.view.y+2,this.view.w-4,this.view.h-4);for(const env of this.environments()){if(env.kind==='rain'){c.fillStyle='rgba(70,140,255,.14)';c.fillRect(this.view.x,this.view.y,this.view.w,this.view.h);}else{const p=this.toScreen(env);c.fillStyle='rgba(220,220,230,.25)';c.beginPath();c.arc(p.x,p.y,env.radius*this.view.scale,0,Math.PI*2);c.fill();}}for(const e of this.enemies())this.drawEnemy(e);for(const p of Object.values(this.state?.players??{})){const pos=p.id===parti.playerId?this.local:p;this.drawPlayer(pos,p.id===parti.playerId?'#ffe06a':'#78b7ff',p.name);}if(this.casting){const a=this.toScreen(this.local),b=this.toScreen(this.casting.target);c.strokeStyle=colors[this.casting.plan.elements[0]!];c.lineWidth=8;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}}
 private drawEnemy(e:EnemyState){const c=mainContext,p=this.toScreen(e),r=e.radius*this.view.scale;c.strokeStyle=e.kind==='water-fiend'?'#54baff':e.kind==='shooter'?'#d298ff':'#ff745f';c.lineWidth=4;c.strokeRect(p.x-r,p.y-r,r*2,r*2);c.fillStyle='#210d16';c.fillRect(p.x-r,p.y-r-10,r*2,5);c.fillStyle='#ff5868';c.fillRect(p.x-r,p.y-r-10,r*2*Math.max(0,e.hp/e.maxHp),5);this.text(e.kind,p.x,p.y+4,11,'#fff','center');}
 private drawPlayer(p:{x:number;y:number;hp:number;downed:boolean;statuses?:StatusInstance[]},color:string,name:string){const c=mainContext,s=this.toScreen(p),r=25*this.view.scale;c.fillStyle=p.downed?'#555':color;c.fillRect(s.x-r,s.y-r,r*2,r*2);c.strokeStyle='#fff';c.lineWidth=2;c.strokeRect(s.x-r,s.y-r,r*2,r*2);this.text(name,s.x,s.y-r-12,12,'#fff','center');c.fillStyle='#220b13';c.fillRect(s.x-r,s.y+r+5,r*2,5);c.fillStyle='#62e77b';c.fillRect(s.x-r,s.y+r+5,r*2*Math.max(0,p.hp/100),5);}
 private drawHud(w:number,h:number){const c=mainContext;c.fillStyle='#17111f';c.fillRect(0,0,w,62);c.fillRect(0,h-HUD_HEIGHT,w,HUD_HEIGHT);this.text(`HP ${this.local.hp}   击杀 ${this.local.kills}`,22,36,18,'#fff');this.text(`怪物 ${this.enemies().length}   ${this.environments().some(e=>e.kind==='rain')?'降雨':'晴朗'}`,w-22,36,17,'#ddd','right');const gap=Math.min(92,(w-30)/7),start=w/2-gap*3;for(let i=0;i<7;i++){const x=start+i*gap,y=h-49,r=Math.min(35,gap*.4),element=ELEMENTS[i]!;this.buttons.push({element,x,y,r:r+7});c.fillStyle=colors[element];c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();c.strokeStyle='#f5e8d0';c.lineWidth=3;c.stroke();this.text(labels[element],x,y+7,20,'#17111f','center');}const plan=resolveSpell(this.local.elements);const queue=this.local.elements.map(e=>labels[e]).join(' + ')||'点击场地移动';this.text(`${queue}${plan?`  ·  ${plan.name}`:''}`,w/2,h-95,15,'#fff','center');}
 private drawLobby(w:number,h:number){this.overlay(w,h,'元素训练场','1–4 人无尽合作训练');const ready=this.me()?.ready;cbox(mainContext,w/2-120,h/2+15,240,60,ready?'#355843':'#704a36');this.text(ready?'等待其他玩家':'点击准备',w/2,h/2+52,20,'#fff','center');}
 private drawGameOver(w:number,h:number){this.overlay(w,h,'全员倒地',`团队击杀 ${Object.values(this.state?.players??{}).reduce((n,p)=>n+p.kills,0)}`);this.text(this.isHost()?'点击任意位置返回大厅':'等待房主重新开始',w/2,h/2+70,17,'#ddd','center');}
 private overlay(w:number,h:number,title:string,sub:string){const c=mainContext;c.fillStyle='rgba(8,6,12,.78)';c.fillRect(0,0,w,h);this.text(title,w/2,h/2-36,34,'#fff','center');this.text(sub,w/2,h/2+2,17,'#ccc','center');}
 private computeView():View{const w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio-HUD_HEIGHT-62,scale=Math.min(w/WORLD_WIDTH,h/WORLD_HEIGHT);return{x:(w-WORLD_WIDTH*scale)/2,y:62+(h-WORLD_HEIGHT*scale)/2,w:WORLD_WIDTH*scale,h:WORLD_HEIGHT*scale,scale};}
 private screenPoint(e:PointerEvent){const r=mainCanvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}private toWorld(p:Point):Point|null{if(p.x<this.view.x||p.x>this.view.x+this.view.w||p.y<this.view.y||p.y>this.view.y+this.view.h)return null;return{x:(p.x-this.view.x)/this.view.scale,y:(p.y-this.view.y)/this.view.scale};}private toScreen(p:Point){return{x:this.view.x+p.x*this.view.scale,y:this.view.y+p.y*this.view.scale};}
 private enemies(){return [...this.hostEnemies.values()];}private environments(){return this.isHost()?[...this.hostEnvironments.values()]:Object.values(this.state?.environments??{});}private me(){return parti.playerId?this.state?.players[parti.playerId]:undefined;}private isHost(){return Boolean(parti.playerId&&this.state?.hostId===parti.playerId);}private notify(s:string){this.flash=s;this.flashUntil=performance.now()+1800;}private text(s:string,x:number,y:number,size:number,color:string,align:CanvasTextAlign='left'){const c=mainContext;c.fillStyle=color;c.font=`600 ${size}px ui-monospace,monospace`;c.textAlign=align;c.textBaseline='alphabetic';c.fillText(s,x,y);}
}
function dist(a:Point,b:Point){return Math.hypot(a.x-b.x,a.y-b.y)}function clamp(n:number,a:number,b:number){return Math.max(a,Math.min(b,n))}function cbox(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string){c.fillStyle=color;c.fillRect(x,y,w,h)}
function segmentDistance(p:Point,a:Point,b:Point){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return dist(p,a);const t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l,0,1);return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}
