import { defineRoom, type RoomContext } from '@parti/worker-sdk';
import { bossStrategies, CONTENT_FINGERPRINT, pickupStrategies, platformStrategies } from '../content';
import { CHUNK_HEIGHT, SCHEMA_VERSION, WORLD_WIDTH, type ActiveEffect, type Enemy, type GameState, type PublicPlayer, type RuntimeContext, type RuntimeEffect } from '../game/contracts';
import { activeBossAfterRestore, canStartBoss } from '../game/boss';
import { bossOrdinalForChunk, contextFor, findEntity, generateChunk, runtimeContext } from '../game/generation';

const RESPAWN_MS = 4000, INVULNERABLE_MS = 2200;
type LatestPose = { sequence: number; x: number; y: number; vy: number; cameraBottom: number; direction: number; persistedAt: number };
let latestPoses = new Map<string, LatestPose>();

export default defineRoom<GameState>({
  meta: { name: '云端远征 2', minPlayers: 1, maxPlayers: 4 }, initialState,
  onRestore(ctx) { latestPoses = new Map(); if (ctx.state.schemaVersion !== SCHEMA_VERSION || ctx.state.contentFingerprint !== CONTENT_FINGERPRINT) replaceState(ctx.state, initialState()); ctx.state.hostId = ctx.host.id; ctx.state.boss = activeBossAfterRestore(ctx.state); for (const p of Object.values(ctx.state.players)) latestPoses.set(p.id, poseFrom(p, ctx.now())); for (const p of Object.values(ctx.state.players)) if (!p.alive && p.respawnAt) scheduleRespawn(ctx, p.id, Math.max(100, p.respawnAt - ctx.now())); if (ctx.state.boss) scheduleBossTick(ctx, 200); },
  onJoin(ctx, player) { ctx.state.hostId = ctx.host.id; if (ctx.state.phase !== 'lobby' && !ctx.state.players[player.id]) { ctx.kick(player.id, '远征已经开始'); return; } const p = ctx.state.players[player.id]; if (p) { p.connected = true; p.name = player.name; } else ctx.state.players[player.id] = createPlayer(player.id, player.name); },
  onReconnect(ctx, player) { const p = ctx.state.players[player.id]; if (p) { p.connected = true; p.name = player.name; latestPoses.set(p.id, poseFrom(p, ctx.now())); } },
  onLeave(ctx, player) { const p = ctx.state.players[player.id]; if (!p) return; if (ctx.state.phase === 'lobby') delete ctx.state.players[player.id]; else { p.connected = false; p.direction = 0; updateVoid(ctx.state); checkWipe(ctx); } },
  actions: {
    setReady(ctx, { player, payload }) { if (ctx.state.phase !== 'lobby') return; const p = ctx.state.players[player.id]; if (!p) return; p.ready = Boolean(payload?.ready); const all = Object.values(ctx.state.players); if (all.length && all.every((x) => x.ready && x.connected)) startRun(ctx); },
    restart(ctx, { player }) { if (ctx.state.phase === 'gameover' && player.id === ctx.host.id) resetLobby(ctx.state); },
    publishPose(ctx, { player, payload }) { if (ctx.state.phase !== 'running') return; const p = activePlayer(ctx.state, player.id); if (!p?.alive) return; const sequence = Number(payload?.sequence), x = Number(payload?.x), y = Number(payload?.y), vy = Number(payload?.vy), cameraBottom = Number(payload?.cameraBottom), direction = Number(payload?.direction); if (!Number.isInteger(sequence) || ![x, y, vy, cameraBottom, direction].every(Number.isFinite)) return; const previous = latestPoses.get(player.id); if (previous && sequence <= previous.sequence) return; const now = ctx.now(), pose = { sequence, x: (x % WORLD_WIDTH + WORLD_WIDTH) % WORLD_WIDTH, y, vy, cameraBottom, direction, persistedAt: previous?.persistedAt ?? 0 }; latestPoses.set(player.id, pose); ctx.broadcast('skyward2:pose', { playerId: player.id, sequence, x: pose.x, y, vy, direction, sentAt: now }); if (now - pose.persistedAt >= 500) persistPose(ctx, p, pose, now); },
    shoot(ctx, { player, payload }) { const p = activePlayer(ctx.state, player.id); if (!p?.alive) return; const shotId = text(payload?.shotId, 96), x = Number(payload?.x), y = Number(payload?.y); if (!shotId || !Number.isFinite(x) || !Number.isFinite(y)) return; p.shots += 1; ctx.broadcast('skyward2:shot', { shotId, playerId: player.id, x, y, damage: effectActive(p, 'power', ctx.now()) ? 2 : 1, spread: effectActive(p, 'spread', ctx.now()), pierce: effectActive(p, 'pierce', ctx.now()) }); },
    hitEnemy(ctx, { player, payload }) { const p = activePlayer(ctx.state, player.id), sequence = Number(payload?.sequence), eventId = text(payload?.eventId, 120), enemyId = text(payload?.enemyId, 120), damage = Number(payload?.damage); if (!p?.alive || !eventId || !Number.isInteger(sequence) || sequence <= p.lastHitSequence || !Number.isFinite(damage)) return; p.lastHitSequence = sequence; damageEnemy(ctx, p, enemyId, Math.max(1, Math.min(3, Math.round(damage)))); },
    stompEnemy(ctx, { player, payload }) { const p = activePlayer(ctx.state, player.id), sequence = Number(payload?.sequence), eventId = text(payload?.eventId, 120), enemyId = text(payload?.enemyId, 120); if (!p?.alive || !eventId || !Number.isInteger(sequence) || sequence <= p.lastHitSequence) return; const enemy = enemyById(ctx.state, enemyId); if (!enemy?.stompable) return; p.lastHitSequence = sequence; damageEnemy(ctx, p, enemyId, 1); },
    landPlatform(ctx, { player, payload }) { const p = activePlayer(ctx.state, player.id), id = text(payload?.platformId, 120), sequence = Number(payload?.sequence); if (!p?.alive || !id || !Number.isInteger(sequence) || sequence <= p.lastOutcomeSequence) return; const entity = findEntity(ctx.state.seed, ctx.state.startedPlayers.length, id); if (!entity || !('width' in entity)) return; p.lastOutcomeSequence = sequence; const now = ctx.now(), strategy = platformStrategies.require(entity.kind), runtime = runtimeFor(ctx.state, entity.id, now), transitioned = strategy.transition(entity, runtime, ctx.state.entities[id]); if (transitioned) ctx.state.entities[id] = transitioned; const result = strategy.contact(entity, runtime, transitioned ?? undefined); applyEffects(ctx, p, result.effects); },
    claimPickup(ctx, { player, payload }) { const p = activePlayer(ctx.state, player.id), id = text(payload?.pickupId, 120), sequence = Number(payload?.sequence), dynamic = ctx.state.entities[id]; if (!p?.alive || !id || !Number.isInteger(sequence) || sequence <= p.lastOutcomeSequence || (dynamic?.kind === 'pickup' && dynamic.claimedBy)) return; const generated = findEntity(ctx.state.seed, ctx.state.startedPlayers.length, id), entity = dynamic?.kind === 'pickup' && dynamic.pickup ? dynamic.pickup : generated && 'durationMs' in generated ? generated : null; if (!entity) return; p.lastOutcomeSequence = sequence; const now = ctx.now(), strategy = pickupStrategies.require(entity.kind); ctx.state.entities[id] = { kind: 'pickup', pickup: dynamic?.kind === 'pickup' ? dynamic.pickup : undefined, claimedBy: p.id, claimedAt: now }; applyEffects(ctx, p, strategy.claim(entity, runtimeFor(ctx.state, id, now))); ctx.broadcast('skyward2:pickup', { playerId: p.id, kind: entity.kind }); },
    playerOutcome(ctx, { player, payload }) { const p = activePlayer(ctx.state, player.id), sequence = Number(payload?.sequence), eventId = text(payload?.eventId, 120), outcome = payload?.outcome; if (!p?.alive || !eventId || !Number.isInteger(sequence) || sequence <= p.lastOutcomeSequence || (outcome !== 'shield' && outcome !== 'death')) return; p.lastOutcomeSequence = sequence; const reason = text(payload?.reason, 40) || '危险'; if (outcome === 'shield' && p.effects.shield) { delete p.effects.shield; p.killStreak = 0; ctx.broadcast('skyward2:outcome', { playerId: p.id, eventId, outcome, reason }); return; } kill(ctx, p.id, reason); },
    enableTilt(ctx, { player, payload }) { const p = ctx.state.players[player.id]; if (p) p.tilt = Boolean(payload?.enabled); },
  },
});

function initialState(): GameState { return { schemaVersion: SCHEMA_VERSION, contentFingerprint: CONTENT_FINGERPRINT, phase: 'lobby', hostId: null, seed: 0, startedAt: null, startedPlayers: [], players: {}, teamVoidY: 0, highestY: 0, completedBossCount: 0, entities: {}, boss: null, bestRun: { height: 0, bosses: 0, kills: 0, noDamageHeight: 0 }, message: '所有人准备后开始' }; }
function createPlayer(id: string, name: string): PublicPlayer { return { id, name, ready: false, connected: true, alive: true, respawnAt: null, invulnerableUntil: 0, x: WORLD_WIDTH / 2, y: 120, vy: 0, cameraBottom: 0, direction: 0, positionEpoch: 0, kills: 0, deaths: 0, shots: 0, killStreak: 0, noDamageHeight: 0, tilt: false, lastHitSequence: 0, lastOutcomeSequence: 0, effects: {} }; }
function replaceState(target: GameState, next: GameState) { for (const key of Object.keys(target) as Array<keyof GameState>) delete target[key]; Object.assign(target, next); }
function poseFrom(p: PublicPlayer, now: number): LatestPose { return { sequence: -1, x: p.x, y: p.y, vy: p.vy, cameraBottom: p.cameraBottom, direction: p.direction, persistedAt: now }; }
function text(value: unknown, max: number) { return typeof value === 'string' ? value.slice(0, max) : ''; }
function activePlayer(s: GameState, id: string) { return s.phase === 'running' && s.startedPlayers.includes(id) ? s.players[id] : undefined; }
function startRun(ctx: RoomContext<GameState>) { const s = ctx.state; Object.assign(s, { schemaVersion: SCHEMA_VERSION, contentFingerprint: CONTENT_FINGERPRINT, phase: 'running', seed: Math.floor(ctx.random() * 0xffffffff) >>> 0, startedAt: ctx.now(), startedPlayers: Object.keys(s.players), teamVoidY: 0, highestY: 0, completedBossCount: 0, entities: {}, boss: null, message: '向上攀登' }); for (const p of Object.values(s.players)) { const positionEpoch = p.positionEpoch + 1; Object.assign(p, createPlayer(p.id, p.name), { positionEpoch }); } ctx.broadcast('skyward2:start', {}); }
function resetLobby(s: GameState) { for (const [id, p] of Object.entries(s.players)) { if (!p.connected) delete s.players[id]; else { const epoch = p.positionEpoch; Object.assign(p, createPlayer(id, p.name), { positionEpoch: epoch }); } } Object.assign(s, { phase: 'lobby', seed: 0, startedAt: null, startedPlayers: [], teamVoidY: 0, highestY: 0, completedBossCount: 0, entities: {}, boss: null, message: '所有人准备后开始' }); }
function runtimeFor(s: GameState, entityId: string, now: number): RuntimeContext { return runtimeContext(contextFor(s.seed, Number(entityId.split(':')[0]), Math.max(1, s.startedPlayers.length)), s.startedAt ?? now, now); }
function effectActive(p: PublicPlayer, id: keyof PublicPlayer['effects'], now: number) { const e = p.effects[id]; return Boolean(e && (e.endsAt == null || e.endsAt > now)); }
function applyEffects(ctx: RoomContext<GameState>, p: PublicPlayer, effects: RuntimeEffect[]) { for (const effect of effects) { if (effect.kind === 'entity-state') ctx.state.entities[effect.entityId] = effect.state; else if (effect.kind === 'apply-effect') applyEffect(p, effect.effect); else if (effect.kind === 'remove-effect') delete p.effects[effect.effectId]; else if (effect.kind === 'stat') { if (effect.stat === 'kills') p.kills += effect.amount; else p.noDamageHeight = Math.max(p.noDamageHeight, effect.amount); } else if (effect.kind === 'message') ctx.state.message = effect.text; else if (effect.kind === 'spawn-enemy') ctx.state.entities[effect.enemy.id] = { kind: 'summon', enemy: effect.enemy, hp: effect.enemy.hp, defeated: false, changedAt: ctx.now() }; else if (effect.kind === 'spawn-hazard') ctx.state.entities[`hazard:${effect.hazard.activeAt}:${Object.keys(ctx.state.entities).length}`] = effect.hazard; } }
function applyEffect(p: PublicPlayer, effect: ActiveEffect) { if (effect.id === 'rocket') delete p.effects.propeller; if (effect.id === 'propeller') delete p.effects.rocket; p.effects[effect.id] = { ...effect, stacks: 1 }; }
function updateVoid(s: GameState) { const alive = s.startedPlayers.map((id) => s.players[id]).filter((p) => p?.connected && p.alive); if (alive.length) s.teamVoidY = Math.max(s.teamVoidY, Math.min(...alive.map((p) => p.cameraBottom))); }
function kill(ctx: RoomContext<GameState>, id: string, reason: string) { const p = ctx.state.players[id]; if (!p?.alive || ctx.state.phase !== 'running') return; p.alive = false; p.deaths += 1; p.killStreak = 0; p.respawnAt = ctx.now() + RESPAWN_MS; p.vy = 0; ctx.broadcast('skyward2:death', { playerId: id, reason }); if (!checkWipe(ctx)) scheduleRespawn(ctx, id, RESPAWN_MS); }
function checkWipe(ctx: RoomContext<GameState>) { if (ctx.state.startedPlayers.some((id) => ctx.state.players[id]?.connected && ctx.state.players[id].alive)) return false; const kills = Math.max(0, ...Object.values(ctx.state.players).map((p) => p.kills)), noDamageHeight = Math.max(0, ...Object.values(ctx.state.players).map((p) => p.noDamageHeight)); ctx.state.bestRun = { height: Math.max(ctx.state.bestRun.height, ctx.state.highestY), bosses: Math.max(ctx.state.bestRun.bosses, ctx.state.completedBossCount), kills: Math.max(ctx.state.bestRun.kills, kills), noDamageHeight: Math.max(ctx.state.bestRun.noDamageHeight, noDamageHeight) }; ctx.state.phase = 'gameover'; ctx.state.boss = null; ctx.state.message = '远征结束'; for (const id of ctx.state.startedPlayers) ctx.clearTimer(`respawn:${id}`); return true; }
function scheduleRespawn(ctx: RoomContext<GameState>, id: string, delay: number) { ctx.setTimer(`respawn:${id}`, delay, () => { const p = ctx.state.players[id]; if (!p || p.alive || ctx.state.phase !== 'running') return; p.alive = true; p.respawnAt = null; p.invulnerableUntil = ctx.now() + INVULNERABLE_MS; p.x = WORLD_WIDTH / 2; p.y = Math.max(ctx.state.teamVoidY + 180, p.cameraBottom + 180); p.vy = 760; p.positionEpoch += 1; }); }

function enemyById(s: GameState, id: string): Enemy | null { const dynamic = s.entities[id]; if (dynamic?.kind === 'summon') return dynamic.enemy; const entity = findEntity(s.seed, s.startedPlayers.length, id); return entity && 'hp' in entity ? entity : null; }
function damageEnemy(ctx: RoomContext<GameState>, p: PublicPlayer, id: string, damage: number) {
  const enemy = enemyById(ctx.state, id); if (!enemy) return; if (enemy.boss && ctx.state.boss?.enemyId !== id) return;
  if (ctx.state.boss?.enemyId === id) { const strategy = bossStrategies.require(ctx.state.boss.bossId), phase = strategy.phases.find((x) => ctx.state.boss!.hp / ctx.state.boss!.maxHp >= x.minHpRatio)!; const applied = strategy.id === 'mechanical-core' && !phase.weak && phase.id !== 'phase-3' ? Math.max(1, Math.floor(damage / 2)) : damage; ctx.state.boss.hp = Math.max(0, ctx.state.boss.hp - applied); if (!ctx.state.boss.hp) defeatBoss(ctx); return; }
  const current = ctx.state.entities[id], hp = (current?.kind === 'enemy' ? current.hp : current?.kind === 'summon' ? current.hp : enemy.hp) - damage;
  if (current?.kind === 'summon') ctx.state.entities[id] = { ...current, hp, defeated: hp <= 0, changedAt: ctx.now() }; else ctx.state.entities[id] = { kind: 'enemy', hp, defeated: hp <= 0, changedAt: ctx.now() };
  if (hp <= 0) { p.kills += 1; p.killStreak += 1; spawnDrop(ctx.state, enemy, ctx.now()); ctx.broadcast('skyward2:enemy-defeated', { enemyId: id, playerId: p.id }); }
}
function spawnDrop(state: GameState, enemy: Enemy, now: number) { const runtime = runtimeFor(state, enemy.id, now), roll = runtime.rng(`drop:${enemy.id}`).float(); if (roll >= .35 || !enemy.drops.length) return; const total = enemy.drops.reduce((sum, item) => sum + item.weight, 0); let cursor = runtime.rng(`drop-kind:${enemy.id}`).float() * total, chosen = enemy.drops[0]!; for (const item of enemy.drops) { cursor -= item.weight; if (cursor <= 0) { chosen = item; break; } } const strategy = pickupStrategies.require(chosen.pickup), id = `${enemy.id}:drop`; state.entities[id] = { kind: 'pickup', pickup: { id, kind: chosen.pickup, x: enemy.x, y: enemy.y, durationMs: strategy.durationMs, sourceId: enemy.id } }; }
function startBoss(ctx: RoomContext<GameState>, chunkIndex: number) { if (!canStartBoss(ctx.state, chunkIndex)) return; const chunk = generateChunk(ctx.state.seed, chunkIndex, ctx.state.startedPlayers.length), enemy = chunk.enemies.find((e) => e.boss); if (!enemy) return; const now = ctx.now(); ctx.state.boss = { enemyId: enemy.id, bossId: enemy.kind as NonNullable<GameState['boss']>['bossId'], ordinal: bossOrdinalForChunk(chunkIndex), chunkIndex, hp: enemy.hp, maxHp: enemy.hp, phaseId: 'phase-1', startedAt: now, nextAttackAt: now + 3000, sequence: 0, attacks: [], summons: [] }; ctx.state.message = `${enemy.kind} 封锁了上行通路`; scheduleBossTick(ctx, 200); }
function scheduleBossTick(ctx: RoomContext<GameState>, delay = 200) {
  ctx.setTimer('boss:tick', delay, () => {
    const boss = ctx.state.boss; if (!boss || ctx.state.phase !== 'running') return;
    const now = ctx.now(), strategy = bossStrategies.require(boss.bossId), generated = findEntity(ctx.state.seed, ctx.state.startedPlayers.length, boss.enemyId); if (!generated || !('hp' in generated)) return;
    boss.attacks = boss.attacks.filter((a) => a.endsAt > now);
    const ratio = boss.hp / boss.maxHp, phase = strategy.phases.find((x) => ratio >= x.minHpRatio) ?? strategy.phases.at(-1)!; boss.phaseId = phase.id;
    if (now >= boss.nextAttackAt) {
      const targets = ctx.state.startedPlayers.map((id) => ctx.state.players[id]).filter((p) => p?.connected && p.alive), target = targets[boss.sequence % Math.max(1, targets.length)];
      const runtime = runtimeFor(ctx.state, boss.enemyId, now), attack = strategy.selectAttack(generated, runtime, phase, boss.sequence, target);
      if (attack.kind === 'platform-hazard' || attack.kind === 'platform-toggle' || attack.kind === 'slam') { const arena = generateChunk(ctx.state.seed, boss.chunkIndex, ctx.state.startedPlayers.length).platforms.filter((p) => p.kind !== 'boss-exit'); attack.platformId = arena[boss.sequence % arena.length]?.id; }
      boss.attacks.push(attack);
      if (attack.kind !== 'summon') ctx.state.entities[attack.id] = { kind: 'hazard', hazardKind: attack.kind, x: attack.x, y: attack.y, radius: attack.radius, activeAt: attack.activeAt, endsAt: attack.endsAt, platformId: attack.platformId, direction: attack.direction };
      if (attack.kind === 'summon') { const summons = strategy.summons(generated, runtime, boss.sequence); boss.summons.push(...summons); for (const summon of summons) ctx.state.entities[summon.id] = { kind: 'summon', enemy: summon, hp: summon.hp, defeated: false, changedAt: now }; }
      boss.sequence += 1; boss.nextAttackAt = now + Math.round(4400 * phase.cooldownScale);
    }
    scheduleBossTick(ctx);
  });
}
function defeatBoss(ctx: RoomContext<GameState>) { const boss = ctx.state.boss; if (!boss) return; ctx.clearTimer('boss:tick'); for (const summon of boss.summons) delete ctx.state.entities[summon.id]; ctx.state.completedBossCount = Math.max(ctx.state.completedBossCount, boss.ordinal); ctx.state.boss = null; ctx.state.message = '通路恢复，继续向上'; ctx.broadcast('skyward2:boss-defeated', { chunkIndex: boss.chunkIndex, ordinal: boss.ordinal }); }
function persistPose(ctx: RoomContext<GameState>, p: PublicPlayer, pose: LatestPose, now: number) { p.x = pose.x; p.y = pose.y; p.vy = pose.vy; p.direction = pose.direction; p.cameraBottom = Math.max(p.cameraBottom, Math.min(pose.cameraBottom, pose.y - 140)); p.noDamageHeight = Math.max(p.noDamageHeight, pose.y); pose.persistedAt = now; ctx.state.highestY = Math.max(ctx.state.highestY, pose.y); expireEffects(p, now); updateVoid(ctx.state); pruneWorld(ctx.state, now); const chunk = Math.floor(pose.y / CHUNK_HEIGHT); if (pose.y >= chunk * CHUNK_HEIGHT + 620) startBoss(ctx, chunk); }
function expireEffects(p: PublicPlayer, now: number) { for (const [id, effect] of Object.entries(p.effects)) if (effect?.endsAt != null && effect.endsAt <= now) delete p.effects[id as keyof PublicPlayer['effects']]; }
function pruneWorld(s: GameState, now: number) { const below = Math.floor(s.teamVoidY / CHUNK_HEIGHT) - 2; for (const [id, value] of Object.entries(s.entities)) { const chunk = Number(id.split(':')[0]); const expired = value.kind === 'hazard' && value.endsAt <= now; if (expired || (Number.isInteger(chunk) && chunk < below)) delete s.entities[id]; } }
