import { defineRoom, type RoomContext } from '@parti/worker-sdk';
import type { Card, GameState, PrivateState, SeatState, Settlement, Suit, VariantId, VariantPublicState } from '../game/types';
import { createDeck, shuffle, sortCards, takeCards } from './cards';
import { chooseChameleon, chameleonCardPoints, isChameleonLegal, validateChoice } from './variants/chameleon';
import { analyzeDoudizhu, canBeatDoudizhu, enumerateDoudizhu } from './variants/doudizhu';
import { analyzeGandengyan, canBeatGandengyan, enumerateGandengyan } from './variants/gandengyan';
import { VARIANTS, variantList } from './variants/registry';

let hands:Record<string,Card[]>={};
let deck:Card[]=[];
let landlordHidden:Card[]=[];
let discardPile:Card[]=[];
let trickPasses=0;
let playCounts:Record<string,number>={};

export default defineRoom<GameState>({
  meta:{name:'超级扑克',minPlayers:1,maxPlayers:8},
  initialState:()=>initialState(),
  onRestore(ctx){resetRoundSecrets(ctx);ctx.state.phase='lobby';ctx.state.currentPlayerId=null;ctx.state.lastPlay=null;ctx.state.settlement=null;ctx.state.variant={};ctx.state.message='房间已恢复，请重新准备';for(const seat of occupied(ctx.state)){seat.ready=seat.bot;seat.handCount=0;seat.role=null;if(!seat.bot)seat.connected=false}},
  onJoin(ctx,player){
    const old=ctx.state.seats.find(s=>s?.id===player.id);if(old){old.connected=true;old.name=player.name;sendPrivate(ctx,old.id);return}
    if(ctx.state.phase!=='lobby'){ctx.kick(player.id,'牌局进行中');return}
    const botIndex=ctx.state.seats.findIndex(s=>s?.bot);const emptyIndex=ctx.state.seats.findIndex(s=>!s);const seat=botIndex>=0?botIndex:emptyIndex;
    if(seat<0){ctx.kick(player.id,'房间已满');return}ctx.state.seats[seat]=makeSeat(player.id,player.name,seat,false);if(!ctx.state.hostId)ctx.state.hostId=player.id;ctx.state.message='选择玩法、安排AI，所有真人准备后开局';
  },
  onReconnect(ctx,player){const seat=findSeat(ctx.state,player.id);if(seat){seat.connected=true;seat.name=player.name;sendPrivate(ctx,player.id)}},
  onLeave(ctx,player){const seat=findSeat(ctx.state,player.id);if(!seat)return;if(ctx.state.phase==='lobby'||ctx.state.phase==='settlement'){ctx.state.seats[seat.seat]=null;if(ctx.state.hostId===player.id)ctx.state.hostId=occupied(ctx.state).find(s=>!s.bot)?.id??null;return}seat.connected=false;scheduleBot(ctx)},
  actions:{
    selectVariant(ctx,{player,payload}){if(!hostLobby(ctx,player.id))return;const id=String(payload?.variantId) as VariantId;if(!VARIANTS[id])return;const meta=VARIANTS[id].meta;const humans=occupied(ctx.state).filter(s=>!s.bot);if(humans.length>meta.maxPlayers){notice(ctx,player.id,`当前有 ${humans.length} 位真人，超过${meta.name}上限`);return}for(let seat=ctx.state.seats.length-1;seat>=meta.maxPlayers;seat-=1){const current=ctx.state.seats[seat];if(current&&!current.bot){notice(ctx,player.id,'请先让超出人数上限的真人离开');return}ctx.state.seats[seat]=null}ctx.state.variantId=id;ctx.state.message=`已选择${meta.name}，请安排席位并准备`;clearReady(ctx.state)},
    addBot(ctx,{player,payload}){if(!hostLobby(ctx,player.id))return;const index=Number(payload?.seat),meta=VARIANTS[ctx.state.variantId].meta;if(!Number.isInteger(index)||index<0||index>=meta.maxPlayers||ctx.state.seats[index])return;ctx.state.seats[index]=makeSeat(`bot:${index}`,`牌侠 ${index+1}`,index,true)},
    removeBot(ctx,{player,payload}){if(!hostLobby(ctx,player.id))return;const index=Number(payload?.seat),seat=ctx.state.seats[index];if(seat?.bot)ctx.state.seats[index]=null},
    setReady(ctx,{player,payload}){if(ctx.state.phase!=='lobby')return;const seat=findSeat(ctx.state,player.id);if(seat&&!seat.bot)seat.ready=Boolean(payload?.ready)},
    startGame(ctx,{player}){if(!hostLobby(ctx,player.id))return;const seats=occupied(ctx.state),meta=VARIANTS[ctx.state.variantId].meta;if(seats.length<meta.minPlayers||seats.length>meta.maxPlayers){notice(ctx,player.id,`${meta.name}需要 ${meta.minPlayers}${meta.minPlayers===meta.maxPlayers?'':`–${meta.maxPlayers}`} 人`);return}if(seats.some(s=>!s.bot&&!s.ready)){notice(ctx,player.id,'请等待所有真人准备');return}startGame(ctx)},
    playCards(ctx,{player,payload}){const seat=findSeat(ctx.state,player.id);if(!seat||!seat.connected)return;if(ctx.state.phase==='bidding'){bidDoudizhu(ctx,seat,Number(payload?.choice?.score));return}const ids=Array.isArray(payload?.cardIds)?payload.cardIds.filter((id:unknown):id is string=>typeof id==='string'):[];playCards(ctx,seat,ids,payload?.choice)},
    pass(ctx,{player}){const seat=findSeat(ctx.state,player.id);if(seat?.connected)RUNTIMES[ctx.state.variantId].pass?.(ctx,seat)},
    drawCard(ctx,{player}){const seat=findSeat(ctx.state,player.id);if(seat?.connected)RUNTIMES[ctx.state.variantId].draw?.(ctx,seat)},
    syncPrivate(ctx,{player}){if(findSeat(ctx.state,player.id))sendPrivate(ctx,player.id)},
    returnToLobby(ctx,{player}){if(ctx.state.phase!=='settlement'||player.id!==ctx.state.hostId)return;returnLobby(ctx)},
  }
});

function initialState():GameState{return{schema:1,phase:'lobby',variantId:'doudizhu',variants:variantList(),hostId:null,seats:Array(8).fill(null),currentPlayerId:null,lastPlay:null,variant:{},settlement:null,message:'等待玩家加入',actionSeq:0}}
function makeSeat(id:string,name:string,seat:number,bot:boolean):SeatState{return{id,name,seat,bot,connected:true,ready:bot,handCount:0,score:0,role:null}}
function occupied(state:GameState){return state.seats.filter((s):s is SeatState=>Boolean(s)).sort((a,b)=>a.seat-b.seat)}
function findSeat(state:GameState,id:string){return state.seats.find(s=>s?.id===id)??null}
function hostLobby(ctx:RoomContext<GameState>,id:string){return ctx.state.phase==='lobby'&&ctx.state.hostId===id}
function clearReady(state:GameState){for(const s of occupied(state))s.ready=s.bot}
function nextId(state:GameState,id:string){const seats=occupied(state),index=seats.findIndex(s=>s.id===id);return seats[(index+1)%seats.length]!.id}
function notice(ctx:RoomContext<GameState>,id:string,message:string){ctx.send(id,'poker:notice',{message})}
function fx(ctx:RoomContext<GameState>,kind:string,actorId?:string,cards?:Card[],label?:string){ctx.broadcast('poker:action-fx',{actionId:`poker:${Date.now()}:${++ctx.state.actionSeq}`,occurredAt:Date.now(),kind,actorId,cards,label})}
function resetRoundSecrets(ctx:RoomContext<GameState>){ctx.clearTimer('poker:bot');hands={};deck=[];landlordHidden=[];discardPile=[];trickPasses=0;playCounts={}}

function startGame(ctx:RoomContext<GameState>){resetRoundSecrets(ctx);const state=ctx.state;state.phase='dealing';state.currentPlayerId=null;state.lastPlay=null;state.settlement=null;state.variant={};for(const s of occupied(state)){s.ready=s.bot;s.handCount=0;s.score=0;s.role=null}RUNTIMES[state.variantId].start(ctx);sendAllPrivate(ctx);fx(ctx,'deal',undefined,undefined,'发牌');scheduleBot(ctx)}
function startDoudizhu(ctx:RoomContext<GameState>){const seats=occupied(ctx.state);deck=shuffle(createDeck({jokers:true,aceHigh:true}),()=>ctx.random());hands={};for(const s of seats)hands[s.id]=sortCards(deck.splice(0,17));landlordHidden=deck.splice(0,3);const starter=seats[0]!.id;ctx.state.phase='bidding';ctx.state.variant={bid:{currentPlayerId:starter,highestScore:0,highestPlayerId:null,turns:0},landlordCards:[],multiplier:1,passCount:0};ctx.state.message=`${findSeat(ctx.state,starter)!.name} 开始叫地主`;for(const s of seats)s.handCount=17;ctx.state.currentPlayerId=starter}
function startGandengyan(ctx:RoomContext<GameState>){const seats=occupied(ctx.state),copies=seats.length===2?1:2;deck=shuffle(createDeck({jokers:true,copies,aceHigh:true}),()=>ctx.random());hands={};for(const s of seats)hands[s.id]=sortCards(deck.splice(0,s.seat===seats[0]!.seat?6:5));for(const s of seats)s.handCount=hands[s.id]!.length;ctx.state.phase='playing';ctx.state.currentPlayerId=seats[0]!.id;ctx.state.variant={bombs:0,deckCount:deck.length,passCount:0};ctx.state.message=`${seats[0]!.name} 先出牌`}
function startChameleon(ctx:RoomContext<GameState>){const seats=occupied(ctx.state);deck=shuffle(createDeck(),()=>ctx.random());hands={};for(const s of seats)hands[s.id]=sortCards(deck.splice(0,5));let firstIndex=deck.findIndex(c=>c.rank!==11);if(firstIndex<0)firstIndex=0;const [first]=deck.splice(firstIndex,1);discardPile=[first!];for(const s of seats)s.handCount=5;ctx.state.phase='playing';ctx.state.currentPlayerId=seats[0]!.id;ctx.state.lastPlay={playerId:'table',cards:[first!]};ctx.state.variant={activeSuit:first!.suit,activeRank:first!.rank,deckCount:deck.length,drawPending:false};ctx.state.message=`${seats[0]!.name} 出牌`}

function playCards(ctx:RoomContext<GameState>,seat:SeatState,ids:string[],choice:unknown){if(ctx.state.phase!=='playing'||ctx.state.currentPlayerId!==seat.id)return invalid(ctx,seat.id,'还没轮到你');const selected=takeCards(hands[seat.id]??[],ids);if(!selected?.length)return invalid(ctx,seat.id,'请选择有效手牌');RUNTIMES[ctx.state.variantId].play(ctx,seat,selected,choice)}
function removeSelected(id:string,cards:Card[]){const ids=new Set(cards.map(c=>c.id));hands[id]=sortCards(hands[id]!.filter(c=>!ids.has(c.id)))}
function invalid(ctx:RoomContext<GameState>,id:string,message:string){notice(ctx,id,message)}

function playDoudizhu(ctx:RoomContext<GameState>,seat:SeatState,cards:Card[]){const analysis=analyzeDoudizhu(cards);if(!analysis)return invalid(ctx,seat.id,'牌型不合法');const previous=ctx.state.lastPlay?.analysis??null;if(!canBeatDoudizhu(analysis,previous))return invalid(ctx,seat.id,'需要出同牌型更大的牌，或使用炸弹/火箭');removeSelected(seat.id,cards);seat.handCount=hands[seat.id]!.length;playCounts[seat.id]=(playCounts[seat.id]??0)+1;ctx.state.lastPlay={playerId:seat.id,cards:sortCards(cards),analysis};trickPasses=0;ctx.state.variant.passCount=0;if(analysis.type==='bomb'||analysis.type==='rocket')ctx.state.variant.multiplier=(ctx.state.variant.multiplier??1)*2;fx(ctx,'play',seat.id,cards,analysis.label);if(!seat.handCount)return settleDoudizhu(ctx,seat.id);ctx.state.currentPlayerId=nextId(ctx.state,seat.id);ctx.state.message=`轮到 ${findSeat(ctx.state,ctx.state.currentPlayerId)!.name}`;sendAllPrivate(ctx);scheduleBot(ctx)}
function settleDoudizhu(ctx:RoomContext<GameState>,winnerId:string){const seats=occupied(ctx.state),landlord=seats.find(s=>s.role==='landlord')!,landlordWon=winnerId===landlord.id,multiplier=ctx.state.variant.multiplier??1;const farmers=seats.filter(s=>s.role==='farmer');const spring=landlordWon?farmers.every(s=>(playCounts[s.id]??0)===0):(playCounts[landlord.id]??0)<=1;const total=multiplier*(spring?2:1),deltas:Record<string,number>={};deltas[landlord.id]=landlordWon?total*2:-total*2;for(const f of farmers)deltas[f.id]=landlordWon?-total:total;settle(ctx,{winnerIds:landlordWon?[landlord.id]:farmers.map(s=>s.id),deltas,title:landlordWon?'地主胜利':'农民胜利',detail:`倍数 x${total}${spring?' · 春天':''}`})}
function bidDoudizhu(ctx:RoomContext<GameState>,seat:SeatState,score:number){const bid=ctx.state.variant.bid;if(ctx.state.phase!=='bidding'||!bid||bid.currentPlayerId!==seat.id||!Number.isInteger(score)||score<0||score>3||(score>0&&score<=bid.highestScore))return;bid.turns+=1;if(score>0){bid.highestScore=score;bid.highestPlayerId=seat.id}fx(ctx,'bid',seat.id,undefined,score?'叫 '+score+' 分':'不叫');if(score===3||bid.turns>=3){if(!bid.highestPlayerId){startDoudizhu(ctx);sendAllPrivate(ctx);scheduleBot(ctx);return}const landlord=findSeat(ctx.state,bid.highestPlayerId)!;for(const s of occupied(ctx.state))s.role=s.id===landlord.id?'landlord':'farmer';hands[landlord.id]=sortCards([...hands[landlord.id]!,...landlordHidden]);landlord.handCount=20;ctx.state.variant.landlordCards=[...landlordHidden];ctx.state.variant.multiplier=bid.highestScore;ctx.state.variant.bid=undefined;ctx.state.phase='playing';ctx.state.currentPlayerId=landlord.id;ctx.state.message=`${landlord.name} 成为地主`;sendAllPrivate(ctx);fx(ctx,'landlord',landlord.id,landlordHidden,'地主');scheduleBot(ctx);return}bid.currentPlayerId=nextId(ctx.state,seat.id);ctx.state.currentPlayerId=bid.currentPlayerId;scheduleBot(ctx)}

function playGandengyan(ctx:RoomContext<GameState>,seat:SeatState,cards:Card[]){const analysis=analyzeGandengyan(cards);if(!analysis)return invalid(ctx,seat.id,'牌型不合法，王不能单独出');if(!canBeatGandengyan(analysis,ctx.state.lastPlay?.analysis??null))return invalid(ctx,seat.id,'必须以相同牌型恰好大一级接牌');removeSelected(seat.id,cards);seat.handCount=hands[seat.id]!.length;ctx.state.lastPlay={playerId:seat.id,cards:sortCards(cards),analysis};trickPasses=0;ctx.state.variant.passCount=0;if(analysis.type==='bomb')ctx.state.variant.bombs=(ctx.state.variant.bombs??0)+1;fx(ctx,'play',seat.id,cards,analysis.label);if(!seat.handCount)return settleGandengyan(ctx,seat.id);ctx.state.currentPlayerId=nextId(ctx.state,seat.id);sendAllPrivate(ctx);scheduleBot(ctx)}
function settleGandengyan(ctx:RoomContext<GameState>,winnerId:string){const factor=2**(ctx.state.variant.bombs??0),deltas:Record<string,number>={},seats=occupied(ctx.state);let sum=0;for(const s of seats)if(s.id!==winnerId){const loss=(hands[s.id]?.length??0)*factor;deltas[s.id]=-loss;sum+=loss}deltas[winnerId]=sum;settle(ctx,{winnerIds:[winnerId],deltas,title:`${findSeat(ctx.state,winnerId)!.name} 胜利`,detail:`炸弹倍率 x${factor}`})}
function pass(ctx:RoomContext<GameState>,seat:SeatState){if(ctx.state.phase!=='playing'||ctx.state.currentPlayerId!==seat.id||!ctx.state.lastPlay||ctx.state.lastPlay.playerId===seat.id)return;if(ctx.state.variantId==='doudizhu'||ctx.state.variantId==='gandengyan'){trickPasses+=1;ctx.state.variant.passCount=trickPasses;fx(ctx,'pass',seat.id,undefined,'不出');const count=occupied(ctx.state).length;if(trickPasses>=count-1){const leader=ctx.state.lastPlay.playerId;ctx.state.lastPlay=null;trickPasses=0;ctx.state.variant.passCount=0;if(ctx.state.variantId==='gandengyan')refillGandengyan(ctx,leader);ctx.state.currentPlayerId=leader;fx(ctx,'clear',leader,undefined,'新一轮')}else ctx.state.currentPlayerId=nextId(ctx.state,seat.id);sendAllPrivate(ctx);scheduleBot(ctx)}}
function refillGandengyan(ctx:RoomContext<GameState>,leader:string){const seats=occupied(ctx.state),start=seats.findIndex(s=>s.id===leader);for(let offset=0;offset<seats.length&&deck.length;offset+=1){const s=seats[(start+offset)%seats.length]!;hands[s.id]!.push(deck.shift()!);hands[s.id]=sortCards(hands[s.id]!);s.handCount=hands[s.id]!.length}ctx.state.variant.deckCount=deck.length}

function playChameleon(ctx:RoomContext<GameState>,seat:SeatState,cards:Card[],rawChoice:unknown){if(cards.length!==1)return invalid(ctx,seat.id,'变色龙每次只能出一张');const card=cards[0]!,suit=ctx.state.variant.activeSuit!,rank=ctx.state.variant.activeRank!;if(!isChameleonLegal(card,suit,rank))return invalid(ctx,seat.id,'只能出同花色、同点数或J');const choice=card.rank===11?validateChoice(rawChoice):null;if(card.rank===11&&!choice)return invalid(ctx,seat.id,'请为变色龙指定花色和点数');removeSelected(seat.id,cards);discardPile.push(card);seat.handCount=hands[seat.id]!.length;ctx.state.lastPlay={playerId:seat.id,cards:[card],choice:choice??undefined};ctx.state.variant.activeSuit=choice?.suit??card.suit;ctx.state.variant.activeRank=choice?.rank??card.rank;ctx.state.variant.drawPending=false;fx(ctx,'play',seat.id,cards,card.rank===11?`变为 ${suitName(choice!.suit)} ${choice!.rank}`:'出牌');if(!seat.handCount)return settleChameleon(ctx,seat.id);ctx.state.currentPlayerId=nextId(ctx.state,seat.id);sendAllPrivate(ctx);scheduleBot(ctx)}
function drawChameleon(ctx:RoomContext<GameState>,seat:SeatState){if(ctx.state.variantId!=='chameleon'||ctx.state.phase!=='playing'||ctx.state.currentPlayerId!==seat.id)return;const legal=hands[seat.id]!.some(c=>isChameleonLegal(c,ctx.state.variant.activeSuit!,ctx.state.variant.activeRank!));if(legal)return invalid(ctx,seat.id,'有牌可出时不能摸牌');if(!deck.length&&discardPile.length>1){const top=discardPile.pop()!;deck=shuffle(discardPile,()=>ctx.random());discardPile=[top]}if(!deck.length){ctx.state.currentPlayerId=nextId(ctx.state,seat.id);sendAllPrivate(ctx);scheduleBot(ctx);return}const card=deck.shift()!;hands[seat.id]=sortCards([...hands[seat.id]!,card]);seat.handCount=hands[seat.id]!.length;ctx.state.variant.deckCount=deck.length;fx(ctx,'draw',seat.id,undefined,'摸牌');if(isChameleonLegal(card,ctx.state.variant.activeSuit!,ctx.state.variant.activeRank!)){ctx.state.variant.drawPending=true;sendAllPrivate(ctx);scheduleBot(ctx);return}ctx.state.variant.drawPending=false;ctx.state.currentPlayerId=nextId(ctx.state,seat.id);sendAllPrivate(ctx);scheduleBot(ctx)}
function settleChameleon(ctx:RoomContext<GameState>,winnerId:string){const deltas:Record<string,number>={},seats=occupied(ctx.state);let sum=0;for(const s of seats)if(s.id!==winnerId){const loss=(hands[s.id]??[]).reduce((n,c)=>n+chameleonCardPoints(c),0);deltas[s.id]=-loss;sum+=loss}deltas[winnerId]=sum;settle(ctx,{winnerIds:[winnerId],deltas,title:`${findSeat(ctx.state,winnerId)!.name} 胜利`,detail:`获得 ${sum} 分`})}
function suitName(suit:Suit){return{spades:'黑桃',hearts:'红心',clubs:'梅花',diamonds:'方块',joker:'王'}[suit]}

function settle(ctx:RoomContext<GameState>,result:Settlement){ctx.clearTimer('poker:bot');ctx.state.phase='settlement';ctx.state.currentPlayerId=null;ctx.state.settlement=result;for(const [id,delta] of Object.entries(result.deltas)){const s=findSeat(ctx.state,id);if(s)s.score+=delta}ctx.state.message=result.title;ctx.broadcast('poker:settlement',result);fx(ctx,'settlement',result.winnerIds[0],undefined,result.title);sendAllPrivate(ctx)}
function returnLobby(ctx:RoomContext<GameState>){resetRoundSecrets(ctx);ctx.state.phase='lobby';ctx.state.currentPlayerId=null;ctx.state.lastPlay=null;ctx.state.variant={};ctx.state.settlement=null;for(const s of occupied(ctx.state)){if(!s.bot&&!s.connected){ctx.state.seats[s.seat]=null;continue}s.ready=s.bot;s.handCount=0;s.role=null;s.score=0}ensureHost(ctx);ctx.state.message='可以重新选择玩法和席位，请准备'}
function ensureHost(ctx:RoomContext<GameState>){if(!ctx.state.hostId||!findSeat(ctx.state,ctx.state.hostId))ctx.state.hostId=occupied(ctx.state).find(s=>!s.bot)?.id??null}
function privateFor(ctx:RoomContext<GameState>,id:string):PrivateState{const hand=hands[id]??[],isTurn=ctx.state.currentPlayerId===id;let hasLegal=false;if(isTurn&&ctx.state.variantId==='chameleon')hasLegal=hand.some(c=>isChameleonLegal(c,ctx.state.variant.activeSuit!,ctx.state.variant.activeRank!));return{hand,canPass:isTurn&&ctx.state.variantId!=='chameleon'&&Boolean(ctx.state.lastPlay&&ctx.state.lastPlay.playerId!==id),canDraw:isTurn&&ctx.state.variantId==='chameleon'&&!hasLegal,needsChoice:isTurn&&ctx.state.variantId==='chameleon'}}
function sendPrivate(ctx:RoomContext<GameState>,id:string){const s=findSeat(ctx.state,id);if(s&&!s.bot&&s.connected)ctx.send(id,'poker:private-state',privateFor(ctx,id))}
function sendAllPrivate(ctx:RoomContext<GameState>){for(const s of occupied(ctx.state))sendPrivate(ctx,s.id)}

function scheduleBot(ctx:RoomContext<GameState>){ctx.clearTimer('poker:bot');const id=ctx.state.currentPlayerId,seat=id?findSeat(ctx.state,id):null;if(!seat||(!seat.bot&&seat.connected)||!['bidding','playing'].includes(ctx.state.phase))return;ctx.setTimer('poker:bot',650+Math.floor(ctx.random()*550),()=>runBot(ctx,seat.id))}
function runBot(ctx:RoomContext<GameState>,id:string){const seat=findSeat(ctx.state,id);if(!seat||ctx.state.currentPlayerId!==id)return;RUNTIMES[ctx.state.variantId].ai(ctx,seat)}

type RuntimeVariant={
  start:(ctx:RoomContext<GameState>)=>void;
  play:(ctx:RoomContext<GameState>,seat:SeatState,cards:Card[],choice:unknown)=>void;
  pass?:(ctx:RoomContext<GameState>,seat:SeatState)=>void;
  draw?:(ctx:RoomContext<GameState>,seat:SeatState)=>void;
  ai:(ctx:RoomContext<GameState>,seat:SeatState)=>void;
  project:(state:GameState)=>VariantPublicState;
};
const RUNTIMES:Record<VariantId,RuntimeVariant>={
  doudizhu:{start:startDoudizhu,play:(ctx,seat,cards)=>playDoudizhu(ctx,seat,cards),pass,project:state=>state.variant,ai(ctx,seat){if(ctx.state.phase==='bidding'){const bid=ctx.state.variant.bid!,hand=hands[seat.id]??[],strength=hand.filter(c=>c.rank>=15).length+hand.filter(c=>hand.filter(x=>x.rank===c.rank).length===4).length/4;let score=strength>=4?3:strength>=2?2:strength>=1?1:0;if(score<=bid.highestScore)score=0;bidDoudizhu(ctx,seat,score);return}const legal=enumerateDoudizhu(hands[seat.id]??[],ctx.state.lastPlay?.analysis??null);if(legal[0])playDoudizhu(ctx,seat,legal[0]);else pass(ctx,seat)}},
  gandengyan:{start:startGandengyan,play:(ctx,seat,cards)=>playGandengyan(ctx,seat,cards),pass,project:state=>state.variant,ai(ctx,seat){const legal=enumerateGandengyan(hands[seat.id]??[],ctx.state.lastPlay?.analysis??null);if(legal[0])playGandengyan(ctx,seat,legal[0]);else pass(ctx,seat)}},
  chameleon:{start:startChameleon,play:playChameleon,draw:drawChameleon,project:state=>state.variant,ai(ctx,seat){const move=chooseChameleon(hands[seat.id]??[],ctx.state.variant.activeSuit!,ctx.state.variant.activeRank!);if(move)playChameleon(ctx,seat,[move.card],move.choice);else drawChameleon(ctx,seat)}}
};
