import type { Element, EntityState, PlayerState, TerrainState, Vec2 } from '../game/contracts';
import { atlasSource, EndwellAssets, TILE_SPRITES, type AssetKey, type TileSprite } from './assets';
import { sprayParticles, visualElementLayers } from './spellVisualGeometry';
import { sampleMonsterDeathEffect, type MonsterDeathEffect } from '../runtime/monsterDeathEffect';
import { terrainBounds } from '../game/rules/terrainGeometry';
import { directionAngle, DIRECTIONAL_VFX_HEADINGS, ELEMENT_VFX_CELLS, spellVisual } from './spellVisualCatalog';

export const ELEMENT_COLORS: Record<Element, string> = { rock: '#b6926a', fire: '#ff6547', ice: '#7de9ff', life: '#75e88c', lightning: '#bd91ff', water: '#4aa5ff', shield: '#ffe06b' };

export type CombatImpact = { position: Vec2; color: string; createdAt: number; duration: number; seed: number; kind: 'hit' | 'death' };

export class EndwellVisuals {
  constructor(readonly assets: EndwellAssets) {}

  tile(c: CanvasRenderingContext2D, sprite: TileSprite, x: number, y: number, options: { flip?: boolean; alpha?: number; tint?: string } = {}) {
    const image = this.assets.image('atlas'); if (!image) return false;
    const source = atlasSource(image, sprite.cell), anchor = sprite.anchorY ?? 0;
    c.save(); c.globalAlpha *= options.alpha ?? 1; c.imageSmoothingEnabled = true; c.translate(x, y + anchor);
    if (options.flip) c.scale(-1, 1);
    if (options.tint) { c.shadowColor = options.tint; c.shadowBlur = 12; }
    c.drawImage(image, source.x, source.y, source.w, source.h, -sprite.drawWidth / 2, -sprite.drawHeight / 2, sprite.drawWidth, sprite.drawHeight);
    c.restore(); return true;
  }

  atlasCell(c: CanvasRenderingContext2D, key: AssetKey, cell: number, x: number, y: number, width: number, height: number, options: { alpha?: number; blend?: GlobalCompositeOperation; rotation?: number } = {}) { const minimapFrame = key === 'ui' && cell === 14; if (minimapFrame) { c.save(); c.strokeStyle = 'rgba(221,190,119,.82)'; c.lineWidth = 2; c.strokeRect(x + 8, y + 8, width - 16, height - 16); c.strokeStyle = 'rgba(126,88,165,.72)'; c.lineWidth = 1; c.strokeRect(x + 12, y + 12, width - 24, height - 24); c.restore(); return true; } const image = this.assets.image(key); if (!image) return false; const source = atlasSource(image, cell); c.save(); c.globalAlpha *= options.alpha ?? 1; c.globalCompositeOperation = options.blend ?? 'source-over'; c.imageSmoothingEnabled = true; c.translate(x + width / 2, y + height / 2); c.rotate(options.rotation ?? 0); c.drawImage(image, source.x, source.y, source.w, source.h, -width / 2, -height / 2, width, height); c.restore(); return true; }

  terrain(c: CanvasRenderingContext2D, terrain: TerrainState) {
    if (terrain.kind === 'safe-zone') this.aura(c, terrain.position, terrain.radius, '#65f3dc', .18);
    if (terrain.kind === 'obstacle' || terrain.kind === 'rune-wall') { this.stoneObstacle(c, terrain); return; }
    if (terrain.kind === 'falling-rock') { const active = Boolean(terrain.activatesAt && Date.now() >= terrain.activatesAt); this.aura(c, terrain.position, terrain.radius, '#ff7958', active ? .38 : .15); this.atlasCell(c, 'vfx', 14, terrain.position.x - terrain.radius, terrain.position.y - terrain.radius, terrain.radius * 2, terrain.radius * 2, { alpha: active ? .96 : .68, blend: 'screen' }); return; }
    this.tile(c, TILE_SPRITES.rune, terrain.position.x, terrain.position.y, { tint: terrain.kind === 'rune' ? '#c79cff' : '#65f3dc' });
  }

  player(c: CanvasRenderingContext2D, pos: Vec2, player: PlayerState, local: boolean, moving: boolean) {
    const now = performance.now(), bob = player.alive ? Math.sin(now / 180 + hash(player.id)) * (moving ? 3 : 1.5) : 9, casting = player.cast.phase === 'chanting' || player.cast.phase === 'active';
    c.save(); c.globalAlpha = player.alive ? 1 : .42; c.translate(pos.x, pos.y); c.scale(casting ? 1 + Math.sin(now / 70) * .06 : 1, casting ? 1 - Math.sin(now / 70) * .04 : 1); c.translate(-pos.x, -pos.y);
    c.fillStyle = player.alive ? local ? '#ffe69a55' : '#76b8ff44' : '#7774'; c.beginPath(); c.ellipse(pos.x, pos.y + 21, local ? 26 : 22, 9, 0, 0, Math.PI * 2); c.fill();
    this.tile(c, local ? TILE_SPRITES.player : TILE_SPRITES.ally, pos.x, pos.y + bob, { flip: player.aim.x < 0, tint: local ? '#ffe9a3' : '#78aaff' }); c.restore();
    if (player.shields.length) { const radius = 44 + Math.sin(now / 150) * 2; this.atlasCell(c, 'vfx', 6, pos.x - radius, pos.y - radius, radius * 2, radius * 2, { alpha: .72, blend: 'screen', rotation: now / 2400 }); this.atlasCell(c, 'vfx', 14, pos.x - radius * .84, pos.y - radius * .84, radius * 1.68, radius * 1.68, { alpha: .34, blend: 'screen', rotation: -now / 3200 }); c.save(); c.strokeStyle = '#fff2a8'; c.shadowColor = '#ffe06b'; c.shadowBlur = 12; c.lineWidth = 2; c.beginPath(); c.arc(pos.x, pos.y, radius * .8, 0, Math.PI * 2); c.stroke(); c.restore(); }
  }

  monster(c: CanvasRenderingContext2D, entity: EntityState, pos: Vec2) {
    const sprite = entity.boss ? TILE_SPRITES.boss : entity.monsterDefinitionId === 'ruins.shooter' ? TILE_SPRITES.shooter : entity.monsterDefinitionId === 'ruins.guardian' ? TILE_SPRITES.guardian : TILE_SPRITES.chaser;
    const now = performance.now(), pulse = entity.cast.phase === 'chanting' ? 1 + Math.sin(now / 70) * .08 : 1, bob = Math.sin(now / 210 + hash(entity.id)) * 2;
    if (entity.boss) { this.aura(c, pos, entity.radius + 22 + Math.sin(now / 180) * 5, '#e04f78', .2); for (let i = 0; i < 5; i++) { const a = now / 900 + i * Math.PI * .4; this.softParticle(c, 'blackSmoke', { x: pos.x + Math.cos(a) * 66, y: pos.y + Math.sin(a) * 38 }, 42, now + i * 80, .28); } }
    c.save(); c.translate(pos.x, pos.y); c.scale(pulse, pulse); c.translate(-pos.x, -pos.y); this.tile(c, sprite, pos.x, pos.y + bob, { flip: (entity.direction?.x ?? -1) > 0, tint: entity.elite ? '#bd82ff' : entity.boss ? '#ff557e' : undefined }); c.restore();
  }

  effect(c: CanvasRenderingContext2D, entity: EntityState, pos: Vec2, beamSegments: Array<{ from: Vec2; to: Vec2 }> = []) {
    const spell = entity.source?.spell, layers = visualElementLayers(spell?.elements ?? ['rock']), element = layers.primary, color = ELEMENT_COLORS[element], age = Date.now() - entity.createdAt, projectileCell = ELEMENT_VFX_CELLS, fieldCell: Record<Element, number> = { rock: 14, fire: 8, ice: 9, life: 12, lightning: 10, water: 11, shield: 6 };
    if (entity.source?.spell.delivery === 'beam') { c.save(); c.globalCompositeOperation = 'screen'; c.shadowBlur = 22; c.shadowColor = color; for (const segment of beamSegments) { const width = entity.source.spell.beam?.width ?? 10, dx = segment.to.x - segment.from.x, dy = segment.to.y - segment.from.y, length = Math.hypot(dx, dy), angle = Math.atan2(dy, dx); c.strokeStyle = colorWithAlpha(color, .18); c.lineWidth = Math.max(28, width * 4.2); line(c, segment.from, segment.to); c.strokeStyle = colorWithAlpha(color, .76); c.lineWidth = Math.max(10, width * 1.15); line(c, segment.from, segment.to); for (const [index, accent] of layers.accents.entries()) { c.strokeStyle = colorWithAlpha(ELEMENT_COLORS[accent], .58); c.lineWidth = Math.max(2, width * .18); c.setLineDash([12 + index * 5, 18]); c.lineDashOffset = -age / (18 + index * 4); line(c, segment.from, segment.to); } c.setLineDash([]); c.strokeStyle = '#ffffff'; c.lineWidth = Math.max(2, width * .22); line(c, segment.from, segment.to); if (element === 'lightning' || layers.accents.includes('lightning')) this.lightning(c, segment.from, segment.to, ELEMENT_COLORS.lightning, entity.id); const steps = Math.max(2, Math.floor(length / 62)); for (let i = 0; i <= steps; i++) { const t = (i / steps + age / 720) % 1, particleElement = i % (layers.accents.length + 1) ? layers.accents[(i - 1) % layers.accents.length]! : element, size = 26 + Math.sin(t * Math.PI) * 18, x = segment.from.x + dx * t, y = segment.from.y + dy * t; this.atlasCell(c, 'vfx', projectileCell[particleElement], x - size / 2, y - size / 2, size, size, { alpha: .62, blend: 'screen', rotation: angle + age / 1100 }); } const burst = 68 + Math.sin(age / 75) * 8; this.atlasCell(c, 'vfx', element === 'shield' ? 6 : 7, segment.to.x - burst / 2, segment.to.y - burst / 2, burst, burst, { alpha: .72, blend: 'screen', rotation: age / 500 }); } c.restore(); return; }
    if (entity.source?.spell.delivery === 'spray') { const d = entity.direction ?? { x: 1, y: 0 }, range = entity.source.spell.range, particles = sprayParticles(entity.position, d, range, entity.source.spell.coneAngle ?? Math.PI / 2, age); c.save(); c.globalCompositeOperation = 'screen'; const gradient = c.createLinearGradient(entity.position.x, entity.position.y, entity.position.x + d.x * range, entity.position.y + d.y * range); gradient.addColorStop(0, colorWithAlpha(color, .72)); gradient.addColorStop(.65, colorWithAlpha(color, .22)); gradient.addColorStop(1, colorWithAlpha(color, 0)); c.strokeStyle = gradient; c.lineCap = 'round'; c.lineWidth = 18; c.beginPath(); c.moveTo(entity.position.x, entity.position.y); c.lineTo(entity.position.x + d.x * range * .82, entity.position.y + d.y * range * .82); c.stroke(); particles.forEach((particle, index) => { const particleElement = index % 3 === 2 && layers.accents.length ? layers.accents[index % layers.accents.length]! : element, size = particle.size * (particleElement === 'rock' ? .72 : 1); this.atlasCell(c, 'vfx', projectileCell[particleElement], particle.x - size / 2, particle.y - size / 2, size, size, { alpha: particle.alpha * .88, blend: 'screen', rotation: particle.angle }); }); c.restore(); return; }
    if (entity.kind === 'wall') { const ice = entity.archetype === 'ice-wall', cell = ice ? 9 : 0; for (let y = pos.y - 70; y <= pos.y + 70; y += 42) this.atlasCell(c, 'vfx', cell, pos.x - 38, y - 38, 76, 76, { alpha: .92, blend: 'screen', rotation: ice ? 0 : Math.PI / 4 }); return; }
    if (entity.kind === 'warning' && entity.archetype === 'meteor-warning') { this.meteorWarning(c, entity, pos, age); return; }
    if (entity.kind === 'warning') { const size = entity.radius * 2.3 * (.9 + Math.sin(age / 80) * .04); this.atlasCell(c, 'vfx', 14, pos.x - size / 2, pos.y - size / 2, size, size, { alpha: .62, blend: 'screen', rotation: age / 700 }); return; }
    if (entity.kind === 'area' && entity.archetype === 'meteor-impact') { this.meteorImpact(c, entity, pos, age); return; }
    if ((entity.kind === 'area' || entity.kind === 'field') && entity.archetype === 'black-hole') { this.blackHole(c, entity, pos, age); return; }
    if (entity.kind === 'area' || entity.kind === 'field') { const size = entity.radius * 2.25, cell = entity.archetype === 'gravity-well' ? 13 : fieldCell[element]; this.atlasCell(c, 'vfx', cell, pos.x - size / 2, pos.y - size / 2, size, size, { alpha: .82, blend: 'screen', rotation: age / 1800 }); this.atlasCell(c, 'vfx', projectileCell[element], pos.x - size * .34, pos.y - size * .34, size * .68, size * .68, { alpha: .64, blend: 'screen', rotation: -age / 950 }); for (let i = 0; i < 8; i++) { const a = i * Math.PI / 4 + age / 900, r = entity.radius * .72, s = 26 + i % 3 * 7, particleElement = i % (layers.accents.length + 1) ? layers.accents[(i - 1) % layers.accents.length]! : element; this.atlasCell(c, 'vfx', projectileCell[particleElement], pos.x + Math.cos(a) * r - s / 2, pos.y + Math.sin(a) * r - s / 2, s, s, { alpha: .58, blend: 'screen', rotation: a }); } layers.accents.forEach((accent, index) => this.aura(c, pos, entity.radius * (.86 - index * .09), ELEMENT_COLORS[accent], .08)); this.aura(c, pos, entity.radius, color, .22); return; }
    if (entity.kind === 'projectile' && spell) { const direction = entity.velocity ?? entity.direction ?? { x: 1, y: 0 }, visual = spellVisual(spell), travelAngle = Math.atan2(direction.y, direction.x), rotation = directionAngle(direction, visual.intrinsicHeading), size = Math.max(38, entity.radius * 4.8) * (visual.scale ?? 1); this.atlasCell(c, 'vfx', visual.cell ?? projectileCell[element], pos.x - size / 2, pos.y - size / 2, size, size, { blend: 'screen', rotation }); layers.accents.forEach((accent, index) => { const s = size * (.55 - index * .09); this.atlasCell(c, 'vfx', projectileCell[accent], pos.x - s / 2 - Math.cos(travelAngle) * (index + 1) * 14, pos.y - s / 2 - Math.sin(travelAngle) * (index + 1) * 14, s, s, { alpha: .58, blend: 'screen', rotation: directionAngle(direction, spellVisual({ ...spell, elements: [accent], delivery: 'projectile' }).intrinsicHeading) }); }); this.atlasCell(c, 'vfx', 7, pos.x - size * .28, pos.y - size * .28, size * .56, size * .56, { alpha: .45, blend: 'screen', rotation: age / 250 }); }
  }

  softParticle(c: CanvasRenderingContext2D, key: 'explosion' | 'flash' | 'whitePuff' | 'blackSmoke', pos: Vec2, size: number, elapsed: number, alpha = .5) { const cell = key === 'explosion' ? 8 : key === 'flash' ? 7 : key === 'blackSmoke' ? 13 : 11, t = (elapsed % 700) / 700, rendered = size * (.72 + t * .42); this.atlasCell(c, 'vfx', cell, pos.x - rendered / 2, pos.y - rendered / 2, rendered, rendered, { alpha: alpha * (1 - t * .55), blend: 'screen', rotation: elapsed / 1300 }); }
  aura(c: CanvasRenderingContext2D, pos: Vec2, radius: number, color: string, alpha: number) { const gradient = c.createRadialGradient(pos.x, pos.y, radius * .1, pos.x, pos.y, radius); gradient.addColorStop(0, colorWithAlpha(color, alpha * 1.8)); gradient.addColorStop(1, colorWithAlpha(color, 0)); c.fillStyle = gradient; c.beginPath(); c.arc(pos.x, pos.y, radius, 0, Math.PI * 2); c.fill(); }
  combatImpact(c: CanvasRenderingContext2D, impact: CombatImpact, now: number) { const t = Math.max(0, Math.min(1, (now - impact.createdAt) / impact.duration)), ease = 1 - (1 - t) ** 3, size = (impact.kind === 'death' ? 148 : 76) * (.45 + ease * .65); this.atlasCell(c, 'vfx', impact.kind === 'death' ? 15 : 7, impact.position.x - size / 2, impact.position.y - size / 2, size, size, { alpha: 1 - t, blend: 'screen', rotation: impact.seed * .013 + t * .3 }); }
  monsterDeath(c: CanvasRenderingContext2D, effect: MonsterDeathEffect, now: number) {
    const image = this.assets.image('atlas'); if (!image) return;
    const sprite = TILE_SPRITES[effect.visual], source = atlasSource(image, sprite.cell), anchor = sprite.anchorY ?? 0;
    const elementColor = effect.element in ELEMENT_COLORS ? ELEMENT_COLORS[effect.element as Element] : effect.element === 'pure' ? '#ffffff' : '#e3b181';
    for (const [fragmentIndex, fragment] of sampleMonsterDeathEffect(effect, now).entries()) {
      c.save(); c.globalAlpha = fragment.alpha; c.translate(fragment.position.x, fragment.position.y); c.rotate(fragment.rotation);
      c.beginPath(); fragment.vertices.forEach((radius, index) => { const angle = index / fragment.vertices.length * Math.PI * 2, length = fragment.size * radius, x = Math.cos(angle) * length, y = Math.sin(angle) * length; if (!index) c.moveTo(x, y); else c.lineTo(x, y); }); c.closePath(); c.clip();
      if (effect.flip) c.scale(-1, 1);
      const textureX = effect.flip ? -fragment.textureOffset.x : fragment.textureOffset.x;
      c.drawImage(image, source.x, source.y, source.w, source.h, -sprite.drawWidth / 2 - textureX, -sprite.drawHeight / 2 + anchor - fragment.textureOffset.y, sprite.drawWidth, sprite.drawHeight);
      c.restore();
      if (fragmentIndex % 3 === 0) { c.save(); c.globalAlpha = fragment.alpha * .65; c.fillStyle = elementColor; c.shadowColor = elementColor; c.shadowBlur = 6; c.translate(fragment.position.x - fragment.size * .25, fragment.position.y + fragment.size * .18); c.rotate(fragment.rotation); c.fillRect(-1.5, -1.5, 3, 3); c.restore(); }
    }
  }
  elementSigil(c: CanvasRenderingContext2D, element: Element, x: number, y: number, radius: number, selectedCount = 0) { const cells: Record<Element, number> = { rock: 0, fire: 1, ice: 2, life: 7, lightning: 4, water: 5, shield: 6 }, pulse = selectedCount ? 1 + Math.sin(performance.now() / 90) * .07 : 1, size = radius * 2.22 * pulse; c.save(); if (selectedCount) { c.shadowColor = ELEMENT_COLORS[element]; c.shadowBlur = 22; } this.atlasCell(c, 'ui', cells[element], x - size / 2, y - size / 2, size, size); if (element === 'life') this.atlasCell(c, 'vfx', 3, x - radius * .72, y - radius * .72, radius * 1.44, radius * 1.44, { blend: 'screen' }); c.restore(); }

  uiFrame(c: CanvasRenderingContext2D, rect: { x: number; y: number; w: number; h: number }, cell = 8, alpha = 1) {
    c.save();
    c.fillStyle = 'rgba(2,2,8,.72)';
    c.fillRect(rect.x + 5, rect.y + 7, rect.w, rect.h);
    c.beginPath(); c.rect(rect.x, rect.y, rect.w, rect.h); c.clip();
    this.atlasCell(c, 'ui', cell, rect.x, rect.y, rect.w, rect.h, { alpha: alpha * .24 });
    const shade = c.createLinearGradient(rect.x, rect.y, rect.x, rect.y + rect.h);
    shade.addColorStop(0, 'rgba(27,21,38,.58)'); shade.addColorStop(.55, 'rgba(7,7,15,.74)'); shade.addColorStop(1, 'rgba(14,9,20,.82)');
    c.fillStyle = shade; c.fillRect(rect.x, rect.y, rect.w, rect.h); c.restore();
    c.save(); c.strokeStyle = 'rgba(214,187,123,.68)'; c.lineWidth = 2; c.strokeRect(rect.x + 1, rect.y + 1, rect.w - 2, rect.h - 2);
    c.strokeStyle = 'rgba(128,92,166,.46)'; c.lineWidth = 1; c.strokeRect(rect.x + 5.5, rect.y + 5.5, rect.w - 11, rect.h - 11); c.restore();
  }
  private meteorWarning(c: CanvasRenderingContext2D, entity: EntityState, pos: Vec2, age: number) {
    const duration = Math.max(1, (entity.expiresAt ?? entity.createdAt + 700) - entity.createdAt), progress = Math.min(1, age / duration), eased = progress * progress, start = { x: pos.x - entity.radius * 1.65, y: pos.y - entity.radius * 2.55 }, meteor = { x: start.x + (pos.x - start.x) * eased, y: start.y + (pos.y - start.y) * eased }, direction = { x: pos.x - start.x, y: pos.y - start.y }, angle = Math.atan2(direction.y, direction.x), rotation = directionAngle(direction, DIRECTIONAL_VFX_HEADINGS.fire), size = 104 + progress * 42;
    c.save(); c.globalCompositeOperation = 'screen'; const trail = c.createLinearGradient(start.x, start.y, meteor.x, meteor.y); trail.addColorStop(0, 'rgba(255,90,35,0)'); trail.addColorStop(1, 'rgba(255,174,70,.78)'); c.strokeStyle = trail; c.lineWidth = 24 + progress * 15; c.lineCap = 'round'; line(c, start, meteor); this.atlasCell(c, 'vfx', 1, meteor.x - size / 2, meteor.y - size / 2, size, size, { alpha: .95, blend: 'screen', rotation }); for (let i = 0; i < 5; i++) { const t = ((age / 320 + i / 5) % 1), s = 26 + (1 - t) * 24, x = meteor.x - Math.cos(angle) * t * 120, y = meteor.y - Math.sin(angle) * t * 120; this.atlasCell(c, 'vfx', i % 2 ? 8 : 1, x - s / 2, y - s / 2, s, s, { alpha: (1 - t) * .7, blend: 'screen', rotation }); } c.restore();
    c.save(); c.strokeStyle = `rgba(255,128,67,${.38 + progress * .55})`; c.lineWidth = 4; c.setLineDash([14, 8]); c.lineDashOffset = -age / 22; c.beginPath(); c.arc(pos.x, pos.y, entity.radius * (1.02 - progress * .12), 0, Math.PI * 2); c.stroke(); c.setLineDash([]); c.fillStyle = `rgba(255,70,36,${progress * .16})`; c.beginPath(); c.arc(pos.x, pos.y, entity.radius * .82, 0, Math.PI * 2); c.fill(); c.restore();
  }
  private meteorImpact(c: CanvasRenderingContext2D, entity: EntityState, pos: Vec2, age: number) {
    const progress = Math.min(1, age / Math.max(1, (entity.expiresAt ?? entity.createdAt + 500) - entity.createdAt)), burst = entity.radius * (1.05 + progress * 1.15);
    c.save(); c.globalCompositeOperation = 'screen'; this.atlasCell(c, 'vfx', 8, pos.x - burst, pos.y - burst, burst * 2, burst * 2, { alpha: 1 - progress * .72, blend: 'screen' }); this.atlasCell(c, 'vfx', 7, pos.x - burst * .55, pos.y - burst * .55, burst * 1.1, burst * 1.1, { alpha: 1 - progress, blend: 'screen' }); for (let i = 0; i < 11; i++) { const a = i / 11 * Math.PI * 2 + hash(entity.id + i) % 20 / 20, distance = entity.radius * progress * (1.1 + i % 3 * .2), s = 24 + i % 4 * 8; this.atlasCell(c, 'vfx', i % 3 === 0 ? 0 : 1, pos.x + Math.cos(a) * distance - s / 2, pos.y + Math.sin(a) * distance * .62 - s / 2, s, s, { alpha: 1 - progress, blend: 'screen', rotation: a }); } c.restore();
  }
  private blackHole(c: CanvasRenderingContext2D, entity: EntityState, pos: Vec2, age: number) {
    const pulse = 1 + Math.sin(age / 180) * .035, radius = entity.radius * pulse, core = radius * .2;
    c.save(); const gravity = c.createRadialGradient(pos.x, pos.y, core * .2, pos.x, pos.y, radius); gravity.addColorStop(0, '#000'); gravity.addColorStop(.16, '#010107'); gravity.addColorStop(.28, 'rgba(91,42,138,.95)'); gravity.addColorStop(.42, 'rgba(183,91,255,.35)'); gravity.addColorStop(1, 'rgba(25,8,44,0)'); c.fillStyle = gravity; c.beginPath(); c.arc(pos.x, pos.y, radius, 0, Math.PI * 2); c.fill();
    c.globalCompositeOperation = 'screen'; c.lineCap = 'round'; for (let ring = 0; ring < 4; ring++) { c.strokeStyle = ring % 2 ? 'rgba(104,185,255,.42)' : 'rgba(202,113,255,.58)'; c.lineWidth = 7 - ring; c.beginPath(); c.ellipse(pos.x, pos.y, radius * (.28 + ring * .105), radius * (.09 + ring * .035), age / (1500 + ring * 240) + ring * .7, ring * .5, Math.PI * (1.05 + ring * .12)); c.stroke(); }
    for (let i = 0; i < 18; i++) { const phase = (age / (1200 + i % 4 * 170) + i / 18) % 1, r = radius * (.88 - phase * .68), a = i * 2.399 + age / (900 + i * 19), s = 9 + (i % 4) * 4; c.fillStyle = i % 3 ? 'rgba(194,116,255,.72)' : 'rgba(101,206,255,.8)'; c.beginPath(); c.arc(pos.x + Math.cos(a) * r, pos.y + Math.sin(a) * r * .46, s * (1 - phase * .45), 0, Math.PI * 2); c.fill(); }
    c.globalCompositeOperation = 'source-over'; c.fillStyle = '#000'; c.shadowColor = '#b65cff'; c.shadowBlur = 24; c.beginPath(); c.arc(pos.x, pos.y, core, 0, Math.PI * 2); c.fill(); c.strokeStyle = 'rgba(238,190,255,.82)'; c.lineWidth = 2; c.stroke(); c.restore();
  }
  private stoneObstacle(c: CanvasRenderingContext2D, terrain: TerrainState) { const bounds = terrainBounds(terrain); if (bounds.shape === 'circle') this.tile(c, { ...TILE_SPRITES.obstacle, drawWidth: bounds.radius * 2, drawHeight: bounds.radius * 2 }, terrain.position.x, terrain.position.y); else { const segment = Math.max(34, bounds.width * 1.45), count = Math.max(1, Math.ceil(bounds.height / segment)), step = bounds.height / count; for (let index = 0; index < count; index++) this.tile(c, { ...TILE_SPRITES.obstacle, drawWidth: bounds.width, drawHeight: step }, terrain.position.x, terrain.position.y - bounds.height / 2 + step * (index + .5), { tint: '#b287ff' }); this.aura(c, terrain.position, Math.max(bounds.width, bounds.height) / 2, '#b287ff', .12); } }
  private lightning(c: CanvasRenderingContext2D, from: Vec2, to: Vec2, color: string, seed: string) { c.strokeStyle = color; c.lineWidth = 3; c.beginPath(); c.moveTo(from.x, from.y); for (let i = 1; i < 7; i++) { const t = i / 7, wobble = ((hash(`${seed}:${i}:${Math.floor(performance.now() / 80)}`) % 21) - 10); c.lineTo(from.x + (to.x - from.x) * t + wobble, from.y + (to.y - from.y) * t - wobble); } c.lineTo(to.x, to.y); c.stroke(); }
}

function line(c: CanvasRenderingContext2D, from: Vec2, to: Vec2) { c.beginPath(); c.moveTo(from.x, from.y); c.lineTo(to.x, to.y); c.stroke(); }
function hash(value: string | number) { let h = 2166136261; for (const ch of String(value)) { h ^= ch.charCodeAt(0); h = Math.imul(h, 16777619); } return h >>> 0; }
function hexAlpha(value: number) { return Math.round(Math.max(0, Math.min(1, value)) * 255).toString(16).padStart(2, '0'); }
export function colorWithAlpha(color: string, alpha: number) { const match = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(color); if (!match) return color; const hex = match[1]!, normalized = hex.length === 3 ? [...hex].map((part) => part + part).join('') : hex; return `#${normalized}${hexAlpha(alpha)}`; }
