import { defineRoom,type RoomContext } from '@parti/worker-sdk';
import { ELEMENTS,SCHEMA_VERSION,WORLD_HEIGHT,WORLD_WIDTH,type ControlState,type Element,type EnemyState,type EnvironmentState,type GameState,type HostProjectile,type PublicPlayer,type RegionEncounter,type StageProgress,type StatusInstance } from '../game/contracts';
import { ZERO_CONTROL } from '../game/combat';
import { generateMap } from '../game/map';

export default defineRoom<GameState>({
 meta:{name:'元素训练场',minPlayers:1,maxPlayers:4},initialState,
 onRestore(ctx){if(ctx.state.schemaVersion!==SCHEMA_VERSION)replace(ctx.state,initialState());ctx.state.hostId=ctx.host.id;},
 onJoin(ctx,player){ctx.state.hostId=ctx.host.id;if(ctx.state.phase!=='lobby'&&!ctx.state.players[player.id]){ctx.kick(player.id,'训练已经开始');return;}const old=ctx.state.players[player.id];if(old){old.connected=true;old.name=player.name;}else ctx.state.players[player.id]=makePlayer(player.id,player.name,ctx.state.runSeed);},
 onReconnect(ctx,player){ctx.state.hostId=ctx.host.id;const p=ctx.state.players[player.id];if(p){p.connected=true;p.name=player.name;}},
 onLeave(ctx,player){const p=ctx.state.players[player.id];if(ctx.state.phase==='lobby')delete ctx.state.players[player.id];else if(p)p.connected=false;ctx.state.hostId=ctx.host.id;checkGameOver(ctx);},
 actions:{
  setReady(ctx,{player,payload}){if(ctx.state.phase!=='lobby')return;const p=ctx.state.players[player.id];if(!p)return;p.ready=Boolean(payload?.ready);const all=Object.values(ctx.state.players);if(all.length&&all.every(v=>v.ready&&v.connected))start(ctx);},
  restart(ctx,{player}){if(player.id!==ctx.host.id||ctx.state.phase!=='gameover')return;resetLobby(ctx.state);},
  advanceStage(ctx,{player}){if(ctx.state.phase!=='running'||player.id!==ctx.host.id||!ctx.state.stage?.portal?.active)return;const portal=ctx.state.stage.portal,connected=Object.values(ctx.state.players).filter(p=>p.connected);if(!connected.length||connected.some(p=>Math.hypot(p.x-portal.x,p.y-portal.y)>80))return;ctx.state.stageIndex+=1;ctx.state.runSeed=randomSeed(ctx.now()+ctx.state.stageIndex*7919);const spawn=generateMap(ctx.state.runSeed).spawn;ctx.state.stage=null;ctx.state.exploredRoomIds=[];ctx.state.enemies={};ctx.state.projectiles={};ctx.state.environments={};ctx.state.encounters={};ctx.state.worldSequence=0;for(const p of Object.values(ctx.state.players))Object.assign(p,{x:spawn.x,y:spawn.y,z:0,hp:Math.max(25,p.hp),downed:false,elements:[],statuses:[],controls:{...ZERO_CONTROL}});ctx.state.message=`进入遗迹第 ${ctx.state.stageIndex+1} 层`;ctx.broadcast('magicka:stage-advanced',{stageIndex:ctx.state.stageIndex});},
  exploreRoom(ctx,{player,payload}){if(ctx.state.phase!=='running'||!ctx.state.players[player.id])return;const roomId=text(payload?.roomId,40);if(!/^room-\d+$/.test(roomId)||ctx.state.exploredRoomIds.includes(roomId))return;const map=generateMap(ctx.state.runSeed);if(map.rooms.some(room=>room.id===roomId))ctx.state.exploredRoomIds.push(roomId);},
  publishPlayer(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id];if(!p)return;const sequence=Number(payload?.sequence);if(!Number.isInteger(sequence)||sequence<=p.sequence)return;p.sequence=sequence;p.x=clamp(Number(payload?.x),0,WORLD_WIDTH);p.y=clamp(Number(payload?.y),130,WORLD_HEIGHT-80);p.z=Math.max(0,Number(payload?.z)||0);p.hp=clamp(Number(payload?.hp),0,100);p.downed=Boolean(payload?.downed)||p.hp<=0;p.elements=elements(payload?.elements);p.statuses=statuses(payload?.statuses);p.controls=controlState(payload?.controls);p.kills=Math.max(0,Math.floor(Number(payload?.kills)||0));ctx.broadcast('magicka:player',{...p});checkGameOver(ctx);},
  syncWorld(ctx,{player,payload}){if(ctx.state.phase!=='running'||player.id!==ctx.host.id)return;const sequence=Number(payload?.sequence);if(!Number.isInteger(sequence)||sequence<=ctx.state.worldSequence)return;const stage=stageProgress(payload?.stage);if(!stage)return;ctx.state.worldSequence=sequence;ctx.state.enemies=Object.fromEntries(enemyList(payload?.enemies).map(e=>[e.id,e]));ctx.state.projectiles=Object.fromEntries(projectileList(payload?.projectiles).map(e=>[e.id,e]));ctx.state.environments=Object.fromEntries(environmentList(payload?.environments).map(e=>[e.id,e]));ctx.state.encounters=Object.fromEntries(encounterList(payload?.encounters).map(e=>[e.roomId,e]));ctx.state.stage=stage;},
  reportEnemyDamage(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const eventId=text(payload?.eventId,100),enemyId=text(payload?.enemyId,100),spellId=text(payload?.spellId,100),amount=Number(payload?.amount);if(!eventId||!enemyId||!Number.isFinite(amount)||amount<=0)return;ctx.broadcast('magicka:enemy-damage',{eventId,worldSequence:Number(payload?.worldSequence)||0,enemyId,sourcePlayerId:player.id,spellId,amount,statuses:statuses(payload?.statuses),controls:Array.isArray(payload?.controls)?payload.controls:[],direction:payload?.direction});},
  reportPlayerEffect(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const eventId=text(payload?.eventId,100),targetPlayerId=text(payload?.targetPlayerId,100);if(!eventId||!targetPlayerId||!ctx.state.players[targetPlayerId])return;ctx.broadcast('magicka:player-effect',{eventId,sourcePlayerId:player.id,targetPlayerId,effects:Array.isArray(payload?.effects)?payload.effects:[]});},
  reportEnvironment(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const environment=environmentList([payload])[0];if(environment)ctx.broadcast('magicka:environment',{...environment,sourcePlayerId:player.id});},
  reportProjectileHit(ctx,{payload}){if(ctx.state.phase!=='running')return;const projectileId=text(payload?.projectileId,100);if(projectileId)ctx.broadcast('magicka:projectile-hit',{projectileId});}
 }
});
function initialState():GameState{const runSeed=randomSeed();return{schemaVersion:SCHEMA_VERSION,phase:'lobby',hostId:null,startedAt:null,runSeed,stageIndex:0,stage:null,exploredRoomIds:[],players:{},enemies:{},projectiles:{},environments:{},encounters:{},worldSequence:0,totalKills:0,message:'所有玩家准备后开始'}}
function makePlayer(id:string,name:string,runSeed=1):PublicPlayer{const spawn=generateMap(runSeed).spawn;return{id,name,ready:false,connected:true,x:spawn.x,y:spawn.y,z:0,hp:100,downed:false,sequence:0,elements:[],statuses:[],controls:{...ZERO_CONTROL},kills:0}}
function start(ctx:RoomContext<GameState>){ctx.state.runSeed=randomSeed(ctx.now());const spawn=generateMap(ctx.state.runSeed).spawn;ctx.state.phase='running';ctx.state.startedAt=ctx.now();ctx.state.hostId=ctx.host.id;ctx.state.stageIndex=0;ctx.state.stage=null;ctx.state.exploredRoomIds=[];ctx.state.enemies={};ctx.state.projectiles={};ctx.state.environments={};ctx.state.encounters={};ctx.state.worldSequence=0;ctx.state.totalKills=0;ctx.state.message='遗迹探索开始';for(const [id,p]of Object.entries(ctx.state.players))Object.assign(p,makePlayer(id,p.name,ctx.state.runSeed),{ready:true,x:spawn.x,y:spawn.y});ctx.broadcast('magicka:start',{});}
function resetLobby(s:GameState){s.runSeed=randomSeed();for(const[id,p]of Object.entries(s.players)){if(!p.connected)delete s.players[id];else Object.assign(p,makePlayer(id,p.name,s.runSeed));}Object.assign(s,{phase:'lobby',startedAt:null,stageIndex:0,stage:null,exploredRoomIds:[],enemies:{},projectiles:{},environments:{},encounters:{},worldSequence:0,totalKills:0,message:'所有玩家准备后开始'});}
function checkGameOver(ctx:RoomContext<GameState>){if(ctx.state.phase!=='running')return;const active=Object.values(ctx.state.players).filter(p=>p.connected);if(active.length&&active.every(p=>p.downed)){ctx.state.phase='gameover';ctx.state.message='全员倒地';ctx.broadcast('magicka:gameover',{});}}
function elements(v:unknown):Element[]{return Array.isArray(v)?v.filter((x):x is Element=>ELEMENTS.includes(x as Element)).slice(0,4):[]}
function statuses(v:unknown):StatusInstance[]{return Array.isArray(v)?v.filter(x=>x&&typeof x==='object'&&typeof x.kind==='string').slice(0,16) as StatusInstance[]:[]}
function enemyList(v:unknown):EnemyState[]{return Array.isArray(v)?v.filter(x=>x&&typeof x.id==='string').slice(0,80) as EnemyState[]:[]}
function projectileList(v:unknown):HostProjectile[]{return Array.isArray(v)?v.filter(x=>x&&typeof x.id==='string').slice(0,120) as HostProjectile[]:[]}
function environmentList(v:unknown):EnvironmentState[]{return Array.isArray(v)?v.filter(x=>x&&typeof x.id==='string').slice(0,32) as EnvironmentState[]:[]}
function encounterList(v:unknown):RegionEncounter[]{return Array.isArray(v)?v.filter(x=>x&&typeof x.roomId==='string'&&(x.kind==='roaming'||x.kind==='sealed')&&(x.status==='dormant'||x.status==='active'||x.status==='cleared')).slice(0,40) as RegionEncounter[]:[]}
function stageProgress(v:unknown):StageProgress|null{const s=v as StageProgress|null;if(!s||!Number.isInteger(s.index)||!Array.isArray(s.objectives)||!s.boss)return null;return s;}
function controlState(v:unknown):ControlState{const c=v as Partial<ControlState>|null;return c&&typeof c==='object'?{vx:Number(c.vx)||0,vy:Number(c.vy)||0,z:Math.max(0,Number(c.z)||0),vz:Number(c.vz)||0,slowedUntil:Number(c.slowedUntil)||0,slowScale:clamp(Number(c.slowScale),.1,1),stunnedUntil:Number(c.stunnedUntil)||0}:{...ZERO_CONTROL}}
function clamp(v:number,min:number,max:number){return Number.isFinite(v)?Math.max(min,Math.min(max,v)):min}function text(v:unknown,n:number){return typeof v==='string'?v.slice(0,n):''}
function replace(target:GameState,next:GameState){for(const k of Object.keys(target)as Array<keyof GameState>)delete target[k];Object.assign(target,next);}
function randomSeed(value=Date.now()){return(Math.imul(value|0,1664525)+1013904223)>>>0;}
