import { defineRoom,type RoomContext } from '@parti/worker-sdk';
import { ELEMENTS,SCHEMA_VERSION,WORLD_HEIGHT,WORLD_WIDTH,type ActiveCast,type ControlState,type Element,type EnemyState,type EnvironmentState,type GameState,type HazardState,type HostProjectile,type LootEntity,type MerchantState,type PlayerActivity,type PublicPlayer,type RegionEncounter,type StageProgress,type StatusInstance,type WorldEventState } from '../game/contracts';
import { ZERO_CONTROL } from '../game/combat';
import { biomeForStage,deriveStageSeed,generateMap,roomAt } from '../game/map';
import { isRecipeId,resolvePlayerSpell } from '../game/spells';
import { applyEquipmentToSpell,fuseEquipment,isCatalyst,isEquipment,sellPrice } from '../game/equipment';

export default defineRoom<GameState>({
 meta:{name:'元素训练场',minPlayers:1,maxPlayers:4},initialState,
 onRestore(ctx){if(ctx.state.schemaVersion!==SCHEMA_VERSION)replace(ctx.state,initialState());ctx.state.hostId=ctx.host.id;},
 onJoin(ctx,player){ctx.state.hostId=ctx.host.id;if(ctx.state.phase!=='lobby'&&!ctx.state.players[player.id]){ctx.kick(player.id,'训练已经开始');return;}const old=ctx.state.players[player.id];if(old){old.connected=true;old.name=player.name;}else ctx.state.players[player.id]=makePlayer(player.id,player.name,ctx.state.runSeed);},
 onReconnect(ctx,player){ctx.state.hostId=ctx.host.id;const p=ctx.state.players[player.id];if(p){p.connected=true;p.name=player.name;}},
 onLeave(ctx,player){const p=ctx.state.players[player.id];if(ctx.state.phase==='lobby')delete ctx.state.players[player.id];else if(p)p.connected=false;ctx.state.hostId=ctx.host.id;checkGameOver(ctx);},
 actions:{
  setReady(ctx,{player,payload}){if(ctx.state.phase!=='lobby')return;const p=ctx.state.players[player.id];if(!p)return;p.ready=Boolean(payload?.ready);const all=Object.values(ctx.state.players);if(all.length&&all.every(v=>v.ready&&v.connected))start(ctx);},
  restart(ctx,{player}){if(player.id!==ctx.host.id||ctx.state.phase!=='gameover')return;resetLobby(ctx.state);},
  advanceStage(ctx,{player,payload}){if(ctx.state.phase!=='running'||player.id!==ctx.host.id||ctx.state.stageIndex>=2||!ctx.state.stage?.portal?.active)return;const eventId=text(payload?.eventId,120);if(!eventId||ctx.state.authorityEventIds.includes(eventId))return;const portal=ctx.state.stage.portal,connected=Object.values(ctx.state.players).filter(p=>p.connected);if(!connected.length||connected.some(p=>Math.hypot(p.x-portal.x,p.y-portal.y)>80))return;rememberAuthority(ctx.state,eventId);ctx.state.stageIndex+=1;ctx.state.biome=biomeForStage(ctx.state.stageIndex);ctx.state.stageSeed=deriveStageSeed(ctx.state.runSeed,ctx.state.stageIndex);const spawn=generateMap(ctx.state.runSeed,ctx.state.stageIndex).spawn;ctx.state.stage=null;ctx.state.activeCasts={};ctx.state.exploredRoomIds=[];ctx.state.enemies={};ctx.state.projectiles={};ctx.state.environments={};ctx.state.hazards={};ctx.state.events={};ctx.state.encounters={};ctx.state.loot={};ctx.state.merchants={};ctx.state.worldSequence=0;for(const p of Object.values(ctx.state.players))Object.assign(p,{x:spawn.x,y:spawn.y,z:0,hp:Math.max(25,p.hp),downed:false,elements:[],activity:{phase:'idle',elements:[],spellId:null,castId:null,phaseStartedAt:ctx.now(),phaseEndsAt:null},statuses:[],controls:{...ZERO_CONTROL}});ctx.state.message=`进入${ctx.state.biome==='swamp'?'腐化沼泽':'熔火火山'}`;ctx.broadcast('magicka:stage-advanced',{stageIndex:ctx.state.stageIndex,biome:ctx.state.biome});},
  completeRun(ctx,{player,payload}){if(ctx.state.phase!=='running'||player.id!==ctx.host.id||ctx.state.stageIndex!==2||ctx.state.stage?.boss.status!=='defeated')return;const eventId=text(payload?.eventId,120);if(!eventId||ctx.state.authorityEventIds.includes(eventId))return;rememberAuthority(ctx.state,eventId);const players=Object.values(ctx.state.players);ctx.state.phase='victory';ctx.state.victorySummary={durationMs:Math.max(0,ctx.now()-(ctx.state.startedAt??ctx.now())),totalKills:players.reduce((n,p)=>n+p.kills,0),totalGold:players.reduce((n,p)=>n+p.gold,0),playerBuilds:players.map(p=>({playerId:p.id,name:p.name,equipment:p.equipment}))};ctx.state.message='三重生态已净化';ctx.broadcast('magicka:victory',ctx.state.victorySummary);},
  equipItem(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id],itemId=text(payload?.itemId,100);if(!p||inCombat(ctx.state,p))return;const index=p.inventory.findIndex(item=>item.id===itemId);if(index<0)return;const item=p.inventory[index]!;if(!isEquipment(item))return;const old=p.equipment[item.slot];p.inventory.splice(index,1);if(old)p.inventory.push(old);p.equipment[item.slot]=item;},
  dropItem(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id],itemId=text(payload?.itemId,100);if(!p)return;let item=p.inventory.find(v=>v.id===itemId);if(item)p.inventory=p.inventory.filter(v=>v.id!==itemId);else for(const slot of ['staff','robe','ring'] as const)if(p.equipment[slot]?.id===itemId){item=p.equipment[slot]!;p.equipment[slot]=null;break;}if(!item)return;const room=roomAt(generateMap(ctx.state.runSeed,ctx.state.stageIndex),p);if(!room)return;const now=ctx.now(),loot:LootEntity={id:`drop:${player.id}:${item.id}:${now}`,x:p.x,y:p.y,roomId:room.id,item,wants:[],droppedByPlayerId:player.id,ownerPriorityUntil:now+1800};ctx.state.loot[loot.id]=loot;ctx.broadcast('magicka:loot-dropped',loot);},
  pickupLoot(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id],lootId=text(payload?.lootId,120),loot=ctx.state.loot[lootId];if(!p||!loot||p.inventory.length>=9||Math.hypot(p.x-loot.x,p.y-loot.y)>110||(loot.droppedByPlayerId&&loot.droppedByPlayerId!==player.id&&ctx.now()<loot.ownerPriorityUntil))return;delete ctx.state.loot[lootId];p.inventory.push(loot.item);ctx.broadcast('magicka:loot-picked',{lootId,playerId:player.id});},
  toggleLootWant(ctx,{player,payload}){const lootId=text(payload?.lootId,120),loot=ctx.state.loot[lootId];if(!loot)return;loot.wants=loot.wants.includes(player.id)?loot.wants.filter(id=>id!==player.id):[...loot.wants,player.id];ctx.broadcast('magicka:loot-wants',{lootId,wants:loot.wants});},
  buyItem(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id],merchantId=text(payload?.merchantId,100),itemId=text(payload?.itemId,100),merchant=ctx.state.merchants[merchantId];if(!p||!merchant||p.inventory.length>=9||Math.hypot(p.x-merchant.x,p.y-merchant.y)>130)return;const index=merchant.stock.findIndex(entry=>entry.item.id===itemId);if(index<0)return;const entry=merchant.stock[index]!;if(p.gold<entry.price)return;p.gold-=entry.price;p.inventory.push(entry.item);merchant.stock.splice(index,1);ctx.broadcast('magicka:merchant-sold',{merchantId,itemId});},
  sellItem(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id],merchantId=text(payload?.merchantId,100),itemId=text(payload?.itemId,100),merchant=ctx.state.merchants[merchantId];if(!p||!merchant||inCombat(ctx.state,p)||Math.hypot(p.x-merchant.x,p.y-merchant.y)>130)return;const index=p.inventory.findIndex(item=>item.id===itemId),item=p.inventory[index];if(index<0||!item||!isEquipment(item))return;const price=sellPrice(item);if(!price)return;p.inventory.splice(index,1);p.gold+=price;ctx.broadcast('magicka:item-sold',{merchantId,itemId,price});},
  fuseEquipment(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id],ids=Array.isArray(payload?.itemIds)?payload.itemIds.map((v:unknown)=>text(v,100)).filter(Boolean):[],forge=Object.values(ctx.state.events).find(event=>event.kind==='forge');if(!p||ids.length!==3||new Set(ids).size!==3||!forge||inCombat(ctx.state,p)||Math.hypot(p.x-forge.x,p.y-forge.y)>140)return;const selected=ids.map((id:string)=>p.inventory.find(item=>item.id===id)).filter(isEquipment);if(selected.length!==3)return;const useCatalyst=Boolean(payload?.useCatalyst),catalystIndex=useCatalyst?p.inventory.findIndex(isCatalyst):-1;if(useCatalyst&&catalystIndex<0)return;const seed=(ctx.state.stageSeed^hashText(`${player.id}:${ids.join(':')}:${ctx.state.worldSequence}`))>>>0,result=fuseEquipment(selected,seed,useCatalyst);if(!result)return;p.inventory=p.inventory.filter(item=>!ids.includes(item.id));if(useCatalyst){const index=p.inventory.findIndex(isCatalyst);if(index>=0)p.inventory.splice(index,1);}p.inventory.push(result);ctx.broadcast('magicka:equipment-fused',{playerId:player.id,item:result});},
  awardGold(ctx,{player,payload}){if(ctx.state.phase!=='running'||player.id!==ctx.host.id)return;const eventId=text(payload?.eventId,120);if(!eventId||ctx.state.rewardEventIds.includes(eventId))return;ctx.state.rewardEventIds.push(eventId);ctx.state.rewardEventIds=ctx.state.rewardEventIds.slice(-120);const amount=clamp(Math.floor(Number(payload?.amount)||0),0,100),ids=Array.isArray(payload?.playerIds)?payload.playerIds.map(String):[];for(const id of ids){const target=ctx.state.players[id];if(target)target.gold+=amount;}},
  exploreRoom(ctx,{player,payload}){if(ctx.state.phase!=='running'||!ctx.state.players[player.id])return;const roomId=text(payload?.roomId,40);if(!/^room-\d+$/.test(roomId)||ctx.state.exploredRoomIds.includes(roomId))return;const map=generateMap(ctx.state.runSeed,ctx.state.stageIndex);if(map.rooms.some(room=>room.id===roomId))ctx.state.exploredRoomIds.push(roomId);},
  publishPlayer(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id];if(!p)return;const sequence=Number(payload?.sequence);if(!Number.isInteger(sequence)||sequence<=p.sequence)return;p.sequence=sequence;p.x=clamp(Number(payload?.x),0,WORLD_WIDTH);p.y=clamp(Number(payload?.y),130,WORLD_HEIGHT-80);p.z=Math.max(0,Number(payload?.z)||0);p.hp=clamp(Number(payload?.hp),0,100);p.downed=Boolean(payload?.downed)||p.hp<=0;p.elements=elements(payload?.elements);p.statuses=statuses(payload?.statuses);p.controls=controlState(payload?.controls);p.kills=Math.max(0,Math.floor(Number(payload?.kills)||0));p.stealthBrokenUntil=clamp(Number(payload?.stealthBrokenUntil),0,ctx.now()+5000);ctx.broadcast('magicka:player',{...p});checkGameOver(ctx);},
  publishRealtimeFrame(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id],sequence=Number(payload?.sequence),x=Number(payload?.x),y=Number(payload?.y),z=Number(payload?.z);if(!p||!Number.isInteger(sequence)||sequence<=p.realtimeSequence||!Number.isFinite(x)||!Number.isFinite(y)||!Number.isFinite(z)||Math.hypot(x-p.x,y-p.y)>700)return;const activity=playerActivity(payload?.activity,p,ctx.now());if(!activity)return;p.realtimeSequence=sequence;p.x=clamp(x,0,WORLD_WIDTH);p.y=clamp(y,130,WORLD_HEIGHT-80);p.z=clamp(z,0,1200);p.activity=activity;p.elements=[...activity.elements];pruneCasts(ctx.state,ctx.now());ctx.broadcast('magicka:realtime-frame',{playerId:player.id,sequence,sentAt:ctx.now(),x:p.x,y:p.y,z:p.z,activity});},
  reportSpellCast(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const p=ctx.state.players[player.id],castId=text(payload?.castId,100),spellId=text(payload?.spellId,100),phase=text(payload?.phase,20),revision=Math.max(0,Math.floor(Number(payload?.revision)||0)),origin=point(payload?.origin),target=point(payload?.target),castElements=elements(payload?.elements),banned=activeBannedElement(ctx.state,p);if(!p||!castId||!spellId||!origin||!target||banned&&castElements.includes(banned)||!['committed','resolved','channeling','cancelled','ended'].includes(phase)||Math.hypot(p.x-origin.x,p.y-origin.y)>180)return;const existing=ctx.state.activeCasts[castId],basePlan=resolvePlayerSpell(castElements.length?castElements:p.activity.elements,p.inventory,p.scrollCooldowns,ctx.now()),plan=basePlan?applyEquipmentToSpell(basePlan,p.equipment):null;if(phase==='committed'){if(existing||!plan||plan.id!==spellId)return;if(isScrollSpell(spellId))p.scrollCooldowns[spellId]=ctx.now()+20000;const cast:ActiveCast={castId,sourcePlayerId:player.id,spellId,phase:'committed',origin,target,committedAt:ctx.now(),resolveAt:ctx.now()+plan.castMs,revision};ctx.state.activeCasts[castId]=cast;p.activity={phase:'windup',elements:[...castElements],spellId,castId,phaseStartedAt:cast.committedAt,phaseEndsAt:cast.resolveAt};ctx.broadcast('magicka:spell-cast',cast);return;}if(!existing||existing.sourcePlayerId!==player.id||revision<=existing.revision)return;if(phase==='resolved'&&existing.phase!=='committed'||phase==='channeling'&&!['committed','channeling'].includes(existing.phase))return;existing.phase=phase as ActiveCast['phase'];existing.revision=revision;existing.target=target;if(phase==='channeling')p.activity={...p.activity,phase:'channeling',spellId,castId,phaseStartedAt:ctx.now(),phaseEndsAt:null};if(phase==='resolved')p.activity={...p.activity,phase:'recovery',spellId,castId:null,phaseStartedAt:ctx.now(),phaseEndsAt:ctx.now()+(plan?.recoveryMs??180)};ctx.broadcast('magicka:spell-cast',{...existing});if(phase==='cancelled'||phase==='ended')delete ctx.state.activeCasts[castId];},
  discoverRecipe(ctx,{player,payload}){const recipeId=text(payload?.recipeId,100),cast=Object.values(ctx.state.activeCasts).find(v=>v.sourcePlayerId===player.id&&v.spellId===recipeId&&(v.phase==='resolved'||v.phase==='channeling'));if(ctx.state.phase!=='running'||!cast||!isRecipeId(recipeId)||ctx.state.discoveredRecipeIds.includes(recipeId))return;ctx.state.discoveredRecipeIds.push(recipeId);ctx.broadcast('magicka:recipe-discovered',{recipeId});},
  syncWorld(ctx,{player,payload}){if(ctx.state.phase!=='running'||player.id!==ctx.host.id)return;const sequence=Number(payload?.sequence);if(!Number.isInteger(sequence)||sequence<=ctx.state.worldSequence)return;const stage=stageProgress(payload?.stage);if(!stage||stage.index!==ctx.state.stageIndex||stage.biome!==ctx.state.biome)return;ctx.state.worldSequence=sequence;ctx.state.enemies=Object.fromEntries(enemyList(payload?.enemies).map(e=>[e.id,e]));ctx.state.projectiles=Object.fromEntries(projectileList(payload?.projectiles).map(e=>[e.id,e]));ctx.state.environments=Object.fromEntries(environmentList(payload?.environments).map(e=>[e.id,e]));ctx.state.hazards=Object.fromEntries(hazardList(payload?.hazards,ctx.state).map(e=>[e.id,e]));ctx.state.events=Object.fromEntries(eventList(payload?.events,ctx.state).map(e=>[e.id,e]));ctx.state.encounters=Object.fromEntries(encounterList(payload?.encounters).map(e=>[e.roomId,e]));ctx.state.loot=Object.fromEntries(lootList(payload?.loot).map(e=>[e.id,e]));ctx.state.merchants=Object.fromEntries(merchantList(payload?.merchants).map(e=>[e.id,e]));ctx.state.stage=stage;},
  reportEnemyDamage(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const eventId=text(payload?.eventId,100),enemyId=text(payload?.enemyId,100),spellId=text(payload?.spellId,100),amount=Number(payload?.amount);if(!eventId||!enemyId||!ctx.state.enemies[enemyId]||!Number.isFinite(amount)||amount===0||Math.abs(amount)>5000||ctx.state.authorityEventIds.includes(eventId))return;rememberAuthority(ctx.state,eventId);ctx.broadcast('magicka:enemy-damage',{eventId,worldSequence:Number(payload?.worldSequence)||0,enemyId,sourcePlayerId:player.id,spellId,amount,statuses:statuses(payload?.statuses),controls:Array.isArray(payload?.controls)?payload.controls:[],direction:payload?.direction});},
  reportPlayerEffect(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const eventId=text(payload?.eventId,100),targetPlayerId=text(payload?.targetPlayerId,100);if(!eventId||!targetPlayerId||!ctx.state.players[targetPlayerId])return;ctx.broadcast('magicka:player-effect',{eventId,sourcePlayerId:player.id,targetPlayerId,effects:Array.isArray(payload?.effects)?payload.effects:[]});},
  reportSpellVisual(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const eventId=text(payload?.eventId,100),source=ctx.state.players[player.id],kind=text(payload?.kind,20),color=text(payload?.color,20),origin=point(payload?.origin),target=point(payload?.target),radius=clamp(Number(payload?.radius),1,1200),coneAngle=clamp(Number(payload?.coneAngle),.1,Math.PI*1.5),durationMs=clamp(Number(payload?.durationMs),80,1500);if(!eventId||!source||!origin||!target||!['cone','impact','beam','projectile','heal'].includes(kind)||!ELEMENTS.includes(color as Element)||Math.hypot(source.x-origin.x,source.y-origin.y)>180)return;ctx.broadcast('magicka:spell-visual',{eventId,sourcePlayerId:player.id,kind,origin,target,radius,angle:Number(payload?.angle)||0,coneAngle,color,durationMs});},
  reportEnvironment(ctx,{player,payload}){if(ctx.state.phase!=='running')return;const environment=environmentList([payload])[0];if(environment)ctx.broadcast('magicka:environment',{...environment,sourcePlayerId:player.id});},
  reportProjectileHit(ctx,{payload}){if(ctx.state.phase!=='running')return;const projectileId=text(payload?.projectileId,100);if(projectileId)ctx.broadcast('magicka:projectile-hit',{projectileId});}
 }
});
function initialState():GameState{const runSeed=randomSeed();return{schemaVersion:SCHEMA_VERSION,phase:'lobby',hostId:null,startedAt:null,runSeed,stageIndex:0,biome:'ruins',stageSeed:deriveStageSeed(runSeed,0),stage:null,activeCasts:{},discoveredRecipeIds:[],exploredRoomIds:[],players:{},enemies:{},projectiles:{},environments:{},hazards:{},events:{},encounters:{},loot:{},merchants:{},rewardEventIds:[],authorityEventIds:[],worldSequence:0,totalKills:0,victorySummary:null,message:'所有玩家准备后开始'}}
function makePlayer(id:string,name:string,runSeed=1):PublicPlayer{const spawn=generateMap(runSeed).spawn;return{id,name,ready:false,connected:true,x:spawn.x,y:spawn.y,z:0,hp:100,downed:false,sequence:0,realtimeSequence:0,activity:{phase:'idle',elements:[],spellId:null,castId:null,phaseStartedAt:0,phaseEndsAt:null},elements:[],statuses:[],controls:{...ZERO_CONTROL},kills:0,gold:50,equipment:{staff:null,robe:null,ring:null},inventory:[],scrollCooldowns:{},stealthBrokenUntil:0}}
function start(ctx:RoomContext<GameState>){ctx.state.runSeed=randomSeed(ctx.now());ctx.state.stageIndex=0;ctx.state.biome='ruins';ctx.state.stageSeed=deriveStageSeed(ctx.state.runSeed,0);const spawn=generateMap(ctx.state.runSeed,0).spawn;Object.assign(ctx.state,{phase:'running',startedAt:ctx.now(),hostId:ctx.host.id,stage:null,activeCasts:{},exploredRoomIds:[],enemies:{},projectiles:{},environments:{},hazards:{},events:{},encounters:{},loot:{},merchants:{},rewardEventIds:[],authorityEventIds:[],worldSequence:0,totalKills:0,victorySummary:null,message:'远古遗迹探索开始'});for(const [id,p]of Object.entries(ctx.state.players))Object.assign(p,makePlayer(id,p.name,ctx.state.runSeed),{ready:true,x:spawn.x,y:spawn.y});ctx.broadcast('magicka:start',{});}
function resetLobby(s:GameState){s.runSeed=randomSeed();for(const[id,p]of Object.entries(s.players)){if(!p.connected)delete s.players[id];else Object.assign(p,makePlayer(id,p.name,s.runSeed));}Object.assign(s,{phase:'lobby',startedAt:null,stageIndex:0,biome:'ruins',stageSeed:deriveStageSeed(s.runSeed,0),stage:null,activeCasts:{},exploredRoomIds:[],enemies:{},projectiles:{},environments:{},hazards:{},events:{},encounters:{},loot:{},merchants:{},rewardEventIds:[],authorityEventIds:[],worldSequence:0,totalKills:0,victorySummary:null,message:'所有玩家准备后开始'});}
function checkGameOver(ctx:RoomContext<GameState>){if(ctx.state.phase!=='running')return;const active=Object.values(ctx.state.players).filter(p=>p.connected);if(active.length&&active.every(p=>p.downed)){ctx.state.phase='gameover';ctx.state.message='全员倒地';ctx.broadcast('magicka:gameover',{});}}
function elements(v:unknown):Element[]{return Array.isArray(v)?v.filter((x):x is Element=>ELEMENTS.includes(x as Element)).slice(0,4):[]}
function statuses(v:unknown):StatusInstance[]{return Array.isArray(v)?v.filter(x=>x&&typeof x==='object'&&typeof x.kind==='string').slice(0,16) as StatusInstance[]:[]}
function enemyList(v:unknown):EnemyState[]{return Array.isArray(v)?v.filter(x=>x&&typeof x.id==='string').slice(0,80) as EnemyState[]:[]}
function projectileList(v:unknown):HostProjectile[]{return Array.isArray(v)?v.filter(x=>x&&typeof x.id==='string').slice(0,120) as HostProjectile[]:[]}
function environmentList(v:unknown):EnvironmentState[]{return Array.isArray(v)?v.filter(x=>x&&typeof x.id==='string').slice(0,32) as EnvironmentState[]:[]}
function hazardList(v:unknown,state:GameState):HazardState[]{const map=generateMap(state.runSeed,state.stageIndex),allowed=new Set(map.hazards.map(h=>h.id));return Array.isArray(v)?v.filter(x=>x&&allowed.has(String(x.id))&&Number.isFinite(x.x)&&Number.isFinite(x.y)&&x.x>=0&&x.x<=WORLD_WIDTH&&x.y>=0&&x.y<=WORLD_HEIGHT).slice(0,40) as HazardState[]:[]}
function eventList(v:unknown,state:GameState):WorldEventState[]{const allowed=new Set(generateMap(state.runSeed,state.stageIndex).events.map(e=>e.id));return Array.isArray(v)?v.filter(x=>x&&allowed.has(String(x.id))).slice(0,12) as WorldEventState[]:[]}
function encounterList(v:unknown):RegionEncounter[]{const result=Array.isArray(v)?v.filter(x=>x&&typeof x.roomId==='string'&&(x.kind==='roaming'||x.kind==='sealed')&&(x.status==='dormant'||x.status==='active'||x.status==='cleared')).slice(0,40) as RegionEncounter[]:[];for(const encounter of result)if(encounter.challenge)encounter.challenge.active=encounter.status==='active';return result;}
function lootList(v:unknown):LootEntity[]{return Array.isArray(v)?v.filter(x=>x&&typeof x.id==='string'&&x.item&&typeof x.item.id==='string').slice(0,80) as LootEntity[]:[]}
function merchantList(v:unknown):MerchantState[]{return Array.isArray(v)?v.filter(x=>x&&typeof x.id==='string'&&Array.isArray(x.stock)).slice(0,8) as MerchantState[]:[]}
function stageProgress(v:unknown):StageProgress|null{const s=v as StageProgress|null;if(!s||!Number.isInteger(s.index)||!Array.isArray(s.objectives)||!s.boss)return null;if(s.boss.challenge)s.boss.challenge.active=s.boss.status==='active';return s;}
function inCombat(state:GameState,p:PublicPlayer){const room=roomAt(generateMap(state.runSeed,state.stageIndex),p);return Boolean(room&&Object.values(state.enemies).some(enemy=>enemy.roomId===room.id));}
function activeBannedElement(state:GameState,p:PublicPlayer){const room=roomAt(generateMap(state.runSeed,state.stageIndex),p);if(!room)return null;const encounter=state.encounters[room.id];if(encounter?.status==='active'&&encounter.challenge)return encounter.challenge.element;if(state.stage?.boss.roomId===room.id&&state.stage.boss.status==='active'&&state.stage.boss.challenge)return state.stage.boss.challenge.element;return null;}
function hashText(value:string){let result=2166136261;for(let i=0;i<value.length;i++){result^=value.charCodeAt(i);result=Math.imul(result,16777619);}return result|0;}
function rememberAuthority(state:GameState,eventId:string){state.authorityEventIds.push(eventId);state.authorityEventIds=state.authorityEventIds.slice(-300);}
function point(v:unknown){const p=v as {x?:unknown;y?:unknown}|null,x=Number(p?.x),y=Number(p?.y);return Number.isFinite(x)&&Number.isFinite(y)&&x>=0&&x<=WORLD_WIDTH&&y>=0&&y<=WORLD_HEIGHT?{x,y}:null;}
function playerActivity(v:unknown,p:PublicPlayer,now:number):PlayerActivity|null{const a=v as Partial<PlayerActivity>|null;if(!a||typeof a!=='object'||!['idle','selecting','aiming','windup','channeling','recovery','interrupted','downed','stunned'].includes(String(a.phase)))return null;const selected=elements(a.elements),plan=resolvePlayerSpell(selected,p.inventory,p.scrollCooldowns,now),spellId=typeof a.spellId==='string'&&a.spellId===plan?.id?a.spellId:null,phase=p.downed?'downed':now<p.controls.stunnedUntil?'stunned':a.phase as PlayerActivity['phase'];return{phase,elements:selected,spellId,castId:typeof a.castId==='string'?a.castId.slice(0,100):null,phaseStartedAt:clamp(Number(a.phaseStartedAt),0,now+1000),phaseEndsAt:a.phaseEndsAt==null?null:clamp(Number(a.phaseEndsAt),0,now+10000)};}
function isScrollSpell(id:string){return id.startsWith('scroll-');}
function pruneCasts(state:GameState,now:number){for(const[id,cast]of Object.entries(state.activeCasts))if((cast.phase==='resolved'&&now>cast.resolveAt+1500)||cast.phase==='cancelled'||cast.phase==='ended')delete state.activeCasts[id];}
function controlState(v:unknown):ControlState{const c=v as Partial<ControlState>|null;return c&&typeof c==='object'?{vx:Number(c.vx)||0,vy:Number(c.vy)||0,z:Math.max(0,Number(c.z)||0),vz:Number(c.vz)||0,slowedUntil:Number(c.slowedUntil)||0,slowScale:clamp(Number(c.slowScale),.1,1),stunnedUntil:Number(c.stunnedUntil)||0}:{...ZERO_CONTROL}}
function clamp(v:number,min:number,max:number){return Number.isFinite(v)?Math.max(min,Math.min(max,v)):min}function text(v:unknown,n:number){return typeof v==='string'?v.slice(0,n):''}
function replace(target:GameState,next:GameState){for(const k of Object.keys(target)as Array<keyof GameState>)delete target[k];Object.assign(target,next);}
function randomSeed(value=Date.now()){return(Math.imul(value|0,1664525)+1013904223)>>>0;}
