import { mainCanvas, mainContext, mousePosScreen, mouseWasPressed } from 'littlejsengine';
import type { GameState, PrivateState, SeatState } from '../game/types';
import { formatActionAnnouncement, type ActionFx } from '../game/presentation';
import type { Tile } from '../worker/types';
import { drawMahjongTile } from './MahjongTileRenderer';

type Hit = { x:number;y:number;w:number;h:number;onClick:()=>void };
type Flash = { text:string; color:string; until:number };
const C={bg:'#050914',table:'#092c38',cyan:'#12f7d6',gold:'#ffc857',red:'#ff355d',white:'#fff8df',muted:'#91b6bd',panel:'#0d1c2d'};

export class MahjongScene {
  private state:GameState|null=null; private privateState:PrivateState={hand:[],canWin:false,concealedGangKinds:[],addedGangKinds:[],reactionOptions:[],chiOptions:[]};
  private selected:string|null=null; private hits:Hit[]=[]; private ratio=1; private disposers:Array<()=>void>=[]; private flash:Flash|null=null; private lastPhase='';
  init(){this.disposers.push(parti.onState(value=>this.receive(value as GameState)),parti.onEvent('mahjong:private-state',value=>{this.privateState=value as PrivateState;if(this.selected&&!this.privateState.hand.some(t=>t.id===this.selected))this.selected=null}),parti.onEvent('mahjong:notice',value=>this.show((value as {message:string}).message,C.gold)),parti.onEvent('mahjong:action-fx',value=>this.show(formatActionAnnouncement(value as ActionFx),C.cyan)),parti.onEvent('mahjong:settlement',value=>this.show((value as {message:string}).message,C.gold)));window.addEventListener('pagehide',this.destroy,{once:true});parti.ready();void parti.action('syncPrivate')}
  private receive(state:GameState){if(this.lastPhase&&state.phase!==this.lastPhase&&(state.phase==='settlement'||state.phase==='matchEnd'))this.show(state.message,C.gold);this.lastPhase=state.phase;this.state=state}
  update(){this.ratio=mainCanvas.width/Math.max(1,mainCanvas.clientWidth);const x=mousePosScreen.x/this.ratio,y=mousePosScreen.y/this.ratio;const hit=[...this.hits].reverse().find(item=>inside(item,x,y));mainCanvas.style.cursor=hit?'pointer':'';if(hit&&mouseWasPressed(0))hit.onClick()}
  render(){const w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio,ctx=mainContext;ctx.save();ctx.setTransform(this.ratio,0,0,this.ratio,0,0);ctx.clearRect(0,0,w,h);this.hits=[];this.background(w,h);if(!this.state){this.center('正在连接牌桌…',w,h/2,22,C.white);ctx.restore();return}this.header(w);if(this.state.phase==='lobby')this.lobby(w,h);else this.table(w,h);this.flashFx(w,h);ctx.restore()}
  private background(w:number,h:number){const ctx=mainContext;const g=ctx.createRadialGradient(w/2,h*.48,20,w/2,h*.48,Math.max(w,h)*.75);g.addColorStop(0,'#103b4b');g.addColorStop(.55,C.table);g.addColorStop(1,C.bg);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(18,247,214,.12)';ctx.lineWidth=1;for(let x=-h;x<w+h;x+=54){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-h,h);ctx.stroke()}}
  private header(w:number){this.text(20,58,'超级麻将',28,C.white,900);this.text(20,91,this.state!.message,14,C.muted,500);this.text(Math.max(220,w-260),62,`第 ${Math.min(this.state!.roundIndex+1,this.state!.rules.rounds)}/${this.state!.rules.rounds} 局  ·  牌墙 ${this.state!.wallCount}`,14,C.gold,700)}
  private lobby(w:number,h:number){const state=this.state!,me=this.me();const compact=w<700;const pw=Math.min(680,w-32),x=(w-pw)/2,y=Math.max(120,h*.18);this.panel(x,y,pw,Math.min(h-y-24,500),C.panel,C.cyan,.92);this.center('红中万能 · 四方雀战',w,y+34,24,C.gold,900);const seats=state.seats.filter(Boolean) as SeatState[];this.center(seats.length?seats.map(s=>`${s.name}${s.ready?' ✓':''}`).join('　'):'等待玩家加入',w,y+75,15,C.white);
    const rules=state.rules;const rows:Array<[string,string,()=>void]>=[['胡牌',rules.winSource==='both'?'自摸+点炮':rules.winSource==='selfDrawOnly'?'仅自摸':'仅点炮',()=>this.config({winSource:rules.winSource==='both'?'selfDrawOnly':rules.winSource==='selfDrawOnly'?'discardOnly':'both'})],['吃牌',rules.allowChi?'允许':'关闭',()=>this.config({allowChi:!rules.allowChi})],['多响',rules.allowMultiWin?'一炮多响':'最近截胡',()=>this.config({allowMultiWin:!rules.allowMultiWin})],['抢杠胡',rules.allowRobGang?'允许':'关闭',()=>this.config({allowRobGang:!rules.allowRobGang})],['海底',rules.allowLastTile?'加倍':'关闭',()=>this.config({allowLastTile:!rules.allowLastTile})],['局数',String(rules.rounds),()=>this.config({rounds:rules.rounds===1?4:rules.rounds===4?8:1})],['底分',String(rules.baseScore),()=>this.config({baseScore:rules.baseScore>=10?1:rules.baseScore+1})],['封顶',`${rules.maxFan} 番`,()=>this.config({maxFan:rules.maxFan>=16?4:rules.maxFan+1})]];
    const cols=compact?2:4,cw=(pw-32)/cols;rows.forEach((row,i)=>{const rx=x+16+(i%cols)*cw,ry=y+108+Math.floor(i/cols)*66;this.button(rx,ry,cw-10,50,`${row[0]}  ${row[1]}`,row[2],state.hostId!==parti.playerId)});
    const by=y+(compact?260:194);if(me)this.button(w/2-150,by,140,50,me.ready?'取消准备':'准备',()=>void parti.action('setReady',{ready:!me.ready}));if(state.hostId===parti.playerId)this.button(w/2+10,by,140,50,'开始牌局',()=>void parti.action('startMatch'),!seats.filter(s=>!s.bot).every(s=>s.ready));this.center('1–4 位真人，空位由雀侠机器人补齐',w,by+78,13,C.muted)}
  private table(w:number,h:number){const state=this.state!,me=this.me(),mySeat=me?.seat??0,centerX=w/2,centerY=Math.max(275,h*.45);const radius=Math.min(w*.36,h*.30);for(const seat of state.seats.filter(Boolean) as SeatState[]){const visual=(seat.seat-mySeat+4)%4;const pos=visual===0?{x:centerX,y:h-122}:visual===1?{x:w-88,y:centerY}:visual===2?{x:centerX,y:135}:{x:88,y:centerY};this.playerBadge(seat,pos.x,pos.y,visual)}
    this.panel(centerX-112,centerY-68,224,136,'rgba(3,13,24,.8)',C.cyan,.86);this.center(state.phase==='reaction'?'等 待 响 应':state.currentSeat===mySeat?'轮 到 你':'雀 局 进 行 中',w,centerY-28,19,state.currentSeat===mySeat?C.gold:C.white,900);this.center(`庄 ${state.dealerSeat+1} · 余 ${state.wallCount}`,w,centerY+8,14,C.muted);if(state.lastDiscard)this.drawTile(centerX-24,centerY+28,state.lastDiscard.tile,48,66,false);
    this.discardRows(w,h,mySeat,radius);this.hand(w,h);this.actions(w,h);if(state.phase==='settlement'||state.phase==='matchEnd')this.settlement(w,h)}
  private playerBadge(seat:SeatState,x:number,y:number,visual:number){const active=this.state!.currentSeat===seat.seat;const width=visual%2?112:170,height=54;this.panel(x-width/2,y-height/2,width,height,'rgba(5,15,28,.92)',active?C.gold:C.cyan,.95);this.centerAt(x,y-8,`${seat.dealer?'庄 · ':''}${seat.name}`,13,C.white,700);this.centerAt(x,y+13,`${seat.score>=0?'+':''}${seat.score}  ·  ${seat.handCount}张`,12,seat.score>=0?C.cyan:C.red,700)}
  private discardRows(w:number,h:number,mySeat:number,radius:number){const cx=w/2,cy=Math.max(275,h*.45);for(const seat of this.state!.seats.filter(Boolean) as SeatState[]){const v=(seat.seat-mySeat+4)%4;const cards=seat.discards.slice(-12);cards.forEach((tile,i)=>{let x=cx,y=cy;if(v===0){x=cx-132+(i%6)*44;y=cy+105+Math.floor(i/6)*56}else if(v===2){x=cx+88-(i%6)*36;y=cy-145-Math.floor(i/6)*48}else if(v===1){x=cx+radius+10+(i%3)*30;y=cy-72+Math.floor(i/3)*38}else{x=cx-radius-100+(i%3)*30;y=cy-72+Math.floor(i/3)*38}this.drawTile(x,y,tile,v%2?28:34,v%2?38:46,false)});this.drawMelds(seat,v,cx,cy,radius)}}
  private drawMelds(seat:SeatState,v:number,cx:number,cy:number,radius:number){seat.melds.flatMap(m=>m.tiles).slice(0,16).forEach((tile,i)=>{const x=v===0?20+i*28:v===2?cx-210+i*25:v===1?cx+radius+52+(i%4)*25:cx-radius-148+(i%4)*25;const y=v===0?Math.max(112,mainCanvas.height/this.ratio-222):v===2?105:v%2?cy+110+Math.floor(i/4)*34:cy;this.drawTile(x,y,tile,25,34,false)})}
  private hand(w:number,h:number){const hand=this.privateState.hand;if(!hand.length)return;const cardW=Math.max(32,Math.min(58,w/11)),cardH=cardW*1.35,gap=Math.max(21,Math.min(cardW*.72,(w-36-cardW)/Math.max(1,hand.length-1))),total=cardW+gap*(hand.length-1),start=(w-total)/2,y=h-cardH-16;hand.forEach((tile,i)=>{const selected=tile.id===this.selected,x=start+i*gap,ty=y-(selected?18:0);this.drawTile(x,ty,tile,cardW,cardH,selected);this.hits.push({x,y:ty,w:i===hand.length-1?cardW:gap,h:cardH,onClick:()=>{this.selected=this.selected===tile.id?null:tile.id}})})}
  private actions(w:number,h:number){const options=this.privateState.reactionOptions;const y=Math.max(128,h-190);let actions:Array<[string,()=>void,boolean]>=[];if(options.length){if(options.includes('win'))actions.push(['胡',()=>void parti.action('declareWin'),false]);if(options.includes('gang'))actions.push(['杠',()=>void parti.action('gang'),false]);if(options.includes('peng'))actions.push(['碰',()=>void parti.action('peng'),false]);if(options.includes('chi'))actions.push(['吃',()=>this.doChi(),false]);actions.push(['过',()=>void parti.action('passReaction'),false])}else if(this.state!.phase==='playing'&&this.me()?.seat===this.state!.currentSeat){if(this.privateState.canWin)actions.push(['自摸',()=>void parti.action('declareWin'),false]);const gang=this.privateState.concealedGangKinds[0]??this.privateState.addedGangKinds[0];if(gang)actions.push(['杠',()=>void parti.action('gang',{kind:gang}),false]);actions.push(['出牌',()=>this.discard(),!this.selected])}const bw=88,gap=10,start=w/2-(actions.length*bw+(actions.length-1)*gap)/2;actions.forEach((a,i)=>this.button(start+i*(bw+gap),y,bw,44,a[0],a[1],a[2]))}
  private settlement(w:number,h:number){const result=this.state!.result;if(!result)return;const boxW=Math.min(520,w-28),boxH=Math.min(330,h-170),x=(w-boxW)/2,y=Math.max(116,(h-boxH)/2-20);this.panel(x,y,boxW,boxH,'rgba(5,9,20,.97)',C.gold,.98);this.center(result.draw?'流 局':'胡 牌 结 算',w,y+38,28,C.gold,900);this.center(result.message,w,y+78,16,C.white,700);let rowY=y+112;for(const seat of this.state!.seats.filter(Boolean) as SeatState[]){const delta=result.deltas[seat.seat]??0;this.text(x+32,rowY,seat.name,15,C.white,700);this.text(x+boxW-120,rowY,`${delta>=0?'+':''}${delta}`,18,delta>=0?C.cyan:C.red,900);rowY+=32}const host=this.state!.hostId===parti.playerId;if(host)this.button(w/2-80,y+boxH-62,160,44,this.state!.phase==='matchEnd'?'新比赛':'下一局',()=>void parti.action(this.state!.phase==='matchEnd'?'restartMatch':'nextRound'))}
  private doChi(){const kinds=this.privateState.chiOptions[0];if(!kinds)return;const ids:string[]=[];for(const kind of kinds){const tile=this.privateState.hand.find(candidate=>candidate.kind===kind&&!ids.includes(candidate.id));if(tile)ids.push(tile.id)}if(ids.length===2)void parti.action('chi',{tileIds:ids})}
  private discard(){if(this.selected)void parti.action('discard',{tileId:this.selected})}
  private config(partial:Record<string,unknown>){if(this.state?.hostId===parti.playerId)void parti.action('configureRules',partial)}
  private drawTile(x:number,y:number,tile:Tile,w:number,h:number,selected:boolean){drawMahjongTile(mainContext,tile.kind,x,y,w,h,{selected})}
  private button(x:number,y:number,w:number,h:number,label:string,onClick:()=>void,disabled=false){this.roundRect(x,y,w,h,10,disabled?'#263746':'#ffc857',disabled?'#49616c':'#fff0a8',2);this.centerAt(x+w/2,y+h/2,label,15,disabled?'#82969e':'#241407',800);if(!disabled)this.hits.push({x,y,w,h,onClick})}
  private panel(x:number,y:number,w:number,h:number,fill:string,stroke:string,alpha=1){mainContext.save();mainContext.globalAlpha=alpha;this.roundRect(x,y,w,h,14,fill,stroke,2);mainContext.restore()}
  private roundRect(x:number,y:number,w:number,h:number,r:number,fill:string,stroke:string,lw:number){const c=mainContext;c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill();c.strokeStyle=stroke;c.lineWidth=lw;c.stroke()}
  private text(x:number,y:number,value:string,size:number,color:string,weight:number|string=400){const c=mainContext;c.font=`${weight} ${size}px system-ui,sans-serif`;c.fillStyle=color;c.textAlign='left';c.textBaseline='top';c.fillText(value,x,y)}
  private center(value:string,w:number,y:number,size:number,color:string,weight:number|string=400){this.centerAt(w/2,y,value,size,color,weight)}
  private centerAt(x:number,y:number,value:string,size:number,color:string,weight:number|string=400){const c=mainContext;c.font=`${weight} ${size}px system-ui,sans-serif`;c.fillStyle=color;c.textAlign='center';c.textBaseline='middle';c.fillText(value,x,y)}
  private flashFx(w:number,h:number){if(!this.flash||performance.now()>this.flash.until){this.flash=null;return}const life=(this.flash.until-performance.now())/1200,scale=1+(1-life)*.18;mainContext.save();mainContext.translate(w/2,h*.26);mainContext.scale(scale,scale);mainContext.shadowBlur=24;mainContext.shadowColor=this.flash.color;this.centerAt(0,0,this.flash.text,Math.min(38,w/10),this.flash.color,900);mainContext.restore()}
  private show(text:string,color:string){this.flash={text,color,until:performance.now()+1200}}
  private me(){return this.state?.seats.find(seat=>seat?.id===parti.playerId)??null}
  private destroy=()=>{for(const dispose of this.disposers.splice(0))dispose()}
}
function inside(hit:Hit,x:number,y:number){return x>=hit.x&&x<=hit.x+hit.w&&y>=hit.y&&y<=hit.y+hit.h}
