import { mainCanvas, mainContext, mousePosScreen, mouseWasPressed } from 'littlejsengine';
import type { GameState, PrivateState, SeatState } from '../game/types';
import { formatActionAnnouncement, formatTileName, type ActionFx } from '../game/presentation';
import type { Tile } from '../worker/types';
import { computeLobbyLayout, computeTableLayout, selectedTileLift, type Rect } from './MahjongLayout';
import { drawMahjongTile } from './MahjongTileRenderer';
import { easeOutBack, MahjongAnimationQueue, type ActiveMahjongAnimation } from './MahjongAnimationQueue';
import { findAddedTile, mahjongPresentationMask, settlementScores } from './MahjongPresentation';

type Hit = Rect & { onClick:()=>void };
type Flash = { text:string; color:string; until:number };
const C={bg:'#050914',table:'#092c38',cyan:'#12f7d6',gold:'#ffc857',red:'#ff355d',white:'#fff8df',muted:'#91b6bd',panel:'#0d1c2d'};
const DIRECTIONS=['南 · 自家','西 · 右家','北 · 对家','东 · 左家'] as const;

export class MahjongScene {
  private state:GameState|null=null;
  private privateState:PrivateState={hand:[],canWin:false,concealedGangKinds:[],addedGangKinds:[],reactionOptions:[],chiOptions:[]};
  private selected:string|null=null; private hits:Hit[]=[]; private ratio=1; private disposers:Array<()=>void>=[];
  private flash:Flash|null=null; private lastPhase=''; private activity:string[]=[];
  private animations=new MahjongAnimationQueue();
  private activeAnimation:ActiveMahjongAnimation|null=null; private pendingDraw:Tile|null=null;
  private presentedHand:Tile[]=[];private pendingDrawAt=0;private roundStartScores:number[]=[];private settlementStartedAt=0;
  private pendingDrawEvent:ActionFx|null=null;
  init(){this.disposers.push(
    parti.onState(value=>this.receive(value as GameState)),
    parti.onEvent('mahjong:private-state',value=>{const next=value as PrivateState,added=findAddedTile(this.privateState.hand,next.hand);if(added){this.pendingDraw=added;this.pendingDrawAt=performance.now();this.presentedHand=[...this.privateState.hand]}else if(!this.pendingDraw)this.presentedHand=[...next.hand];this.privateState=next;if(added&&this.pendingDrawEvent){const event=this.pendingDrawEvent;this.pendingDrawEvent=null;this.actionFx(event)}if(this.selected&&!this.privateState.hand.some(t=>t.id===this.selected))this.selected=null}),
    parti.onEvent('mahjong:notice',value=>this.announce((value as {message:string}).message,C.gold)),
    parti.onEvent('mahjong:action-fx',value=>this.actionFx(value as ActionFx)),
    parti.onEvent('mahjong:settlement',value=>this.announce((value as {message:string}).message,C.gold)),
  );window.addEventListener('pagehide',this.destroy,{once:true});document.addEventListener('visibilitychange',this.visibility);parti.ready();void parti.action('syncPrivate')}
  private receive(state:GameState){if(state.phase==='playing'&&this.lastPhase!=='playing'&&this.lastPhase!=='reaction')this.roundStartScores=state.seats.map(seat=>seat?.score??0);if(this.lastPhase&&state.phase!==this.lastPhase&&(state.phase==='settlement'||state.phase==='matchEnd')){this.settlementStartedAt=performance.now();this.announce(state.message,C.gold)}this.lastPhase=state.phase;this.state=state}
  update(){this.ratio=mainCanvas.width/Math.max(1,mainCanvas.clientWidth);const previous=this.activeAnimation;this.activeAnimation=this.animations.update(performance.now());if(previous?.kind==='draw'&&this.activeAnimation?.id!==previous.id)this.presentedHand=[...this.privateState.hand];if((previous?.kind==='win'||previous?.kind==='drawGame')&&this.activeAnimation?.id!==previous.id)this.settlementStartedAt=performance.now();if(this.pendingDrawEvent&&performance.now()-this.pendingDrawAt>500){this.pendingDrawEvent=null;this.pendingDraw=null;this.presentedHand=[...this.privateState.hand]}if(this.pendingDraw&&performance.now()-this.pendingDrawAt>1600&&!this.animations.presentationAnimations().some(item=>item.kind==='draw')){this.pendingDraw=null;this.presentedHand=[...this.privateState.hand]}const x=mousePosScreen.x/this.ratio,y=mousePosScreen.y/this.ratio;const hit=[...this.hits].reverse().find(item=>inside(item,x,y));mainCanvas.style.cursor=hit?'pointer':'';if(hit&&mouseWasPressed(0)&&!this.animations.isInputBlocked())hit.onClick()}
  render(){const w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio,ctx=mainContext;ctx.save();ctx.setTransform(this.ratio,0,0,this.ratio,0,0);ctx.clearRect(0,0,w,h);this.hits=[];this.background(w,h);if(!this.state){this.center('正在连接牌桌…',w,h/2,22,C.white);ctx.restore();return}if(this.state.phase==='lobby')this.lobby(w,h);else this.table(w,h);this.animationFx(w,h);this.flashFx(w,h);ctx.restore()}
  private background(w:number,h:number){const ctx=mainContext;const g=ctx.createRadialGradient(w/2,h*.48,20,w/2,h*.48,Math.max(w,h)*.75);g.addColorStop(0,'#103b4b');g.addColorStop(.55,C.table);g.addColorStop(1,C.bg);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(18,247,214,.1)';for(let x=-h;x<w+h;x+=54){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-h,h);ctx.stroke()}}

  private lobby(w:number,h:number){const state=this.state!,me=this.me(),layout=computeLobbyLayout(w,h),compact=h<560;this.text(layout.header.x,layout.header.y,'超级麻将',compact?23:28,C.white,900);this.text(layout.header.x,layout.header.y+(compact?29:38),'红中万能 · 四方雀战 · 1–4 位真人',compact?12:14,C.gold,700);this.sectionLabel(layout.seatsArea.x,layout.seatsArea.y-16,'入座与准备');
    const seats=Array.from({length:4},(_,index)=>state.seats[index]);layout.seatCards.forEach((rect,index)=>this.lobbySeat(rect,seats[index],index));this.sectionLabel(layout.rulesArea.x,layout.rulesArea.y-18,state.hostId===parti.playerId?'玩法设置 · 点击切换':'玩法设置 · 房主配置');
    const rules=state.rules;const rows:Array<[string,string,()=>void]>=[['胡牌',rules.winSource==='both'?'自摸 + 点炮':rules.winSource==='selfDrawOnly'?'仅自摸':'仅点炮',()=>this.config({winSource:rules.winSource==='both'?'selfDrawOnly':rules.winSource==='selfDrawOnly'?'discardOnly':'both'})],['吃牌',rules.allowChi?'允许':'关闭',()=>this.config({allowChi:!rules.allowChi})],['多响',rules.allowMultiWin?'一炮多响':'最近截胡',()=>this.config({allowMultiWin:!rules.allowMultiWin})],['抢杠胡',rules.allowRobGang?'允许':'关闭',()=>this.config({allowRobGang:!rules.allowRobGang})],['海底',rules.allowLastTile?'加倍':'关闭',()=>this.config({allowLastTile:!rules.allowLastTile})],['局数',`${rules.rounds} 局`,()=>this.config({rounds:rules.rounds===1?4:rules.rounds===4?8:1})],['底分',String(rules.baseScore),()=>this.config({baseScore:rules.baseScore>=10?1:rules.baseScore+1})],['封顶',`${rules.maxFan} 番`,()=>this.config({maxFan:rules.maxFan>=16?4:rules.maxFan+1})]];
    layout.ruleCards.forEach((rect,index)=>{const row=rows[index]!;this.ruleCard(rect,row[0],row[1],row[2],state.hostId===parti.playerId)});this.actionBar(layout.actionBar,me,state)}
  private lobbySeat(rect:Rect,seat:SeatState|null,index:number){this.panel(rect.x,rect.y,rect.w,rect.h,seat?'rgba(8,31,44,.94)':'rgba(8,20,31,.72)',seat?.ready?C.gold:'rgba(18,247,214,.45)',.96);this.text(rect.x+10,rect.y+7,`${index+1} 号位`,11,C.muted,700);this.text(rect.x+10,rect.y+23,seat?.name??'等待加入',Math.min(14,rect.h*.3),C.white,800);if(seat)this.text(rect.x+rect.w-10,rect.y+10,seat.bot?'机器人':seat.ready?'已准备':'未准备',11,seat.ready?C.gold:C.muted,700,'right')}
  private ruleCard(rect:Rect,label:string,value:string,onClick:()=>void,editable:boolean){this.panel(rect.x,rect.y,rect.w,rect.h,editable?'rgba(13,34,48,.96)':'rgba(15,29,40,.92)',editable?C.cyan:'rgba(145,182,189,.38)',.96);this.text(rect.x+10,rect.y+8,label,11,C.muted,700);this.text(rect.x+10,rect.y+Math.max(22,rect.h*.45),value,Math.min(15,rect.h*.25),C.white,800);if(editable){this.text(rect.x+rect.w-12,rect.y+rect.h/2-8,'›',18,C.gold,900,'right');this.hits.push({...rect,onClick})}}
  private actionBar(rect:Rect,me:SeatState|null,state:GameState){this.panel(rect.x,rect.y,rect.w,rect.h,'rgba(4,14,25,.96)',C.gold,.98);const seats=state.seats.filter(Boolean) as SeatState[];const bw=Math.min(154,(rect.w-34)/2),bh=Math.min(46,rect.h-14),y=rect.y+(rect.h-bh)/2;if(me)this.button(rect.x+rect.w/2-bw-6,y,bw,bh,me.ready?'取消准备':'准备',()=>void parti.action('setReady',{ready:!me.ready}));if(state.hostId===parti.playerId)this.button(rect.x+rect.w/2+6,y,bw,bh,'开始牌局',()=>void parti.action('startMatch'),!seats.filter(s=>!s.bot).every(s=>s.ready))}

  private table(w:number,h:number){const state=this.state!,me=this.me(),mySeat=me?.seat??0,layout=computeTableLayout(w,h,this.privateState.hand.length);this.tableHud(layout.hud,layout.activityLines);this.panel(layout.table.x,layout.table.y,layout.table.w,layout.table.h,'rgba(4,28,38,.44)','rgba(18,247,214,.2)',.9);
    for(const seat of state.seats.filter(Boolean) as SeatState[]){const visual=(seat.seat-mySeat+4)%4;this.playerBadge(seat,layout.seats[visual]!,visual);this.discardRiver(seat,layout.rivers[visual]!,visual,state.lastDiscard?.seat===seat.seat);this.drawMelds(seat,layout.melds[visual]!,visual)}
    this.centerPanel(layout.center,mySeat);this.actions(layout.actions);this.hand(layout.hand);const mask=mahjongPresentationMask(this.activeAnimation,mySeat,this.animations.presentationAnimations());if((state.phase==='settlement'||state.phase==='matchEnd')&&!mask.hiddenSettlement)this.settlement(w,h)}
  private tableHud(rect:Rect,lines:1|3){const state=this.state!;mainContext.fillStyle='rgba(3,10,20,.82)';mainContext.fillRect(rect.x,rect.y,rect.w,rect.h);this.text(14,10,'超级麻将',22,C.white,900);this.text(14,38,`第 ${Math.min(state.roundIndex+1,state.rules.rounds)}/${state.rules.rounds} 局  ·  庄 ${state.dealerSeat+1} 号  ·  牌墙 ${state.wallCount}`,13,C.gold,700);const available=Math.max(150,rect.w-330);this.activity.slice(-lines).reverse().forEach((line,index)=>this.text(190,10+index*21,clip(line,available),12,index?C.muted:C.cyan,700));this.text(rect.w-106,rect.h-19,state.phase==='reaction'?'响应中':state.message,11,C.muted,600,'right')}
  private playerBadge(seat:SeatState,rect:Rect,visual:number){const active=this.state!.currentSeat===seat.seat;this.panel(rect.x,rect.y,rect.w,rect.h,'rgba(4,15,27,.96)',active?C.gold:C.cyan,.98);if(visual%2){mainContext.save();mainContext.translate(rect.x+rect.w/2,rect.y+rect.h/2);mainContext.rotate(visual===1?Math.PI/2:-Math.PI/2);this.centerAt(0,-9,`${seat.dealer?'庄 · ':''}${seat.name}`,13,C.white,800);this.centerAt(0,11,`${seat.score>=0?'+':''}${seat.score} · ${seat.handCount}张`,11,active?C.gold:C.cyan,700);mainContext.restore()}else{this.centerAt(rect.x+rect.w/2,rect.y+rect.h*.36,`${seat.dealer?'庄 · ':''}${seat.name}`,13,C.white,800);this.centerAt(rect.x+rect.w/2,rect.y+rect.h*.7,`${seat.score>=0?'+':''}${seat.score} · ${seat.handCount}张`,11,active?C.gold:C.cyan,700)}}
  private discardRiver(seat:SeatState,rect:Rect,visual:number,isLastSource:boolean){this.panel(rect.x,rect.y,rect.w,rect.h,isLastSource?'rgba(255,200,87,.09)':'rgba(3,15,25,.38)',isLastSource?'rgba(255,200,87,.5)':'rgba(145,182,189,.22)',.9);this.text(rect.x+6,rect.y+4,DIRECTIONS[visual],9,isLastSource?C.gold:C.muted,700);const mask=mahjongPresentationMask(this.activeAnimation,this.me()?.seat??0,this.animations.presentationAnimations()),hidden=mask.hiddenDiscardCounts.get(seat.seat)??0,visible=hidden?seat.discards.slice(0,-hidden):seat.discards;const cards=visible.slice(-18),side=visual%2===1,cols=side?3:6;const gap=3,top=16,tileW=Math.max(18,Math.min(side?28:34,(rect.w-12-gap*(cols-1))/cols)),tileH=tileW*1.34;cards.forEach((tile,index)=>{const x=rect.x+6+(index%cols)*(tileW+gap),y=rect.y+top+Math.floor(index/cols)*(tileH*.72+gap);if(y+tileH<=rect.y+rect.h+2)this.drawTile(x,y,tile,tileW,tileH,false)})}
  private drawMelds(seat:SeatState,rect:Rect,visual:number){const mask=mahjongPresentationMask(this.activeAnimation,this.me()?.seat??0,this.animations.presentationAnimations()),melds=mask.hiddenMeldSeats.has(seat.seat)?[]:seat.melds;const tiles=melds.flatMap(m=>m.tiles).slice(0,16);if(!tiles.length)return;const side=visual%2===1,tileW=side?22:25,tileH=tileW*1.34;tiles.forEach((tile,index)=>{const x=side?rect.x+(index%2)*(tileW*.72):rect.x+index*(tileW*.72),y=side?rect.y+Math.floor(index/2)*(tileH*.72):rect.y+(rect.h-tileH)/2;this.drawTile(x,y,tile,tileW,tileH,false)})}
  private centerPanel(rect:Rect,mySeat:number){const state=this.state!,active=state.currentSeat===mySeat,mask=mahjongPresentationMask(this.activeAnimation,mySeat,this.animations.presentationAnimations());this.panel(rect.x,rect.y,rect.w,rect.h,'rgba(3,13,24,.92)',active?C.gold:C.cyan,.96);const headline=state.phase==='reaction'?'等待响应':active?'轮到你':'牌局进行中';this.centerAt(rect.x+rect.w/2,rect.y+24,headline,17,active?C.gold:C.white,900);if(state.lastDiscard&&mask.hiddenDiscardCounts.size===0){const player=state.seats[state.lastDiscard.seat]?.name??`${state.lastDiscard.seat+1}号位`;this.centerAt(rect.x+rect.w/2,rect.y+48,`${player} 出了${formatTileName(state.lastDiscard.tile.kind)}`,11,C.muted,700);const tw=Math.min(42,rect.w*.2),th=tw*1.34;this.drawTile(rect.x+(rect.w-tw)/2,rect.y+58,state.lastDiscard.tile,tw,th,false)}else this.centerAt(rect.x+rect.w/2,rect.y+rect.h*.62,`余 ${state.wallCount} 张`,13,C.muted,700)}
  private hand(layout:ReturnType<typeof computeTableLayout>['hand']){const mask=mahjongPresentationMask(this.activeAnimation,this.me()?.seat??0,this.animations.presentationAnimations()),source=this.presentedHand.length?this.presentedHand:this.privateState.hand,hand=source.filter(tile=>!mask.hiddenHandTileIds.has(tile.id)),insert=this.activeAnimation?.kind==='draw'&&this.activeAnimation.drawnTile?Math.max(0,(this.activeAnimation.progress-.64)/.36):0;if(!hand.length)return;this.panel(layout.rect.x,layout.rect.y,layout.rect.w,layout.rect.h,'rgba(3,12,23,.9)','rgba(255,200,87,.35)',.96);hand.forEach((tile,index)=>{const finalIndex=this.privateState.hand.findIndex(candidate=>candidate.id===tile.id),visualIndex=index+(Math.max(0,finalIndex)-index)*Math.min(1,insert),selected=tile.id===this.selected,x=layout.startX+visualIndex*layout.gap,ty=layout.y-(selected?selectedTileLift(layout):0);this.drawTile(x,ty,tile,layout.tileWidth,layout.tileHeight,selected);this.hits.push({x,y:ty,w:index===hand.length-1?layout.tileWidth:layout.gap,h:layout.tileHeight,onClick:()=>{this.selected=this.selected===tile.id?null:tile.id}})})}
  private actions(rect:Rect){const options=this.privateState.reactionOptions;let actions:Array<[string,()=>void,boolean]>=[];if(options.length){if(options.includes('win'))actions.push(['胡',()=>void parti.action('declareWin'),false]);if(options.includes('gang'))actions.push(['杠',()=>void parti.action('gang'),false]);if(options.includes('peng'))actions.push(['碰',()=>void parti.action('peng'),false]);if(options.includes('chi'))actions.push(['吃',()=>this.doChi(),false]);actions.push(['过',()=>void parti.action('passReaction'),false])}else if(this.state!.phase==='playing'&&this.me()?.seat===this.state!.currentSeat){if(this.privateState.canWin)actions.push(['自摸',()=>void parti.action('declareWin'),false]);const gang=this.privateState.concealedGangKinds[0]??this.privateState.addedGangKinds[0];if(gang)actions.push(['杠',()=>void parti.action('gang',{kind:gang}),false]);actions.push(['出牌',()=>this.discard(),!this.selected])}if(!actions.length)return;const gap=8,bw=Math.min(88,(rect.w-gap*(actions.length-1))/actions.length),total=actions.length*bw+(actions.length-1)*gap,start=rect.x+(rect.w-total)/2;actions.forEach((a,index)=>this.button(start+index*(bw+gap),rect.y+(rect.h-42)/2,bw,42,a[0],a[1],a[2]))}
  private settlement(w:number,h:number){const state=this.state!,result=state.result;if(!result)return;const seats=state.seats.filter(Boolean) as SeatState[],boxW=Math.min(600,w-24),boxH=Math.min(h-20,154+seats.length*44+(state.phase==='matchEnd'?34:0)),footerSpace=state.phase==='matchEnd'?70:45,rowGap=Math.max(24,Math.min(44,(boxH-80-footerSpace)/Math.max(1,seats.length))),x=(w-boxW)/2,y=(h-boxH)/2,elapsed=Math.min(1,(performance.now()-this.settlementStartedAt)/1100);this.panel(x,y,boxW,boxH,'rgba(5,9,20,.98)',C.gold,.99);this.center(result.draw?'流 局':'本 局 结 算',w,y+25,Math.min(25,boxH*.1),C.gold,900);this.center(result.message,w,y+52,12,C.white,700);const scores=settlementScores(state.seats.map(seat=>seat?.score??0),result,this.roundStartScores.length?this.roundStartScores:undefined);seats.forEach((seat,index)=>{const score=scores[seat.seat]!,rowP=Math.max(0,Math.min(1,elapsed*1.5-index*.12)),rowY=y+72+index*rowGap,rowX=x+18+(1-rowP)*42,winner=result.winners.some(win=>win.seat===seat.seat),font=Math.min(13,rowGap*.38);mainContext.save();mainContext.globalAlpha=rowP;this.roundRect(rowX,rowY,boxW-36,rowGap-4,8,winner?'rgba(18,247,214,.12)':'rgba(17,32,45,.9)',winner?C.cyan:'rgba(145,182,189,.28)',1);if(winner){mainContext.fillStyle=`rgba(255,200,87,${.2*(.5+.5*Math.sin(performance.now()/130))})`;mainContext.beginPath();mainContext.arc(rowX+boxW-60,rowY+rowGap/2-2,7,0,Math.PI*2);mainContext.fill()}this.text(rowX+10,rowY+6,`${index+1}. ${seat.name}`,font,C.white,800);this.text(rowX+boxW*.34,rowY+6,`本局 ${score.delta>=0?'+':''}${score.delta}`,font,score.delta>=0?C.cyan:C.red,800);const numberP=Math.max(0,Math.min(1,(rowP-.35)/.65)),rolling=Math.round(score.before+(score.total-score.before)*numberP);this.text(rowX+boxW-56,rowY+6,`总分 ${score.before} → ${rolling}`,font,C.gold,900,'right');mainContext.restore()});const footerY=y+72+seats.length*rowGap;if(state.phase==='matchEnd'){const ranking=[...seats].sort((a,b)=>b.score-a.score).map((seat,index)=>`${index+1}.${seat.name} ${seat.score}`).join('   ');this.center(ranking,w,footerY+3,Math.min(12,rowGap*.38),C.muted,700)}if(state.hostId===parti.playerId)this.button(w/2-80,y+boxH-37,160,30,state.phase==='matchEnd'?'新比赛':'下一局',()=>void parti.action(state.phase==='matchEnd'?'restartMatch':'nextRound'))}

  private doChi(){const kinds=this.privateState.chiOptions[0];if(!kinds)return;const ids:string[]=[];for(const kind of kinds){const tile=this.privateState.hand.find(candidate=>candidate.kind===kind&&!ids.includes(candidate.id));if(tile)ids.push(tile.id)}if(ids.length===2)void parti.action('chi',{tileIds:ids})}
  private discard(){if(this.selected)void parti.action('discard',{tileId:this.selected})}
  private config(partial:Record<string,unknown>){if(this.state?.hostId===parti.playerId)void parti.action('configureRules',partial)}
  private drawTile(x:number,y:number,tile:Tile,w:number,h:number,selected:boolean){drawMahjongTile(mainContext,tile.kind,x,y,w,h,{selected})}
  private button(x:number,y:number,w:number,h:number,label:string,onClick:()=>void,disabled=false){this.roundRect(x,y,w,h,10,disabled?'#243744':'#ffc857',disabled?'#647d85':'#fff0a8',2);this.centerAt(x+w/2,y+h/2,label,14,disabled?'#a6b6ba':'#241407',800);if(!disabled)this.hits.push({x,y,w,h,onClick})}
  private panel(x:number,y:number,w:number,h:number,fill:string,stroke:string,alpha=1){mainContext.save();mainContext.globalAlpha=alpha;this.roundRect(x,y,w,h,12,fill,stroke,1.5);mainContext.restore()}
  private roundRect(x:number,y:number,w:number,h:number,r:number,fill:string,stroke:string,lw:number){const c=mainContext;c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill();c.strokeStyle=stroke;c.lineWidth=lw;c.stroke()}
  private sectionLabel(x:number,y:number,value:string){this.text(x,y,value,11,C.muted,800)}
  private text(x:number,y:number,value:string,size:number,color:string,weight:number|string=400,align:CanvasTextAlign='left'){const c=mainContext;c.font=`${weight} ${size}px system-ui,sans-serif`;c.fillStyle=color;c.textAlign=align;c.textBaseline='top';c.fillText(value,x,y)}
  private center(value:string,w:number,y:number,size:number,color:string,weight:number|string=400){this.centerAt(w/2,y,value,size,color,weight)}
  private centerAt(x:number,y:number,value:string,size:number,color:string,weight:number|string=400){const c=mainContext;c.font=`${weight} ${size}px system-ui,sans-serif`;c.fillStyle=color;c.textAlign='center';c.textBaseline='middle';c.fillText(value,x,y)}
  private flashFx(w:number,h:number){if(!this.flash||performance.now()>this.flash.until){this.flash=null;return}const life=(this.flash.until-performance.now())/1200,scale=1+(1-life)*.18;mainContext.save();mainContext.translate(w/2,Math.min(138,h*.2));mainContext.scale(scale,scale);mainContext.shadowBlur=24;mainContext.shadowColor=this.flash.color;this.centerAt(0,0,this.flash.text,Math.min(32,w/13),this.flash.color,900);mainContext.restore()}
  private actionFx(event:ActionFx){const mySeat=this.me()?.seat;if(event.kind==='draw'&&event.actorSeat===mySeat&&!this.pendingDraw){this.pendingDrawEvent=event;this.pendingDrawAt=performance.now();return}const drawn=event.kind==='draw'&&event.actorSeat===mySeat?this.pendingDraw:null;this.enqueueActionFx(event,drawn)}
  private enqueueActionFx(event:ActionFx,drawn:Tile|null){if(drawn)this.pendingDraw=null;const label=formatActionAnnouncement(event);this.announce(label,C.cyan);const important=['deal','win','drawGame'].includes(event.kind),blocksInput=!['draw','scoreChange'].includes(event.kind);this.animations.enqueue({id:event.actionId??`${event.kind}:${event.actorSeat}:${event.occurredAt??performance.now()}`,kind:event.kind,duration:drawn?1350:important?1100:460,blocking:blocksInput,actorSeat:event.actorSeat,sourceSeat:event.sourceSeat,tiles:event.tiles,label:event.label??label,drawnTile:drawn??undefined})}
  private animationFx(w:number,h:number){const fx=this.activeAnimation;if(!fx)return;const p=fx.progress,e=easeOutBack(Math.min(1,p)),ctx=mainContext;ctx.save();if(fx.kind==='deal'){ctx.globalAlpha=Math.sin(Math.PI*p);for(let i=0;i<8;i++){const a=i/8*Math.PI*2,t=Math.min(1,p*1.8-i*.04),x=w/2+Math.cos(a)*w*.3*t,y=h*.46+Math.sin(a)*h*.24*t;this.roundRect(x-15,y-22,30,44,5,'#e8dfc5',C.gold,1)}}else if(fx.kind==='draw'&&fx.drawnTile){const flight=Math.min(1,p/.3),reveal=Math.max(0,Math.min(1,(p-.3)/.34)),insert=Math.max(0,Math.min(1,(p-.64)/.36)),rightX=Math.min(w-46,w*.78),rightY=h-105,targetIndex=this.privateState.hand.findIndex(tile=>tile.id===fx.drawnTile!.id),layout=computeTableLayout(w,h,this.privateState.hand.length).hand,targetX=layout.startX+Math.max(0,targetIndex)*layout.gap+layout.tileWidth/2,targetY=layout.y+layout.tileHeight/2,x=w/2+(rightX-w/2)*easeOutBack(flight)+(targetX-rightX)*easeOutBack(insert),y=h*.46+(rightY-h*.46)*easeOutBack(flight)+(targetY-rightY)*easeOutBack(insert)-Math.sin(Math.PI*flight)*42,flip=Math.abs(Math.cos(Math.PI*reveal));ctx.translate(x,y);if(reveal<.5){ctx.scale(Math.max(.05,flip),1);this.roundRect(-22,-31,44,62,7,'#0e6070',C.gold,2)}else{ctx.scale(Math.max(.05,flip),1);drawMahjongTile(ctx,fx.drawnTile.kind as Tile['kind'],-22,-31,44,62)}if(p>.3&&p<.72){ctx.setTransform(this.ratio,0,0,this.ratio,0,0);ctx.globalAlpha=Math.sin(Math.PI*(p-.3)/.42);this.center(`摸到 ${formatTileName(fx.drawnTile.kind as Tile['kind'])}`,w,h-185,18,C.gold,900)}}else if(['discard','draw','chi','peng','concealedGang','discardGang','addedGang'].includes(fx.kind)){const angle=((fx.actorSeat??0)-(this.me()?.seat??0)+4)%4*Math.PI/2+Math.PI/2,start={x:w/2+Math.cos(angle)*w*.38,y:h*.48+Math.sin(angle)*h*.34},end={x:w/2,y:h*.46};const reverse=fx.kind==='draw',from=reverse?end:start,to=reverse?start:end,x=from.x+(to.x-from.x)*e,y=from.y+(to.y-from.y)*e-Math.sin(Math.PI*p)*50;ctx.translate(x,y);ctx.rotate((1-p)*.22);const tile=fx.tiles?.[0];if(tile)drawMahjongTile(ctx,tile as Tile['kind'],-18,-25,36,50);else this.roundRect(-18,-25,36,50,6,'#efe7cf',C.cyan,1)}else{ctx.globalAlpha=Math.sin(Math.PI*Math.min(1,p));ctx.fillStyle=fx.kind==='win'?'rgba(255,200,87,.14)':'rgba(18,247,214,.1)';ctx.fillRect(0,0,w,h);ctx.translate(w/2,h*.35);ctx.scale(.7+e*.3,.7+e*.3);ctx.shadowBlur=28;ctx.shadowColor=fx.kind==='win'?C.gold:C.cyan;this.centerAt(0,0,fx.label??'牌局结算',Math.min(38,w/11),fx.kind==='win'?C.gold:C.cyan,900)}ctx.restore()}
  private announce(text:string,color:string){if(text&&this.activity.at(-1)!==text)this.activity=[...this.activity.slice(-2),text];this.flash={text,color,until:performance.now()+1200}}
  private me(){return this.state?.seats.find(seat=>seat?.id===parti.playerId)??null}
  private visibility=()=>{if(document.hidden){this.animations.skipToLatest();this.pendingDraw=null;this.pendingDrawEvent=null;this.presentedHand=[...this.privateState.hand]}}
  private destroy=()=>{for(const dispose of this.disposers.splice(0))dispose();document.removeEventListener('visibilitychange',this.visibility)}
}
function inside(hit:Rect,x:number,y:number){return x>=hit.x&&x<=hit.x+hit.w&&y>=hit.y&&y<=hit.y+hit.h}
function clip(value:string,width:number){const max=Math.max(8,Math.floor(width/13));return value.length>max?`${value.slice(0,max-1)}…`:value}
