import { mainCanvas, mainContext, mousePosScreen, mouseWasPressed } from 'littlejsengine';
import type { GameState, PrivateState, SeatState } from '../game/types';
import { formatActionAnnouncement, formatTileName, type ActionFx } from '../game/presentation';
import type { Tile } from '../worker/types';
import { computeLobbyLayout, computeTableLayout, type Rect } from './MahjongLayout';
import { drawMahjongTile } from './MahjongTileRenderer';

type Hit = Rect & { onClick:()=>void };
type Flash = { text:string; color:string; until:number };
const C={bg:'#050914',table:'#092c38',cyan:'#12f7d6',gold:'#ffc857',red:'#ff355d',white:'#fff8df',muted:'#91b6bd',panel:'#0d1c2d'};
const DIRECTIONS=['南 · 自家','西 · 右家','北 · 对家','东 · 左家'] as const;

export class MahjongScene {
  private state:GameState|null=null;
  private privateState:PrivateState={hand:[],canWin:false,concealedGangKinds:[],addedGangKinds:[],reactionOptions:[],chiOptions:[]};
  private selected:string|null=null; private hits:Hit[]=[]; private ratio=1; private disposers:Array<()=>void>=[];
  private flash:Flash|null=null; private lastPhase=''; private activity:string[]=[];
  init(){this.disposers.push(
    parti.onState(value=>this.receive(value as GameState)),
    parti.onEvent('mahjong:private-state',value=>{this.privateState=value as PrivateState;if(this.selected&&!this.privateState.hand.some(t=>t.id===this.selected))this.selected=null}),
    parti.onEvent('mahjong:notice',value=>this.announce((value as {message:string}).message,C.gold)),
    parti.onEvent('mahjong:action-fx',value=>this.announce(formatActionAnnouncement(value as ActionFx),C.cyan)),
    parti.onEvent('mahjong:settlement',value=>this.announce((value as {message:string}).message,C.gold)),
  );window.addEventListener('pagehide',this.destroy,{once:true});parti.ready();void parti.action('syncPrivate')}
  private receive(state:GameState){if(this.lastPhase&&state.phase!==this.lastPhase&&(state.phase==='settlement'||state.phase==='matchEnd'))this.announce(state.message,C.gold);this.lastPhase=state.phase;this.state=state}
  update(){this.ratio=mainCanvas.width/Math.max(1,mainCanvas.clientWidth);const x=mousePosScreen.x/this.ratio,y=mousePosScreen.y/this.ratio;const hit=[...this.hits].reverse().find(item=>inside(item,x,y));mainCanvas.style.cursor=hit?'pointer':'';if(hit&&mouseWasPressed(0))hit.onClick()}
  render(){const w=mainCanvas.width/this.ratio,h=mainCanvas.height/this.ratio,ctx=mainContext;ctx.save();ctx.setTransform(this.ratio,0,0,this.ratio,0,0);ctx.clearRect(0,0,w,h);this.hits=[];this.background(w,h);if(!this.state){this.center('正在连接牌桌…',w,h/2,22,C.white);ctx.restore();return}if(this.state.phase==='lobby')this.lobby(w,h);else this.table(w,h);this.flashFx(w,h);ctx.restore()}
  private background(w:number,h:number){const ctx=mainContext;const g=ctx.createRadialGradient(w/2,h*.48,20,w/2,h*.48,Math.max(w,h)*.75);g.addColorStop(0,'#103b4b');g.addColorStop(.55,C.table);g.addColorStop(1,C.bg);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(18,247,214,.1)';for(let x=-h;x<w+h;x+=54){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-h,h);ctx.stroke()}}

  private lobby(w:number,h:number){const state=this.state!,me=this.me(),layout=computeLobbyLayout(w,h),compact=h<560;this.text(layout.header.x,layout.header.y,'超级麻将',compact?23:28,C.white,900);this.text(layout.header.x,layout.header.y+(compact?29:38),'红中万能 · 四方雀战 · 1–4 位真人',compact?12:14,C.gold,700);this.sectionLabel(layout.seatsArea.x,layout.seatsArea.y-16,'入座与准备');
    const seats=Array.from({length:4},(_,index)=>state.seats[index]);layout.seatCards.forEach((rect,index)=>this.lobbySeat(rect,seats[index],index));this.sectionLabel(layout.rulesArea.x,layout.rulesArea.y-18,state.hostId===parti.playerId?'玩法设置 · 点击切换':'玩法设置 · 房主配置');
    const rules=state.rules;const rows:Array<[string,string,()=>void]>=[['胡牌',rules.winSource==='both'?'自摸 + 点炮':rules.winSource==='selfDrawOnly'?'仅自摸':'仅点炮',()=>this.config({winSource:rules.winSource==='both'?'selfDrawOnly':rules.winSource==='selfDrawOnly'?'discardOnly':'both'})],['吃牌',rules.allowChi?'允许':'关闭',()=>this.config({allowChi:!rules.allowChi})],['多响',rules.allowMultiWin?'一炮多响':'最近截胡',()=>this.config({allowMultiWin:!rules.allowMultiWin})],['抢杠胡',rules.allowRobGang?'允许':'关闭',()=>this.config({allowRobGang:!rules.allowRobGang})],['海底',rules.allowLastTile?'加倍':'关闭',()=>this.config({allowLastTile:!rules.allowLastTile})],['局数',`${rules.rounds} 局`,()=>this.config({rounds:rules.rounds===1?4:rules.rounds===4?8:1})],['底分',String(rules.baseScore),()=>this.config({baseScore:rules.baseScore>=10?1:rules.baseScore+1})],['封顶',`${rules.maxFan} 番`,()=>this.config({maxFan:rules.maxFan>=16?4:rules.maxFan+1})]];
    layout.ruleCards.forEach((rect,index)=>{const row=rows[index]!;this.ruleCard(rect,row[0],row[1],row[2],state.hostId===parti.playerId)});this.actionBar(layout.actionBar,me,state)}
  private lobbySeat(rect:Rect,seat:SeatState|null,index:number){this.panel(rect.x,rect.y,rect.w,rect.h,seat?'rgba(8,31,44,.94)':'rgba(8,20,31,.72)',seat?.ready?C.gold:'rgba(18,247,214,.45)',.96);this.text(rect.x+10,rect.y+7,`${index+1} 号位`,11,C.muted,700);this.text(rect.x+10,rect.y+23,seat?.name??'等待加入',Math.min(14,rect.h*.3),C.white,800);if(seat)this.text(rect.x+rect.w-10,rect.y+10,seat.bot?'机器人':seat.ready?'已准备':'未准备',11,seat.ready?C.gold:C.muted,700,'right')}
  private ruleCard(rect:Rect,label:string,value:string,onClick:()=>void,editable:boolean){this.panel(rect.x,rect.y,rect.w,rect.h,editable?'rgba(13,34,48,.96)':'rgba(15,29,40,.92)',editable?C.cyan:'rgba(145,182,189,.38)',.96);this.text(rect.x+10,rect.y+8,label,11,C.muted,700);this.text(rect.x+10,rect.y+Math.max(22,rect.h*.45),value,Math.min(15,rect.h*.25),C.white,800);if(editable){this.text(rect.x+rect.w-12,rect.y+rect.h/2-8,'›',18,C.gold,900,'right');this.hits.push({...rect,onClick})}}
  private actionBar(rect:Rect,me:SeatState|null,state:GameState){this.panel(rect.x,rect.y,rect.w,rect.h,'rgba(4,14,25,.96)',C.gold,.98);const seats=state.seats.filter(Boolean) as SeatState[];const bw=Math.min(154,(rect.w-34)/2),bh=Math.min(46,rect.h-14),y=rect.y+(rect.h-bh)/2;if(me)this.button(rect.x+rect.w/2-bw-6,y,bw,bh,me.ready?'取消准备':'准备',()=>void parti.action('setReady',{ready:!me.ready}));if(state.hostId===parti.playerId)this.button(rect.x+rect.w/2+6,y,bw,bh,'开始牌局',()=>void parti.action('startMatch'),!seats.filter(s=>!s.bot).every(s=>s.ready))}

  private table(w:number,h:number){const state=this.state!,me=this.me(),mySeat=me?.seat??0,layout=computeTableLayout(w,h,this.privateState.hand.length);this.tableHud(layout.hud,layout.activityLines);this.panel(layout.table.x,layout.table.y,layout.table.w,layout.table.h,'rgba(4,28,38,.44)','rgba(18,247,214,.2)',.9);
    for(const seat of state.seats.filter(Boolean) as SeatState[]){const visual=(seat.seat-mySeat+4)%4;this.playerBadge(seat,layout.seats[visual]!,visual);this.discardRiver(seat,layout.rivers[visual]!,visual,state.lastDiscard?.seat===seat.seat);this.drawMelds(seat,layout.melds[visual]!,visual)}
    this.centerPanel(layout.center,mySeat);this.actions(layout.actions);this.hand(layout.hand);if(state.phase==='settlement'||state.phase==='matchEnd')this.settlement(w,h)}
  private tableHud(rect:Rect,lines:1|3){const state=this.state!;mainContext.fillStyle='rgba(3,10,20,.82)';mainContext.fillRect(rect.x,rect.y,rect.w,rect.h);this.text(14,10,'超级麻将',22,C.white,900);this.text(14,38,`第 ${Math.min(state.roundIndex+1,state.rules.rounds)}/${state.rules.rounds} 局  ·  庄 ${state.dealerSeat+1} 号  ·  牌墙 ${state.wallCount}`,13,C.gold,700);const available=Math.max(150,rect.w-330);this.activity.slice(-lines).reverse().forEach((line,index)=>this.text(190,10+index*21,clip(line,available),12,index?C.muted:C.cyan,700));this.text(rect.w-106,rect.h-19,state.phase==='reaction'?'响应中':state.message,11,C.muted,600,'right')}
  private playerBadge(seat:SeatState,rect:Rect,visual:number){const active=this.state!.currentSeat===seat.seat;this.panel(rect.x,rect.y,rect.w,rect.h,'rgba(4,15,27,.96)',active?C.gold:C.cyan,.98);if(visual%2){mainContext.save();mainContext.translate(rect.x+rect.w/2,rect.y+rect.h/2);mainContext.rotate(visual===1?Math.PI/2:-Math.PI/2);this.centerAt(0,-9,`${seat.dealer?'庄 · ':''}${seat.name}`,13,C.white,800);this.centerAt(0,11,`${seat.score>=0?'+':''}${seat.score} · ${seat.handCount}张`,11,active?C.gold:C.cyan,700);mainContext.restore()}else{this.centerAt(rect.x+rect.w/2,rect.y+rect.h*.36,`${seat.dealer?'庄 · ':''}${seat.name}`,13,C.white,800);this.centerAt(rect.x+rect.w/2,rect.y+rect.h*.7,`${seat.score>=0?'+':''}${seat.score} · ${seat.handCount}张`,11,active?C.gold:C.cyan,700)}}
  private discardRiver(seat:SeatState,rect:Rect,visual:number,isLastSource:boolean){this.panel(rect.x,rect.y,rect.w,rect.h,isLastSource?'rgba(255,200,87,.09)':'rgba(3,15,25,.38)',isLastSource?'rgba(255,200,87,.5)':'rgba(145,182,189,.22)',.9);this.text(rect.x+6,rect.y+4,DIRECTIONS[visual],9,isLastSource?C.gold:C.muted,700);const cards=seat.discards.slice(-18),side=visual%2===1,cols=side?3:6;const gap=3,top=16,tileW=Math.max(18,Math.min(side?28:34,(rect.w-12-gap*(cols-1))/cols)),tileH=tileW*1.34;cards.forEach((tile,index)=>{const x=rect.x+6+(index%cols)*(tileW+gap),y=rect.y+top+Math.floor(index/cols)*(tileH*.72+gap);if(y+tileH<=rect.y+rect.h+2)this.drawTile(x,y,tile,tileW,tileH,false)})}
  private drawMelds(seat:SeatState,rect:Rect,visual:number){const tiles=seat.melds.flatMap(m=>m.tiles).slice(0,16);if(!tiles.length)return;const side=visual%2===1,tileW=side?22:25,tileH=tileW*1.34;tiles.forEach((tile,index)=>{const x=side?rect.x+(index%2)*(tileW*.72):rect.x+index*(tileW*.72),y=side?rect.y+Math.floor(index/2)*(tileH*.72):rect.y+(rect.h-tileH)/2;this.drawTile(x,y,tile,tileW,tileH,false)})}
  private centerPanel(rect:Rect,mySeat:number){const state=this.state!,active=state.currentSeat===mySeat;this.panel(rect.x,rect.y,rect.w,rect.h,'rgba(3,13,24,.92)',active?C.gold:C.cyan,.96);const headline=state.phase==='reaction'?'等待响应':active?'轮到你':'牌局进行中';this.centerAt(rect.x+rect.w/2,rect.y+24,headline,17,active?C.gold:C.white,900);if(state.lastDiscard){const player=state.seats[state.lastDiscard.seat]?.name??`${state.lastDiscard.seat+1}号位`;this.centerAt(rect.x+rect.w/2,rect.y+48,`${player} 出了${formatTileName(state.lastDiscard.tile.kind)}`,11,C.muted,700);const tw=Math.min(42,rect.w*.2),th=tw*1.34;this.drawTile(rect.x+(rect.w-tw)/2,rect.y+58,state.lastDiscard.tile,tw,th,false)}else this.centerAt(rect.x+rect.w/2,rect.y+rect.h*.62,`余 ${state.wallCount} 张`,13,C.muted,700)}
  private hand(layout:ReturnType<typeof computeTableLayout>['hand']){const hand=this.privateState.hand;if(!hand.length)return;this.panel(layout.rect.x,layout.rect.y,layout.rect.w,layout.rect.h,'rgba(3,12,23,.9)','rgba(255,200,87,.35)',.96);hand.forEach((tile,index)=>{const selected=tile.id===this.selected,x=layout.startX+index*layout.gap,ty=layout.y-(selected?Math.min(16,layout.rect.y-layout.y+20):0);this.drawTile(x,ty,tile,layout.tileWidth,layout.tileHeight,selected);this.hits.push({x,y:ty,w:index===hand.length-1?layout.tileWidth:layout.gap,h:layout.tileHeight,onClick:()=>{this.selected=this.selected===tile.id?null:tile.id}})})}
  private actions(rect:Rect){const options=this.privateState.reactionOptions;let actions:Array<[string,()=>void,boolean]>=[];if(options.length){if(options.includes('win'))actions.push(['胡',()=>void parti.action('declareWin'),false]);if(options.includes('gang'))actions.push(['杠',()=>void parti.action('gang'),false]);if(options.includes('peng'))actions.push(['碰',()=>void parti.action('peng'),false]);if(options.includes('chi'))actions.push(['吃',()=>this.doChi(),false]);actions.push(['过',()=>void parti.action('passReaction'),false])}else if(this.state!.phase==='playing'&&this.me()?.seat===this.state!.currentSeat){if(this.privateState.canWin)actions.push(['自摸',()=>void parti.action('declareWin'),false]);const gang=this.privateState.concealedGangKinds[0]??this.privateState.addedGangKinds[0];if(gang)actions.push(['杠',()=>void parti.action('gang',{kind:gang}),false]);actions.push(['出牌',()=>this.discard(),!this.selected])}if(!actions.length)return;const gap=8,bw=Math.min(88,(rect.w-gap*(actions.length-1))/actions.length),total=actions.length*bw+(actions.length-1)*gap,start=rect.x+(rect.w-total)/2;actions.forEach((a,index)=>this.button(start+index*(bw+gap),rect.y+(rect.h-42)/2,bw,42,a[0],a[1],a[2]))}
  private settlement(w:number,h:number){const result=this.state!.result;if(!result)return;const boxW=Math.min(520,w-28),boxH=Math.min(330,h-100),x=(w-boxW)/2,y=(h-boxH)/2;this.panel(x,y,boxW,boxH,'rgba(5,9,20,.98)',C.gold,.99);this.center(result.draw?'流 局':'胡 牌 结 算',w,y+38,28,C.gold,900);this.center(result.message,w,y+76,15,C.white,700);let rowY=y+108;for(const seat of this.state!.seats.filter(Boolean) as SeatState[]){const delta=result.deltas[seat.seat]??0;this.text(x+28,rowY,seat.name,14,C.white,700);this.text(x+boxW-28,rowY,`${delta>=0?'+':''}${delta}`,17,delta>=0?C.cyan:C.red,900,'right');rowY+=30}if(this.state!.hostId===parti.playerId)this.button(w/2-80,y+boxH-56,160,42,this.state!.phase==='matchEnd'?'新比赛':'下一局',()=>void parti.action(this.state!.phase==='matchEnd'?'restartMatch':'nextRound'))}

  private doChi(){const kinds=this.privateState.chiOptions[0];if(!kinds)return;const ids:string[]=[];for(const kind of kinds){const tile=this.privateState.hand.find(candidate=>candidate.kind===kind&&!ids.includes(candidate.id));if(tile)ids.push(tile.id)}if(ids.length===2)void parti.action('chi',{tileIds:ids})}
  private discard(){if(this.selected)void parti.action('discard',{tileId:this.selected})}
  private config(partial:Record<string,unknown>){if(this.state?.hostId===parti.playerId)void parti.action('configureRules',partial)}
  private drawTile(x:number,y:number,tile:Tile,w:number,h:number,selected:boolean){drawMahjongTile(mainContext,tile.kind,x,y,w,h,{selected})}
  private button(x:number,y:number,w:number,h:number,label:string,onClick:()=>void,disabled=false){this.roundRect(x,y,w,h,10,disabled?'#243744':'#ffc857',disabled?'#647d85':'#fff0a8',2);this.centerAt(x+w/2,y+h/2,label,14,disabled?'#a6b6ba':'#241407',800);if(!disabled)this.hits.push({x,y,w,h,onClick})}
  private panel(x:number,y:number,w:number,h:number,fill:string,stroke:string,alpha=1){mainContext.save();mainContext.globalAlpha=alpha;this.roundRect(x,y,w,h,12,fill,stroke,1.5);mainContext.restore()}
  private roundRect(x:number,y:number,w:number,h:number,r:number,fill:string,stroke:string,lw:number){const c=mainContext;c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill();c.strokeStyle=stroke;c.lineWidth=lw;c.stroke()}
  private sectionLabel(x:number,y:number,value:string){this.text(x,y,value,11,C.muted,800)}
  private text(x:number,y:number,value:string,size:number,color:string,weight:number|string=400,align:CanvasTextAlign='left'){const c=mainContext;c.font=`${weight} ${size}px system-ui,sans-serif`;c.fillStyle=color;c.textAlign=align;c.textBaseline='top';c.fillText(value,x,y)}
  private center(value:string,w:number,y:number,size:number,color:string,weight:number|string=400){this.centerAt(w/2,y,value,size,color,weight)}
  private centerAt(x:number,y:number,value:string,size:number,color:string,weight:number|string=400){const c=mainContext;c.font=`${weight} ${size}px system-ui,sans-serif`;c.fillStyle=color;c.textAlign='center';c.textBaseline='middle';c.fillText(value,x,y)}
  private flashFx(w:number,h:number){if(!this.flash||performance.now()>this.flash.until){this.flash=null;return}const life=(this.flash.until-performance.now())/1200,scale=1+(1-life)*.18;mainContext.save();mainContext.translate(w/2,Math.min(138,h*.2));mainContext.scale(scale,scale);mainContext.shadowBlur=24;mainContext.shadowColor=this.flash.color;this.centerAt(0,0,this.flash.text,Math.min(32,w/13),this.flash.color,900);mainContext.restore()}
  private announce(text:string,color:string){if(text&&this.activity.at(-1)!==text)this.activity=[...this.activity.slice(-2),text];this.flash={text,color,until:performance.now()+1200}}
  private me(){return this.state?.seats.find(seat=>seat?.id===parti.playerId)??null}
  private destroy=()=>{for(const dispose of this.disposers.splice(0))dispose()}
}
function inside(hit:Rect,x:number,y:number){return x>=hit.x&&x<=hit.x+hit.w&&y>=hit.y&&y<=hit.y+hit.h}
function clip(value:string,width:number){const max=Math.max(8,Math.floor(width/13));return value.length>max?`${value.slice(0,max-1)}…`:value}
