import { mainCanvas, mainContext } from 'littlejsengine';
import type { Element, EntityState, GameEvent, GameState, PlayerState, SpellSpec, Vec2 } from '../game/contracts';
import { positionAt } from '../game/rules/entities';
import { resolveSpell } from '../game/rules/spells';
import { collisionCandidates } from '../runtime/collision';
import { createEndwellFlow, type EndwellFlow } from '../runtime/flow';
import { computeHudLayout, contains, hudBlocksWorld, type HudLayout, type Rect } from '../ui/hud';

const WORLD = { width: 960, height: 600 }, ELEMENTS: Element[] = ['rock', 'fire', 'ice', 'life', 'lightning', 'water', 'shield'];
const COLORS: Record<Element, string> = { rock: '#aa8b68', fire: '#ff5c45', ice: '#77e6ff', life: '#79df78', lightning: '#c596ff', water: '#469cff', shield: '#ffd952' };
const LABELS: Record<Element, string> = { rock: '岩', fire: '火', ice: '冰', life: '命', lightning: '雷', water: '水', shield: '盾' };
type AimState = { pointerId: number; target: Vec2; spell: SpellSpec; elements: Element[]; castId: string | null };

export class EndwellScene {
  private flow: EndwellFlow | null = null; private state: GameState | null = null; private selected: Element[] = []; private local: Vec2 = { x: 260, y: 360 }; private localEpoch = -1; private aim: Vec2 = { x: 1, y: 0 }; private moveTarget: Vec2 | null = null; private aiming: AimState | null = null; private sequence = 0; private poseSequence = 0; private aimSequence = 0; private last = performance.now(); private poseAt = 0; private hitTick = 0; private hitKeys = new Set<string>(); private projectilePrevious = new Map<string, Vec2>(); private notice = ''; private noticeUntil = 0; private pixelRatio = 1; private hud: HudLayout = computeHudLayout(1280, 720); private lobbyButton: Rect | null = null;
  init() { this.flow = createEndwellFlow(parti, { state: (state) => this.receive(state), event: (event) => this.event(event) }); mainCanvas.addEventListener('pointerdown', this.pointerDown); mainCanvas.addEventListener('pointermove', this.pointerMove); mainCanvas.addEventListener('pointerup', this.pointerUp); mainCanvas.addEventListener('pointercancel', this.pointerCancel); window.addEventListener('keydown', this.keyDown); window.addEventListener('pagehide', this.destroy, { once: true }); parti.ready(); }
  update() { const now = performance.now(), dt = Math.min(.04, Math.max(.001, (now - this.last) / 1000)); this.last = now; this.pixelRatio = mainCanvas.width / Math.max(1, mainCanvas.clientWidth); if (!this.flow || this.state?.phase !== 'running') return; if (this.moveTarget && !this.aiming) { const dx = this.moveTarget.x - this.local.x, dy = this.moveTarget.y - this.local.y, distance = Math.hypot(dx, dy), step = 220 * dt; if (distance <= step || distance < 3) { this.local = { ...this.moveTarget }; this.moveTarget = null; } else this.local = { x: this.local.x + dx / distance * step, y: this.local.y + dy / distance * step }; }
    if (now >= this.poseAt) { this.poseAt = now + 64; this.flow.pose({ sequence: ++this.poseSequence, sentAt: Date.now(), position: this.local, aim: this.aim }); if (this.aiming?.castId) this.flow.aim({ sequence: ++this.aimSequence, aim: this.aim }); }
    this.flow.game.update(dt); this.collisions(Date.now()); }
  render() { const c = mainContext, width = mainCanvas.width / this.pixelRatio, height = mainCanvas.height / this.pixelRatio; this.hud = computeHudLayout(width, height); c.save(); c.setTransform(this.pixelRatio, 0, 0, this.pixelRatio, 0, 0); c.fillStyle = '#090a13'; c.fillRect(0, 0, width, height); const view = this.view(width, height); c.save(); c.translate(view.ox, view.oy); c.scale(view.scale, view.scale); this.drawArena(c); c.restore(); if (this.state?.environment.global?.kind === 'rain') this.drawRain(c, width, height); this.drawHud(c, width); if (!this.state) this.overlay(c, width, height, '连接无底之尽…', ''); else if (this.state.phase === 'lobby') this.lobby(c, width, height); else if (this.state.phase === 'gameover') this.overlay(c, width, height, '试炼结束', ''); if (performance.now() < this.noticeUntil) { c.fillStyle = 'rgba(54,24,40,.9)'; c.fillRect(width / 2 - 170, this.hud.message.y, 340, this.hud.message.h); this.text(c, this.notice, width / 2, this.hud.message.y + this.hud.message.h / 2, 13, '#fff', 'center'); } c.restore(); }
  private drawArena(c: CanvasRenderingContext2D) { c.fillStyle = '#111528'; c.fillRect(0, 0, WORLD.width, WORLD.height); c.strokeStyle = '#252c47'; c.lineWidth = 2; for (let x = 0; x <= WORLD.width; x += 60) { c.beginPath(); c.moveTo(x, 0); c.lineTo(x, WORLD.height); c.stroke(); } for (let y = 0; y <= WORLD.height; y += 60) { c.beginPath(); c.moveTo(0, y); c.lineTo(WORLD.width, y); c.stroke(); }
    if (!this.state || !this.flow) return; for (const id of this.flow.game.world.entitiesWith('Transform')) { const pos = this.flow.game.world.getComponent<Vec2>(id, 'Transform'), p = this.flow.game.world.getComponent<PlayerState>(id, 'PlayerState'), e = this.flow.game.world.getComponent<EntityState>(id, 'EntityState'); if (!pos) continue; if (p) this.player(c, p.id === this.flow.game.playerId ? this.local : pos, p); else if (e) this.entity(c, e, positionAt(e, Date.now())); }
    if (this.moveTarget) { c.strokeStyle = '#d8cb91'; c.setLineDash([8, 8]); c.beginPath(); c.moveTo(this.local.x, this.local.y); c.lineTo(this.moveTarget.x, this.moveTarget.y); c.stroke(); c.setLineDash([]); c.beginPath(); c.arc(this.moveTarget.x, this.moveTarget.y, 14, 0, Math.PI * 2); c.stroke(); }
    if (this.aiming) this.drawAim(c, this.aiming); }
  private drawAim(c: CanvasRenderingContext2D, state: AimState) { const color = COLORS[state.spell.elements[0] ?? 'rock'], angle = Math.atan2(this.aim.y, this.aim.x); c.strokeStyle = color; c.fillStyle = `${color}35`; c.lineWidth = 3; if (state.spell.delivery === 'spray') { const half = (state.spell.coneAngle ?? Math.PI / 2) / 2; c.beginPath(); c.moveTo(this.local.x, this.local.y); c.arc(this.local.x, this.local.y, state.spell.range, angle - half, angle + half); c.closePath(); c.fill(); c.stroke(); } else if (state.spell.delivery === 'beam') { c.lineWidth = Math.max(3, (state.spell.beam?.width ?? 10) * 2); c.beginPath(); c.moveTo(this.local.x, this.local.y); c.lineTo(this.local.x + this.aim.x * state.spell.range, this.local.y + this.aim.y * state.spell.range); c.stroke(); } else if (state.spell.delivery === 'shield' || state.spell.delivery === 'environment') { c.beginPath(); c.arc(this.local.x, this.local.y, 38, 0, Math.PI * 2); c.stroke(); } else if (state.spell.delivery === 'area' || state.spell.delivery === 'summon' && !state.spell.summon?.archetype.endsWith('wall')) { c.beginPath(); c.arc(state.target.x, state.target.y, state.spell.radius, 0, Math.PI * 2); c.fill(); c.stroke(); } else { c.beginPath(); c.moveTo(this.local.x, this.local.y); c.lineTo(state.target.x, state.target.y); c.stroke(); if (state.spell.delivery === 'summon') c.strokeRect(state.target.x - 18, state.target.y - 70, 36, 140); } }
  private player(c: CanvasRenderingContext2D, pos: Vec2, p: PlayerState) { c.fillStyle = p.id === this.flow?.game.playerId ? '#f5eecb' : '#75a7ff'; c.beginPath(); c.arc(pos.x, pos.y, 24, 0, Math.PI * 2); c.fill(); if (p.shields.length) { c.strokeStyle = '#ffd952'; c.lineWidth = 4; c.beginPath(); c.arc(pos.x, pos.y, 31, 0, Math.PI * 2); c.stroke(); } c.fillStyle = '#16182b'; c.fillRect(pos.x - 27, pos.y - 38, 54, 6); c.fillStyle = '#6ee7a8'; c.fillRect(pos.x - 27, pos.y - 38, 54 * p.health.current / p.health.max, 6); this.text(c, p.name, pos.x, pos.y - 50, 12, '#fff', 'center'); }
  private entity(c: CanvasRenderingContext2D, e: EntityState, pos: Vec2) { const element = e.source?.spell.elements.find((value) => value !== 'rock' && value !== 'shield' && value !== 'life') ?? e.source?.spell.elements[0] ?? 'rock', color = COLORS[element]; if (e.kind === 'projectile') { c.fillStyle = color; c.beginPath(); c.arc(pos.x, pos.y, e.radius, 0, Math.PI * 2); c.fill(); c.strokeStyle = `${color}88`; c.lineWidth = 5; c.beginPath(); c.moveTo(pos.x - (e.velocity?.x ?? 0) * .05, pos.y - (e.velocity?.y ?? 0) * .05); c.lineTo(pos.x, pos.y); c.stroke(); } else if (e.source?.spell.delivery === 'spray') { const direction = e.direction ?? { x: 1, y: 0 }, angle = Math.atan2(direction.y, direction.x), half = (e.source.spell.coneAngle ?? Math.PI / 2) / 2; c.fillStyle = `${color}55`; c.beginPath(); c.moveTo(e.position.x, e.position.y); c.arc(e.position.x, e.position.y, e.source.spell.range, angle - half, angle + half); c.closePath(); c.fill(); } else if (e.source?.spell.delivery === 'beam') { const direction = e.direction ?? { x: 1, y: 0 }, hit = this.state ? collisionCandidates(this.state, e, Date.now())[0] : undefined, end = hit?.target.position ?? { x: e.position.x + direction.x * e.source.spell.range, y: e.position.y + direction.y * e.source.spell.range }; c.strokeStyle = color; c.lineWidth = Math.max(5, (e.source.spell.beam?.width ?? 10) * 2); c.beginPath(); c.moveTo(e.position.x, e.position.y); c.lineTo(end.x, end.y); c.stroke(); } else if (e.kind === 'warning') { c.strokeStyle = '#ffcc58'; c.lineWidth = 5; c.beginPath(); c.arc(pos.x, pos.y, e.radius, 0, Math.PI * 2); c.stroke(); } else if (e.kind === 'area') { c.fillStyle = '#ff6a3d88'; c.beginPath(); c.arc(pos.x, pos.y, e.radius, 0, Math.PI * 2); c.fill(); } else if (e.kind === 'field') { c.fillStyle = `${color}45`; c.beginPath(); c.arc(e.position.x, e.position.y, e.radius, 0, Math.PI * 2); c.fill(); } else if (e.kind === 'wall') { c.fillStyle = e.archetype === 'ice-wall' ? '#77e6ff' : '#796a61'; c.fillRect(pos.x - 18, pos.y - 70, 36, 140); } else { c.fillStyle = '#d84e69'; c.fillRect(pos.x - e.radius, pos.y - e.radius, e.radius * 2, e.radius * 2); } if (e.health.max > 1) { c.fillStyle = '#301b2d'; c.fillRect(pos.x - 34, pos.y - e.radius - 15, 68, 6); c.fillStyle = '#f06a7e'; c.fillRect(pos.x - 34, pos.y - e.radius - 15, 68 * e.health.current / e.health.max, 6); } }
  private drawRain(c: CanvasRenderingContext2D, width: number, height: number) { c.fillStyle = 'rgba(50,120,180,.16)'; c.fillRect(0, 0, width, height); c.strokeStyle = 'rgba(120,200,255,.55)'; c.lineWidth = 2; const offset = performance.now() / 8 % 36; for (let x = -height; x < width + height; x += 36) { c.beginPath(); c.moveTo(x + offset, 0); c.lineTo(x - height + offset, height); c.stroke(); } }
  private drawHud(c: CanvasRenderingContext2D, width: number) { if (this.state?.phase !== 'running') return; const { status, elementPanel, elementCenters, compact } = this.hud, me = this.flow && this.state.players[this.flow.game.playerId]; c.fillStyle = 'rgba(18,14,27,.8)'; c.fillRect(status.x, status.y, status.w, status.h); this.text(c, `HP ${Math.round(me?.health.current ?? 0)}`, status.x + 10, status.y + 18, 12, '#fff'); c.fillStyle = '#25101a'; c.fillRect(status.x + 10, status.y + 28, status.w - 20, 8); c.fillStyle = '#62df7c'; c.fillRect(status.x + 10, status.y + 28, (status.w - 20) * (me?.health.current ?? 0) / Math.max(1, me?.health.max ?? 1), 8); c.fillStyle = 'rgba(18,14,27,.78)'; c.fillRect(elementPanel.x, elementPanel.y, elementPanel.w, elementPanel.h); const spell = this.selected.length ? resolveSpell(this.selected) : null, statusText = this.aiming ? this.aiming.spell.channelled ? '按住持续施法 · 抬起结束' : '拖动瞄准 · 抬起施法' : spell ? spell.name : '点击场地移动 · 选择元素后按住场地施法'; this.text(c, `${statusText}${this.selected.length ? ` · ${this.selected.map((e) => LABELS[e]).join('+')}` : ''}`, width / 2, elementPanel.y + 17, compact ? 10 : 12, '#fff', 'center'); if (this.selected.length && !this.aiming) { const clear = this.clearButton(); c.fillStyle = '#493541'; c.fillRect(clear.x, clear.y, clear.w, clear.h); this.text(c, '清空', clear.x + clear.w / 2, clear.y + clear.h / 2, 9, '#fff', 'center'); } for (let i = 0; i < elementCenters.length; i++) { const button = elementCenters[i]!, element = ELEMENTS[i]!, selectedCount = this.selected.filter((value) => value === element).length; c.fillStyle = COLORS[element]; c.beginPath(); c.arc(button.x, button.y, button.r - 3, 0, Math.PI * 2); c.fill(); c.strokeStyle = selectedCount ? '#fff' : '#e8ddcb'; c.lineWidth = selectedCount ? 4 : 2; c.stroke(); this.text(c, LABELS[element], button.x, button.y + 4, compact ? 15 : 18, '#17111f', 'center'); if (selectedCount) this.text(c, String(selectedCount), button.x + button.r - 8, button.y - button.r + 12, 10, '#fff', 'center'); } }
  private lobby(c: CanvasRenderingContext2D, width: number, height: number) { this.overlay(c, width, height, 'ENDWELL', '触碰元素，点击场地'); this.lobbyButton = null; if (this.state?.hostId === parti.playerId) { const rect = { x: width / 2 - 100, y: height / 2 + 48, w: 200, h: 52 }; this.lobbyButton = rect; c.fillStyle = '#e7d89d'; c.fillRect(rect.x, rect.y, rect.w, rect.h); this.text(c, '开始试炼', width / 2, rect.y + rect.h / 2, 17, '#171522', 'center'); } }
  private overlay(c: CanvasRenderingContext2D, width: number, height: number, title: string, sub: string) { c.fillStyle = 'rgba(6,7,15,.82)'; c.fillRect(0, 0, width, height); this.text(c, title, width / 2, height / 2 - 34, 32, '#f4e9c6', 'center'); this.text(c, sub, width / 2, height / 2 + 6, 15, '#aeb4d1', 'center'); }
  private collisions(now: number) { if (!this.state || !this.flow) return; const me = this.flow.game.playerId, alive = new Set<string>(); for (const source of Object.values(this.state.entities)) { if (source.ownerId !== me || !source.source) continue; alive.add(source.id); const current = positionAt(source, now), previous = this.projectilePrevious.get(source.id) ?? current, tick = source.source.tickMs > 0 ? Math.floor(now / source.source.tickMs) : 0, candidates = collisionCandidates(this.state, source, now, previous); for (const candidate of candidates) { const key = `${source.id}:${candidate.target.id}:${tick}`; if (this.hitKeys.has(key)) continue; this.hitKeys.add(key); this.flow.hit({ hitId: `${source.id}:hit:${candidate.target.id}:${tick}`, sourceId: source.id, targetId: candidate.target.id, tick: ++this.hitTick, reason: candidate.reason }); if (source.kind === 'projectile') break; } this.projectilePrevious.set(source.id, current); } for (const id of this.projectilePrevious.keys()) if (!alive.has(id)) this.projectilePrevious.delete(id); if (this.hitKeys.size > 500) this.hitKeys.clear(); }
  private receive(state: GameState) { const previousPhase = this.state?.phase; this.state = state; const me = this.flow && state.players[this.flow.game.playerId]; if (me) { if (previousPhase !== 'running' && state.phase === 'running' || this.localEpoch !== me.positionEpoch) { this.local = { ...me.position }; this.localEpoch = me.positionEpoch; this.moveTarget = null; } this.poseSequence = Math.max(this.poseSequence, me.lastPoseSequence); this.sequence = Math.max(this.sequence, me.lastCastSequence); } }
  private event(event: GameEvent) { if (event.type === 'reaction_triggered') this.notify(event.id); else if (event.type === 'cast_interrupted' && event.reason !== 'cancelled') this.notify(`施法中断：${event.reason ?? ''}`); }
  private selectElement(element: Element) { if (this.aiming || this.selected.length >= 4) return; this.selected.push(element); }
  private beginAim(target: Vec2, pointerId: number) { const spell = resolveSpell(this.selected), elements = [...this.selected], resolvedTarget = this.targetFor(spell, target), direction = this.directionTo(resolvedTarget); this.aim = direction; this.moveTarget = null; const castId = spell.channelled ? this.flow!.cast(++this.sequence, elements, direction, resolvedTarget) : null; this.aiming = { pointerId, target: resolvedTarget, spell, elements, castId }; }
  private finishAim(pointerId: number, cancelled = false) { const state = this.aiming; if (!state || state.pointerId !== pointerId) return; this.aiming = null; if (state.spell.channelled) { if (state.castId) this.flow?.release(state.castId); this.selected = []; return; } if (!cancelled) { this.flow?.cast(++this.sequence, state.elements, this.directionTo(state.target), state.target); this.selected = []; } }
  private pointerDown = (event: PointerEvent) => { const point = this.screenPoint(event); if (this.state?.phase === 'lobby') { if (this.lobbyButton && contains(this.lobbyButton, point)) this.flow?.start(); return; } if (this.state?.phase !== 'running') return; if (this.selected.length && !this.aiming && contains(this.clearButton(), point)) { this.selected = []; return; } const elementIndex = this.hud.elementCenters.findIndex((button) => Math.hypot(point.x - button.x, point.y - button.y) <= button.r); if (elementIndex >= 0) { this.selectElement(ELEMENTS[elementIndex]!); return; } if (hudBlocksWorld(this.hud, point)) return; const world = this.toWorld(point); if (!world) return; mainCanvas.setPointerCapture(event.pointerId); if (this.selected.length) this.beginAim(world, event.pointerId); else { this.moveTarget = world; this.aiming = null; } };
  private pointerMove = (event: PointerEvent) => { if (this.aiming?.pointerId !== event.pointerId) return; const target = this.toWorld(this.screenPoint(event)); if (!target) return; this.aiming.target = this.targetFor(this.aiming.spell, target); this.aim = this.directionTo(this.aiming.target); };
  private pointerUp = (event: PointerEvent) => this.finishAim(event.pointerId);
  private pointerCancel = (event: PointerEvent) => this.finishAim(event.pointerId, true);
  private keyDown = (event: KeyboardEvent) => { const index = Number(event.key) - 1; if (index >= 0 && index < ELEMENTS.length) this.selectElement(ELEMENTS[index]!); else if (event.key === 'Backspace') this.selected.pop(); else if (event.key === 'Escape') { this.selected = []; this.moveTarget = null; } };
  private directionTo(target: Vec2) { const dx = target.x - this.local.x, dy = target.y - this.local.y, length = Math.hypot(dx, dy) || 1; return { x: dx / length, y: dy / length }; }
  private targetFor(spell: SpellSpec, target: Vec2) { if (spell.delivery === 'shield' || spell.delivery === 'environment') return { ...this.local }; const dx = target.x - this.local.x, dy = target.y - this.local.y, distance = Math.hypot(dx, dy); if (!spell.range || distance <= spell.range) return target; return { x: this.local.x + dx / distance * spell.range, y: this.local.y + dy / distance * spell.range }; }
  private clearButton(): Rect { return { x: this.hud.elementPanel.x + this.hud.elementPanel.w - 50, y: this.hud.elementPanel.y + 5, w: 42, h: 24 }; }
  private notify(message: string) { this.notice = message; this.noticeUntil = performance.now() + 1600; }
  private view(width = mainCanvas.width / this.pixelRatio, height = mainCanvas.height / this.pixelRatio) { const scale = Math.min(width / WORLD.width, height / WORLD.height), ox = (width - WORLD.width * scale) / 2, oy = (height - WORLD.height * scale) / 2; return { scale, ox, oy }; }
  private screenPoint(event: PointerEvent) { const rect = mainCanvas.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; }
  private toWorld(point: Vec2) { const width = mainCanvas.width / this.pixelRatio, height = mainCanvas.height / this.pixelRatio, view = this.view(width, height), x = (point.x - view.ox) / view.scale, y = (point.y - view.oy) / view.scale; return x >= 0 && x <= WORLD.width && y >= 0 && y <= WORLD.height ? { x, y } : null; }
  private text(c: CanvasRenderingContext2D, text: string, x: number, y: number, size: number, color: string, align: CanvasTextAlign = 'left') { c.font = `600 ${size}px ui-monospace, monospace`; c.fillStyle = color; c.textAlign = align; c.textBaseline = 'middle'; c.fillText(text, x, y); }
  private destroy = () => { this.flow?.game.dispose(); this.flow = null; mainCanvas.removeEventListener('pointerdown', this.pointerDown); mainCanvas.removeEventListener('pointermove', this.pointerMove); mainCanvas.removeEventListener('pointerup', this.pointerUp); mainCanvas.removeEventListener('pointercancel', this.pointerCancel); window.removeEventListener('keydown', this.keyDown); };
}
