import { mainCanvas, mainContext } from 'littlejsengine';
import type { DamageElement, Element, ElementStatusType, EntityState, ForgeState, GameEvent, GameState, InventoryItem, LootEntity, MerchantState, PlayerState, SpellSpec, Vec2 } from '../game/contracts';
import { positionAt } from '../game/rules/entities';
import { canFuse, distance, fusionPrice, isCatalyst, isEquipment, isScroll, itemDetailLines, itemTypeText, moveSpeedMultiplier, sellPrice } from '../game/rules/equipment';
import { resolveScrollSpell } from '../game/rules/scrolls';
import { resolveSpell, specialSpellCatalog } from '../game/rules/spells';
import { collisionCandidates } from '../runtime/collision';
import { createEndwellFlow, type EndwellFlow } from '../runtime/flow';
import { computeHudLayout, contains, hudBlocksWorld, type HudLayout, type Rect } from '../ui/hud';
import { roomAt, THEMES } from '../game/roguelike';
import { resolveWorldMovement } from '../game/rules/worldCollision';
import { buildMinimapModel } from '../ui/minimap';
import { beamSegments } from '../game/rules/hitDetection';
import { presentedSpellEntity, updateLocalSpellPresentations, type LocalSpellPresentation } from '../runtime/localSpellPresentation';
import { EndwellAssets, TILE_SPRITES } from '../rendering/assets';
import { ELEMENT_COLORS, EndwellVisuals, type CombatImpact } from '../rendering/visuals';
import { DungeonTileRenderer } from '../rendering/dungeonTileRenderer';
import { alignToDevicePixel } from '../rendering/view';

const ELEMENTS: Element[] = ['rock', 'fire', 'ice', 'life', 'lightning', 'water', 'shield'];
const COLORS = ELEMENT_COLORS;
const LABELS: Record<Element, string> = { rock: '岩', fire: '火', ice: '冰', life: '命', lightning: '雷', water: '水', shield: '盾' };
const STATUS_LABELS: Partial<Record<ElementStatusType, string>> = { wet: '潮湿', burning: '燃烧', chilled: '冰冷', frozen: '冻结', shocked: '感电', poisoned: '中毒', shielded: '护盾', stoneArmor: '岩甲', regenerating: '再生', hasted: '加速', fireWard: '防火', frostWard: '防霜', waterWard: '防水', grounded: '接地' };
type AimState = { pointerId: number; target: Vec2; spell: SpellSpec; elements: Element[]; castId: string | null };
type ItemSource = 'equipment' | 'inventory' | 'loot' | 'merchant';
type UiAction = Rect & { kind: 'toggle-inventory' | 'close-inventory' | 'toggle-spellbook' | 'close-spellbook' | 'encyclopedia-spells' | 'encyclopedia-controls' | 'select-item' | 'equip' | 'unequip' | 'drop' | 'pickup' | 'buy' | 'sell' | 'fusion-select' | 'fusion-remove' | 'fuse'; source?: ItemSource; itemId?: string; entityId?: string };
type CombatFeedback = { text: string; color: string; createdAt: number; expiresAt: number };

export class EndwellScene {
  private assets = new EndwellAssets(); private visuals = new EndwellVisuals(this.assets); private dungeonTiles = new DungeonTileRenderer(this.assets); private assetsReady = false;
  private impacts: CombatImpact[] = []; private lastTargetPositions = new Map<string, Vec2>(); private shakeUntil = 0; private shakeStrength = 0;
  private flow: EndwellFlow | null = null; private state: GameState | null = null; private selected: Element[] = []; private local: Vec2 = { x: 260, y: 360 }; private localEpoch = -1; private aim: Vec2 = { x: 1, y: 0 }; private moveTarget: Vec2 | null = null; private moveIndicator: Vec2 | null = null; private moveIndicatorUntil = 0; private aiming: AimState | null = null; private sequence = 0; private poseSequence = 0; private aimSequence = 0; private last = performance.now(); private poseAt = 0; private activatedCastId: string | null = null; private hitTick = 0; private hitKeys = new Set<string>(); private projectilePrevious = new Map<string, Vec2>(); private spellPresentations = new Map<string, LocalSpellPresentation>(); private feedbacks = new Map<string, CombatFeedback[]>(); private notice = ''; private noticeUntil = 0; private pixelRatio = 1; private hud: HudLayout = computeHudLayout(1280, 720); private lobbyButton: Rect | null = null; private inventoryOpen = false; private spellbookOpen = false; private encyclopediaTab: 'spells' | 'controls' = 'spells'; private selectedItem: { source: ItemSource; itemId: string; entityId?: string } | null = null; private fusionIds: string[] = []; private uiActions: UiAction[] = [];
  init() { this.flow = createEndwellFlow(parti, { state: (state) => this.receive(state), event: (event) => this.event(event), rejected: () => window.setTimeout(() => this.hitKeys.clear(), 120) }); mainCanvas.addEventListener('pointerdown', this.pointerDown); mainCanvas.addEventListener('pointermove', this.pointerMove); mainCanvas.addEventListener('pointerup', this.pointerUp); mainCanvas.addEventListener('pointercancel', this.pointerCancel); window.addEventListener('keydown', this.keyDown); window.addEventListener('pagehide', this.destroy, { once: true }); void this.assets.load().finally(() => { this.assetsReady = true; parti.ready(); }); }
  update() { const now = performance.now(), dt = Math.min(.04, Math.max(.001, (now - this.last) / 1000)); this.last = now; this.pixelRatio = mainCanvas.width / Math.max(1, mainCanvas.clientWidth); if (!this.flow) return; this.state = this.flow.game.state.get<GameState>('') ?? this.state; if (this.state?.phase !== 'running') { this.spellPresentations.clear(); this.flow.game.update(dt); return; } const meState = this.me(), stage = this.state.run.stage; if (meState && this.localEpoch !== meState.positionEpoch) { const forced = Boolean(meState.forceVelocity); this.local = { ...meState.position }; this.localEpoch = meState.positionEpoch; if (!forced) this.moveTarget = null; } if (meState && !meState.alive) { this.moveTarget = null; this.aiming = null; } if (meState?.alive && stage && this.moveTarget && !this.aiming) { const me = this.me(), speed = 220 * moveSpeedMultiplier(me?.equipment ?? {}) * (me?.statuses.hasted ? 1.7 : 1), dx = this.moveTarget.x - this.local.x, dy = this.moveTarget.y - this.local.y, distance = Math.hypot(dx, dy), step = speed * dt, desired = distance <= step || distance < 3 ? { ...this.moveTarget } : { x: this.local.x + dx / distance * step, y: this.local.y + dy / distance * step }, previous = this.local, next = resolveWorldMovement(this.state, previous, desired, 24, meState.id); this.local = next; if (distance <= step || distance < 3 || next.x === previous.x && next.y === previous.y) this.moveTarget = null; }
    if (meState?.alive && now >= this.poseAt) { this.poseAt = now + 64; this.flow.pose({ sequence: ++this.poseSequence, sentAt: Date.now(), position: this.local, aim: this.aim, selectedElements: [...this.selected] }); if (this.aiming?.castId) this.flow.aim({ sequence: ++this.aimSequence, aim: this.aim }); }
    const cast = meState?.cast; if (cast?.phase === 'chanting' && cast.castId && cast.phaseEndsAt != null && Date.now() >= cast.phaseEndsAt && this.activatedCastId !== cast.castId) { this.activatedCastId = cast.castId; this.flow.activate(cast.castId); }
    if (cast?.castId !== this.activatedCastId && cast?.phase !== 'chanting') this.activatedCastId = null;
    if (meState?.alive && cast?.phase === 'active' && cast.spell?.channelled) updateLocalSpellPresentations(this.spellPresentations, this.state, meState.id, this.local, this.aim, dt); else this.spellPresentations.clear();
    this.flow.game.update(dt); this.collisions(Date.now()); }
  render() {
    const c = mainContext, width = mainCanvas.width / this.pixelRatio, height = mainCanvas.height / this.pixelRatio, now = performance.now();
    this.hud = computeHudLayout(width, height); this.uiActions = []; c.save(); c.setTransform(this.pixelRatio, 0, 0, this.pixelRatio, 0, 0); c.fillStyle = '#080710'; c.fillRect(0, 0, width, height);
    const view = this.view(width, height), shaking = now < this.shakeUntil, shakeFade = shaking ? (this.shakeUntil - now) / 180 : 0, shakeX = shaking ? Math.sin(now * .19) * this.shakeStrength * shakeFade : 0, shakeY = shaking ? Math.cos(now * .27) * this.shakeStrength * shakeFade : 0;
    const worldOx = alignToDevicePixel(view.ox + shakeX, this.pixelRatio), worldOy = alignToDevicePixel(view.oy + shakeY, this.pixelRatio), viewport = { x: -worldOx / view.scale, y: -worldOy / view.scale, w: width / view.scale, h: height / view.scale };
    c.save(); c.translate(worldOx, worldOy); c.scale(view.scale, view.scale); this.drawArena(c, viewport); c.restore();
    if (this.state?.environment.global?.kind === 'rain') this.drawRain(c, width, height); else if (this.state?.environment.global?.kind === 'blizzard') this.drawBlizzard(c, width, height); this.drawOffscreenMonsters(c, width, height); this.drawHud(c, width, height);
    if (!this.assetsReady) this.overlay(c, width, height, '唤醒遗迹…', '正在整理法术与远征装备'); else if (!this.state) this.overlay(c, width, height, '连接无底之尽…', ''); else if (this.state.phase === 'lobby') this.lobby(c, width, height); else if (this.state.phase === 'gameover') this.overlay(c, width, height, '远征失败', '遗迹吞没了这支队伍', '#c95e72'); else if (this.state.phase === 'victory') this.overlay(c, width, height, '远征胜利', `三关完成 · ${Object.values(this.state.players).reduce((sum, player) => sum + player.gold, 0)} 金币`, '#7fe2b2'); c.restore();
  }
  private drawArena(c: CanvasRenderingContext2D, viewport: { x: number; y: number; w: number; h: number }) { const state = this.state, stage = state?.run.stage; if (!state || !stage) return; const theme = THEMES[stage.themeId]; c.fillStyle = '#090a13'; c.fillRect(0, 0, stage.world.width, stage.world.height); if (this.assetsReady) this.dungeonTiles.render(c, stage, viewport, this.pixelRatio); else { c.fillStyle = theme.visual.floor; c.strokeStyle = theme.visual.wall; c.lineWidth = 7; for (const corridor of stage.world.corridors) { c.fillRect(corridor.position.x, corridor.position.y, corridor.width, corridor.height); c.strokeRect(corridor.position.x, corridor.position.y, corridor.width, corridor.height); } for (const room of stage.world.rooms) { c.fillRect(room.position.x, room.position.y, room.width, room.height); c.strokeRect(room.position.x, room.position.y, room.width, room.height); } } for (const room of stage.world.rooms) if (state.run.exploredRoomIds.includes(room.id)) this.text(c, room.id === stage.boss.roomId ? '守卫大厅' : room.id, room.position.x + 18, room.position.y + 25, 12, '#a99ab8');
    for (const terrain of stage.terrains) { if (!terrain.active && terrain.kind !== 'falling-rock') continue; if (this.assetsReady) this.visuals.terrain(c, terrain); else { c.fillStyle = terrain.kind === 'rune' ? '#9d78e8aa' : '#514b58'; c.beginPath(); c.arc(terrain.position.x, terrain.position.y, terrain.radius, 0, Math.PI * 2); c.fill(); } }
    for (const rune of stage.boss.runes) { this.visuals.aura(c, rune.position, 52, rune.active ? '#ffe08c' : '#625970', rune.active ? .24 : .08); this.visuals.tile(c, TILE_SPRITES.rune, rune.position.x, rune.position.y, { tint: rune.active ? '#ffe08c' : undefined }); } const portal = state.run.portal; if (portal?.active) { this.visuals.aura(c, portal.position, 72, '#65f3dc', .32); this.visuals.tile(c, TILE_SPRITES.portal, portal.position.x, portal.position.y, { tint: '#65f3dc' }); }
    if (!this.state || !this.flow) return; for (const id of this.flow.game.world.entitiesWith('Transform', 'PlayerState')) { const pos = this.flow.game.world.getComponent<Vec2>(id, 'Transform'), p = this.flow.game.world.getComponent<PlayerState>(id, 'PlayerState'); if (pos && p) this.player(c, p.id === this.flow.game.playerId ? this.local : pos, this.state.players[p.id] ?? p); } for (const logical of Object.values(this.state.entities)) { const e = presentedSpellEntity(logical, this.spellPresentations); this.entity(c, e, positionAt(e, Date.now())); } this.drawEconomyWorld(c);
    const impactNow = performance.now(); this.impacts = this.impacts.filter((impact) => impactNow < impact.createdAt + impact.duration); for (const impact of this.impacts) this.visuals.combatImpact(c, impact, impactNow);
    if (this.moveIndicator && performance.now() < this.moveIndicatorUntil) { const alpha = Math.max(0, (this.moveIndicatorUntil - performance.now()) / 350); c.save(); c.globalAlpha = alpha * .7; c.strokeStyle = '#d8cb91'; c.lineWidth = 2; c.beginPath(); c.arc(this.moveIndicator.x, this.moveIndicator.y, 10 + (1 - alpha) * 8, 0, Math.PI * 2); c.stroke(); c.restore(); }
    if (this.aiming && (!this.aiming.castId || this.me()?.cast.phase === 'chanting')) this.drawAim(c, this.aiming); }
  private drawAim(c: CanvasRenderingContext2D, state: AimState) { const color = COLORS[state.spell.elements[0] ?? 'rock'], angle = Math.atan2(this.aim.y, this.aim.x); c.save(); c.globalAlpha = .58; c.strokeStyle = color; c.fillStyle = `${color}18`; c.lineWidth = 2; c.setLineDash([10, 8]); if (state.spell.delivery === 'spray') { const half = (state.spell.coneAngle ?? Math.PI / 2) / 2; c.beginPath(); c.moveTo(this.local.x, this.local.y); c.arc(this.local.x, this.local.y, state.spell.range, angle - half, angle + half); c.closePath(); c.fill(); c.stroke(); } else if (state.spell.delivery === 'beam') { c.lineWidth = 3; c.beginPath(); c.moveTo(this.local.x, this.local.y); c.lineTo(this.local.x + this.aim.x * state.spell.range, this.local.y + this.aim.y * state.spell.range); c.stroke(); c.setLineDash([]); c.fillStyle = color; c.beginPath(); c.arc(this.local.x + this.aim.x * state.spell.range, this.local.y + this.aim.y * state.spell.range, 5, 0, Math.PI * 2); c.fill(); } else if (state.spell.delivery === 'shield' || state.spell.delivery === 'environment') { c.beginPath(); c.arc(this.local.x, this.local.y, 38, 0, Math.PI * 2); c.stroke(); } else if (state.spell.delivery === 'area' || state.spell.delivery === 'summon' && !state.spell.summon?.archetype.endsWith('wall')) { c.beginPath(); c.arc(state.target.x, state.target.y, state.spell.radius, 0, Math.PI * 2); c.fill(); c.stroke(); } else { c.beginPath(); c.moveTo(this.local.x, this.local.y); c.lineTo(state.target.x, state.target.y); c.stroke(); if (state.spell.delivery === 'summon') c.strokeRect(state.target.x - 18, state.target.y - 70, 36, 140); } c.restore(); }
  private drawEconomyWorld(c: CanvasRenderingContext2D) { if (!this.state) return; const merchant = this.state.merchant, forge = this.state.forge; if (forge) { this.visuals.aura(c, forge.position, 58, '#ffb06c', .2); this.visuals.tile(c, TILE_SPRITES.forge, forge.position.x, forge.position.y); this.text(c, '元素合成台', forge.position.x, forge.position.y - 52, 13, '#ffd19c', 'center'); } if (merchant) { this.visuals.tile(c, TILE_SPRITES.merchant, merchant.position.x, merchant.position.y); this.text(c, '流浪商人', merchant.position.x, merchant.position.y - 48, 13, '#9cf0dc', 'center'); } for (const loot of Object.values(this.state.loot)) { const item = loot.item, color = isCatalyst(item) ? '#65f3dc' : isEquipment(item) && item.rarity === 'rare' ? '#d3a2ff' : isEquipment(item) && item.rarity === 'excellent' ? '#83e2a1' : '#eee', sprite = isCatalyst(item) ? TILE_SPRITES.lootCatalyst : isScroll(item) ? TILE_SPRITES.lootScroll : item.slot === 'staff' ? TILE_SPRITES.lootStaff : item.slot === 'robe' ? TILE_SPRITES.lootRobe : TILE_SPRITES.lootRing; this.visuals.aura(c, loot.position, 28, color, .2); this.visuals.tile(c, sprite, loot.position.x, loot.position.y, { tint: color }); this.text(c, item.name, loot.position.x, loot.position.y - 26, 10, '#fff', 'center'); } }
  private player(c: CanvasRenderingContext2D, pos: Vec2, p: PlayerState) { const local = p.id === this.flow?.game.playerId; if (this.assets.image('atlas')) this.visuals.player(c, pos, p, local, local && Boolean(this.moveTarget)); else { c.fillStyle = local ? '#f5eecb' : '#75a7ff'; c.beginPath(); c.arc(pos.x, pos.y, 24, 0, Math.PI * 2); c.fill(); } c.fillStyle = '#16121f'; c.fillRect(pos.x - 28, pos.y - 41, 56, 7); c.fillStyle = p.alive ? '#67e4a1' : '#777'; c.fillRect(pos.x - 27, pos.y - 40, 54 * p.health.current / p.health.max, 5); this.text(c, p.alive ? p.name : `${p.name} · 已死亡`, pos.x, pos.y - 53, 12, '#fff', 'center'); this.drawElementRunes(c, pos, local ? this.selected : p.selectedElements ?? []); this.drawStatusLabels(c, pos.x, pos.y + 38, p.statuses); this.drawFeedback(c, p.id, pos.x, pos.y - 64); }
  private drawElementRunes(c: CanvasRenderingContext2D, pos: Vec2, elements: Element[]) { if (!elements.length) return; const size = 10, gap = 4, width = elements.length * size + (elements.length - 1) * gap, x = pos.x - width / 2; elements.forEach((element, index) => { const cx = x + index * (size + gap) + size / 2, cy = pos.y - 72; c.save(); c.translate(cx, cy); c.rotate(Math.PI / 4); c.fillStyle = COLORS[element]; c.fillRect(-size / 2, -size / 2, size, size); c.strokeStyle = '#fff'; c.lineWidth = 1.2; c.strokeRect(-size / 2, -size / 2, size, size); c.restore(); }); }
  private entity(c: CanvasRenderingContext2D, e: EntityState, pos: Vec2) { if (e.kind === 'monster') this.visuals.monster(c, e, pos); else this.visuals.effect(c, e, pos, e.source?.spell.delivery === 'beam' && this.state ? beamSegments(this.state, e, Date.now()) : []); if (e.kind === 'monster' && e.cast.phase === 'chanting' && e.cast.spell) { const duration = Math.max(1, (e.cast.phaseEndsAt ?? Date.now()) - e.cast.startedAt), progress = Math.max(0, Math.min(1, (Date.now() - e.cast.startedAt) / duration)); c.strokeStyle = COLORS[e.cast.spell.elements[0] ?? 'rock']; c.lineWidth = 5; c.beginPath(); c.arc(pos.x, pos.y, e.radius + 11, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * progress); c.stroke(); } if (e.health.max > 1) { const width = e.boss ? 116 : 68; c.fillStyle = '#301b2d'; c.fillRect(pos.x - width / 2, pos.y - e.radius - 17, width, 7); c.fillStyle = e.boss ? '#e55276' : '#f06a7e'; c.fillRect(pos.x - width / 2 + 1, pos.y - e.radius - 16, (width - 2) * e.health.current / e.health.max, 5); } this.drawStatusLabels(c, pos.x, pos.y + e.radius + 16, e.statuses); this.drawFeedback(c, e.id, pos.x, pos.y - e.radius - 28); }
  private drawStatusLabels(c: CanvasRenderingContext2D, x: number, y: number, statuses: PlayerState['statuses']) { const labels = Object.keys(statuses).map((key) => STATUS_LABELS[key as ElementStatusType]).filter(Boolean).slice(0, 4); if (!labels.length) return; const text = labels.join(' · '); c.fillStyle = 'rgba(12,10,18,.72)'; c.fillRect(x - text.length * 5 - 8, y - 9, text.length * 10 + 16, 18); this.text(c, text, x, y, 10, '#d9ecff', 'center'); }
  private drawFeedback(c: CanvasRenderingContext2D, id: string, x: number, y: number) { const now = performance.now(), entries = (this.feedbacks.get(id) ?? []).filter((entry) => entry.expiresAt > now); if (!entries.length) { this.feedbacks.delete(id); return; } this.feedbacks.set(id, entries); for (const [index, entry] of entries.slice(-3).entries()) { const age = now - entry.createdAt, alpha = Math.max(0, 1 - age / (entry.expiresAt - entry.createdAt)); c.save(); c.globalAlpha = alpha; this.text(c, entry.text, x, y - index * 15 - age * .025, 12, entry.color, 'center'); c.restore(); } }
  private addFeedback(id: string, text: string, color: string) { const now = performance.now(), entries = this.feedbacks.get(id) ?? []; entries.push({ text, color, createdAt: now, expiresAt: now + 900 }); this.feedbacks.set(id, entries.slice(-5)); }
  private drawRain(c: CanvasRenderingContext2D, width: number, height: number) { c.fillStyle = 'rgba(50,120,180,.16)'; c.fillRect(0, 0, width, height); c.strokeStyle = 'rgba(120,200,255,.55)'; c.lineWidth = 2; const offset = performance.now() / 8 % 36; for (let x = -height; x < width + height; x += 36) { c.beginPath(); c.moveTo(x + offset, 0); c.lineTo(x - height + offset, height); c.stroke(); } }
  private drawBlizzard(c: CanvasRenderingContext2D, width: number, height: number) { c.fillStyle = 'rgba(120,210,255,.12)'; c.fillRect(0, 0, width, height); c.fillStyle = 'rgba(210,245,255,.72)'; const offset = performance.now() / 12 % 48; for (let y = -20; y < height + 20; y += 48) for (let x = -20; x < width + 20; x += 64) { c.beginPath(); c.arc(x + offset, y + (x % 3) * 5, 2.2, 0, Math.PI * 2); c.fill(); } }
  private drawOffscreenMonsters(c: CanvasRenderingContext2D, width: number, height: number) { const stage = this.state?.run.stage; if (!this.state || !stage) return; const roomId = roomAt(stage, this.local)?.id, view = this.view(width, height), left = 20, right = width - 20, top = this.hud.message.y + this.hud.message.h + 12, bottom = this.hud.elementPanel.y - 14, cx = width / 2, cy = height / 2, groups = new Map<string, { count: number; angle: number; x: number; y: number; elite: boolean; boss: boolean }>(); for (const monster of Object.values(this.state.entities)) { if (monster.kind !== 'monster' || monster.roomId !== roomId || monster.health.current <= 0) continue; const sx = monster.position.x * view.scale + view.ox, sy = monster.position.y * view.scale + view.oy; if (sx >= left && sx <= right && sy >= top && sy <= bottom) continue; const dx = monster.position.x - this.local.x, dy = monster.position.y - this.local.y, angle = Math.atan2(dy, dx), tx = Math.abs(dx) < .001 ? Infinity : (dx > 0 ? right - cx : left - cx) / dx, ty = Math.abs(dy) < .001 ? Infinity : (dy > 0 ? bottom - cy : top - cy) / dy, t = Math.min(tx > 0 ? tx : Infinity, ty > 0 ? ty : Infinity), x = Math.max(left, Math.min(right, cx + dx * t)), y = Math.max(top, Math.min(bottom, cy + dy * t)), edge = tx < ty ? dx > 0 ? 'right' : 'left' : dy > 0 ? 'bottom' : 'top', bin = Math.round((edge === 'top' || edge === 'bottom' ? x : y) / 44), key = `${edge}:${bin}`, group = groups.get(key) ?? { count: 0, angle, x, y, elite: false, boss: false }; group.count += 1; group.angle = angle; group.elite ||= Boolean(monster.elite); group.boss ||= Boolean(monster.boss); groups.set(key, group); } for (const group of groups.values()) { const color = group.boss ? '#ff557e' : group.elite ? '#f0b76d' : '#f3d99a'; c.save(); c.translate(group.x, group.y); c.rotate(group.angle + Math.PI / 2); c.fillStyle = color; c.beginPath(); c.moveTo(0, -9); c.lineTo(7, 7); c.lineTo(0, 4); c.lineTo(-7, 7); c.closePath(); c.fill(); c.restore(); if (group.count > 1) this.text(c, String(group.count), group.x + 10, group.y, 9, color, 'center'); } }
  private drawHud(c: CanvasRenderingContext2D, width: number, height: number) {
    if (this.state?.phase !== 'running') return;
    const { status, inventoryButton, elementCenters, compact } = this.hud, me = this.me();
    this.panel(c, status, '#20192c');
    this.text(c, me && !me.alive ? '已死亡 · 等待复活术' : `HP ${Math.round(me?.health.current ?? 0)} / ${Math.round(me?.health.max ?? 0)}`, status.x + 10, status.y + 18, 12, '#fff');
    c.fillStyle = '#25101a'; c.fillRect(status.x + 10, status.y + 30, status.w - 20, 9);
    c.fillStyle = '#62df7c'; c.fillRect(status.x + 10, status.y + 30, (status.w - 20) * (me?.health.current ?? 0) / Math.max(1, me?.health.max ?? 1), 9);
    c.save(); c.strokeStyle = 'rgba(236,211,145,.72)'; c.lineWidth = 1; c.strokeRect(status.x + 9.5, status.y + 29.5, status.w - 19, 10); c.restore();
    this.text(c, `金币 ${me?.gold ?? 0}G`, status.x + 10, status.y + status.h - 16, 11, '#f2d477');
    const stage = this.state.run.stage, objectiveCount = stage?.objectives.filter((objective) => objective.status === 'completed').length ?? 0, bossLabel = stage?.boss.status === 'locked' ? '未解锁' : stage?.boss.status === 'available' ? '可挑战' : stage?.boss.status === 'active' ? `战斗中 P${stage.boss.phase}` : '已击败', roomId = stage && me ? roomAt(stage, me.position)?.id : undefined, encounter = stage?.encounters.find((candidate) => candidate.roomId === roomId && candidate.status === 'active'), recentlyCleared = stage?.encounters.find((candidate) => candidate.roomId === roomId && candidate.status === 'cleared' && candidate.clearedAt != null && Date.now() - candidate.clearedAt < 1600), waveLabel = encounter ? encounter.nextWaveAt != null ? encounter.currentWave === 0 ? '敌潮来袭 · 准备战斗' : `第 ${encounter.currentWave} 波完成 · 敌人即将出现` : `第 ${encounter.currentWave}/${encounter.totalWaves} 波` : recentlyCleared ? '房间肃清 · 奖励已结算' : null, persistent = waveLabel ?? (stage ? `第 ${stage.index + 1}/3 关 · 钥印 ${objectiveCount}/2 · Boss ${bossLabel}` : this.state.message), toast = performance.now() < this.noticeUntil ? this.notice : persistent;
    this.visuals.uiFrame(c, this.hud.message, 15); this.text(c, toast, this.hud.message.x + this.hud.message.w / 2, this.hud.message.y + this.hud.message.h / 2, compact ? 11 : 13, performance.now() < this.noticeUntil ? '#fff' : '#e2c98e', 'center');
    this.panel(c, inventoryButton, this.inventoryOpen ? '#4b3546' : '#261e32');
    this.text(c, `背包 ${me?.inventory.length ?? 0}/9`, inventoryButton.x + inventoryButton.w / 2, inventoryButton.y + inventoryButton.h / 2, 11, this.inventoryOpen ? '#9a8d99' : '#fff', 'center');
    if (!this.inventoryOpen) this.uiActions.push({ ...inventoryButton, kind: 'toggle-inventory' });
    const spellbookButton = { x: inventoryButton.x + inventoryButton.w + 8, y: inventoryButton.y, w: inventoryButton.w, h: inventoryButton.h }; this.panel(c, spellbookButton, this.spellbookOpen ? '#4b3546' : '#261e32'); this.text(c, `百科 ${(this.state.run.discoveredSpellIds ?? ['resurrect']).length}`, spellbookButton.x + spellbookButton.w / 2, spellbookButton.y + spellbookButton.h / 2, 11, this.spellbookOpen ? '#9a8d99' : '#fff', 'center'); if (!this.spellbookOpen) this.uiActions.push({ ...spellbookButton, kind: 'toggle-spellbook' });
    if (this.selected.length && !this.aiming) { const clear = this.clearButton(); c.fillStyle = 'rgba(73,53,65,.9)'; c.fillRect(clear.x, clear.y, clear.w, clear.h); this.text(c, '清空', clear.x + clear.w / 2, clear.y + clear.h / 2, 9, '#fff', 'center'); }
    for (let i = 0; i < elementCenters.length; i++) { const button = elementCenters[i]!, element = ELEMENTS[i]!, selectedCount = this.selected.filter((value) => value === element).length; this.visuals.elementSigil(c, element, button.x, button.y, button.r - 3, selectedCount); this.text(c, LABELS[element], button.x, button.y + button.r - 8, compact ? 8 : 9, '#f6efff', 'center'); if (selectedCount) { c.fillStyle = '#fff'; c.beginPath(); c.arc(button.x + button.r - 9, button.y - button.r + 9, 9, 0, Math.PI * 2); c.fill(); this.text(c, String(selectedCount), button.x + button.r - 9, button.y - button.r + 9, 9, '#211529', 'center'); } }
    if (this.inventoryOpen) this.drawInventory(c, width, height); else if (this.spellbookOpen) this.drawSpellbook(c, width, height); else this.drawMinimap(c, width);
  }
  private drawSpellbook(c: CanvasRenderingContext2D, width: number, height: number) { if (!this.state) return; const panel = this.hud.inventoryPanel, discovered = new Set(this.state.run.discoveredSpellIds ?? ['resurrect']), entries = specialSpellCatalog().filter(({ spell }) => discovered.has(spell.id)); c.fillStyle = 'rgba(8,6,12,.58)'; c.fillRect(0, 0, width, height); c.fillStyle = 'rgba(20,16,28,.98)'; c.fillRect(panel.x, panel.y, panel.w, panel.h); this.text(c, '百科', panel.x + 18, panel.y + 26, 16, '#ffe09a'); const tabW = 94, spellTab = { x: panel.x + 82, y: panel.y + 10, w: tabW, h: 28 }, controlsTab = { x: panel.x + 180, y: panel.y + 10, w: tabW, h: 28 }; for (const [rect, label, active, kind] of [[spellTab, '已解锁法术', this.encyclopediaTab === 'spells', 'encyclopedia-spells'], [controlsTab, '操作提示', this.encyclopediaTab === 'controls', 'encyclopedia-controls']] as const) { c.fillStyle = active ? '#655071' : '#31293b'; c.fillRect(rect.x, rect.y, rect.w, rect.h); this.text(c, label, rect.x + rect.w / 2, rect.y + rect.h / 2, 10, '#fff', 'center'); this.uiActions.push({ ...rect, kind }); } if (this.encyclopediaTab === 'spells') { this.text(c, `已发现 ${entries.length} / ${specialSpellCatalog().length}`, panel.x + 18, panel.y + 58, 11, '#bcaec8'); const columns = panel.w < 560 ? 1 : 2, cardW = (panel.w - 36 - (columns - 1) * 10) / columns, cardH = 58; entries.forEach(({ sequence, spell }, index) => { const col = index % columns, row = Math.floor(index / columns), rect = { x: panel.x + 18 + col * (cardW + 10), y: panel.y + 74 + row * (cardH + 8), w: cardW, h: cardH }; if (rect.y + rect.h > panel.y + panel.h - 12) return; c.fillStyle = '#31293b'; c.fillRect(rect.x, rect.y, rect.w, rect.h); this.text(c, spell.name, rect.x + 10, rect.y + 17, 12, '#fff'); this.text(c, `${sequence.map((element) => LABELS[element]).join(' · ')} · ${spell.delivery}`, rect.x + 10, rect.y + 39, 10, '#d9c8ec'); }); } else { const tips = ['点击场地：移动到目标位置', '点击元素或按 1–7：按顺序加入施法组合', '组合最多四个元素；重复元素会增强对应效果', '选好元素后按住场地并拖动：瞄准；抬起：施法', '持续型法术需要保持按住，抬起后结束', '退格：撤销最后一个元素；清空：移除全部元素', 'Esc：取消选择、移动并关闭当前面板', '背包可管理装备；靠近商人、掉落或合成台时可交互']; tips.forEach((tip, index) => { const y = panel.y + 70 + index * 40; c.fillStyle = index % 2 ? '#272130' : '#31293b'; c.fillRect(panel.x + 18, y - 14, panel.w - 36, 31); this.text(c, `${index + 1}. ${tip}`, panel.x + 30, y, panel.w < 500 ? 10 : 12, '#e6dff0'); }); } const close = { x: panel.x + panel.w - 72, y: panel.y + 10, w: 58, h: 28 }; c.fillStyle = '#6b465d'; c.fillRect(close.x, close.y, close.w, close.h); this.text(c, '关闭', close.x + close.w / 2, close.y + close.h / 2, 10, '#fff', 'center'); this.uiActions.push({ ...close, kind: 'close-spellbook' }); }
  private drawMinimap(c: CanvasRenderingContext2D, width: number) { if (!this.state || !this.flow) return; const compact = width < 760, rect = { x: width - (compact ? 125 : 160) - 12, y: 12, w: compact ? 125 : 160, h: compact ? 90 : 112 }, model = buildMinimapModel(this.state, this.flow.game.playerId, rect); c.fillStyle = 'rgba(8,8,14,.9)'; c.fillRect(rect.x + 8, rect.y + 8, rect.w - 16, rect.h - 16); for (const line of model.lines) { c.strokeStyle = line.frontier ? '#4b4654' : '#8b8295'; c.setLineDash(line.frontier ? [3, 4] : []); c.beginPath(); c.moveTo(line.from.x, line.from.y); c.lineTo(line.to.x, line.to.y); c.stroke(); } c.setLineDash([]); for (const room of model.rooms) { c.fillStyle = room.current ? '#74658a' : room.boss ? '#4e3345' : '#34303d'; c.fillRect(room.x, room.y, room.w, room.h); c.strokeStyle = room.current ? '#ead9ff' : '#777080'; c.strokeRect(room.x, room.y, room.w, room.h); } const colors = { self: '#fff1a8', ally: '#75a7ff', objective: '#d7a0ff', merchant: '#79e2c7', forge: '#f0a56d', boss: '#ff6f83', portal: '#65f3dc' } as const; for (const marker of model.markers) { if (marker.kind === 'ally' && marker.state === 'dead') { c.strokeStyle = '#ff7a8e'; c.lineWidth = 2; c.beginPath(); c.arc(marker.position.x, marker.position.y, 4, 0, Math.PI * 2); c.moveTo(marker.position.x - 3, marker.position.y - 3); c.lineTo(marker.position.x + 3, marker.position.y + 3); c.moveTo(marker.position.x + 3, marker.position.y - 3); c.lineTo(marker.position.x - 3, marker.position.y + 3); c.stroke(); continue; } c.fillStyle = colors[marker.kind]; c.beginPath(); if (marker.kind === 'objective' || marker.kind === 'boss') { c.moveTo(marker.position.x, marker.position.y - 3); c.lineTo(marker.position.x + 3, marker.position.y + 3); c.lineTo(marker.position.x - 3, marker.position.y + 3); c.closePath(); } else c.arc(marker.position.x, marker.position.y, marker.kind === 'self' ? 3.5 : 2.5, 0, Math.PI * 2); c.fill(); } this.visuals.atlasCell(c, 'ui', 14, rect.x - 8, rect.y - 8, rect.w + 16, rect.h + 16); this.text(c, '探索', rect.x + 10, rect.y + 10, 8, '#ddd3e8'); }
  private drawInventory(c: CanvasRenderingContext2D, width: number, height: number) {
    const me = this.me(); if (!me || !this.state) return;
    const panel = this.hud.inventoryPanel, detailsW = Math.min(250, panel.w * .38), leftW = panel.w - detailsW - 18, x = panel.x, y = panel.y, loot = this.nearbyLoot(), merchant = this.nearbyMerchant(), forge = this.nearbyForge();
    if (!forge) this.fusionIds = []; this.fusionIds = this.fusionIds.filter((id) => me.inventory.some((item) => item.id === id));
    c.fillStyle = 'rgba(8,6,12,.66)'; c.fillRect(0, 0, width, height); this.panel(c, { x, y, w: panel.w, h: panel.h }, '#181320');
    this.text(c, `背包 · ${me.gold} 金币`, x + 14, y + 24, 14, '#ffe09a'); let top = y + 42;
    if (forge) {
      const uses = this.state.forgeUses[forge.id]?.[me.id] ?? 0, price = fusionPrice(uses), selected = this.fusionItems(), enabled = selected.length === 3 && canFuse(selected) && me.gold >= price;
      this.text(c, `合成台 · 第 ${uses + 1} 次 ${price}G`, x + 12, top + 12, 11, '#ffd19c');
      for (let i = 0; i < 3; i++) { const slot = { x: x + 128 + i * 74, y: top - 5, w: 68, h: 34 }, item = selected[i]; this.itemCard(c, slot, item, item ? '' : '空位'); if (item) this.uiActions.push({ ...slot, kind: 'fusion-remove', itemId: item.id }); }
      const button = { x: x + Math.min(leftW - 112, 364), y: top - 5, w: 104, h: 34 }; c.fillStyle = enabled ? '#9b6038' : '#40363b'; c.fillRect(button.x, button.y, button.w, button.h); this.text(c, '合成', button.x + button.w / 2, button.y + button.h / 2, 10, enabled ? '#fff' : '#888', 'center'); if (enabled) this.uiActions.push({ ...button, kind: 'fuse', entityId: forge.id }); top += 48;
    }
    const cardH = 44, slotNames = { staff: '法杖', robe: '法袍', ring: '法戒' } as const;
    this.text(c, '装备栏', x + 12, top + 10, 11, '#bcaec8'); top += 18;
    for (const [index, slot] of (['staff', 'robe', 'ring'] as const).entries()) { const rect = { x: x + 12 + index * ((leftW - 24) / 3), y: top, w: (leftW - 36) / 3, h: cardH }, item = me.equipment[slot]; this.itemCard(c, rect, item, slotNames[slot]); if (item) this.uiActions.push({ ...rect, kind: 'select-item', source: 'equipment', itemId: item.id }); }
    top += cardH + 25; this.text(c, '背包区域', x + 12, top - 4, 11, '#bcaec8');
    const cellW = (leftW - 34) / 3;
    for (let i = 0; i < 9; i++) { const item = me.inventory[i], rect = { x: x + 12 + i % 3 * (cellW + 5), y: top + Math.floor(i / 3) * (cardH + 5), w: cellW, h: cardH }; this.itemCard(c, rect, item); if (item) this.uiActions.push({ ...rect, kind: 'select-item', source: 'inventory', itemId: item.id }); }
    top += 3 * (cardH + 5) + 12;
    if (loot.length) { this.text(c, '掉落区域', x + 12, top + 10, 11, '#e4b9ff'); top += 18; for (const entry of loot.slice(0, 3)) { const rect = { x: x + 12, y: top, w: leftW - 24, h: 34 }; this.itemCard(c, rect, entry.item); this.uiActions.push({ ...rect, kind: 'select-item', source: 'loot', itemId: entry.item.id, entityId: entry.id }); top += 38; } }
    if (merchant && top < y + panel.h - 38) { this.text(c, '商人贩卖区域', x + 12, top + 10, 11, '#9cf0dc'); top += 18; for (const entry of merchant.stock.slice(0, Math.max(1, Math.floor((y + panel.h - top - 8) / 38)))) { const rect = { x: x + 12, y: top, w: leftW - 24, h: 34 }; this.itemCard(c, rect, entry.item, `${entry.price}G`); this.uiActions.push({ ...rect, kind: 'select-item', source: 'merchant', itemId: entry.item.id, entityId: merchant.id }); top += 38; } }
    this.drawItemDetails(c, x + leftW + 8, y + 10, detailsW, panel.h - 20, merchant, loot, forge);
    const close = { x: x + panel.w - 72, y: y + 10, w: 58, h: 28 };
    c.fillStyle = '#6b465d'; c.fillRect(close.x, close.y, close.w, close.h);
    c.strokeStyle = '#d8cb91'; c.lineWidth = 1; c.strokeRect(close.x + .5, close.y + .5, close.w - 1, close.h - 1);
    this.text(c, '关闭', close.x + close.w / 2, close.y + close.h / 2, 10, '#fff', 'center');
    this.uiActions.push({ ...close, kind: 'close-inventory' });
  }
  private itemCard(c: CanvasRenderingContext2D, rect: Rect, item?: InventoryItem | null, prefix = '') { const selected = Boolean(item && this.selectedItem?.itemId === item.id); c.save(); c.fillStyle = selected ? '#46345d' : item ? '#201b2c' : '#12101a'; c.fillRect(rect.x, rect.y, rect.w, rect.h); c.strokeStyle = selected ? '#d3a2ff' : '#5d526d'; c.lineWidth = selected ? 2 : 1; c.strokeRect(rect.x + .5, rect.y + .5, rect.w - 1, rect.h - 1); c.restore(); if (!item) { this.text(c, prefix || '空', rect.x + rect.w / 2, rect.y + rect.h / 2, 9, '#625b6c', 'center'); return; } this.itemIcon(c, item, rect.x + 20, rect.y + rect.h / 2, 12); const color = isCatalyst(item) ? '#65f3dc' : isScroll(item) ? '#f4d56f' : item.rarity === 'rare' ? '#d3a2ff' : item.rarity === 'excellent' ? '#83e2a1' : '#eee'; this.text(c, `${prefix ? `${prefix} · ` : ''}${item.name}`, rect.x + 40, rect.y + rect.h / 2, 10, color); }
  private itemIcon(c: CanvasRenderingContext2D, item: InventoryItem, x: number, y: number, r: number) { const sprite = isCatalyst(item) ? TILE_SPRITES.lootCatalyst : isScroll(item) ? TILE_SPRITES.lootScroll : item.slot === 'staff' ? TILE_SPRITES.lootStaff : item.slot === 'robe' ? TILE_SPRITES.lootRobe : TILE_SPRITES.lootRing, color = isCatalyst(item) ? '#65f3dc' : isScroll(item) ? '#f4d56f' : item.rarity === 'rare' ? '#d3a2ff' : item.rarity === 'excellent' ? '#83e2a1' : undefined; this.visuals.tile(c, { ...sprite, drawWidth: r * 2.35, drawHeight: r * 2.35 }, x, y, { tint: color }); }
  private drawItemDetails(c: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, merchant: MerchantState | null, loot: LootEntity[], forge: ForgeState | null) {
    c.fillStyle = '#17131f'; c.fillRect(x, y, w, h); const item = this.selectedInventoryItem(merchant, loot); if (!item) { this.selectedItem = null; this.text(c, '选择物品查看详情', x + w / 2, y + h / 2, 12, '#777', 'center'); return; }
    this.itemIcon(c, item, x + 31, y + 38, 18); this.text(c, item.name, x + 58, y + 30, 14, '#fff'); this.text(c, itemTypeText(item), x + 58, y + 50, 10, '#b9aec3'); let yy = y + 78;
    for (const line of itemDetailLines(item)) { this.text(c, line.slice(0, Math.max(16, Math.floor((w - 24) / 9))), x + 12, yy, 10, '#cdd7ea'); yy += 16; }
    this.text(c, item.description.slice(0, Math.max(16, Math.floor((w - 24) / 9))), x + 12, yy + 10, 10, '#aaa'); yy += 40;
    const add = (label: string, kind: UiAction['kind'], extra: Partial<UiAction> = {}) => { const rect = { x: x + 12, y: yy, w: w - 24, h: 30 }; c.fillStyle = '#493541'; c.fillRect(rect.x, rect.y, rect.w, rect.h); this.text(c, label, rect.x + rect.w / 2, rect.y + rect.h / 2, 10, '#fff', 'center'); this.uiActions.push({ ...rect, kind, itemId: item.id, ...extra }); yy += 36; };
    const source = this.selectedItem?.source;
    if (source === 'loot') add('拾取', 'pickup', { entityId: this.selectedItem?.entityId });
    else if (source === 'merchant') add('购买', 'buy', { entityId: merchant?.id });
    else if (source === 'equipment') add('卸下', 'unequip');
    else if (source === 'inventory') { if (isEquipment(item)) add('装配', 'equip'); add('丢弃', 'drop'); if (merchant && (isEquipment(item) || isScroll(item))) add(`出售 ${sellPrice(item)}G`, 'sell', { entityId: merchant.id }); if (forge && this.canAddFusion(item)) add('放入合成台', 'fusion-select'); }
  }
  private me() { return this.flow && this.state ? this.state.players[this.flow.game.playerId] : undefined; }
  private previewSpell(elements: Element[]) { const me = this.me(); return me ? resolveScrollSpell(elements, me, Date.now()) ?? resolveSpell(elements) : resolveSpell(elements); }
  private nearbyLoot() { return this.state ? Object.values(this.state.loot).filter((entry) => distance(this.local, entry.position) <= 125) : []; }
  private nearbyMerchant() { const merchant = this.state?.merchant; return merchant && distance(this.local, merchant.position) <= merchant.radius + 90 ? merchant : null; }
  private nearbyForge() { const forge = this.state?.forge; return forge && distance(this.local, forge.position) <= forge.radius + 90 ? forge : null; }
  private selectedInventoryItem(merchant: MerchantState | null, loot: LootEntity[]) { const selected = this.selectedItem, me = this.me(); if (!selected || !me) return null; if (selected.source === 'inventory') return me.inventory.find((item) => item.id === selected.itemId) ?? null; if (selected.source === 'equipment') return Object.values(me.equipment).find((item) => item?.id === selected.itemId) ?? null; if (selected.source === 'loot') return loot.find((entry) => entry.id === selected.entityId)?.item ?? null; return merchant?.stock.find((entry) => entry.item.id === selected.itemId)?.item ?? null; }
  private fusionItems() { const me = this.me(); return this.fusionIds.map((id) => me?.inventory.find((item) => item.id === id)).filter((item): item is InventoryItem => Boolean(item)); }
  private canAddFusion(item: InventoryItem) { if (this.fusionIds.length >= 3 || this.fusionIds.includes(item.id)) return false; const chosen = this.fusionItems(); if (isCatalyst(item)) return !chosen.some(isCatalyst); if (!isEquipment(item)) return false; const equipment = chosen.filter(isEquipment); return !equipment.length || equipment[0]!.slot === item.slot; }
  private handleUiAction(action: UiAction) {
    if (action.kind === 'toggle-inventory') { this.spellbookOpen = false; this.inventoryOpen = !this.inventoryOpen; if (!this.inventoryOpen) { this.selectedItem = null; this.fusionIds = []; } return true; }
    if (action.kind === 'close-inventory') { this.inventoryOpen = false; this.selectedItem = null; this.fusionIds = []; return true; }
    if (action.kind === 'toggle-spellbook') { this.inventoryOpen = false; this.spellbookOpen = !this.spellbookOpen; this.selectedItem = null; this.fusionIds = []; return true; }
    if (action.kind === 'close-spellbook') { this.spellbookOpen = false; return true; }
    if (action.kind === 'encyclopedia-spells') { this.encyclopediaTab = 'spells'; return true; }
    if (action.kind === 'encyclopedia-controls') { this.encyclopediaTab = 'controls'; return true; }
    if (action.kind === 'select-item' && action.source && action.itemId) { this.selectedItem = { source: action.source, itemId: action.itemId, entityId: action.entityId }; return true; }
    if (action.kind === 'fusion-remove' && action.itemId) { this.fusionIds = this.fusionIds.filter((id) => id !== action.itemId); return true; }
    if (!this.me()?.alive) { this.notify('已死亡，等待复活术'); return true; }
    if (action.kind === 'fusion-select' && action.itemId) { const item = this.me()?.inventory.find((value) => value.id === action.itemId); if (!item || !this.canAddFusion(item)) this.notify(this.fusionIds.length >= 3 ? '合成台已满' : '只能放入同类型装备或合成宝珠'); else this.fusionIds.push(item.id); return true; }
    if (action.kind === 'fuse' && action.entityId) { this.flow?.fuse(action.entityId, [...this.fusionIds]); this.fusionIds = []; this.selectedItem = null; return true; }
    if (action.kind === 'equip' && action.itemId) this.flow?.equip(action.itemId);
    else if (action.kind === 'unequip' && action.itemId) this.flow?.unequip(action.itemId);
    else if (action.kind === 'drop' && action.itemId) this.flow?.drop(action.itemId);
    else if (action.kind === 'pickup' && action.entityId) this.flow?.pickup(action.entityId);
    else if (action.kind === 'buy' && action.entityId && action.itemId) this.flow?.buy(action.entityId, action.itemId);
    else if (action.kind === 'sell' && action.entityId && action.itemId) this.flow?.sell(action.entityId, action.itemId);
    else return false;
    this.selectedItem = null; return true;
  }
  private lobby(c: CanvasRenderingContext2D, width: number, height: number) { this.overlay(c, width, height, 'ENDWELL', `遗迹远征 · ${Object.keys(this.state?.players ?? {}).length} 名施法者`); this.lobbyButton = null; this.visuals.tile(c, TILE_SPRITES.player, width / 2 - 70, height / 2 + 42); this.visuals.tile(c, TILE_SPRITES.guardian, width / 2 + 70, height / 2 + 42, { tint: '#ff557e' }); if (this.state?.hostId === parti.playerId) { const rect = { x: width / 2 - 100, y: height / 2 + 94, w: 200, h: 52 }; this.lobbyButton = rect; this.panel(c, rect, '#c6a65b'); this.text(c, '开始试炼', width / 2, rect.y + rect.h / 2, 17, '#171522', 'center'); } else this.text(c, '等待房主开启远征', width / 2, height / 2 + 118, 13, '#bcb0cb', 'center'); }
  private overlay(c: CanvasRenderingContext2D, width: number, height: number, title: string, sub: string, accent = '#d8c27a') { c.fillStyle = 'rgba(6,5,12,.86)'; c.fillRect(0, 0, width, height); const card = { x: Math.max(22, width / 2 - 250), y: height / 2 - 105, w: Math.min(500, width - 44), h: 174 }; this.panel(c, card, '#17121f', accent); this.visuals.aura(c, { x: width / 2, y: height / 2 - 30 }, 150, accent, .12); this.text(c, title, width / 2, height / 2 - 46, 34, '#f6eac7', 'center'); this.text(c, sub, width / 2, height / 2 + 2, 14, '#bcb3cc', 'center'); }
  private collisions(now: number) { if (!this.state || !this.flow) return; const me = this.flow.game.playerId, alive = new Set<string>(); for (const logical of Object.values(this.state.entities)) { if (logical.ownerId !== me || !logical.source) continue; const source = presentedSpellEntity(logical, this.spellPresentations), hitSource = source.source; if (!hitSource) continue; alive.add(source.id); const current = positionAt(source, now), previous = this.projectilePrevious.get(source.id) ?? current, tick = hitSource.tickMs > 0 ? Math.floor(now / hitSource.tickMs) : 0, candidates = collisionCandidates(this.state, source, now, previous); for (const candidate of candidates) { const key = `${source.id}:${candidate.target.id}:${tick}`; if (this.hitKeys.has(key)) continue; this.hitKeys.add(key); this.flow.hit({ hitId: `${source.id}:hit:${candidate.target.id}:${tick}`, sourceId: source.id, targetId: candidate.target.id, tick: ++this.hitTick, reason: candidate.reason }); if (source.kind === 'projectile' && !hitSource.spell.tags.includes('pierce')) break; } this.projectilePrevious.set(source.id, current); } for (const id of this.projectilePrevious.keys()) if (!alive.has(id)) this.projectilePrevious.delete(id); if (this.hitKeys.size > 500) this.hitKeys.clear(); }
  private receive(state: GameState) { const previousPhase = this.state?.phase; this.state = state; const me = this.flow && state.players[this.flow.game.playerId]; if (me) { if (previousPhase !== 'running' && state.phase === 'running' || this.localEpoch !== me.positionEpoch) { const forced = Boolean(me.forceVelocity); this.local = { ...me.position }; this.localEpoch = me.positionEpoch; if (!forced) this.moveTarget = null; } this.poseSequence = Math.max(this.poseSequence, me.lastPoseSequence); this.sequence = Math.max(this.sequence, me.lastCastSequence); } }
  private event(event: GameEvent) {
    if (event.type === 'cast_started' && event.casterId === this.flow?.game.playerId && event.spellId === 'self-heal') this.notify('生命治愈 · 恢复 20');
    else if (event.type === 'reaction_triggered') this.notify(event.id); else if (event.type === 'cast_interrupted' && event.reason !== 'cancelled') { this.notify(`施法中断：${event.reason ?? ''}`); this.addFeedback(event.casterId, '打断', '#ffe28a'); }
    if (event.type === 'damage_applied') { this.addFeedback(event.targetId, event.amount > 0 ? `-${Math.round(event.amount)}` : '0', event.amount > 0 ? '#ff8b8b' : '#d8d2e0'); const position = this.targetPosition(event.targetId); if (position && event.amount > 0) { this.lastTargetPositions.set(event.targetId, position); this.impacts.push({ position, color: this.impactColor(event.element), createdAt: performance.now(), duration: 260, seed: this.impacts.length + Math.round(event.amount * 17), kind: 'hit' }); this.shake(2.5); } }
    else if (event.type === 'entity_destroyed') { const position = this.lastTargetPositions.get(event.entityId); if (position) { this.impacts.push({ position, color: '#bd91ff', createdAt: performance.now(), duration: 680, seed: this.impacts.length + event.entityId.length * 31, kind: 'death' }); this.shake(9); this.lastTargetPositions.delete(event.entityId); } }
    else if (event.type === 'damage_immune') this.addFeedback(event.targetId, '免疫', '#f5e7a4'); else if (event.type === 'heal_applied') this.addFeedback(event.targetId, `+${Math.round(event.amount)}`, '#7df09a'); else if (event.type === 'status_applied') this.addFeedback(event.targetId, STATUS_LABELS[event.status] ?? event.status, '#d9ecff');
  }
  private targetPosition(id: string) { const player = this.state?.players[id], entity = this.state?.entities[id]; return player ? player.id === this.flow?.game.playerId ? { ...this.local } : { ...player.position } : entity ? { ...positionAt(entity, Date.now()) } : this.lastTargetPositions.get(id); }
  private impactColor(element: DamageElement) { return element in COLORS ? COLORS[element as Element] : element === 'pure' ? '#ffffff' : '#f0b37b'; }
  private shake(strength: number) { const now = performance.now(); this.shakeStrength = now >= this.shakeUntil ? strength : Math.max(this.shakeStrength, strength); this.shakeUntil = now + 180; }
  private selectElement(element: Element) { if (!this.me()?.alive || this.aiming || this.selected.length >= 4) return; this.selected.push(element); }
  private beginAim(target: Vec2, pointerId: number) { if (!this.me()?.alive) { this.notify('已死亡，等待复活术'); return; } const elements = [...this.selected], spell = this.previewSpell(elements), resolvedTarget = this.targetFor(spell, target), direction = this.directionTo(resolvedTarget); this.aim = direction; this.moveTarget = null; const castId = spell.channelled ? this.flow!.cast(++this.sequence, elements, direction, resolvedTarget).castId : null; this.aiming = { pointerId, target: resolvedTarget, spell, elements, castId }; }
  private finishAim(pointerId: number, cancelled = false) { const state = this.aiming; if (!state || state.pointerId !== pointerId) return; this.aiming = null; if (state.spell.channelled) { if (state.castId) this.flow?.release(state.castId); this.selected = []; return; } if (!cancelled) { this.flow?.cast(++this.sequence, state.elements, this.directionTo(state.target), state.target); this.selected = []; } }
  private pointerDown = (event: PointerEvent) => { const point = this.screenPoint(event); if (this.state?.phase === 'lobby') { if (this.lobbyButton && contains(this.lobbyButton, point)) this.flow?.start(); return; } if (this.state?.phase !== 'running') return; const action = [...this.uiActions].reverse().find((entry) => contains(entry, point)); if (action && this.handleUiAction(action)) return; if (!this.me()?.alive) { this.notify('已死亡，等待复活术'); return; } if (this.selected.length && !this.aiming && contains(this.clearButton(), point)) { this.selected = []; return; } const elementIndex = this.hud.elementCenters.findIndex((button) => Math.hypot(point.x - button.x, point.y - button.y) <= button.r); if (elementIndex >= 0) { this.selectElement(ELEMENTS[elementIndex]!); return; } if (hudBlocksWorld(this.hud, point, this.inventoryOpen || this.spellbookOpen)) return; const world = this.toWorld(point); if (!world) return; mainCanvas.setPointerCapture(event.pointerId); if (this.selected.length) this.beginAim(world, event.pointerId); else { this.moveTarget = world; this.moveIndicator = { ...world }; this.moveIndicatorUntil = performance.now() + 350; this.aiming = null; } };
  private pointerMove = (event: PointerEvent) => { if (this.aiming?.pointerId !== event.pointerId) return; const target = this.toWorld(this.screenPoint(event)); if (!target) return; this.aiming.target = this.targetFor(this.aiming.spell, target); this.aim = this.directionTo(this.aiming.target); };
  private pointerUp = (event: PointerEvent) => this.finishAim(event.pointerId);
  private pointerCancel = (event: PointerEvent) => this.finishAim(event.pointerId, true);
  private keyDown = (event: KeyboardEvent) => { const index = Number(event.key) - 1; if (!this.me()?.alive && event.key !== 'Escape') return; if (index >= 0 && index < ELEMENTS.length) this.selectElement(ELEMENTS[index]!); else if (event.key === 'Backspace') this.selected.pop(); else if (event.key === 'Escape') { this.selected = []; this.moveTarget = null; this.inventoryOpen = false; this.spellbookOpen = false; this.selectedItem = null; this.fusionIds = []; } };
  private directionTo(target: Vec2) { const dx = target.x - this.local.x, dy = target.y - this.local.y, length = Math.hypot(dx, dy) || 1; return { x: dx / length, y: dy / length }; }
  private targetFor(spell: SpellSpec, target: Vec2) { if (spell.delivery === 'shield' || spell.delivery === 'environment') return { ...this.local }; const dx = target.x - this.local.x, dy = target.y - this.local.y, distance = Math.hypot(dx, dy); if (!spell.range || distance <= spell.range) return target; return { x: this.local.x + dx / distance * spell.range, y: this.local.y + dy / distance * spell.range }; }
  private clearButton(): Rect { return { x: this.hud.elementPanel.x + this.hud.elementPanel.w - 50, y: this.hud.elementPanel.y - 25, w: 42, h: 22 }; }
  private notify(message: string) { this.notice = message; this.noticeUntil = performance.now() + 1600; }
  private view(width = mainCanvas.width / this.pixelRatio, height = mainCanvas.height / this.pixelRatio) { const stage = this.state?.run.stage, scale = Math.max(.52, Math.min(1, Math.min(width / 1050, height / 720))), worldWidth = stage?.world.width ?? 960, worldHeight = stage?.world.height ?? 600, cameraX = Math.max(width / scale / 2, Math.min(worldWidth - width / scale / 2, this.local.x)), cameraY = Math.max(height / scale / 2, Math.min(worldHeight - height / scale / 2, this.local.y)); return { scale, ox: alignToDevicePixel(width / 2 - cameraX * scale, this.pixelRatio), oy: alignToDevicePixel(height / 2 - cameraY * scale, this.pixelRatio) }; }
  private screenPoint(event: PointerEvent) { const rect = mainCanvas.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; }
  private toWorld(point: Vec2) { const width = mainCanvas.width / this.pixelRatio, height = mainCanvas.height / this.pixelRatio, view = this.view(width, height), stage = this.state?.run.stage, x = (point.x - view.ox) / view.scale, y = (point.y - view.oy) / view.scale; return stage && x >= 0 && x <= stage.world.width && y >= 0 && y <= stage.world.height ? { x, y } : null; }
  private panel(c: CanvasRenderingContext2D, rect: Rect, fill = '#21192b', accent = '#77658d') { this.visuals.uiFrame(c, rect, rect.h <= 58 ? 9 : 8); c.save(); c.globalAlpha = .22; c.fillStyle = fill; c.fillRect(rect.x + 10, rect.y + 10, Math.max(0, rect.w - 20), Math.max(0, rect.h - 20)); c.strokeStyle = accent; c.lineWidth = 1; c.strokeRect(rect.x + 8.5, rect.y + 8.5, Math.max(0, rect.w - 17), Math.max(0, rect.h - 17)); c.restore(); }
  private text(c: CanvasRenderingContext2D, text: string, x: number, y: number, size: number, color: string, align: CanvasTextAlign = 'left') { c.font = `700 ${size}px "PingFang SC", "Microsoft YaHei", ui-monospace, monospace`; c.fillStyle = color; c.textAlign = align; c.textBaseline = 'middle'; c.shadowColor = 'rgba(0,0,0,.65)'; c.shadowBlur = 2; c.fillText(text, x, y); c.shadowBlur = 0; }
  private destroy = () => { this.flow?.game.dispose(); this.flow = null; this.dungeonTiles.clear(); mainCanvas.removeEventListener('pointerdown', this.pointerDown); mainCanvas.removeEventListener('pointermove', this.pointerMove); mainCanvas.removeEventListener('pointerup', this.pointerUp); mainCanvas.removeEventListener('pointercancel', this.pointerCancel); window.removeEventListener('keydown', this.keyDown); };
}
