import { mainCanvas, mainContext } from 'littlejsengine';
import type { Element, ElementStatusType, EntityState, ForgeState, GameEvent, GameState, InventoryItem, LootEntity, MerchantState, PlayerState, SpellSpec, Vec2 } from '../game/contracts';
import { positionAt } from '../game/rules/entities';
import { canFuse, distance, fusionPrice, isCatalyst, isEquipment, isScroll, itemDetailLines, itemTypeText, moveSpeedMultiplier, sellPrice } from '../game/rules/equipment';
import { resolveScrollSpell } from '../game/rules/scrolls';
import { resolveSpell } from '../game/rules/spells';
import { collisionCandidates } from '../runtime/collision';
import { createEndwellFlow, type EndwellFlow } from '../runtime/flow';
import { computeHudLayout, contains, hudBlocksWorld, type HudLayout, type Rect } from '../ui/hud';

const WORLD = { width: 960, height: 600 }, ELEMENTS: Element[] = ['rock', 'fire', 'ice', 'life', 'lightning', 'water', 'shield'];
const COLORS: Record<Element, string> = { rock: '#aa8b68', fire: '#ff5c45', ice: '#77e6ff', life: '#79df78', lightning: '#c596ff', water: '#469cff', shield: '#ffd952' };
const LABELS: Record<Element, string> = { rock: '岩', fire: '火', ice: '冰', life: '命', lightning: '雷', water: '水', shield: '盾' };
const STATUS_LABELS: Partial<Record<ElementStatusType, string>> = { wet: '潮湿', burning: '燃烧', chilled: '冰冷', frozen: '冻结', shocked: '感电', poisoned: '中毒', shielded: '护盾', stoneArmor: '岩甲', regenerating: '再生', hasted: '加速', fireWard: '防火', frostWard: '防霜', waterWard: '防水', grounded: '接地' };
type AimState = { pointerId: number; target: Vec2; spell: SpellSpec; elements: Element[]; castId: string | null };
type ItemSource = 'equipment' | 'inventory' | 'loot' | 'merchant';
type UiAction = Rect & { kind: 'toggle-inventory' | 'close-inventory' | 'select-item' | 'equip' | 'unequip' | 'drop' | 'pickup' | 'buy' | 'sell' | 'fusion-select' | 'fusion-remove' | 'fuse'; source?: ItemSource; itemId?: string; entityId?: string };
type CombatFeedback = { text: string; color: string; createdAt: number; expiresAt: number };

export class EndwellScene {
  private flow: EndwellFlow | null = null; private state: GameState | null = null; private selected: Element[] = []; private local: Vec2 = { x: 260, y: 360 }; private localEpoch = -1; private aim: Vec2 = { x: 1, y: 0 }; private moveTarget: Vec2 | null = null; private aiming: AimState | null = null; private sequence = 0; private poseSequence = 0; private aimSequence = 0; private last = performance.now(); private poseAt = 0; private hitTick = 0; private hitKeys = new Set<string>(); private projectilePrevious = new Map<string, Vec2>(); private feedbacks = new Map<string, CombatFeedback[]>(); private notice = ''; private noticeUntil = 0; private pixelRatio = 1; private hud: HudLayout = computeHudLayout(1280, 720); private lobbyButton: Rect | null = null; private inventoryOpen = false; private selectedItem: { source: ItemSource; itemId: string; entityId?: string } | null = null; private fusionIds: string[] = []; private uiActions: UiAction[] = [];
  init() { this.flow = createEndwellFlow(parti, { state: (state) => this.receive(state), event: (event) => this.event(event) }); mainCanvas.addEventListener('pointerdown', this.pointerDown); mainCanvas.addEventListener('pointermove', this.pointerMove); mainCanvas.addEventListener('pointerup', this.pointerUp); mainCanvas.addEventListener('pointercancel', this.pointerCancel); window.addEventListener('keydown', this.keyDown); window.addEventListener('pagehide', this.destroy, { once: true }); parti.ready(); }
  update() { const now = performance.now(), dt = Math.min(.04, Math.max(.001, (now - this.last) / 1000)); this.last = now; this.pixelRatio = mainCanvas.width / Math.max(1, mainCanvas.clientWidth); if (!this.flow || this.state?.phase !== 'running') return; const meState = this.me(); if (meState && !meState.alive) { this.moveTarget = null; this.aiming = null; } if (meState?.alive && this.moveTarget && !this.aiming) { const me = this.me(), speed = 220 * moveSpeedMultiplier(me?.equipment ?? {}) * (me?.statuses.hasted ? 1.7 : 1), dx = this.moveTarget.x - this.local.x, dy = this.moveTarget.y - this.local.y, distance = Math.hypot(dx, dy), step = speed * dt; if (distance <= step || distance < 3) { this.local = { ...this.moveTarget }; this.moveTarget = null; } else this.local = { x: this.local.x + dx / distance * step, y: this.local.y + dy / distance * step }; }
    if (meState?.alive && now >= this.poseAt) { this.poseAt = now + 64; this.flow.pose({ sequence: ++this.poseSequence, sentAt: Date.now(), position: this.local, aim: this.aim }); if (this.aiming?.castId) this.flow.aim({ sequence: ++this.aimSequence, aim: this.aim }); }
    this.flow.game.update(dt); this.collisions(Date.now()); }
  render() { const c = mainContext, width = mainCanvas.width / this.pixelRatio, height = mainCanvas.height / this.pixelRatio; this.hud = computeHudLayout(width, height); this.uiActions = []; c.save(); c.setTransform(this.pixelRatio, 0, 0, this.pixelRatio, 0, 0); c.fillStyle = '#090a13'; c.fillRect(0, 0, width, height); const view = this.view(width, height); c.save(); c.translate(view.ox, view.oy); c.scale(view.scale, view.scale); this.drawArena(c); c.restore(); if (this.state?.environment.global?.kind === 'rain') this.drawRain(c, width, height); else if (this.state?.environment.global?.kind === 'blizzard') this.drawBlizzard(c, width, height); this.drawHud(c, width, height); if (!this.state) this.overlay(c, width, height, '连接无底之尽…', ''); else if (this.state.phase === 'lobby') this.lobby(c, width, height); else if (this.state.phase === 'gameover') this.overlay(c, width, height, '试炼结束', ''); if (performance.now() < this.noticeUntil) { c.fillStyle = 'rgba(54,24,40,.9)'; c.fillRect(width / 2 - 170, this.hud.message.y, 340, this.hud.message.h); this.text(c, this.notice, width / 2, this.hud.message.y + this.hud.message.h / 2, 13, '#fff', 'center'); } c.restore(); }
  private drawArena(c: CanvasRenderingContext2D) { c.fillStyle = '#111528'; c.fillRect(0, 0, WORLD.width, WORLD.height); c.strokeStyle = '#252c47'; c.lineWidth = 2; for (let x = 0; x <= WORLD.width; x += 60) { c.beginPath(); c.moveTo(x, 0); c.lineTo(x, WORLD.height); c.stroke(); } for (let y = 0; y <= WORLD.height; y += 60) { c.beginPath(); c.moveTo(0, y); c.lineTo(WORLD.width, y); c.stroke(); }
    if (!this.state || !this.flow) return; for (const id of this.flow.game.world.entitiesWith('Transform')) { const pos = this.flow.game.world.getComponent<Vec2>(id, 'Transform'), p = this.flow.game.world.getComponent<PlayerState>(id, 'PlayerState'), e = this.flow.game.world.getComponent<EntityState>(id, 'EntityState'); if (!pos) continue; if (p) this.player(c, p.id === this.flow.game.playerId ? this.local : pos, p); else if (e) this.entity(c, e, positionAt(e, Date.now())); } this.drawEconomyWorld(c);
    if (this.moveTarget) { c.strokeStyle = '#d8cb91'; c.setLineDash([8, 8]); c.beginPath(); c.moveTo(this.local.x, this.local.y); c.lineTo(this.moveTarget.x, this.moveTarget.y); c.stroke(); c.setLineDash([]); c.beginPath(); c.arc(this.moveTarget.x, this.moveTarget.y, 14, 0, Math.PI * 2); c.stroke(); }
    if (this.aiming) this.drawAim(c, this.aiming); }
  private drawAim(c: CanvasRenderingContext2D, state: AimState) { const color = COLORS[state.spell.elements[0] ?? 'rock'], angle = Math.atan2(this.aim.y, this.aim.x); c.strokeStyle = color; c.fillStyle = `${color}35`; c.lineWidth = 3; if (state.spell.delivery === 'spray') { const half = (state.spell.coneAngle ?? Math.PI / 2) / 2; c.beginPath(); c.moveTo(this.local.x, this.local.y); c.arc(this.local.x, this.local.y, state.spell.range, angle - half, angle + half); c.closePath(); c.fill(); c.stroke(); } else if (state.spell.delivery === 'beam') { c.lineWidth = Math.max(3, (state.spell.beam?.width ?? 10) * 2); c.beginPath(); c.moveTo(this.local.x, this.local.y); c.lineTo(this.local.x + this.aim.x * state.spell.range, this.local.y + this.aim.y * state.spell.range); c.stroke(); } else if (state.spell.delivery === 'shield' || state.spell.delivery === 'environment') { c.beginPath(); c.arc(this.local.x, this.local.y, 38, 0, Math.PI * 2); c.stroke(); } else if (state.spell.delivery === 'area' || state.spell.delivery === 'summon' && !state.spell.summon?.archetype.endsWith('wall')) { c.beginPath(); c.arc(state.target.x, state.target.y, state.spell.radius, 0, Math.PI * 2); c.fill(); c.stroke(); } else { c.beginPath(); c.moveTo(this.local.x, this.local.y); c.lineTo(state.target.x, state.target.y); c.stroke(); if (state.spell.delivery === 'summon') c.strokeRect(state.target.x - 18, state.target.y - 70, 36, 140); } }
  private drawEconomyWorld(c: CanvasRenderingContext2D) { if (!this.state) return; const merchant = this.state.merchant, forge = this.state.forge; if (forge) { c.fillStyle = '#9b6038'; c.beginPath(); c.arc(forge.position.x, forge.position.y, 34, 0, Math.PI * 2); c.fill(); c.strokeStyle = '#ffd19c'; c.lineWidth = 3; c.stroke(); this.text(c, '元素合成台', forge.position.x, forge.position.y - 52, 13, '#ffd19c', 'center'); } if (merchant) { c.fillStyle = '#25423d'; c.fillRect(merchant.position.x - 24, merchant.position.y - 30, 48, 60); c.strokeStyle = '#9cf0dc'; c.lineWidth = 3; c.strokeRect(merchant.position.x - 24, merchant.position.y - 30, 48, 60); this.text(c, '流浪商人', merchant.position.x, merchant.position.y - 48, 13, '#9cf0dc', 'center'); } for (const loot of Object.values(this.state.loot)) { const item = loot.item, color = isCatalyst(item) ? '#65f3dc' : isEquipment(item) && item.rarity === 'rare' ? '#d3a2ff' : isEquipment(item) && item.rarity === 'excellent' ? '#83e2a1' : '#eee'; c.fillStyle = color; c.beginPath(); c.arc(loot.position.x, loot.position.y, 14, 0, Math.PI * 2); c.fill(); this.text(c, item.name, loot.position.x, loot.position.y - 26, 10, '#fff', 'center'); } }
  private player(c: CanvasRenderingContext2D, pos: Vec2, p: PlayerState) { c.save(); c.globalAlpha = p.alive ? 1 : .48; c.fillStyle = p.alive ? p.id === this.flow?.game.playerId ? '#f5eecb' : '#75a7ff' : '#8a8792'; c.beginPath(); c.arc(pos.x, pos.y, 24, 0, Math.PI * 2); c.fill(); if (p.shields.length) { c.strokeStyle = '#ffd952'; c.lineWidth = 4; c.beginPath(); c.arc(pos.x, pos.y, 31, 0, Math.PI * 2); c.stroke(); } c.fillStyle = '#16182b'; c.fillRect(pos.x - 27, pos.y - 38, 54, 6); c.fillStyle = p.alive ? '#6ee7a8' : '#777'; c.fillRect(pos.x - 27, pos.y - 38, 54 * p.health.current / p.health.max, 6); this.text(c, p.alive ? p.name : `${p.name} · 已死亡`, pos.x, pos.y - 50, 12, '#fff', 'center'); c.restore(); this.drawStatusLabels(c, pos.x, pos.y + 36, p.statuses); this.drawFeedback(c, p.id, pos.x, pos.y - 62); }
  private entity(c: CanvasRenderingContext2D, e: EntityState, pos: Vec2) { const element = e.source?.spell.elements.find((value) => value !== 'rock' && value !== 'shield' && value !== 'life') ?? e.source?.spell.elements[0] ?? 'rock', color = COLORS[element]; if (e.kind === 'projectile') { c.fillStyle = color; c.beginPath(); c.arc(pos.x, pos.y, e.radius, 0, Math.PI * 2); c.fill(); c.strokeStyle = `${color}88`; c.lineWidth = 5; c.beginPath(); c.moveTo(pos.x - (e.velocity?.x ?? 0) * .05, pos.y - (e.velocity?.y ?? 0) * .05); c.lineTo(pos.x, pos.y); c.stroke(); } else if (e.source?.spell.delivery === 'spray') { const direction = e.direction ?? { x: 1, y: 0 }, angle = Math.atan2(direction.y, direction.x), half = (e.source.spell.coneAngle ?? Math.PI / 2) / 2; c.fillStyle = `${color}55`; c.beginPath(); c.moveTo(e.position.x, e.position.y); c.arc(e.position.x, e.position.y, e.source.spell.range, angle - half, angle + half); c.closePath(); c.fill(); } else if (e.source?.spell.delivery === 'beam') { const direction = e.direction ?? { x: 1, y: 0 }, hit = this.state ? collisionCandidates(this.state, e, Date.now())[0] : undefined, end = hit?.target.position ?? { x: e.position.x + direction.x * e.source.spell.range, y: e.position.y + direction.y * e.source.spell.range }; c.strokeStyle = color; c.lineWidth = Math.max(5, (e.source.spell.beam?.width ?? 10) * 2); c.beginPath(); c.moveTo(e.position.x, e.position.y); c.lineTo(end.x, end.y); c.stroke(); } else if (e.kind === 'warning') { c.strokeStyle = '#ffcc58'; c.lineWidth = 5; c.beginPath(); c.arc(pos.x, pos.y, e.radius, 0, Math.PI * 2); c.stroke(); } else if (e.kind === 'area') { c.fillStyle = '#ff6a3d88'; c.beginPath(); c.arc(pos.x, pos.y, e.radius, 0, Math.PI * 2); c.fill(); } else if (e.kind === 'field') { c.fillStyle = `${color}45`; c.beginPath(); c.arc(e.position.x, e.position.y, e.radius, 0, Math.PI * 2); c.fill(); } else if (e.kind === 'wall') { c.fillStyle = e.archetype === 'ice-wall' ? '#77e6ff' : '#796a61'; c.fillRect(pos.x - 18, pos.y - 70, 36, 140); } else { c.fillStyle = '#d84e69'; c.fillRect(pos.x - e.radius, pos.y - e.radius, e.radius * 2, e.radius * 2); } if (e.health.max > 1) { c.fillStyle = '#301b2d'; c.fillRect(pos.x - 34, pos.y - e.radius - 15, 68, 6); c.fillStyle = '#f06a7e'; c.fillRect(pos.x - 34, pos.y - e.radius - 15, 68 * e.health.current / e.health.max, 6); } this.drawStatusLabels(c, pos.x, pos.y + e.radius + 16, e.statuses); this.drawFeedback(c, e.id, pos.x, pos.y - e.radius - 28); }
  private drawStatusLabels(c: CanvasRenderingContext2D, x: number, y: number, statuses: PlayerState['statuses']) { const labels = Object.keys(statuses).map((key) => STATUS_LABELS[key as ElementStatusType]).filter(Boolean).slice(0, 4); if (!labels.length) return; const text = labels.join(' · '); c.fillStyle = 'rgba(12,10,18,.72)'; c.fillRect(x - text.length * 5 - 8, y - 9, text.length * 10 + 16, 18); this.text(c, text, x, y, 10, '#d9ecff', 'center'); }
  private drawFeedback(c: CanvasRenderingContext2D, id: string, x: number, y: number) { const now = performance.now(), entries = (this.feedbacks.get(id) ?? []).filter((entry) => entry.expiresAt > now); if (!entries.length) { this.feedbacks.delete(id); return; } this.feedbacks.set(id, entries); for (const [index, entry] of entries.slice(-3).entries()) { const age = now - entry.createdAt, alpha = Math.max(0, 1 - age / (entry.expiresAt - entry.createdAt)); c.save(); c.globalAlpha = alpha; this.text(c, entry.text, x, y - index * 15 - age * .025, 12, entry.color, 'center'); c.restore(); } }
  private addFeedback(id: string, text: string, color: string) { const now = performance.now(), entries = this.feedbacks.get(id) ?? []; entries.push({ text, color, createdAt: now, expiresAt: now + 900 }); this.feedbacks.set(id, entries.slice(-5)); }
  private drawRain(c: CanvasRenderingContext2D, width: number, height: number) { c.fillStyle = 'rgba(50,120,180,.16)'; c.fillRect(0, 0, width, height); c.strokeStyle = 'rgba(120,200,255,.55)'; c.lineWidth = 2; const offset = performance.now() / 8 % 36; for (let x = -height; x < width + height; x += 36) { c.beginPath(); c.moveTo(x + offset, 0); c.lineTo(x - height + offset, height); c.stroke(); } }
  private drawBlizzard(c: CanvasRenderingContext2D, width: number, height: number) { c.fillStyle = 'rgba(120,210,255,.12)'; c.fillRect(0, 0, width, height); c.fillStyle = 'rgba(210,245,255,.72)'; const offset = performance.now() / 12 % 48; for (let y = -20; y < height + 20; y += 48) for (let x = -20; x < width + 20; x += 64) { c.beginPath(); c.arc(x + offset, y + (x % 3) * 5, 2.2, 0, Math.PI * 2); c.fill(); } }
  private drawHud(c: CanvasRenderingContext2D, width: number, height: number) {
    if (this.state?.phase !== 'running') return;
    const { status, inventoryButton, elementPanel, elementCenters, compact } = this.hud, me = this.me();
    c.fillStyle = 'rgba(18,14,27,.8)'; c.fillRect(status.x, status.y, status.w, status.h);
    this.text(c, me && !me.alive ? `已死亡 · 等待复活术 · ${me.gold}G` : `HP ${Math.round(me?.health.current ?? 0)} · ${me?.gold ?? 0}G`, status.x + 10, status.y + 18, 12, '#fff');
    c.fillStyle = '#25101a'; c.fillRect(status.x + 10, status.y + 28, status.w - 20, 8);
    c.fillStyle = '#62df7c'; c.fillRect(status.x + 10, status.y + 28, (status.w - 20) * (me?.health.current ?? 0) / Math.max(1, me?.health.max ?? 1), 8);
    c.fillStyle = this.inventoryOpen ? 'rgba(55,42,50,.58)' : 'rgba(32,25,40,.84)'; c.fillRect(inventoryButton.x, inventoryButton.y, inventoryButton.w, inventoryButton.h);
    this.text(c, `背包 ${me?.inventory.length ?? 0}/9`, inventoryButton.x + inventoryButton.w / 2, inventoryButton.y + inventoryButton.h / 2, 11, this.inventoryOpen ? '#9a8d99' : '#fff', 'center');
    if (!this.inventoryOpen) this.uiActions.push({ ...inventoryButton, kind: 'toggle-inventory' });
    c.fillStyle = 'rgba(18,14,27,.78)'; c.fillRect(elementPanel.x, elementPanel.y, elementPanel.w, elementPanel.h);
    const spell = this.selected.length ? this.previewSpell(this.selected) : null, statusText = me && !me.alive ? '你已死亡 · 等待队友使用复活术' : this.aiming ? this.aiming.spell.channelled ? '按住持续施法 · 抬起结束' : '拖动瞄准 · 抬起施法' : spell ? spell.name : '点击场地移动 · 选择元素后按住场地施法';
    this.text(c, `${statusText}${this.selected.length ? ` · ${this.selected.map((e) => LABELS[e]).join('+')}` : ''}`, width / 2, elementPanel.y + 17, compact ? 10 : 12, '#fff', 'center');
    if (this.selected.length && !this.aiming) { const clear = this.clearButton(); c.fillStyle = '#493541'; c.fillRect(clear.x, clear.y, clear.w, clear.h); this.text(c, '清空', clear.x + clear.w / 2, clear.y + clear.h / 2, 9, '#fff', 'center'); }
    for (let i = 0; i < elementCenters.length; i++) { const button = elementCenters[i]!, element = ELEMENTS[i]!, selectedCount = this.selected.filter((value) => value === element).length; c.fillStyle = COLORS[element]; c.beginPath(); c.arc(button.x, button.y, button.r - 3, 0, Math.PI * 2); c.fill(); c.strokeStyle = selectedCount ? '#fff' : '#e8ddcb'; c.lineWidth = selectedCount ? 4 : 2; c.stroke(); this.text(c, LABELS[element], button.x, button.y + 4, compact ? 15 : 18, '#17111f', 'center'); if (selectedCount) this.text(c, String(selectedCount), button.x + button.r - 8, button.y - button.r + 12, 10, '#fff', 'center'); }
    if (this.inventoryOpen) this.drawInventory(c, width, height);
  }
  private drawInventory(c: CanvasRenderingContext2D, width: number, height: number) {
    const me = this.me(); if (!me || !this.state) return;
    const panel = this.hud.inventoryPanel, detailsW = Math.min(250, panel.w * .38), leftW = panel.w - detailsW - 18, x = panel.x, y = panel.y, loot = this.nearbyLoot(), merchant = this.nearbyMerchant(), forge = this.nearbyForge();
    if (!forge) this.fusionIds = []; this.fusionIds = this.fusionIds.filter((id) => me.inventory.some((item) => item.id === id));
    c.fillStyle = 'rgba(8,6,12,.58)'; c.fillRect(0, 0, width, height); c.fillStyle = 'rgba(20,16,28,.98)'; c.fillRect(x, y, panel.w, panel.h);
    this.text(c, `背包 · ${me.gold} 金币`, x + 14, y + 24, 14, '#ffe09a'); let top = y + 42;
    if (forge) {
      const uses = this.state.forgeUses[forge.id]?.[me.id] ?? 0, price = fusionPrice(uses), selected = this.fusionItems(), enabled = selected.length === 3 && canFuse(selected) && me.gold >= price;
      this.text(c, `合成台 · 第 ${uses + 1} 次 ${price}G`, x + 12, top + 12, 11, '#ffd19c');
      for (let i = 0; i < 3; i++) { const slot = { x: x + 128 + i * 74, y: top - 5, w: 68, h: 34 }, item = selected[i]; this.itemCard(c, slot, item, item ? '' : '空位'); if (item) this.uiActions.push({ ...slot, kind: 'fusion-remove', itemId: item.id }); }
      const button = { x: x + Math.min(leftW - 112, 364), y: top - 5, w: 104, h: 34 }; c.fillStyle = enabled ? '#9b6038' : '#40363b'; c.fillRect(button.x, button.y, button.w, button.h); this.text(c, '合成', button.x + button.w / 2, button.y + button.h / 2, 10, enabled ? '#fff' : '#888', 'center'); if (enabled) this.uiActions.push({ ...button, kind: 'fuse', entityId: forge.id }); top += 48;
    }
    const cardH = 44, slotNames = { staff: '法杖', robe: '法袍', ring: '法戒' } as const;
    this.text(c, '装备栏', x + 12, top + 10, 11, '#bcaec8'); top += 18;
    for (const [index, slot] of (['staff', 'robe', 'ring'] as const).entries()) { const rect = { x: x + 12 + index * ((leftW - 24) / 3), y: top, w: (leftW - 36) / 3, h: cardH }, item = me.equipment[slot]; this.itemCard(c, rect, item, slotNames[slot]); if (item) this.uiActions.push({ ...rect, kind: 'select-item', source: 'equipment', itemId: item.id }); }
    top += cardH + 25; this.text(c, '背包区域', x + 12, top - 4, 11, '#bcaec8');
    const cellW = (leftW - 34) / 3;
    for (let i = 0; i < 9; i++) { const item = me.inventory[i], rect = { x: x + 12 + i % 3 * (cellW + 5), y: top + Math.floor(i / 3) * (cardH + 5), w: cellW, h: cardH }; this.itemCard(c, rect, item); if (item) this.uiActions.push({ ...rect, kind: 'select-item', source: 'inventory', itemId: item.id }); }
    top += 3 * (cardH + 5) + 12;
    if (loot.length) { this.text(c, '掉落区域', x + 12, top + 10, 11, '#e4b9ff'); top += 18; for (const entry of loot.slice(0, 3)) { const rect = { x: x + 12, y: top, w: leftW - 24, h: 34 }; this.itemCard(c, rect, entry.item); this.uiActions.push({ ...rect, kind: 'select-item', source: 'loot', itemId: entry.item.id, entityId: entry.id }); top += 38; } }
    if (merchant && top < y + panel.h - 38) { this.text(c, '商人贩卖区域', x + 12, top + 10, 11, '#9cf0dc'); top += 18; for (const entry of merchant.stock.slice(0, Math.max(1, Math.floor((y + panel.h - top - 8) / 38)))) { const rect = { x: x + 12, y: top, w: leftW - 24, h: 34 }; this.itemCard(c, rect, entry.item, `${entry.price}G`); this.uiActions.push({ ...rect, kind: 'select-item', source: 'merchant', itemId: entry.item.id, entityId: merchant.id }); top += 38; } }
    this.drawItemDetails(c, x + leftW + 8, y + 10, detailsW, panel.h - 20, merchant, loot, forge);
    const close = { x: x + panel.w - 72, y: y + 10, w: 58, h: 28 };
    c.fillStyle = '#6b465d'; c.fillRect(close.x, close.y, close.w, close.h);
    c.strokeStyle = '#d8cb91'; c.lineWidth = 1; c.strokeRect(close.x + .5, close.y + .5, close.w - 1, close.h - 1);
    this.text(c, '关闭', close.x + close.w / 2, close.y + close.h / 2, 10, '#fff', 'center');
    this.uiActions.push({ ...close, kind: 'close-inventory' });
  }
  private itemCard(c: CanvasRenderingContext2D, rect: Rect, item?: InventoryItem | null, prefix = '') { const selected = Boolean(item && this.selectedItem?.itemId === item.id); c.fillStyle = selected ? '#655071' : item ? '#373043' : '#211d28'; c.fillRect(rect.x, rect.y, rect.w, rect.h); if (!item) { this.text(c, prefix || '空', rect.x + 8, rect.y + rect.h / 2, 9, '#666'); return; } this.itemIcon(c, item, rect.x + 18, rect.y + rect.h / 2, 11); const color = isCatalyst(item) ? '#65f3dc' : isScroll(item) ? '#f4d56f' : item.rarity === 'rare' ? '#d3a2ff' : item.rarity === 'excellent' ? '#83e2a1' : '#eee'; this.text(c, `${prefix ? `${prefix} · ` : ''}${item.name}`, rect.x + 34, rect.y + rect.h / 2, 10, color); }
  private itemIcon(c: CanvasRenderingContext2D, item: InventoryItem, x: number, y: number, r: number) { c.save(); c.strokeStyle = isCatalyst(item) ? '#65f3dc' : isScroll(item) ? '#f4d56f' : item.slot === 'staff' ? '#e6b06e' : item.slot === 'robe' ? '#83a8e2' : '#d3a2ff'; c.lineWidth = 2; if (isCatalyst(item)) { c.beginPath(); c.moveTo(x, y - r); c.lineTo(x + r, y); c.lineTo(x, y + r); c.lineTo(x - r, y); c.closePath(); c.stroke(); } else if (isScroll(item)) { c.strokeRect(x - r * .7, y - r, r * 1.4, r * 2); c.beginPath(); c.moveTo(x - r * .45, y - r * .45); c.lineTo(x + r * .45, y - r * .45); c.moveTo(x - r * .45, y); c.lineTo(x + r * .35, y); c.stroke(); } else if (item.slot === 'ring') { c.beginPath(); c.arc(x, y, r * .75, 0, Math.PI * 2); c.stroke(); } else if (item.slot === 'staff') { c.beginPath(); c.moveTo(x - r * .5, y + r); c.lineTo(x + r * .45, y - r); c.stroke(); } else { c.beginPath(); c.moveTo(x - r, y - r); c.lineTo(x + r, y - r); c.lineTo(x + r * .7, y + r); c.lineTo(x - r * .7, y + r); c.closePath(); c.stroke(); } c.restore(); }
  private drawItemDetails(c: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, merchant: MerchantState | null, loot: LootEntity[], forge: ForgeState | null) {
    c.fillStyle = '#17131f'; c.fillRect(x, y, w, h); const item = this.selectedInventoryItem(merchant, loot); if (!item) { this.selectedItem = null; this.text(c, '选择物品查看详情', x + w / 2, y + h / 2, 12, '#777', 'center'); return; }
    this.itemIcon(c, item, x + 31, y + 38, 18); this.text(c, item.name, x + 58, y + 30, 14, '#fff'); this.text(c, itemTypeText(item), x + 58, y + 50, 10, '#b9aec3'); let yy = y + 78;
    for (const line of itemDetailLines(item)) { this.text(c, line.slice(0, Math.max(16, Math.floor((w - 24) / 9))), x + 12, yy, 10, '#cdd7ea'); yy += 16; }
    this.text(c, item.description.slice(0, Math.max(16, Math.floor((w - 24) / 9))), x + 12, yy + 10, 10, '#aaa'); yy += 40;
    const add = (label: string, kind: UiAction['kind'], extra: Partial<UiAction> = {}) => { const rect = { x: x + 12, y: yy, w: w - 24, h: 30 }; c.fillStyle = '#493541'; c.fillRect(rect.x, rect.y, rect.w, rect.h); this.text(c, label, rect.x + rect.w / 2, rect.y + rect.h / 2, 10, '#fff', 'center'); this.uiActions.push({ ...rect, kind, itemId: item.id, ...extra }); yy += 36; };
    const source = this.selectedItem?.source;
    if (source === 'loot') add('拾取', 'pickup', { entityId: this.selectedItem?.entityId });
    else if (source === 'merchant') add('购买', 'buy', { entityId: merchant?.id });
    else if (source === 'equipment') add('卸下', 'unequip');
    else if (source === 'inventory') { if (isEquipment(item)) add('装配', 'equip'); add('丢弃', 'drop'); if (merchant && (isEquipment(item) || isScroll(item))) add(`出售 ${sellPrice(item)}G`, 'sell', { entityId: merchant.id }); if (forge && this.canAddFusion(item)) add('放入合成台', 'fusion-select'); }
  }
  private me() { return this.flow && this.state ? this.state.players[this.flow.game.playerId] : undefined; }
  private previewSpell(elements: Element[]) { const me = this.me(); return me ? resolveScrollSpell(elements, me, Date.now()) ?? resolveSpell(elements) : resolveSpell(elements); }
  private nearbyLoot() { return this.state ? Object.values(this.state.loot).filter((entry) => distance(this.local, entry.position) <= 125) : []; }
  private nearbyMerchant() { const merchant = this.state?.merchant; return merchant && distance(this.local, merchant.position) <= merchant.radius + 90 ? merchant : null; }
  private nearbyForge() { const forge = this.state?.forge; return forge && distance(this.local, forge.position) <= forge.radius + 90 ? forge : null; }
  private selectedInventoryItem(merchant: MerchantState | null, loot: LootEntity[]) { const selected = this.selectedItem, me = this.me(); if (!selected || !me) return null; if (selected.source === 'inventory') return me.inventory.find((item) => item.id === selected.itemId) ?? null; if (selected.source === 'equipment') return Object.values(me.equipment).find((item) => item?.id === selected.itemId) ?? null; if (selected.source === 'loot') return loot.find((entry) => entry.id === selected.entityId)?.item ?? null; return merchant?.stock.find((entry) => entry.item.id === selected.itemId)?.item ?? null; }
  private fusionItems() { const me = this.me(); return this.fusionIds.map((id) => me?.inventory.find((item) => item.id === id)).filter((item): item is InventoryItem => Boolean(item)); }
  private canAddFusion(item: InventoryItem) { if (this.fusionIds.length >= 3 || this.fusionIds.includes(item.id)) return false; const chosen = this.fusionItems(); if (isCatalyst(item)) return !chosen.some(isCatalyst); if (!isEquipment(item)) return false; const equipment = chosen.filter(isEquipment); return !equipment.length || equipment[0]!.slot === item.slot; }
  private handleUiAction(action: UiAction) {
    if (action.kind === 'toggle-inventory') { this.inventoryOpen = !this.inventoryOpen; if (!this.inventoryOpen) { this.selectedItem = null; this.fusionIds = []; } return true; }
    if (action.kind === 'close-inventory') { this.inventoryOpen = false; this.selectedItem = null; this.fusionIds = []; return true; }
    if (action.kind === 'select-item' && action.source && action.itemId) { this.selectedItem = { source: action.source, itemId: action.itemId, entityId: action.entityId }; return true; }
    if (action.kind === 'fusion-remove' && action.itemId) { this.fusionIds = this.fusionIds.filter((id) => id !== action.itemId); return true; }
    if (!this.me()?.alive) { this.notify('已死亡，等待复活术'); return true; }
    if (action.kind === 'fusion-select' && action.itemId) { const item = this.me()?.inventory.find((value) => value.id === action.itemId); if (!item || !this.canAddFusion(item)) this.notify(this.fusionIds.length >= 3 ? '合成台已满' : '只能放入同类型装备或合成宝珠'); else this.fusionIds.push(item.id); return true; }
    if (action.kind === 'fuse' && action.entityId) { this.flow?.fuse(action.entityId, [...this.fusionIds]); this.fusionIds = []; this.selectedItem = null; return true; }
    if (action.kind === 'equip' && action.itemId) this.flow?.equip(action.itemId);
    else if (action.kind === 'unequip' && action.itemId) this.flow?.unequip(action.itemId);
    else if (action.kind === 'drop' && action.itemId) this.flow?.drop(action.itemId);
    else if (action.kind === 'pickup' && action.entityId) this.flow?.pickup(action.entityId);
    else if (action.kind === 'buy' && action.entityId && action.itemId) this.flow?.buy(action.entityId, action.itemId);
    else if (action.kind === 'sell' && action.entityId && action.itemId) this.flow?.sell(action.entityId, action.itemId);
    else return false;
    this.selectedItem = null; return true;
  }
  private lobby(c: CanvasRenderingContext2D, width: number, height: number) { this.overlay(c, width, height, 'ENDWELL', '触碰元素，点击场地'); this.lobbyButton = null; if (this.state?.hostId === parti.playerId) { const rect = { x: width / 2 - 100, y: height / 2 + 48, w: 200, h: 52 }; this.lobbyButton = rect; c.fillStyle = '#e7d89d'; c.fillRect(rect.x, rect.y, rect.w, rect.h); this.text(c, '开始试炼', width / 2, rect.y + rect.h / 2, 17, '#171522', 'center'); } }
  private overlay(c: CanvasRenderingContext2D, width: number, height: number, title: string, sub: string) { c.fillStyle = 'rgba(6,7,15,.82)'; c.fillRect(0, 0, width, height); this.text(c, title, width / 2, height / 2 - 34, 32, '#f4e9c6', 'center'); this.text(c, sub, width / 2, height / 2 + 6, 15, '#aeb4d1', 'center'); }
  private collisions(now: number) { if (!this.state || !this.flow) return; const me = this.flow.game.playerId, alive = new Set<string>(); for (const source of Object.values(this.state.entities)) { if (source.ownerId !== me || !source.source) continue; alive.add(source.id); const current = positionAt(source, now), previous = this.projectilePrevious.get(source.id) ?? current, tick = source.source.tickMs > 0 ? Math.floor(now / source.source.tickMs) : 0, candidates = collisionCandidates(this.state, source, now, previous); for (const candidate of candidates) { const key = `${source.id}:${candidate.target.id}:${tick}`; if (this.hitKeys.has(key)) continue; this.hitKeys.add(key); this.flow.hit({ hitId: `${source.id}:hit:${candidate.target.id}:${tick}`, sourceId: source.id, targetId: candidate.target.id, tick: ++this.hitTick, reason: candidate.reason }); if (source.kind === 'projectile' && !source.source.spell.tags.includes('pierce')) break; } this.projectilePrevious.set(source.id, current); } for (const id of this.projectilePrevious.keys()) if (!alive.has(id)) this.projectilePrevious.delete(id); if (this.hitKeys.size > 500) this.hitKeys.clear(); }
  private receive(state: GameState) { const previousPhase = this.state?.phase; this.state = state; const me = this.flow && state.players[this.flow.game.playerId]; if (me) { if (previousPhase !== 'running' && state.phase === 'running' || this.localEpoch !== me.positionEpoch) { const forced = Boolean(me.forceVelocity); this.local = { ...me.position }; this.localEpoch = me.positionEpoch; if (!forced) this.moveTarget = null; } this.poseSequence = Math.max(this.poseSequence, me.lastPoseSequence); this.sequence = Math.max(this.sequence, me.lastCastSequence); } }
  private event(event: GameEvent) { if (event.type === 'reaction_triggered') this.notify(event.id); else if (event.type === 'cast_interrupted' && event.reason !== 'cancelled') this.notify(`施法中断：${event.reason ?? ''}`); if (event.type === 'damage_applied') this.addFeedback(event.targetId, `-${Math.round(event.amount)}`, '#ff8b8b'); else if (event.type === 'heal_applied') this.addFeedback(event.targetId, `+${Math.round(event.amount)}`, '#7df09a'); else if (event.type === 'status_applied') this.addFeedback(event.targetId, STATUS_LABELS[event.status] ?? event.status, '#d9ecff'); }
  private selectElement(element: Element) { if (!this.me()?.alive || this.aiming || this.selected.length >= 4) return; this.selected.push(element); }
  private beginAim(target: Vec2, pointerId: number) { if (!this.me()?.alive) { this.notify('已死亡，等待复活术'); return; } const elements = [...this.selected], spell = this.previewSpell(elements), resolvedTarget = this.targetFor(spell, target), direction = this.directionTo(resolvedTarget); this.aim = direction; this.moveTarget = null; const castId = spell.channelled ? this.flow!.cast(++this.sequence, elements, direction, resolvedTarget) : null; this.aiming = { pointerId, target: resolvedTarget, spell, elements, castId }; }
  private finishAim(pointerId: number, cancelled = false) { const state = this.aiming; if (!state || state.pointerId !== pointerId) return; this.aiming = null; if (state.spell.channelled) { if (state.castId) this.flow?.release(state.castId); this.selected = []; return; } if (!cancelled) { this.flow?.cast(++this.sequence, state.elements, this.directionTo(state.target), state.target); this.selected = []; } }
  private pointerDown = (event: PointerEvent) => { const point = this.screenPoint(event); if (this.state?.phase === 'lobby') { if (this.lobbyButton && contains(this.lobbyButton, point)) this.flow?.start(); return; } if (this.state?.phase !== 'running') return; const action = [...this.uiActions].reverse().find((entry) => contains(entry, point)); if (action && this.handleUiAction(action)) return; if (!this.me()?.alive) { this.notify('已死亡，等待复活术'); return; } if (this.selected.length && !this.aiming && contains(this.clearButton(), point)) { this.selected = []; return; } const elementIndex = this.hud.elementCenters.findIndex((button) => Math.hypot(point.x - button.x, point.y - button.y) <= button.r); if (elementIndex >= 0) { this.selectElement(ELEMENTS[elementIndex]!); return; } if (hudBlocksWorld(this.hud, point, this.inventoryOpen)) return; const world = this.toWorld(point); if (!world) return; mainCanvas.setPointerCapture(event.pointerId); if (this.selected.length) this.beginAim(world, event.pointerId); else { this.moveTarget = world; this.aiming = null; } };
  private pointerMove = (event: PointerEvent) => { if (this.aiming?.pointerId !== event.pointerId) return; const target = this.toWorld(this.screenPoint(event)); if (!target) return; this.aiming.target = this.targetFor(this.aiming.spell, target); this.aim = this.directionTo(this.aiming.target); };
  private pointerUp = (event: PointerEvent) => this.finishAim(event.pointerId);
  private pointerCancel = (event: PointerEvent) => this.finishAim(event.pointerId, true);
  private keyDown = (event: KeyboardEvent) => { const index = Number(event.key) - 1; if (!this.me()?.alive && event.key !== 'Escape') return; if (index >= 0 && index < ELEMENTS.length) this.selectElement(ELEMENTS[index]!); else if (event.key === 'Backspace') this.selected.pop(); else if (event.key === 'Escape') { this.selected = []; this.moveTarget = null; } };
  private directionTo(target: Vec2) { const dx = target.x - this.local.x, dy = target.y - this.local.y, length = Math.hypot(dx, dy) || 1; return { x: dx / length, y: dy / length }; }
  private targetFor(spell: SpellSpec, target: Vec2) { if (spell.delivery === 'shield' || spell.delivery === 'environment') return { ...this.local }; const dx = target.x - this.local.x, dy = target.y - this.local.y, distance = Math.hypot(dx, dy); if (!spell.range || distance <= spell.range) return target; return { x: this.local.x + dx / distance * spell.range, y: this.local.y + dy / distance * spell.range }; }
  private clearButton(): Rect { return { x: this.hud.elementPanel.x + this.hud.elementPanel.w - 50, y: this.hud.elementPanel.y + 5, w: 42, h: 24 }; }
  private notify(message: string) { this.notice = message; this.noticeUntil = performance.now() + 1600; }
  private view(width = mainCanvas.width / this.pixelRatio, height = mainCanvas.height / this.pixelRatio) { const scale = Math.min(width / WORLD.width, height / WORLD.height), ox = (width - WORLD.width * scale) / 2, oy = (height - WORLD.height * scale) / 2; return { scale, ox, oy }; }
  private screenPoint(event: PointerEvent) { const rect = mainCanvas.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; }
  private toWorld(point: Vec2) { const width = mainCanvas.width / this.pixelRatio, height = mainCanvas.height / this.pixelRatio, view = this.view(width, height), x = (point.x - view.ox) / view.scale, y = (point.y - view.oy) / view.scale; return x >= 0 && x <= WORLD.width && y >= 0 && y <= WORLD.height ? { x, y } : null; }
  private text(c: CanvasRenderingContext2D, text: string, x: number, y: number, size: number, color: string, align: CanvasTextAlign = 'left') { c.font = `600 ${size}px ui-monospace, monospace`; c.fillStyle = color; c.textAlign = align; c.textBaseline = 'middle'; c.fillText(text, x, y); }
  private destroy = () => { this.flow?.game.dispose(); this.flow = null; mainCanvas.removeEventListener('pointerdown', this.pointerDown); mainCanvas.removeEventListener('pointermove', this.pointerMove); mainCanvas.removeEventListener('pointerup', this.pointerUp); mainCanvas.removeEventListener('pointercancel', this.pointerCancel); window.removeEventListener('keydown', this.keyDown); };
}
