import { describe, expect, it } from 'vitest';
import type { FlowReducerContext, GameAction } from '@parti/flow';
import type { GameState, SpellSpec } from './contracts';
import { endwellGame } from './definition';
import { initialState, player } from './rules/state';
import { resolveSpell } from './rules/spells';

function setup(spell: SpellSpec) { const state = initialState(), p = state.players.p1 = player('p1', 'one', 0), timers: Array<{ action: string; payload: unknown }> = []; state.phase = 'running'; p.cast = { phase: 'chanting', castId: 'p1:cast:1', spell, startedAt: 0, phaseEndsAt: 100, aim: { x: 1, y: 0 }, target: { x: 600, y: 300 } }; const actor = { id: p.id, name: p.name, role: 'host' as const }, ctx: FlowReducerContext<GameState> = { state, role: 'authority', actor, players: [actor], host: actor, now: () => 1000, random: () => .5, timers: { dispatch(_name, _delay, action, payload) { timers.push({ action, payload }); }, clear() {} }, emit() {}, dispatch() {}, kick() {} }; const action = { id: 'a', type: '', payload: null, from: p.id, seq: 1, origin: 'host', createdAt: 0 } as GameAction; return { state, p, ctx, action, timers }; }
describe('delivery activation', () => {
  it('applies shields without spawning a fake hit source', () => { const test = setup(resolveSpell(['fire', 'shield'])); endwellGame.actions['internal.castActivate']!.reduce(test.ctx, { playerId: 'p1', castId: 'p1:cast:1' }, test.action); expect(test.p.shields).toHaveLength(1); expect(test.state.entities).toEqual({}); expect(test.p.cast.phase).toBe('recovery'); });
  it('creates meteor warning then impact', () => { const test = setup(resolveSpell(['fire', 'rock', 'rock', 'fire'])); endwellGame.actions['internal.castActivate']!.reduce(test.ctx, { playerId: 'p1', castId: 'p1:cast:1' }, test.action); expect(test.state.entities['p1:cast:1:warning:0']?.source).toBeUndefined(); endwellGame.actions['internal.areaImpact']!.reduce(test.ctx, { playerId: 'p1', castId: 'p1:cast:1' }, test.action); expect(test.state.entities['p1:cast:1:warning:0']).toBeUndefined(); expect(test.state.entities['p1:cast:1:area:0']?.source?.spell.id).toBe('meteor'); });
  it('starts rain and advances authoritative wet ticks', () => { const test = setup(resolveSpell(['fire', 'water', 'water', 'fire'])); endwellGame.actions['internal.castActivate']!.reduce(test.ctx, { playerId: 'p1', castId: 'p1:cast:1' }, test.action); const environment = test.state.environment.global!; expect(environment.kind).toBe('rain'); for (let i = 0; i < 6; i++) endwellGame.actions['internal.environmentTick']!.reduce(test.ctx, { environmentId: environment.id }, test.action); expect(test.p.statuses.wet).toBeDefined(); expect(test.p.statuses.burning).toBeUndefined(); endwellGame.actions['internal.environmentExpire']!.reduce(test.ctx, { environmentId: environment.id }, test.action); expect(test.state.environment.global).toBeNull(); });
});
