import { accept, defineGame, reject, type FlowReducerContext } from '@parti/flow';
import type { CastAimPayload, CastReleasePayload, CastRequestPayload, ElementStatusType, GameEvent, GameState, HitEvent, HitRequestPayload, PlayerState, PosePayload, SpellSpec, Vec2 } from './contracts';
import { applyHit } from './rules/combat';
import { spawnMeteorImpact, spawnMeteorWarning, spawnSpellEntity } from './rules/entities';
import { applySpellModifiers } from './rules/modifiers';
import { idleCast, initialState, normalize, player, trainingMonster } from './rules/state';
import { resolveSpell } from './rules/spells';
import { ELEMENTS } from '../content/spells';

const finiteVec = (value: Vec2) => Number.isFinite(value?.x) && Number.isFinite(value?.y);
const clampPosition = (value: Vec2): Vec2 => ({ x: Math.max(30, Math.min(930, value.x)), y: Math.max(80, Math.min(520, value.y)) });
const emitAll = (ctx: FlowReducerContext<GameState>, events: GameEvent[]) => { for (const event of events) ctx.emit(`endwell.${event.type}`, event); };
function clampTarget(origin: Vec2, target: Vec2, range: number) { const dx = target.x - origin.x, dy = target.y - origin.y, distance = Math.hypot(dx, dy); if (!range || distance <= range) return clampPosition(target); const scale = range / Math.max(1, distance); return clampPosition({ x: origin.x + dx * scale, y: origin.y + dy * scale }); }
function recovery(ctx: FlowReducerContext<GameState>, p: PlayerState, castId: string, spell: SpellSpec) { p.cast.phase = 'recovery'; p.cast.phaseEndsAt = ctx.now() + spell.recoveryMs; if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${castId}:idle`, spell.recoveryMs, 'internal.castIdle', { playerId: p.id, castId }, p.id); }
function applyRain(state: GameState, now: number, ownerId: string) { const all = [...Object.values(state.players), ...Object.values(state.entities).filter((entity) => entity.kind === 'monster')]; for (const target of all) { delete target.statuses.burning; target.buildup.burning = 0; target.buildup.wet = (target.buildup.wet ?? 0) + 18; if ((target.buildup.wet ?? 0) >= 100) { target.buildup.wet = 0; target.statuses.wet = { type: 'wet', endsAt: now + 2400, potency: 1, stacks: 1, sourceId: ownerId, tags: ['rain'] }; } } }

export const endwellGame = defineGame<GameState>({
  meta: { name: 'Endwell', minPlayers: 1, maxPlayers: 4 }, initialState,
  lifecycle: {
    create(ctx) { ctx.state.seed = Math.floor(ctx.random() * 0x7fffffff); },
    join(ctx, joined) { ctx.state.hostId ??= joined.id; const existing = ctx.state.players[joined.id]; if (existing) existing.connected = true; else ctx.state.players[joined.id] = player(joined.id, joined.name || `巫师 ${Object.keys(ctx.state.players).length + 1}`, Object.keys(ctx.state.players).length); },
    reconnect(ctx, joined) { if (ctx.state.players[joined.id]) ctx.state.players[joined.id].connected = true; },
    leave(ctx, leaving) { if (ctx.state.players[leaving.id]) ctx.state.players[leaving.id].connected = false; if (ctx.state.hostId === leaving.id) ctx.state.hostId = Object.values(ctx.state.players).find((p) => p.connected)?.id ?? null; },
  },
  actions: {
    'game.start': { sync: { mode: 'hostAuthoritative' }, validate(ctx) { return ctx.actor.id === ctx.state.hostId ? accept(null) : reject('host-only'); }, reduce(ctx) { ctx.state.phase = 'running'; ctx.state.startedAt = ctx.now(); ctx.state.worldTime = ctx.now(); ctx.state.entities = { 'monster:training': trainingMonster(ctx.now()) }; ctx.state.environment = { global: null, fields: [] }; ctx.state.seen = { hits: {}, spawns: {} }; for (const [index, p] of Object.values(ctx.state.players).entries()) { p.position = { x: 180 + index * 80, y: 360 }; p.positionEpoch += 1; p.alive = true; p.health.current = p.health.max; p.cast = idleCast(); p.shields = []; } ctx.state.message = '元素试炼开始'; } },
    'game.finish': { sync: { mode: 'hostAuthoritative' }, validate(ctx) { return ctx.actor.id === ctx.state.hostId ? accept(null) : reject('host-only'); }, reduce(ctx) { ctx.state.phase = 'gameover'; ctx.state.message = '试炼结束'; } },
    'player.pose': { sync: { mode: 'hostRelay' }, validate(ctx, payload: PosePayload) { const p = ctx.state.players[ctx.actor.id]; if (!p || !Number.isInteger(payload.sequence) || payload.sequence <= p.lastPoseSequence || !Number.isFinite(payload.sentAt) || !finiteVec(payload.position) || !finiteVec(payload.aim)) return reject('invalid-pose'); return accept({ ...payload, sentAt: Math.max(ctx.now() - 5000, Math.min(ctx.now() + 1000, payload.sentAt)), position: clampPosition(payload.position), aim: normalize(payload.aim) }); }, reduce(ctx, payload: PosePayload) { const p = ctx.state.players[ctx.actor.id]; if (!p || payload.sequence <= p.lastPoseSequence) return; p.lastPoseSequence = payload.sequence; p.position = payload.position; p.aim = payload.aim; if (p.cast.phase === 'active' && p.cast.spell?.channelled) { p.cast.aim = payload.aim; for (const entity of Object.values(ctx.state.entities)) if (entity.ownerId === p.id && !entity.detached) { entity.position = { ...p.position }; entity.direction = payload.aim; } } ctx.emit('endwell.player_pose', { playerId: p.id, ...payload }); } },
    'cast.request': { sync: { mode: 'hostRelay' }, validate(ctx, payload: CastRequestPayload) { const p = ctx.state.players[ctx.actor.id]; if (ctx.state.phase !== 'running' || !p?.alive || p.cast.phase !== 'idle' || !Number.isInteger(payload.sequence) || payload.sequence <= p.lastCastSequence || payload.castId !== `${ctx.actor.id}:cast:${payload.sequence}` || !Array.isArray(payload.elements) || payload.elements.length < 1 || payload.elements.length > 4 || !payload.elements.every((element) => ELEMENTS.includes(element)) || !finiteVec(payload.aim) || !finiteVec(payload.target)) return reject('invalid-cast'); const spell = resolveSpell(payload.elements); return accept({ ...payload, aim: normalize(payload.aim), target: spell.delivery === 'shield' || spell.delivery === 'environment' ? { ...p.position } : clampTarget(p.position, payload.target, spell.range) }); }, reduce(ctx, payload: CastRequestPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p || payload.sequence <= p.lastCastSequence || p.cast.phase !== 'idle') return; const spell = applySpellModifiers(resolveSpell(payload.elements), p.buffs.flatMap((buff) => buff.modifiers)); p.lastCastSequence = payload.sequence; p.cast = { phase: 'chanting', castId: payload.castId, spell, startedAt: ctx.now(), phaseEndsAt: ctx.now() + spell.chantMs, aim: normalize(payload.aim), target: payload.target }; ctx.emit('endwell.cast_started', { type: 'cast_started', casterId: p.id, spellId: spell.id } satisfies GameEvent); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:activate`, spell.chantMs, 'internal.castActivate', { playerId: p.id, castId: payload.castId }, p.id); } },
    'cast.aim': { sync: { mode: 'hostRelay' }, validate(_ctx, payload: CastAimPayload) { return finiteVec(payload.aim) && Number.isInteger(payload.sequence) ? accept({ ...payload, aim: normalize(payload.aim) }) : reject('invalid-aim'); }, reduce(ctx, payload: CastAimPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p) return; p.aim = payload.aim; if (p.cast.phase === 'chanting' || p.cast.phase === 'active') p.cast.aim = payload.aim; if (p.cast.phase === 'active') for (const entity of Object.values(ctx.state.entities)) if (entity.ownerId === p.id && !entity.detached) { entity.position = { ...p.position }; entity.direction = payload.aim; } } },
    'cast.release': { sync: { mode: 'hostRelay' }, validate(ctx, payload: CastReleasePayload) { return ctx.state.players[ctx.actor.id]?.cast.castId === payload.castId ? accept(payload) : reject('cast-mismatch'); }, reduce(ctx, payload: CastReleasePayload) { const p = ctx.state.players[ctx.actor.id]; if (!p || p.cast.castId !== payload.castId || !p.cast.spell?.channelled) return; for (const entity of Object.values(ctx.state.entities)) if (entity.ownerId === p.id && !entity.detached) delete ctx.state.entities[entity.id]; const early = p.cast.phase === 'chanting'; if (early) ctx.emit('endwell.cast_interrupted', { type: 'cast_interrupted', casterId: p.id, reason: 'cancelled' } satisfies GameEvent); recovery(ctx, p, payload.castId, p.cast.spell); } },
    'internal.castActivate': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string }) { const p = ctx.state.players[payload.playerId], spell = p?.cast.spell; if (!p || !spell || p.cast.castId !== payload.castId || p.cast.phase !== 'chanting') return; p.cast.phase = 'active'; p.cast.phaseEndsAt = spell.channelled ? ctx.now() + spell.lifetimeMs : ctx.now(); if (spell.delivery === 'shield' && spell.shield) { p.shields.push({ id: payload.castId, amount: spell.shield.amount, maxAmount: spell.shield.amount, absorbElements: spell.shield.absorbElements, priority: 10, tags: spell.tags }); recovery(ctx, p, payload.castId, spell); return; } if (spell.delivery === 'environment' && spell.environment) { ctx.state.environment.global = { id: payload.castId, kind: spell.environment.kind, ownerId: p.id, startedAt: ctx.now(), endsAt: ctx.now() + spell.environment.duration, tickInterval: spell.environment.tickInterval, nextTickAt: ctx.now() }; recovery(ctx, p, payload.castId, spell); return; } if (spell.delivery === 'area' && spell.area) { const warning = spawnMeteorWarning(ctx.state, p, spell, ctx.now()); p.cast.phase = 'warning'; p.cast.phaseEndsAt = ctx.now() + spell.area.warningMs; ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: warning.id } satisfies GameEvent); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:impact`, spell.area.warningMs, 'internal.areaImpact', payload, p.id); return; } const entity = spawnSpellEntity(ctx.state, p, spell, ctx.now()); ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: entity.id } satisfies GameEvent); if (spell.channelled) { if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:interrupt`, spell.lifetimeMs, 'cast.interrupt', { playerId: p.id, castId: payload.castId, reason: 'timeout' }, p.id); } else recovery(ctx, p, payload.castId, spell); } },
    'internal.areaImpact': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string }) { const p = ctx.state.players[payload.playerId], spell = p?.cast.spell; if (!p || !spell || p.cast.castId !== payload.castId || spell.delivery !== 'area') return; delete ctx.state.entities[`${payload.castId}:warning:0`]; const impact = spawnMeteorImpact(ctx.state, p, spell, ctx.now()); ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: impact.id } satisfies GameEvent); recovery(ctx, p, payload.castId, spell); } },
    'internal.castIdle': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string }) { const p = ctx.state.players[payload.playerId]; if (p?.cast.castId === payload.castId) p.cast = idleCast(p.aim); } },
    'cast.interrupt': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string; reason: string }) { const p = ctx.state.players[payload.playerId]; if (!p || p.cast.castId !== payload.castId) return; for (const entity of Object.values(ctx.state.entities)) if (entity.ownerId === p.id && !entity.detached) delete ctx.state.entities[entity.id]; p.cast.phase = 'interrupted'; p.cast.phaseEndsAt = ctx.now() + 350; ctx.emit('endwell.cast_interrupted', { type: 'cast_interrupted', casterId: p.id, reason: payload.reason } satisfies GameEvent); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:idle`, 350, 'internal.castIdle', { playerId: p.id, castId: payload.castId }, p.id); } },
    'combat.hit': { sync: { mode: 'hostRelay' }, validate(ctx, payload: HitRequestPayload) { const source = ctx.state.entities[payload.sourceId]; if (!source?.source || source.ownerId !== ctx.actor.id || !ctx.state.players[payload.targetId] && !ctx.state.entities[payload.targetId] || typeof payload.hitId !== 'string' || payload.hitId.length > 160 || payload.reason !== 'hit' && payload.reason !== 'blocked' || ctx.state.seen.hits[payload.hitId]) return reject('invalid-hit'); return accept(payload); }, reduce(ctx, payload: HitRequestPayload) { const source = ctx.state.entities[payload.sourceId]; if (!source?.source) return; const event: HitEvent = { hitId: payload.hitId, sourceId: source.id, ownerId: source.ownerId, targetId: payload.targetId, payload: source.source.spell.payload, delivery: source.source.spell.delivery, detached: source.detached, tags: source.source.spell.tags }; const resolution = applyHit(ctx.state, event, ctx.now()); emitAll(ctx, resolution.events); if (!resolution.accepted && payload.reason !== 'blocked') return; const target = ctx.state.players[payload.targetId] ?? ctx.state.entities[payload.targetId]; if (resolution.accepted && target && target.health.current <= 0) { if ('alive' in target) target.alive = false; else delete ctx.state.entities[payload.targetId]; ctx.emit('endwell.entity_destroyed', { type: 'entity_destroyed', entityId: payload.targetId } satisfies GameEvent); } if (source.kind === 'projectile') delete ctx.state.entities[source.id]; } },
    'internal.environmentTick': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { environmentId: string }) { const environment = ctx.state.environment.global; if (!environment || environment.id !== payload.environmentId) return; applyRain(ctx.state, ctx.now(), environment.ownerId); environment.nextTickAt = ctx.now() + environment.tickInterval; } },
    'internal.environmentExpire': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { environmentId: string }) { if (ctx.state.environment.global?.id === payload.environmentId) ctx.state.environment.global = null; } },
    'entity.expire': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { entityId: string }) { if (!ctx.state.entities[payload.entityId]) return; delete ctx.state.entities[payload.entityId]; ctx.state.environment.fields = ctx.state.environment.fields.filter((id) => id !== payload.entityId); ctx.emit('endwell.entity_destroyed', { type: 'entity_destroyed', entityId: payload.entityId } satisfies GameEvent); } },
  },
  systems: [{ runOn: 'authority', intervalMs: 100, update(ctx) { const now = ctx.now(); ctx.state.worldTime = now; for (const [id, entity] of Object.entries(ctx.state.entities)) if (entity.expiresAt != null && entity.expiresAt <= now) ctx.dispatch('entity.expire', { entityId: id }, ctx.host.id); const environment = ctx.state.environment.global; if (environment && environment.endsAt <= now) ctx.dispatch('internal.environmentExpire', { environmentId: environment.id }, ctx.host.id); else if (environment && environment.nextTickAt <= now) ctx.dispatch('internal.environmentTick', { environmentId: environment.id }, ctx.host.id); for (const target of [...Object.values(ctx.state.players), ...Object.values(ctx.state.entities)]) for (const [key, instance] of Object.entries(target.statuses)) if (instance && instance.endsAt <= now) delete target.statuses[key as ElementStatusType]; } }],
});
