import { accept, defineGame, reject, type FlowReducerContext } from '@parti/flow';
import type { CastAimPayload, CastReleasePayload, CastRequestPayload, Element, ElementStatusType, ForgeFusePayload, GameEvent, GameState, HitEvent, HitRequestPayload, InventoryItem, ItemActionPayload, MerchantItemPayload, PickupPayload, PlayerState, PosePayload, SpellSpec, Vec2 } from './contracts';
import { applyHit } from './rules/combat';
import { spawnMeteorImpact, spawnMeteorWarning, spawnSpellEntity } from './rules/entities';
import { applyEquipmentToSpell, canFuse, distance, fusionPrice, fusionSeed, fuseEquipment, isEquipment, isScroll, sellPrice } from './rules/equipment';
import { applySpellModifiers } from './rules/modifiers';
import { ownedReadyScrollFor, resolveScrollSpell } from './rules/scrolls';
import { idleCast, initialEconomy, initialState, normalize, player, trainingMonster } from './rules/state';
import { resolveSpell } from './rules/spells';
import { ELEMENTS } from '../content/spells';

const finiteVec = (value: Vec2) => Number.isFinite(value?.x) && Number.isFinite(value?.y);
const clampPosition = (value: Vec2): Vec2 => ({ x: Math.max(30, Math.min(930, value.x)), y: Math.max(80, Math.min(520, value.y)) });
const emitAll = (ctx: FlowReducerContext<GameState>, events: GameEvent[]) => { for (const event of events) ctx.emit(`endwell.${event.type}`, event); };
const playerAlive = (ctx: FlowReducerContext<GameState>) => Boolean(ctx.state.players[ctx.actor.id]?.alive);
const FORCE_DAMPING_PER_SECOND = .18;
function integrateForceMotion(target: PlayerState | NonNullable<GameState['entities'][string]>, dt: number) {
  const velocity = target.forceVelocity;
  if (!velocity) return false;
  const next = clampPosition({ x: target.position.x + velocity.x * dt, y: target.position.y + velocity.y * dt });
  const moved = Math.hypot(next.x - target.position.x, next.y - target.position.y) > .01;
  target.position = next;
  const damping = Math.pow(FORCE_DAMPING_PER_SECOND, dt), slowed = { x: velocity.x * damping, y: velocity.y * damping };
  if (Math.hypot(slowed.x, slowed.y) < 4) delete target.forceVelocity;
  else target.forceVelocity = slowed;
  if (moved && 'positionEpoch' in target) target.positionEpoch += 1;
  return moved;
}
function clampTarget(origin: Vec2, target: Vec2, range: number) { const dx = target.x - origin.x, dy = target.y - origin.y, distance = Math.hypot(dx, dy); if (!range || distance <= range) return clampPosition(target); const scale = range / Math.max(1, distance); return clampPosition({ x: origin.x + dx * scale, y: origin.y + dy * scale }); }
function recovery(ctx: FlowReducerContext<GameState>, p: PlayerState, castId: string, spell: SpellSpec) { p.cast.phase = 'recovery'; p.cast.phaseEndsAt = ctx.now() + spell.recoveryMs; if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${castId}:idle`, spell.recoveryMs, 'internal.castIdle', { playerId: p.id, castId }, p.id); }
function livingTargets(state: GameState) { return [...Object.values(state.players).filter((target) => target.alive), ...Object.values(state.entities).filter((entity) => entity.kind === 'monster')]; }
function removeOwnedActiveEntities(state: GameState, playerId: string) { for (const entity of Object.values(state.entities)) if (entity.ownerId === playerId && !entity.detached) { delete state.entities[entity.id]; state.environment.fields = state.environment.fields.filter((id) => id !== entity.id); } }
function killPlayer(ctx: FlowReducerContext<GameState>, p: PlayerState) { if (!p.alive) return; const interrupted = p.cast.phase !== 'idle'; removeOwnedActiveEntities(ctx.state, p.id); p.alive = false; p.health.current = 0; p.cast = idleCast(p.aim); p.shields = []; delete p.forceVelocity; if (interrupted) ctx.emit('endwell.cast_interrupted', { type: 'cast_interrupted', casterId: p.id, reason: 'dead' } satisfies GameEvent); }
function applyRain(state: GameState, now: number, ownerId: string) { for (const target of livingTargets(state)) { delete target.statuses.burning; target.buildup.burning = 0; target.buildup.wet = (target.buildup.wet ?? 0) + 18; if ((target.buildup.wet ?? 0) >= 100) { target.buildup.wet = 0; target.statuses.wet = { type: 'wet', endsAt: now + 2400, potency: 1, stacks: 1, sourceId: ownerId, tags: ['rain'] }; } } }
function applyBlizzard(state: GameState, now: number, ownerId: string) { for (const target of livingTargets(state)) { if (target.statuses.frostWard) { target.buildup.chilled = 0; continue; } target.buildup.chilled = (target.buildup.chilled ?? 0) + 22; if ((target.buildup.chilled ?? 0) >= 100) { target.buildup.chilled = 0; target.statuses.chilled = { type: 'chilled', endsAt: now + 3000, potency: 1, stacks: 1, sourceId: ownerId, tags: ['blizzard'] }; } } }
function applyEnvironment(state: GameState, now: number, ownerId: string) { const environment = state.environment.global; if (environment?.kind === 'rain') applyRain(state, now, ownerId); else if (environment?.kind === 'blizzard') applyBlizzard(state, now, ownerId); }
function status(p: PlayerState, type: ElementStatusType, now: number, duration: number, sourceId: string) { p.statuses[type] = { type, endsAt: now + duration, potency: 1, stacks: 1, sourceId, tags: ['spell'] }; p.buildup[type] = 0; }
function applyShieldStatuses(p: PlayerState, spell: SpellSpec, now: number) { for (const type of ['fireWard', 'frostWard', 'waterWard', 'grounded'] as const) if (spell.tags.includes(type)) status(p, type, now, spell.lifetimeMs, p.id); }
function applyInstant(state: GameState, p: PlayerState, spell: SpellSpec, now: number) {
  const instant = spell.instant;
  if (!instant) return;
  if (instant.kind === 'teleport') { p.position = clampPosition(p.cast.target); p.positionEpoch += 1; return; }
  if (instant.kind === 'haste') { status(p, 'hasted', now, instant.durationMs ?? 6000, p.id); return; }
  if (instant.kind === 'supernova') { for (const target of livingTargets(state)) target.health.current = Math.max(0, target.health.current * (1 - (instant.amount ?? .5))); return; }
  if (instant.kind === 'equilibrium') { for (const target of livingTargets(state)) target.health.current = Math.max(0, target.health.max * (instant.amount ?? .5)); return; }
  const radius = instant.radius ?? spell.radius, center = p.cast.target;
  if (instant.kind === 'cleanse') for (const target of livingTargets(state)) if (distance(target.position, center) <= radius) { target.statuses = {}; target.buildup = {}; }
  if (instant.kind === 'resurrect') for (const target of Object.values(state.players)) if (target.faction.id === p.faction.id && !target.alive && distance(target.position, center) <= radius) { target.alive = true; target.health.current = Math.max(1, Math.round(target.health.max * (instant.amount ?? .25))); target.statuses = {}; target.buildup = {}; delete target.forceVelocity; }
  if (instant.kind === 'annihilation') { const targets = livingTargets(state).filter((target) => distance(target.position, center) <= radius); if (targets.length === 1) targets[0]!.health.current = Math.max(0, targets[0]!.health.current * (1 - (instant.amount ?? .99))); }
}
function resolveCastSpell(p: PlayerState, elements: Element[], now: number) { return resolveScrollSpell(elements, p, now) ?? resolveSpell(elements); }
function drop(state: GameState, p: PlayerState, item: InventoryItem, now: number, prefix: string) { const id = `${prefix}:${p.id}:${item.id}:${now}`; state.loot[id] = { id, position: { ...p.position }, item, droppedByPlayerId: p.id, ownerPriorityUntil: now + 1800 }; }
function itemPayload(value: unknown): value is ItemActionPayload { return typeof (value as ItemActionPayload)?.itemId === 'string'; }
function pickupPayload(value: unknown): value is PickupPayload { return typeof (value as PickupPayload)?.lootId === 'string'; }
function merchantPayload(value: unknown): value is MerchantItemPayload { const payload = value as MerchantItemPayload; return typeof payload?.merchantId === 'string' && typeof payload?.itemId === 'string'; }
function forgePayload(value: unknown): value is ForgeFusePayload { const payload = value as ForgeFusePayload; return typeof payload?.forgeId === 'string' && Array.isArray(payload.itemIds) && payload.itemIds.every((id) => typeof id === 'string'); }

export const endwellGame = defineGame<GameState>({
  meta: { name: 'Endwell', minPlayers: 1, maxPlayers: 4 }, initialState,
  lifecycle: {
    create(ctx) { ctx.state.seed = Math.floor(ctx.random() * 0x7fffffff); },
    join(ctx, joined) { ctx.state.hostId ??= joined.id; const existing = ctx.state.players[joined.id]; if (existing) existing.connected = true; else ctx.state.players[joined.id] = player(joined.id, joined.name || `巫师 ${Object.keys(ctx.state.players).length + 1}`, Object.keys(ctx.state.players).length); },
    reconnect(ctx, joined) { if (ctx.state.players[joined.id]) ctx.state.players[joined.id].connected = true; },
    leave(ctx, leaving) { if (ctx.state.players[leaving.id]) ctx.state.players[leaving.id].connected = false; if (ctx.state.hostId === leaving.id) ctx.state.hostId = Object.values(ctx.state.players).find((p) => p.connected)?.id ?? null; },
  },
  actions: {
    'game.start': { sync: { mode: 'hostAuthoritative' }, validate(ctx) { return ctx.actor.id === ctx.state.hostId ? accept(null) : reject('host-only'); }, reduce(ctx) { ctx.state.phase = 'running'; ctx.state.startedAt = ctx.now(); ctx.state.worldTime = ctx.now(); ctx.state.entities = { 'monster:training': trainingMonster(ctx.now()) }; ctx.state.environment = { global: null, fields: [] }; Object.assign(ctx.state, initialEconomy(ctx.state.seed)); ctx.state.seen = { hits: {}, spawns: {} }; for (const [index, p] of Object.values(ctx.state.players).entries()) { p.position = { x: 180 + index * 80, y: 360 }; p.positionEpoch += 1; p.alive = true; p.health.current = p.health.max; p.cast = idleCast(); p.shields = []; delete p.forceVelocity; p.scrollCooldowns = {}; } ctx.state.message = '元素试炼开始'; } },
    'game.finish': { sync: { mode: 'hostAuthoritative' }, validate(ctx) { return ctx.actor.id === ctx.state.hostId ? accept(null) : reject('host-only'); }, reduce(ctx) { ctx.state.phase = 'gameover'; ctx.state.message = '试炼结束'; } },
    'player.pose': { sync: { mode: 'hostRelay' }, validate(ctx, payload: PosePayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive || !Number.isInteger(payload.sequence) || payload.sequence <= p.lastPoseSequence || !Number.isFinite(payload.sentAt) || !finiteVec(payload.position) || !finiteVec(payload.aim)) return reject('invalid-pose'); return accept({ ...payload, sentAt: Math.max(ctx.now() - 5000, Math.min(ctx.now() + 1000, payload.sentAt)), position: clampPosition(payload.position), aim: normalize(payload.aim) }); }, reduce(ctx, payload: PosePayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive || payload.sequence <= p.lastPoseSequence) return; p.lastPoseSequence = payload.sequence; p.position = payload.position; p.aim = payload.aim; if (p.cast.phase === 'active' && p.cast.spell?.channelled) { p.cast.aim = payload.aim; for (const entity of Object.values(ctx.state.entities)) if (entity.ownerId === p.id && !entity.detached) { entity.position = { ...p.position }; entity.direction = payload.aim; } } ctx.emit('endwell.player_pose', { playerId: p.id, ...payload }); } },
    'cast.request': { sync: { mode: 'hostRelay' }, validate(ctx, payload: CastRequestPayload) { const p = ctx.state.players[ctx.actor.id]; if (ctx.state.phase !== 'running' || !p?.alive || p.cast.phase !== 'idle' || !Number.isInteger(payload.sequence) || payload.sequence <= p.lastCastSequence || payload.castId !== `${ctx.actor.id}:cast:${payload.sequence}` || !Array.isArray(payload.elements) || payload.elements.length < 1 || payload.elements.length > 4 || !payload.elements.every((element) => ELEMENTS.includes(element)) || !finiteVec(payload.aim) || !finiteVec(payload.target)) return reject('invalid-cast'); const spell = applyEquipmentToSpell(resolveCastSpell(p, payload.elements, ctx.now()), p.equipment); return accept({ ...payload, aim: normalize(payload.aim), target: spell.delivery === 'shield' || spell.delivery === 'environment' ? { ...p.position } : clampTarget(p.position, payload.target, spell.range) }); }, reduce(ctx, payload: CastRequestPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p || payload.sequence <= p.lastCastSequence || p.cast.phase !== 'idle') return; const scroll = ownedReadyScrollFor(payload.elements, p, ctx.now()); const baseSpell = scroll ? scroll.definition.spec(payload.elements) : resolveSpell(payload.elements); const spell = applySpellModifiers(applyEquipmentToSpell(baseSpell, p.equipment), p.buffs.flatMap((buff) => buff.modifiers)); if (scroll) p.scrollCooldowns[scroll.definition.id] = ctx.now() + scroll.definition.cooldownMs; p.lastCastSequence = payload.sequence; p.cast = { phase: 'chanting', castId: payload.castId, spell, startedAt: ctx.now(), phaseEndsAt: ctx.now() + spell.chantMs, aim: normalize(payload.aim), target: payload.target }; ctx.emit('endwell.cast_started', { type: 'cast_started', casterId: p.id, spellId: spell.id } satisfies GameEvent); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:activate`, spell.chantMs, 'internal.castActivate', { playerId: p.id, castId: payload.castId }, p.id); } },
    'cast.aim': { sync: { mode: 'hostRelay' }, validate(ctx, payload: CastAimPayload) { return playerAlive(ctx) && finiteVec(payload.aim) && Number.isInteger(payload.sequence) ? accept({ ...payload, aim: normalize(payload.aim) }) : reject('invalid-aim'); }, reduce(ctx, payload: CastAimPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive) return; p.aim = payload.aim; if (p.cast.phase === 'chanting' || p.cast.phase === 'active') p.cast.aim = payload.aim; if (p.cast.phase === 'active') for (const entity of Object.values(ctx.state.entities)) if (entity.ownerId === p.id && !entity.detached) { entity.position = { ...p.position }; entity.direction = payload.aim; } } },
    'cast.release': { sync: { mode: 'hostRelay' }, validate(ctx, payload: CastReleasePayload) { const p = ctx.state.players[ctx.actor.id]; return p?.alive && p.cast.castId === payload.castId ? accept(payload) : reject('cast-mismatch'); }, reduce(ctx, payload: CastReleasePayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive || p.cast.castId !== payload.castId || !p.cast.spell?.channelled) return; removeOwnedActiveEntities(ctx.state, p.id); const early = p.cast.phase === 'chanting'; if (early) ctx.emit('endwell.cast_interrupted', { type: 'cast_interrupted', casterId: p.id, reason: 'cancelled' } satisfies GameEvent); recovery(ctx, p, payload.castId, p.cast.spell); } },
    'internal.castActivate': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string }) { const p = ctx.state.players[payload.playerId], spell = p?.cast.spell; if (!p?.alive || !spell || p.cast.castId !== payload.castId || p.cast.phase !== 'chanting') return; p.cast.phase = 'active'; p.cast.phaseEndsAt = spell.channelled ? ctx.now() + spell.lifetimeMs : ctx.now(); if (spell.delivery === 'instant') { applyInstant(ctx.state, p, spell, ctx.now()); recovery(ctx, p, payload.castId, spell); return; } if (spell.delivery === 'shield' && spell.shield) { p.shields.push({ id: payload.castId, amount: spell.shield.amount, maxAmount: spell.shield.amount, absorbElements: spell.shield.absorbElements, priority: 10, tags: spell.tags }); applyShieldStatuses(p, spell, ctx.now()); recovery(ctx, p, payload.castId, spell); return; } if (spell.delivery === 'environment' && spell.environment) { ctx.state.environment.global = { id: payload.castId, kind: spell.environment.kind, ownerId: p.id, startedAt: ctx.now(), endsAt: ctx.now() + spell.environment.duration, tickInterval: spell.environment.tickInterval, nextTickAt: ctx.now() }; recovery(ctx, p, payload.castId, spell); return; } if (spell.delivery === 'area' && spell.area) { const warning = spawnMeteorWarning(ctx.state, p, spell, ctx.now()); p.cast.phase = 'warning'; p.cast.phaseEndsAt = ctx.now() + spell.area.warningMs; ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: warning.id } satisfies GameEvent); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:impact`, spell.area.warningMs, 'internal.areaImpact', payload, p.id); return; } const entity = spawnSpellEntity(ctx.state, p, spell, ctx.now()); ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: entity.id } satisfies GameEvent); if (spell.channelled) { if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:interrupt`, spell.lifetimeMs, 'cast.interrupt', { playerId: p.id, castId: payload.castId, reason: 'timeout' }, p.id); } else recovery(ctx, p, payload.castId, spell); } },
    'internal.areaImpact': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string }) { const p = ctx.state.players[payload.playerId], spell = p?.cast.spell; if (!p?.alive || !spell || p.cast.castId !== payload.castId || spell.delivery !== 'area') return; delete ctx.state.entities[`${payload.castId}:warning:0`]; const impact = spawnMeteorImpact(ctx.state, p, spell, ctx.now()); ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: impact.id } satisfies GameEvent); recovery(ctx, p, payload.castId, spell); } },
    'internal.castIdle': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string }) { const p = ctx.state.players[payload.playerId]; if (p?.cast.castId === payload.castId) p.cast = idleCast(p.aim); } },
    'cast.interrupt': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string; reason: string }) { const p = ctx.state.players[payload.playerId]; if (!p || p.cast.castId !== payload.castId) return; removeOwnedActiveEntities(ctx.state, p.id); p.cast.phase = 'interrupted'; p.cast.phaseEndsAt = ctx.now() + 350; ctx.emit('endwell.cast_interrupted', { type: 'cast_interrupted', casterId: p.id, reason: payload.reason } satisfies GameEvent); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:idle`, 350, 'internal.castIdle', { playerId: p.id, castId: payload.castId }, p.id); } },
    'combat.hit': { sync: { mode: 'hostRelay' }, validate(ctx, payload: HitRequestPayload) { const source = ctx.state.entities[payload.sourceId], owner = source?.ownerId ? ctx.state.players[source.ownerId] : undefined; if (!source?.source || source.ownerId !== ctx.actor.id || owner && !owner.alive || !ctx.state.players[payload.targetId] && !ctx.state.entities[payload.targetId] || typeof payload.hitId !== 'string' || payload.hitId.length > 160 || payload.reason !== 'hit' && payload.reason !== 'blocked' || ctx.state.seen.hits[payload.hitId]) return reject('invalid-hit'); return accept(payload); }, reduce(ctx, payload: HitRequestPayload) { const source = ctx.state.entities[payload.sourceId]; if (!source?.source) return; const owner = source.ownerId ? ctx.state.players[source.ownerId] : undefined; if (owner && !owner.alive) return; const event: HitEvent = { hitId: payload.hitId, sourceId: source.id, ownerId: source.ownerId, targetId: payload.targetId, payload: source.source.spell.payload, delivery: source.source.spell.delivery, detached: source.detached, tags: source.source.spell.tags }; const resolution = applyHit(ctx.state, event, ctx.now()); emitAll(ctx, resolution.events); if (!resolution.accepted && payload.reason !== 'blocked') return; const target = ctx.state.players[payload.targetId] ?? ctx.state.entities[payload.targetId]; if (resolution.accepted && target && target.health.current <= 0) { if ('alive' in target) killPlayer(ctx, target); else { delete ctx.state.entities[payload.targetId]; ctx.emit('endwell.entity_destroyed', { type: 'entity_destroyed', entityId: payload.targetId } satisfies GameEvent); if (payload.targetId === 'monster:training' && ctx.role === 'authority') ctx.timers.dispatch('monster:training:respawn', 3000, 'internal.trainingMonsterRespawn', {}, ctx.host.id); } } if (source.kind === 'projectile' && !source.source.spell.tags.includes('pierce')) delete ctx.state.entities[source.id]; } },
    'inventory.equip': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && itemPayload(payload) ? accept(payload) : reject('invalid-item'); }, reduce(ctx, payload: ItemActionPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive) return; const index = p.inventory.findIndex((item) => item.id === payload.itemId), item = p.inventory[index]; if (index < 0 || !isEquipment(item)) return; const old = p.equipment[item.slot]; p.inventory.splice(index, 1); if (old) p.inventory.push(old); p.equipment[item.slot] = item; } },
    'inventory.unequip': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && itemPayload(payload) ? accept(payload) : reject('invalid-item'); }, reduce(ctx, payload: ItemActionPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive) return; const slot = (['staff', 'robe', 'ring'] as const).find((key) => p.equipment[key]?.id === payload.itemId); if (!slot) return; const item = p.equipment[slot]!; delete p.equipment[slot]; if (p.inventory.length < 9) p.inventory.push(item); else drop(ctx.state, p, item, ctx.now(), 'unequip'); } },
    'inventory.drop': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && itemPayload(payload) ? accept(payload) : reject('invalid-item'); }, reduce(ctx, payload: ItemActionPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive) return; const index = p.inventory.findIndex((item) => item.id === payload.itemId), item = p.inventory[index]; if (index < 0 || !item) return; p.inventory.splice(index, 1); drop(ctx.state, p, item, ctx.now(), 'drop'); } },
    'inventory.pickup': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && pickupPayload(payload) ? accept(payload) : reject('invalid-loot'); }, reduce(ctx, payload: PickupPayload) { const p = ctx.state.players[ctx.actor.id], loot = ctx.state.loot[payload.lootId]; if (!p?.alive || !loot || p.inventory.length >= 9 || distance(p.position, loot.position) > 115 || loot.droppedByPlayerId && loot.droppedByPlayerId !== p.id && ctx.now() < loot.ownerPriorityUntil) return; delete ctx.state.loot[payload.lootId]; p.inventory.push(loot.item); } },
    'merchant.buy': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && merchantPayload(payload) ? accept(payload) : reject('invalid-merchant'); }, reduce(ctx, payload: MerchantItemPayload) { const p = ctx.state.players[ctx.actor.id], merchant = ctx.state.merchant; if (!p?.alive || !merchant || merchant.id !== payload.merchantId || p.inventory.length >= 9 || distance(p.position, merchant.position) > merchant.radius + 90) return; const index = merchant.stock.findIndex((entry) => entry.item.id === payload.itemId), entry = merchant.stock[index]; if (index < 0 || !entry || p.gold < entry.price) return; p.gold -= entry.price; p.inventory.push(entry.item); merchant.stock.splice(index, 1); } },
    'merchant.sell': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && merchantPayload(payload) ? accept(payload) : reject('invalid-merchant'); }, reduce(ctx, payload: MerchantItemPayload) { const p = ctx.state.players[ctx.actor.id], merchant = ctx.state.merchant; if (!p?.alive || !merchant || merchant.id !== payload.merchantId || distance(p.position, merchant.position) > merchant.radius + 90) return; const index = p.inventory.findIndex((item) => item.id === payload.itemId), item = p.inventory[index]; if (index < 0 || !item || (!isEquipment(item) && !isScroll(item))) return; const price = sellPrice(item); if (price <= 0) return; p.inventory.splice(index, 1); p.gold += price; } },
    'forge.fuse': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && forgePayload(payload) ? accept({ ...payload, itemIds: payload.itemIds.slice(0, 3) }) : reject('invalid-forge'); }, reduce(ctx, payload: ForgeFusePayload) { const p = ctx.state.players[ctx.actor.id], forge = ctx.state.forge, ids = payload.itemIds; if (!p?.alive || !forge || forge.id !== payload.forgeId || ids.length !== 3 || new Set(ids).size !== 3 || distance(p.position, forge.position) > forge.radius + 90) return; const materials = ids.map((id) => p.inventory.find((item) => item.id === id)); if (materials.some((item) => !item) || !canFuse(materials as InventoryItem[])) return; const uses = ctx.state.forgeUses[forge.id]?.[p.id] ?? 0, price = fusionPrice(uses), wasFull = p.inventory.length >= 9; if (p.gold < price) return; const result = fuseEquipment(materials as InventoryItem[], fusionSeed(ctx.state.seed, p.id, ids, uses)); if (!result) return; p.gold -= price; p.inventory = p.inventory.filter((item) => !ids.includes(item.id)); ctx.state.forgeUses[forge.id] ??= {}; ctx.state.forgeUses[forge.id]![p.id] = uses + 1; if (!wasFull && p.inventory.length < 9) p.inventory.push(result); else drop(ctx.state, p, result, ctx.now(), 'fusion'); } },
    'internal.environmentTick': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { environmentId: string }) { const environment = ctx.state.environment.global; if (!environment || environment.id !== payload.environmentId) return; applyEnvironment(ctx.state, ctx.now(), environment.ownerId); environment.nextTickAt = ctx.now() + environment.tickInterval; } },
    'internal.environmentExpire': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { environmentId: string }) { if (ctx.state.environment.global?.id === payload.environmentId) ctx.state.environment.global = null; } },
    'entity.expire': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { entityId: string }) { if (!ctx.state.entities[payload.entityId]) return; delete ctx.state.entities[payload.entityId]; ctx.state.environment.fields = ctx.state.environment.fields.filter((id) => id !== payload.entityId); ctx.emit('endwell.entity_destroyed', { type: 'entity_destroyed', entityId: payload.entityId } satisfies GameEvent); } },
    'internal.trainingMonsterRespawn': { sync: { mode: 'hostAuthoritative' }, reduce(ctx) { if (ctx.state.phase !== 'running' || ctx.state.entities['monster:training']) return; ctx.state.entities['monster:training'] = trainingMonster(ctx.now()); ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: 'monster:training' } satisfies GameEvent); } },
  },
  systems: [{ runOn: 'authority', intervalMs: 100, update(ctx, dt = .1) { const now = ctx.now(), step = Math.min(.2, Math.max(.001, dt)); ctx.state.worldTime = now; for (const target of Object.values(ctx.state.players).filter((p) => p.alive)) integrateForceMotion(target, step); for (const entity of Object.values(ctx.state.entities).filter((e) => e.kind === 'monster')) integrateForceMotion(entity, step); for (const [id, entity] of Object.entries(ctx.state.entities)) if (entity.expiresAt != null && entity.expiresAt <= now) ctx.dispatch('entity.expire', { entityId: id }, ctx.host.id); const environment = ctx.state.environment.global; if (environment && environment.endsAt <= now) ctx.dispatch('internal.environmentExpire', { environmentId: environment.id }, ctx.host.id); else if (environment && environment.nextTickAt <= now) ctx.dispatch('internal.environmentTick', { environmentId: environment.id }, ctx.host.id); for (const target of [...Object.values(ctx.state.players), ...Object.values(ctx.state.entities)]) for (const [key, instance] of Object.entries(target.statuses)) if (instance && instance.endsAt <= now) delete target.statuses[key as ElementStatusType]; } }],
});
