import { accept, defineGame, reject, type FlowReducerContext } from '@parti/flow';
import type { CastActivatePayload, CastAimPayload, CastReleasePayload, CastRequestPayload, Element, ElementStatusType, ForgeFusePayload, GameEvent, GameState, HitEvent, HitRequestPayload, InventoryItem, ItemActionPayload, MerchantItemPayload, PickupPayload, PlayerState, PosePayload, SpellSpec, Vec2 } from './contracts';
import { applyHit } from './rules/combat';
import { spawnMeteorImpact, spawnMeteorWarning, spawnSpellEntity } from './rules/entities';
import { applyEquipmentToSpell, canFuse, distance, fusionPrice, fusionSeed, fuseEquipment, generateEquipment, isEquipment, isScroll, sellPrice } from './rules/equipment';
import { applySpellModifiers } from './rules/modifiers';
import { ownedReadyScrollFor, resolveScrollSpell } from './rules/scrolls';
import { idleCast, initialState, normalize, player } from './rules/state';
import { beginCast, beginRecovery, resetCast } from './rules/casting';
import { collisionCandidates, verifiesHit } from './rules/hitDetection';
import { canPlaceObstacle, resolveTeleportDestination, resolveWorldMovement } from './rules/worldCollision';
import { isSpecialSpellId, resolveSpell, spellTargetMode } from './rules/spells';
import { ELEMENTS } from '../content/spells';
import { allPlayersInRoom, bossDefinition, completedObjectives, encounterWaves, generateStage, isWalkable, monsterDefinition, monsterEntity, onlineLivingPlayers, roomAt, stageDefinition, type MonsterAbilityDefinition } from './roguelike';

const finiteVec = (value: Vec2) => Number.isFinite(value?.x) && Number.isFinite(value?.y);
const clampPosition = (state: GameState, value: Vec2, from: Vec2 = value, moverId?: string): Vec2 => state.run.stage ? resolveWorldMovement(state, from, value, 24, moverId) : value;
const emitAll = (ctx: FlowReducerContext<GameState>, events: GameEvent[]) => { for (const event of events) ctx.emit(`endwell.${event.type}`, event); };
const playerAlive = (ctx: FlowReducerContext<GameState>) => Boolean(ctx.state.players[ctx.actor.id]?.alive);
const discoveredSpells = (state: GameState) => state.run.discoveredSpellIds ??= ['resurrect'];
const playerInCombat = (state: GameState, playerId: string) => { const stage = state.run.stage, p = state.players[playerId]; if (!stage || !p) return false; const roomId = roomAt(stage, p.position)?.id; return stage.encounters.some((encounter) => encounter.roomId === roomId && encounter.status === 'active') || stage.boss.roomId === roomId && stage.boss.status === 'active'; };
const FORCE_DAMPING_PER_SECOND = .18;
function integrateForceMotion(state: GameState, target: PlayerState | NonNullable<GameState['entities'][string]>, dt: number) {
  const velocity = target.forceVelocity;
  if (!velocity) return false;
  const desired = { x: target.position.x + velocity.x * dt, y: target.position.y + velocity.y * dt }, next = resolveWorldMovement(state, target.position, desired, 'alive' in target ? 24 : target.radius, target.id);
  const moved = Math.hypot(next.x - target.position.x, next.y - target.position.y) > .01;
  target.position = next;
  const damping = Math.pow(FORCE_DAMPING_PER_SECOND, dt), slowed = { x: velocity.x * damping, y: velocity.y * damping };
  if (Math.hypot(slowed.x, slowed.y) < 4) delete target.forceVelocity;
  else target.forceVelocity = slowed;
  if (moved && 'positionEpoch' in target) target.positionEpoch += 1;
  return moved;
}
function turnToward(current: Vec2, target: Vec2, maxRadians: number) { const from = Math.atan2(current.y, current.x), to = Math.atan2(target.y, target.x), delta = Math.atan2(Math.sin(to - from), Math.cos(to - from)), angle = from + Math.max(-maxRadians, Math.min(maxRadians, delta)); return { x: Math.cos(angle), y: Math.sin(angle) }; }
function updateAttachedDirections(state: GameState, step: number) { for (const entity of Object.values(state.entities)) { if (!entity.source || entity.detached || !entity.targetDirection) continue; if (entity.source.spell.delivery === 'beam') entity.direction = turnToward(entity.direction ?? entity.targetDirection, entity.targetDirection, (entity.source.spell.beam?.turnSpeed ?? Math.PI * 1.5) * step); else entity.direction = entity.targetDirection; } }
function clampTarget(state: GameState, origin: Vec2, target: Vec2, range: number) { const dx = target.x - origin.x, dy = target.y - origin.y, distance = Math.hypot(dx, dy), value = !range || distance <= range ? target : { x: origin.x + dx / Math.max(1, distance) * range, y: origin.y + dy / Math.max(1, distance) * range }; return clampPosition(state, value, origin); }
function recovery(ctx: FlowReducerContext<GameState>, p: PlayerState, castId: string, spell: SpellSpec) { beginRecovery(p, ctx.now(), spell.recoveryMs); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${castId}:idle`, spell.recoveryMs, 'internal.castIdle', { playerId: p.id, castId }, p.id); }
function livingTargets(state: GameState) { return [...Object.values(state.players).filter((target) => target.alive), ...Object.values(state.entities).filter((entity) => entity.kind === 'monster')]; }
function removeOwnedActiveEntities(state: GameState, playerId: string) { for (const entity of Object.values(state.entities)) if (entity.ownerId === playerId && !entity.detached) { delete state.entities[entity.id]; state.environment.fields = state.environment.fields.filter((id) => id !== entity.id); } }
function killPlayer(ctx: FlowReducerContext<GameState>, p: PlayerState) { if (!p.alive) return; const interrupted = p.cast.phase !== 'idle'; removeOwnedActiveEntities(ctx.state, p.id); p.alive = false; p.health.current = 0; p.cast = idleCast(p.aim); p.selectedElements = []; p.shields = []; delete p.forceVelocity; if (interrupted) ctx.emit('endwell.cast_interrupted', { type: 'cast_interrupted', casterId: p.id, reason: 'dead' } satisfies GameEvent); }
function applyRain(state: GameState, now: number, ownerId: string) { for (const target of livingTargets(state)) { delete target.statuses.burning; target.buildup.burning = 0; target.buildup.wet = (target.buildup.wet ?? 0) + 18; if ((target.buildup.wet ?? 0) >= 100) { target.buildup.wet = 0; target.statuses.wet = { type: 'wet', endsAt: now + 2400, potency: 1, stacks: 1, sourceId: ownerId, tags: ['rain'] }; } } }
function applyBlizzard(state: GameState, now: number, ownerId: string) { for (const target of livingTargets(state)) { if (target.statuses.frostWard) { target.buildup.chilled = 0; continue; } target.buildup.chilled = (target.buildup.chilled ?? 0) + 22; if ((target.buildup.chilled ?? 0) >= 100) { target.buildup.chilled = 0; target.statuses.chilled = { type: 'chilled', endsAt: now + 3000, potency: 1, stacks: 1, sourceId: ownerId, tags: ['blizzard'] }; } } }
function applyEnvironment(state: GameState, now: number, ownerId: string) { const environment = state.environment.global; if (environment?.kind === 'rain') applyRain(state, now, ownerId); else if (environment?.kind === 'blizzard') applyBlizzard(state, now, ownerId); }
function status(p: PlayerState, type: ElementStatusType, now: number, duration: number, sourceId: string) { p.statuses[type] = { type, endsAt: now + duration, potency: 1, stacks: 1, sourceId, tags: ['spell'] }; p.buildup[type] = 0; }
function applyShieldStatuses(p: PlayerState, spell: SpellSpec, now: number) { for (const type of ['fireWard', 'frostWard', 'waterWard', 'grounded'] as const) if (spell.tags.includes(type)) status(p, type, now, spell.lifetimeMs, p.id); }
function applyInstant(state: GameState, p: PlayerState, spell: SpellSpec, now: number) {
  const instant = spell.instant;
  if (!instant) return;
  if (instant.kind === 'teleport') { p.position = resolveTeleportDestination(state, p.position, p.cast.target, 24, p.id); p.positionEpoch += 1; return; }
  if (instant.kind === 'selfHeal') { p.health.current = Math.min(p.health.max, p.health.current + (instant.amount ?? 20)); return; }
  if (instant.kind === 'haste') { status(p, 'hasted', now, instant.durationMs ?? 6000, p.id); return; }
  if (instant.kind === 'supernova') { for (const target of livingTargets(state)) target.health.current = Math.max(0, target.health.current * (1 - (instant.amount ?? .5))); return; }
  if (instant.kind === 'equilibrium') { for (const target of livingTargets(state)) target.health.current = Math.max(0, target.health.max * (instant.amount ?? .5)); return; }
  const radius = instant.radius ?? spell.radius, center = p.cast.target;
  if (instant.kind === 'cleanse') for (const target of livingTargets(state)) if (distance(target.position, center) <= radius) { target.statuses = {}; target.buildup = {}; }
  if (instant.kind === 'resurrect') for (const target of Object.values(state.players)) if (target.faction.id === p.faction.id && !target.alive && distance(target.position, center) <= radius) { target.alive = true; target.health.current = Math.max(1, Math.round(target.health.max * (instant.amount ?? .25))); target.statuses = {}; target.buildup = {}; delete target.forceVelocity; }
  if (instant.kind === 'annihilation') { const targets = livingTargets(state).filter((target) => distance(target.position, center) <= radius); if (targets.length === 1) targets[0]!.health.current = Math.max(0, targets[0]!.health.current * (1 - (instant.amount ?? .99))); }
}
function activatePlayerCast(ctx: FlowReducerContext<GameState>, playerId: string, castId: string) {
  const p = ctx.state.players[playerId], spell = p?.cast.spell;
  if (!p?.alive || !spell || p.cast.castId !== castId || p.cast.phase !== 'chanting') return;
  p.cast.phase = 'active'; p.cast.phaseEndsAt = spell.channelled ? ctx.now() + spell.lifetimeMs : ctx.now();
  if (isSpecialSpellId(spell.id) && !discoveredSpells(ctx.state).includes(spell.id)) discoveredSpells(ctx.state).push(spell.id);
  if (spell.delivery === 'instant') { const before = spell.tags.includes('large-impact') ? new Map(livingTargets(ctx.state).map((target) => [target.id, target.health.current])) : null; applyInstant(ctx.state, p, spell, ctx.now()); if (before) for (const target of livingTargets(ctx.state)) { const amount = Math.max(0, (before.get(target.id) ?? target.health.current) - target.health.current); if (amount > 0) ctx.emit('endwell.damage_applied', { type: 'damage_applied', targetId: target.id, amount, element: 'pure', sourceId: castId, largeImpact: true } satisfies GameEvent); } recovery(ctx, p, castId, spell); return; }
  if (spell.delivery === 'shield' && spell.shield) { p.shields.push({ id: castId, amount: spell.shield.amount, maxAmount: spell.shield.amount, absorbElements: spell.shield.absorbElements, priority: 10, tags: spell.tags }); applyShieldStatuses(p, spell, ctx.now()); recovery(ctx, p, castId, spell); return; }
  if (spell.delivery === 'environment' && spell.environment) { ctx.state.environment.global = { id: castId, kind: spell.environment.kind, ownerId: p.id, startedAt: ctx.now(), endsAt: ctx.now() + spell.environment.duration, tickInterval: spell.environment.tickInterval, nextTickAt: ctx.now() }; recovery(ctx, p, castId, spell); return; }
  if (spell.delivery === 'area' && spell.area) { const warning = spawnMeteorWarning(ctx.state, p, spell, ctx.now()); p.cast.phase = 'warning'; p.cast.phaseEndsAt = ctx.now() + spell.area.warningMs; ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: warning.id } satisfies GameEvent); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${castId}:impact`, spell.area.warningMs, 'internal.areaImpact', { playerId: p.id, castId }, p.id); return; }
  const wall = spell.summon?.archetype === 'rock-wall' || spell.summon?.archetype === 'ice-wall';
  if (wall && !canPlaceObstacle(ctx.state, p.cast.target, 36, 140, p.id)) { recovery(ctx, p, castId, spell); return; }
  const entity = spawnSpellEntity(ctx.state, p, spell, ctx.now()); ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: entity.id } satisfies GameEvent);
  if (spell.channelled) { if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${castId}:interrupt`, spell.lifetimeMs, 'cast.interrupt', { playerId: p.id, castId, reason: 'timeout' }, p.id); }
  else recovery(ctx, p, castId, spell);
}
function resolveCastSpell(p: PlayerState, elements: Element[], now: number) { return resolveScrollSpell(elements, p, now) ?? resolveSpell(elements); }
function drop(state: GameState, p: PlayerState, item: InventoryItem, now: number, prefix: string) { const id = `${prefix}:${p.id}:${item.id}:${now}`; state.loot[id] = { id, position: { ...p.position }, item, droppedByPlayerId: p.id, ownerPriorityUntil: now + 1800 }; }
function itemPayload(value: unknown): value is ItemActionPayload { return typeof (value as ItemActionPayload)?.itemId === 'string'; }
function pickupPayload(value: unknown): value is PickupPayload { return typeof (value as PickupPayload)?.lootId === 'string'; }
function merchantPayload(value: unknown): value is MerchantItemPayload { const payload = value as MerchantItemPayload; return typeof payload?.merchantId === 'string' && typeof payload?.itemId === 'string'; }
function forgePayload(value: unknown): value is ForgeFusePayload { const payload = value as ForgeFusePayload; return typeof payload?.forgeId === 'string' && Array.isArray(payload.itemIds) && payload.itemIds.every((id) => typeof id === 'string'); }

function roomCenter(state: GameState, roomId: string) { const room = state.run.stage?.world.rooms.find((candidate) => candidate.id === roomId); return room ? { x: room.position.x + room.width / 2, y: room.position.y + room.height / 2 } : { x: 0, y: 0 }; }
function scaleEncounter(encounter: NonNullable<GameState['run']['stage']>['encounters'][number], playerCount: number) {
  if (encounter.scaledForPlayers != null) return;
  const count = Math.max(1, playerCount), cycle = encounter.id.includes(':altar:') ? Number(encounter.id.split(':').at(-1)) || 0 : 0;
  encounter.waves = encounterWaves(encounter.roomId, count, cycle);
  encounter.monsterIds = encounter.waves.flat(); encounter.totalWaves = encounter.waves.length; encounter.scaledForPlayers = count;
}
function encounterSpawnPosition(state: GameState, room: NonNullable<GameState['run']['stage']>['world']['rooms'][number], wave: number, index: number, count: number): Vec2 | null {
  const stage = state.run.stage!, c = roomCenter(state, room.id), facilities = [stage.merchant, stage.forge], players = onlineLivingPlayers(state.players);
  for (let attempt = 0; attempt < 12; attempt++) { const angle = (index / Math.max(1, count) + attempt * .381 + wave * .13) * Math.PI * 2, distanceFromCenter = Math.min(room.width, room.height) * (.27 + attempt % 3 * .045), point = { x: c.x + Math.cos(angle) * distanceFromCenter, y: c.y + Math.sin(angle) * distanceFromCenter }; if (!isWalkable(stage, point, 34)) continue; if (players.some((player) => distance(player.position, point) < 120)) continue; if (facilities.some((facility) => distance(facility.position, point) < facility.radius + 54)) continue; return point; }
  for (let y = .18; y <= .82; y += .16) for (let x = .18; x <= .82; x += .16) { const point = { x: room.position.x + room.width * x, y: room.position.y + room.height * y }; if (isWalkable(stage, point, 34) && !players.some((player) => distance(player.position, point) < 120) && !facilities.some((facility) => distance(facility.position, point) < facility.radius + 54)) return point; }
  return null;
}
function spawnEncounterWave(state: GameState, encounter: NonNullable<GameState['run']['stage']>['encounters'][number], now: number) {
  const stage = state.run.stage, room = stage?.world.rooms.find((candidate) => candidate.id === encounter.roomId), waveIndex = encounter.currentWave, ids = encounter.waves[waveIndex] ?? []; if (!stage || !room || !ids.length) return;
  const objective = stage.objectives.find((candidate) => candidate.roomId === room.id);
  ids.forEach((id, index) => { if (state.seen.spawns[id]) return; const elite = waveIndex === 2 && index === ids.length - 1, definitionId = elite ? 'ruins.guardian' : waveIndex === 0 ? 'ruins.chaser' : waveIndex === 1 && index % 3 === 1 ? 'ruins.shooter' : waveIndex === 2 && index % 3 === 0 ? 'ruins.shooter' : 'ruins.chaser', objectiveElite = objective?.kind === 'elite' && waveIndex === 2 && index === 0, position = encounterSpawnPosition(state, room, waveIndex, index, ids.length); if (!position) return; state.entities[id] = monsterEntity(id, objectiveElite ? 'ruins.guardian' : definitionId, room.id, position, stage.difficulty, now, elite || objectiveElite); state.seen.spawns[id] = true; });
  encounter.currentWave += 1; encounter.nextWaveAt = null;
}
function spawnEncounter(state: GameState, encounter: NonNullable<GameState['run']['stage']>['encounters'][number], now: number) { const stage = state.run.stage; if (!stage || encounter.status !== 'dormant') return; scaleEncounter(encounter, onlineLivingPlayers(state.players).length); encounter.status = 'active'; encounter.activatedAt ??= now; encounter.currentWave = 0; encounter.nextWaveAt = now + 900; const room = stage.world.rooms.find((candidate) => candidate.id === encounter.roomId); if (!room) return; for (const rock of stage.terrains.filter((terrain) => terrain.roomId === room.id && terrain.kind === 'falling-rock')) { rock.warningAt = now; rock.activatesAt = now + 1200; rock.endsAt = now + 2200; } const objective = stage.objectives.find((candidate) => candidate.roomId === room.id); if (objective) objective.status = 'active'; }
function rewardEncounter(state: GameState, encounterId: string, position: Vec2, now: number) { const stage = state.run.stage; if (!stage || state.run.completedRewardIds.includes(encounterId)) return; state.run.completedRewardIds.push(encounterId); const seed = stage.rewardSeeds[encounterId] ?? stage.stageSeed, item = generateEquipment(seed, state.run.completedRewardIds.length + stage.index * 20), id = `loot:${encounterId}`; state.loot[id] = { id, position, item, droppedByPlayerId: null, ownerPriorityUntil: now }; for (const player of onlineLivingPlayers(state.players)) player.gold += Math.round(18 * stage.rewardMultiplier); }
function updateEncounters(state: GameState, now: number) {
  const stage = state.run.stage; if (!stage) return; const livingPlayers = onlineLivingPlayers(state.players), playerRooms = livingPlayers.map((player) => roomAt(stage, player.position)?.id);
  for (const encounter of stage.encounters) {
    if (encounter.status === 'dormant') { const shouldStart = encounter.kind === 'sealed' ? allPlayersInRoom(state.players, stage, encounter.roomId) : playerRooms.includes(encounter.roomId); if (shouldStart) spawnEncounter(state, encounter, now); }
    if (encounter.status !== 'active') continue;
    const objective = stage.objectives.find((candidate) => candidate.roomId === encounter.roomId);
    if (objective?.kind === 'puzzle' && objective.progress < objective.target) { const room = stage.world.rooms.find((candidate) => candidate.id === objective.roomId)!; const rune = { x: room.position.x + room.width * (.25 + objective.progress * .25), y: room.position.y + room.height * (objective.progress % 2 ? .68 : .32) }; if (livingPlayers.some((player) => distance(player.position, rune) <= 48)) objective.progress += 1; }
    const alive = encounter.monsterIds.filter((id) => state.entities[id]).length;
    if (alive > 0) { encounter.nextWaveAt = null; continue; }
    if (encounter.currentWave < encounter.totalWaves) { encounter.nextWaveAt ??= now + 900; if (now >= encounter.nextWaveAt) spawnEncounterWave(state, encounter, now); continue; }
    if (objective?.kind === 'puzzle' && objective.progress < objective.target) continue;
    if (objective?.kind === 'altar' && objective.progress + 1 < objective.target) { objective.progress += 1; encounter.status = 'dormant'; encounter.id = `encounter:${encounter.roomId}:altar:${objective.progress}`; encounter.scaledForPlayers = null; encounter.activatedAt = null; encounter.currentWave = 0; encounter.nextWaveAt = null; encounter.waves = []; encounter.monsterIds = []; continue; }
    encounter.status = 'cleared'; encounter.clearedAt = now; encounter.nextWaveAt = null; if (objective) { objective.progress = objective.target; objective.status = 'completed'; } rewardEncounter(state, encounter.id, roomCenter(state, encounter.roomId), now);
  }
  if (stage.boss.status === 'locked' && completedObjectives(stage) >= stageDefinition(stage.index).requiredObjectives) stage.boss.status = 'available';
}
function startBoss(state: GameState, now: number) { const stage = state.run.stage; if (!stage || stage.boss.status !== 'available' || !allPlayersInRoom(state.players, stage, stage.boss.roomId)) return; const definition = bossDefinition(stage.boss.definitionId), id = `boss:${stage.index}:${stage.boss.roomId}`, entity = monsterEntity(id, definition.monsterId, stage.boss.roomId, roomCenter(state, stage.boss.roomId), stage.difficulty * Math.max(1, .72 + onlineLivingPlayers(state.players).length * .28), now, true, true); stage.boss.status = 'active'; stage.boss.entityId = id; stage.boss.phase = 1; stage.boss.shielded = true; stage.boss.nextMechanicAt = now + definition.mechanicIntervalMs * stageDefinition(stage.index).mechanicSpeed; state.entities[id] = entity; state.seen.spawns[id] = true; }
function updateBoss(state: GameState, now: number) { const stage = state.run.stage; if (!stage) return; startBoss(state, now); if (stage.boss.status !== 'active') return; const boss = stage.boss.entityId ? state.entities[stage.boss.entityId] : undefined; if (!boss) { stage.boss.status = 'defeated'; stage.boss.shielded = false; rewardEncounter(state, `boss:${stage.index}`, roomCenter(state, stage.boss.roomId), now); state.run.portal = { id: `portal:${stage.index}`, roomId: stage.boss.roomId, position: roomCenter(state, stage.boss.roomId), active: true }; return; } const definition = bossDefinition(stage.boss.definitionId), ratio = boss.health.current / boss.health.max, nextPhase = ratio <= definition.phaseThresholds[1]! ? 3 : ratio <= definition.phaseThresholds[0]! ? 2 : 1; if (nextPhase > stage.boss.phase) { stage.boss.phase = nextPhase; stage.boss.shielded = true; for (const rune of stage.boss.runes) rune.active = true; }
  for (const rune of stage.boss.runes.filter((candidate) => candidate.active)) if (onlineLivingPlayers(state.players).some((player) => distance(player.position, rune.position) <= 55)) rune.active = false; stage.boss.shielded = stage.boss.runes.some((rune) => rune.active);
  if (now >= stage.boss.nextMechanicAt) { stage.boss.nextMechanicAt = now + definition.mechanicIntervalMs * stageDefinition(stage.index).mechanicSpeed; const current = Object.values(state.entities).filter((entity) => entity.roomId === stage.boss.roomId && !entity.boss && entity.kind === 'monster').length, cap = definition.baseAddCap + stageDefinition(stage.index).addBonus + Math.min(3, onlineLivingPlayers(state.players).length); for (let index = current; index < Math.min(cap, current + stage.boss.phase); index++) { let ordinal = index; while (state.seen.spawns[`boss-add:${stage.index}:${stage.boss.phase}:${ordinal}`]) ordinal += 1; const id = `boss-add:${stage.index}:${stage.boss.phase}:${ordinal}`; state.entities[id] = monsterEntity(id, definition.addDefinitionId, stage.boss.roomId, { x: boss.position.x + Math.cos(ordinal) * 180, y: boss.position.y + Math.sin(ordinal) * 140 }, stage.difficulty, now); state.seen.spawns[id] = true; } const rocks = stage.terrains.filter((terrain) => terrain.kind === 'falling-rock' && terrain.roomId === stage.boss.roomId); for (const rock of rocks) { rock.active = true; rock.warningAt = now; rock.activatesAt = now + 900; rock.endsAt = now + 1800; } }
}
function scaledMonsterSpell(ability: MonsterAbilityDefinition, difficulty: number, boss = false) { const spell = structuredClone(ability.spell); if (spell.payload.damage) for (const key of Object.keys(spell.payload.damage) as Array<keyof typeof spell.payload.damage>) if (spell.payload.damage[key] != null) spell.payload.damage[key]! *= difficulty * (boss && spell.id !== 'ruins-boss-flame' ? 1.3 : 1); return spell; }
function selectAbility(abilities: MonsterAbilityDefinition[], range: number) { return abilities.filter((ability) => range >= ability.minRange && range <= ability.maxRange).sort((a, b) => b.priority - a.priority)[0]; }
function updateMonsterAi(state: GameState, now: number, dt: number) { const stage = state.run.stage, players = onlineLivingPlayers(state.players); if (!stage || !players.length) return; for (const entity of Object.values(state.entities)) { if (entity.kind !== 'monster' || !entity.monsterDefinitionId || !entity.ai) continue; const definition = monsterDefinition(entity.monsterDefinitionId), candidates = players.filter((player) => roomAt(stage, player.position)?.id === entity.roomId); if (!candidates.length) continue; const target = candidates.sort((a, b) => distance(a.position, entity.position) - distance(b.position, entity.position))[0]!, dx = target.position.x - entity.position.x, dy = target.position.y - entity.position.y, range = Math.hypot(dx, dy) || 1, aim = { x: dx / range, y: dy / range }; entity.ai.targetId = target.id; if (entity.cast.phase === 'idle' && now >= entity.ai.nextThinkAt) { const ability = selectAbility(definition.abilities, range); if (ability) { const spell = scaledMonsterSpell(ability, stage.difficulty, entity.boss), castId = `${entity.id}:cast:${Math.floor(now)}`; entity.ai.currentAbilityId = ability.id; entity.ai.movement = 'hold'; beginCast(entity, castId, spell, aim, { ...target.position }, now); continue; } entity.ai.nextThinkAt = now + 160; }
    if (entity.cast.phase !== 'idle' && entity.cast.phase !== 'recovery') continue; const nearest = [...definition.abilities].sort((a, b) => Math.abs(range - a.preferredRange) - Math.abs(range - b.preferredRange))[0]!; entity.ai.movement = range < nearest.minRange ? 'retreat' : range > nearest.preferredRange ? 'approach' : 'hold'; if (entity.ai.movement === 'hold') continue; const sign = entity.ai.movement === 'retreat' ? -1 : 1, statusSpeed = entity.statuses.frozen ? 0 : entity.statuses.chilled ? .55 : 1, desired = { x: entity.position.x + aim.x * definition.speed * statusSpeed * dt * sign, y: entity.position.y + aim.y * definition.speed * statusSpeed * dt * sign }; entity.position = resolveWorldMovement(state, entity.position, desired, entity.radius, entity.id); }
}
function updateMonsterCasts(state: GameState, now: number) { for (const entity of Object.values(state.entities)) { if (entity.kind !== 'monster' || !entity.ai || !entity.cast.spell || entity.cast.phaseEndsAt == null || now < entity.cast.phaseEndsAt) continue; const spell = entity.cast.spell; if (entity.cast.phase === 'chanting') { if (spell.delivery === 'area' && spell.area) { spawnMeteorWarning(state, entity, spell, now); entity.cast.phase = 'warning'; entity.cast.phaseEndsAt = now + spell.area.warningMs; } else { spawnSpellEntity(state, entity, spell, now); beginRecovery(entity, now); } } else if (entity.cast.phase === 'warning') { delete state.entities[`${entity.cast.castId}:warning:0`]; spawnMeteorImpact(state, entity, spell, now); beginRecovery(entity, now); } else if (entity.cast.phase === 'recovery' || entity.cast.phase === 'interrupted') { resetCast(entity); entity.ai.currentAbilityId = null; entity.ai.nextThinkAt = now + 180; } } }
function updateMonsterHitSources(ctx: FlowReducerContext<GameState>, now: number) { for (const source of Object.values(ctx.state.entities)) { const owner = source.ownerId ? ctx.state.entities[source.ownerId] : undefined; if (!source.source || owner?.kind !== 'monster' || now < source.source.nextTickAt) continue; const tick = source.source.tickMs > 0 ? Math.floor(now / source.source.tickMs) : 0, candidates = collisionCandidates(ctx.state, source, now, source.position); for (const candidate of candidates) { const eventId = `${source.id}:hit:${candidate.target.id}:${tick}`; if (ctx.state.seen.hits[eventId]) continue; ctx.dispatch('combat.resolveHit', { hitId: eventId, sourceId: source.id, targetId: candidate.target.id, tick, reason: candidate.reason }, ctx.host.id); if (source.kind === 'projectile' && !source.source.spell.tags.includes('pierce')) break; } source.source.nextTickAt = source.kind === 'projectile' && !candidates.length ? now + 50 : source.source.tickMs > 0 ? now + source.source.tickMs : Number.MAX_SAFE_INTEGER; } }
function updateTerrain(state: GameState, now: number) { for (const terrain of state.run.stage?.terrains ?? []) { if (terrain.kind !== 'falling-rock' || terrain.activatesAt == null) continue; if (terrain.endsAt != null && now >= terrain.endsAt) { terrain.active = false; terrain.warningAt = terrain.activatesAt = terrain.endsAt = null; continue; } if (now >= terrain.activatesAt) for (const player of onlineLivingPlayers(state.players)) if (distance(player.position, terrain.position) <= terrain.radius) { player.health.current = Math.max(0, player.health.current - 22); terrain.activatesAt = Number.MAX_SAFE_INTEGER; } } }
function advancePortal(state: GameState, now: number) { const portal = state.run.portal; if (!portal || !portal.active || !onlineLivingPlayers(state.players).every((player) => distance(player.position, portal.position) <= 58)) return; if (state.run.stageIndex >= 2) { state.phase = 'victory'; state.run.completedAt = now; state.message = '远征胜利'; return; } const nextIndex = state.run.stageIndex + 1, stage = generateStage(state.run.seed, nextIndex); state.run.stageIndex = nextIndex; state.run.stage = stage; state.run.exploredRoomIds = ['room-0']; state.run.portal = null; state.entities = {}; state.loot = {}; state.merchant = stage.merchant; state.forge = stage.forge; state.seen = { hits: {}, spawns: {} }; for (const [index, player] of onlineLivingPlayers(state.players).entries()) { player.position = { x: stage.world.spawn.x + index * 54, y: stage.world.spawn.y }; player.positionEpoch += 1; player.health.current = player.health.max; player.cast = idleCast(); } state.message = `遗迹远征 · 第${nextIndex + 1}关`; }
function resolveCombatHit(ctx: FlowReducerContext<GameState>, payload: HitRequestPayload) { const source = ctx.state.entities[payload.sourceId], targetBefore = ctx.state.entities[payload.targetId]; if (!source?.source) return; const owner = source.ownerId ? ctx.state.players[source.ownerId] ?? ctx.state.entities[source.ownerId] : undefined; if (!owner || 'alive' in owner && !owner.alive) return; const hitPayload = structuredClone(source.source.spell.payload); if (targetBefore?.boss && ctx.state.run.stage?.boss.shielded && hitPayload.damage) for (const key of Object.keys(hitPayload.damage) as Array<keyof typeof hitPayload.damage>) if (hitPayload.damage[key] != null) hitPayload.damage[key]! *= .2; const event: HitEvent = { hitId: payload.hitId, sourceId: source.id, ownerId: source.ownerId, targetId: payload.targetId, payload: hitPayload, delivery: source.source.spell.delivery, detached: source.detached, tags: source.source.spell.tags }, resolution = applyHit(ctx.state, event, ctx.now()); emitAll(ctx, resolution.events); if (!resolution.accepted && payload.reason !== 'blocked') return; const target = ctx.state.players[payload.targetId] ?? ctx.state.entities[payload.targetId]; if (resolution.accepted && target && target.health.current <= 0) { if ('alive' in target) killPlayer(ctx, target); else { delete ctx.state.entities[payload.targetId]; ctx.emit('endwell.entity_destroyed', { type: 'entity_destroyed', entityId: payload.targetId, kind: targetBefore?.kind ?? 'monster', reason: 'killed' } satisfies GameEvent); } } if (source.kind === 'projectile' && !source.source.spell.tags.includes('pierce')) delete ctx.state.entities[source.id]; }

export const endwellGame = defineGame<GameState>({
  meta: { name: 'Endwell', minPlayers: 1, maxPlayers: 4 }, initialState,
  lifecycle: {
    create(ctx) { ctx.state.seed = Math.floor(ctx.random() * 0x7fffffff); ctx.state.schemaVersion = 5; ctx.state.run.discoveredSpellIds ??= ['resurrect']; for (const p of Object.values(ctx.state.players)) p.selectedElements ??= []; for (const encounter of ctx.state.run.stage?.encounters ?? []) { encounter.waves ??= [encounter.monsterIds]; encounter.totalWaves ??= encounter.waves.length; encounter.currentWave ??= encounter.status === 'dormant' ? 0 : encounter.totalWaves; encounter.nextWaveAt ??= null; encounter.scaledForPlayers ??= encounter.status === 'dormant' ? null : Math.max(1, onlineLivingPlayers(ctx.state.players).length); } },
    join(ctx, joined) { ctx.state.hostId ??= joined.id; const existing = ctx.state.players[joined.id]; if (existing) { existing.connected = true; existing.selectedElements ??= []; } else ctx.state.players[joined.id] = player(joined.id, joined.name || `巫师 ${Object.keys(ctx.state.players).length + 1}`, Object.keys(ctx.state.players).length); },
    reconnect(ctx, joined) { if (ctx.state.players[joined.id]) ctx.state.players[joined.id].connected = true; },
    leave(ctx, leaving) { if (ctx.state.players[leaving.id]) ctx.state.players[leaving.id].connected = false; if (ctx.state.hostId === leaving.id) ctx.state.hostId = Object.values(ctx.state.players).find((p) => p.connected)?.id ?? null; },
  },
  actions: {
    'game.start': { sync: { mode: 'hostAuthoritative' }, validate(ctx) { return ctx.actor.id === ctx.state.hostId ? accept(null) : reject('host-only'); }, reduce(ctx) { const now = ctx.now(), stage = generateStage(ctx.state.seed, 0); ctx.state.phase = 'running'; ctx.state.startedAt = now; ctx.state.worldTime = now; ctx.state.run = { seed: ctx.state.seed, stageIndex: 0, stage, exploredRoomIds: ['room-0'], discoveredSpellIds: ['resurrect'], completedRewardIds: [], portal: null, startedAt: now, completedAt: null }; ctx.state.entities = {}; ctx.state.environment = { global: null, fields: [] }; ctx.state.loot = {}; ctx.state.merchant = stage.merchant; ctx.state.forge = stage.forge; ctx.state.forgeUses = {}; ctx.state.seen = { hits: {}, spawns: {} }; for (const [index, p] of Object.values(ctx.state.players).entries()) { p.position = { x: stage.world.spawn.x + index * 54, y: stage.world.spawn.y }; p.positionEpoch += 1; p.alive = true; p.gold = 50; p.inventory = []; p.equipment = {}; p.health.current = p.health.max; p.cast = idleCast(); p.shields = []; delete p.forceVelocity; p.scrollCooldowns = {}; } ctx.state.message = '遗迹远征 · 第一关'; } },
    'game.finish': { sync: { mode: 'hostAuthoritative' }, validate(ctx) { return ctx.actor.id === ctx.state.hostId ? accept(null) : reject('host-only'); }, reduce(ctx) { ctx.state.phase = 'gameover'; ctx.state.message = '试炼结束'; } },
    'player.pose': { sync: { mode: 'hostRelay' }, validate(ctx, payload: PosePayload) { const p = ctx.state.players[ctx.actor.id], stage = ctx.state.run.stage, selected = payload.selectedElements ?? []; if (!stage || !p?.alive || !Number.isInteger(payload.sequence) || payload.sequence <= p.lastPoseSequence || !Number.isFinite(payload.sentAt) || !finiteVec(payload.position) || !finiteVec(payload.aim) || !Array.isArray(selected) || selected.length > 4 || !selected.every((element) => ELEMENTS.includes(element))) return reject('invalid-pose'); const dt = Math.max(.064, Math.min(1, (payload.sentAt - ctx.state.worldTime) / 1000)), maxDistance = 420 * dt + 45, dx = payload.position.x - p.position.x, dy = payload.position.y - p.position.y, distance = Math.hypot(dx, dy), limited = distance > maxDistance ? { x: p.position.x + dx / distance * maxDistance, y: p.position.y + dy / distance * maxDistance } : payload.position; return accept({ ...payload, selectedElements: [...selected], sentAt: Math.max(ctx.now() - 5000, Math.min(ctx.now() + 1000, payload.sentAt)), position: clampPosition(ctx.state, limited, p.position, p.id), aim: normalize(payload.aim) }); }, reduce(ctx, payload: PosePayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive || payload.sequence <= p.lastPoseSequence) return; p.lastPoseSequence = payload.sequence; p.position = payload.position; p.aim = payload.aim; p.selectedElements = [...(payload.selectedElements ?? [])]; const room = ctx.state.run.stage && roomAt(ctx.state.run.stage, p.position); if (room && !ctx.state.run.exploredRoomIds.includes(room.id)) ctx.state.run.exploredRoomIds.push(room.id); if (p.cast.phase === 'active' && p.cast.spell?.channelled) { p.cast.aim = payload.aim; for (const entity of Object.values(ctx.state.entities)) if (entity.ownerId === p.id && !entity.detached) { entity.position = { ...p.position }; if (entity.source?.spell.delivery === 'beam') entity.targetDirection = payload.aim; else entity.direction = payload.aim; } } ctx.emit('endwell.player_pose', { playerId: p.id, ...payload, selectedElements: [...(payload.selectedElements ?? [])] }); } },
    'cast.request': { sync: { mode: 'hostRelay' }, validate(ctx, payload: CastRequestPayload) { const p = ctx.state.players[ctx.actor.id]; if (ctx.state.phase !== 'running' || !p?.alive || p.cast.phase !== 'idle' || !Number.isInteger(payload.sequence) || payload.sequence <= p.lastCastSequence || payload.castId !== `${ctx.actor.id}:cast:${payload.sequence}` || !Array.isArray(payload.elements) || payload.elements.length < 1 || payload.elements.length > 4 || !payload.elements.every((element) => ELEMENTS.includes(element)) || !finiteVec(payload.aim) || !finiteVec(payload.target)) return reject('invalid-cast'); const spell = applyEquipmentToSpell(resolveCastSpell(p, payload.elements, ctx.now()), p.equipment); return accept({ ...payload, aim: normalize(payload.aim), target: spellTargetMode(spell) === 'self' ? { ...p.position } : clampTarget(ctx.state, p.position, payload.target, spell.range) }); }, reduce(ctx, payload: CastRequestPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p || payload.sequence <= p.lastCastSequence || p.cast.phase !== 'idle') return; const scroll = ownedReadyScrollFor(payload.elements, p, ctx.now()); const baseSpell = scroll ? scroll.definition.spec(payload.elements) : resolveSpell(payload.elements); const spell = applySpellModifiers(applyEquipmentToSpell(baseSpell, p.equipment), p.buffs.flatMap((buff) => buff.modifiers)); if (scroll) p.scrollCooldowns[scroll.definition.id] = ctx.now() + scroll.definition.cooldownMs; p.lastCastSequence = payload.sequence; beginCast(p, payload.castId, spell, normalize(payload.aim), payload.target, ctx.now()); ctx.emit('endwell.cast_started', { type: 'cast_started', casterId: p.id, spellId: spell.id } satisfies GameEvent); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:activate`, spell.chantMs, 'internal.castActivate', { playerId: p.id, castId: payload.castId }, p.id); } },
    'cast.aim': { sync: { mode: 'hostRelay' }, validate(ctx, payload: CastAimPayload) { return playerAlive(ctx) && finiteVec(payload.aim) && Number.isInteger(payload.sequence) ? accept({ ...payload, aim: normalize(payload.aim) }) : reject('invalid-aim'); }, reduce(ctx, payload: CastAimPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive) return; p.aim = payload.aim; if (p.cast.phase === 'chanting' || p.cast.phase === 'active') p.cast.aim = payload.aim; if (p.cast.phase === 'active') for (const entity of Object.values(ctx.state.entities)) if (entity.ownerId === p.id && !entity.detached) { entity.position = { ...p.position }; if (entity.source?.spell.delivery === 'beam') entity.targetDirection = payload.aim; else entity.direction = payload.aim; } } },
    'cast.release': { sync: { mode: 'hostRelay' }, validate(ctx, payload: CastReleasePayload) { const p = ctx.state.players[ctx.actor.id]; return p?.alive && p.cast.castId === payload.castId ? accept(payload) : reject('cast-mismatch'); }, reduce(ctx, payload: CastReleasePayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive || p.cast.castId !== payload.castId || !p.cast.spell?.channelled) return; removeOwnedActiveEntities(ctx.state, p.id); const early = p.cast.phase === 'chanting'; if (early) ctx.emit('endwell.cast_interrupted', { type: 'cast_interrupted', casterId: p.id, reason: 'cancelled' } satisfies GameEvent); recovery(ctx, p, payload.castId, p.cast.spell); } },
    'cast.activate': { sync: { mode: 'hostRelay' }, validate(ctx, payload: CastActivatePayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive || p.cast.castId !== payload.castId || p.cast.phase !== 'chanting') return reject('cast-mismatch'); if (p.cast.phaseEndsAt != null && ctx.now() + 80 < p.cast.phaseEndsAt) return reject('chanting'); return accept(payload); }, reduce(ctx, payload: CastActivatePayload) { activatePlayerCast(ctx, ctx.actor.id, payload.castId); } },
    'internal.castActivate': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string }) { activatePlayerCast(ctx, payload.playerId, payload.castId); } },
    'internal.areaImpact': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string }) { const p = ctx.state.players[payload.playerId], spell = p?.cast.spell; if (!p?.alive || !spell || p.cast.castId !== payload.castId || spell.delivery !== 'area') return; delete ctx.state.entities[`${payload.castId}:warning:0`]; const impact = spawnMeteorImpact(ctx.state, p, spell, ctx.now()); ctx.emit('endwell.entity_spawned', { type: 'entity_spawned', entityId: impact.id } satisfies GameEvent); recovery(ctx, p, payload.castId, spell); } },
    'internal.castIdle': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string }) { const p = ctx.state.players[payload.playerId]; if (p?.cast.castId === payload.castId) resetCast(p); } },
    'cast.interrupt': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { playerId: string; castId: string; reason: string }) { const p = ctx.state.players[payload.playerId]; if (!p || p.cast.castId !== payload.castId) return; removeOwnedActiveEntities(ctx.state, p.id); p.cast.phase = 'interrupted'; p.cast.phaseEndsAt = ctx.now() + 350; ctx.emit('endwell.cast_interrupted', { type: 'cast_interrupted', casterId: p.id, reason: payload.reason } satisfies GameEvent); if (ctx.role === 'authority') ctx.timers.dispatch(`cast:${payload.castId}:idle`, 350, 'internal.castIdle', { playerId: p.id, castId: payload.castId }, p.id); } },
    'combat.hit': { sync: { mode: 'hostRelay' }, validate(ctx, payload: HitRequestPayload) { const source = ctx.state.entities[payload.sourceId], owner = source?.ownerId ? ctx.state.players[source.ownerId] : undefined; if (!source?.source || source.ownerId !== ctx.actor.id || !owner?.alive || !ctx.state.players[payload.targetId] && !ctx.state.entities[payload.targetId] || typeof payload.hitId !== 'string' || payload.hitId.length > 160 || payload.reason !== 'hit' && payload.reason !== 'blocked' || ctx.state.seen.hits[payload.hitId] || !verifiesHit(ctx.state, source, payload.targetId, payload.reason, ctx.now())) return reject('invalid-hit'); return accept(payload); }, reduce: resolveCombatHit },
    'combat.resolveHit': { sync: { mode: 'hostAuthoritative' }, reduce: resolveCombatHit },
    'inventory.equip': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && itemPayload(payload) ? accept(payload) : reject('invalid-item'); }, reduce(ctx, payload: ItemActionPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive || playerInCombat(ctx.state, p.id)) return; const index = p.inventory.findIndex((item) => item.id === payload.itemId), item = p.inventory[index]; if (index < 0 || !isEquipment(item)) return; const old = p.equipment[item.slot]; p.inventory.splice(index, 1); if (old) p.inventory.push(old); p.equipment[item.slot] = item; } },
    'inventory.unequip': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && itemPayload(payload) ? accept(payload) : reject('invalid-item'); }, reduce(ctx, payload: ItemActionPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive || playerInCombat(ctx.state, p.id)) return; const slot = (['staff', 'robe', 'ring'] as const).find((key) => p.equipment[key]?.id === payload.itemId); if (!slot) return; const item = p.equipment[slot]!; delete p.equipment[slot]; if (p.inventory.length < 9) p.inventory.push(item); else drop(ctx.state, p, item, ctx.now(), 'unequip'); } },
    'inventory.drop': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && itemPayload(payload) ? accept(payload) : reject('invalid-item'); }, reduce(ctx, payload: ItemActionPayload) { const p = ctx.state.players[ctx.actor.id]; if (!p?.alive) return; const index = p.inventory.findIndex((item) => item.id === payload.itemId), item = p.inventory[index]; if (index < 0 || !item) return; p.inventory.splice(index, 1); drop(ctx.state, p, item, ctx.now(), 'drop'); } },
    'inventory.pickup': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && pickupPayload(payload) ? accept(payload) : reject('invalid-loot'); }, reduce(ctx, payload: PickupPayload) { const p = ctx.state.players[ctx.actor.id], loot = ctx.state.loot[payload.lootId]; if (!p?.alive || !loot || p.inventory.length >= 9 || distance(p.position, loot.position) > 115 || loot.droppedByPlayerId && loot.droppedByPlayerId !== p.id && ctx.now() < loot.ownerPriorityUntil) return; delete ctx.state.loot[payload.lootId]; p.inventory.push(loot.item); } },
    'merchant.buy': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && merchantPayload(payload) ? accept(payload) : reject('invalid-merchant'); }, reduce(ctx, payload: MerchantItemPayload) { const p = ctx.state.players[ctx.actor.id], merchant = ctx.state.merchant; if (!p?.alive || !merchant || merchant.id !== payload.merchantId || p.inventory.length >= 9 || distance(p.position, merchant.position) > merchant.radius + 90) return; const index = merchant.stock.findIndex((entry) => entry.item.id === payload.itemId), entry = merchant.stock[index]; if (index < 0 || !entry || p.gold < entry.price) return; p.gold -= entry.price; p.inventory.push(entry.item); merchant.stock.splice(index, 1); } },
    'merchant.sell': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && merchantPayload(payload) ? accept(payload) : reject('invalid-merchant'); }, reduce(ctx, payload: MerchantItemPayload) { const p = ctx.state.players[ctx.actor.id], merchant = ctx.state.merchant; if (!p?.alive || !merchant || merchant.id !== payload.merchantId || distance(p.position, merchant.position) > merchant.radius + 90) return; const index = p.inventory.findIndex((item) => item.id === payload.itemId), item = p.inventory[index]; if (index < 0 || !item || (!isEquipment(item) && !isScroll(item))) return; const price = sellPrice(item); if (price <= 0) return; p.inventory.splice(index, 1); p.gold += price; } },
    'forge.fuse': { sync: { mode: 'hostRelay' }, validate(ctx, payload: unknown) { return playerAlive(ctx) && forgePayload(payload) ? accept({ ...payload, itemIds: payload.itemIds.slice(0, 3) }) : reject('invalid-forge'); }, reduce(ctx, payload: ForgeFusePayload) { const p = ctx.state.players[ctx.actor.id], forge = ctx.state.forge, ids = payload.itemIds; if (!p?.alive || !forge || forge.id !== payload.forgeId || ids.length !== 3 || new Set(ids).size !== 3 || distance(p.position, forge.position) > forge.radius + 90) return; const materials = ids.map((id) => p.inventory.find((item) => item.id === id)); if (materials.some((item) => !item) || !canFuse(materials as InventoryItem[])) return; const uses = ctx.state.forgeUses[forge.id]?.[p.id] ?? 0, price = fusionPrice(uses), wasFull = p.inventory.length >= 9; if (p.gold < price) return; const result = fuseEquipment(materials as InventoryItem[], fusionSeed(ctx.state.run.stage?.stageSeed ?? ctx.state.seed, p.id, [...ids].sort(), uses)); if (!result) return; p.gold -= price; p.inventory = p.inventory.filter((item) => !ids.includes(item.id)); ctx.state.forgeUses[forge.id] ??= {}; ctx.state.forgeUses[forge.id]![p.id] = uses + 1; if (!wasFull && p.inventory.length < 9) p.inventory.push(result); else drop(ctx.state, p, result, ctx.now(), 'fusion'); } },
    'internal.environmentTick': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { environmentId: string }) { const environment = ctx.state.environment.global; if (!environment || environment.id !== payload.environmentId) return; applyEnvironment(ctx.state, ctx.now(), environment.ownerId); environment.nextTickAt = ctx.now() + environment.tickInterval; } },
    'internal.environmentExpire': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { environmentId: string }) { if (ctx.state.environment.global?.id === payload.environmentId) ctx.state.environment.global = null; } },
    'entity.expire': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: { entityId: string }) { const entity = ctx.state.entities[payload.entityId]; if (!entity) return; delete ctx.state.entities[payload.entityId]; ctx.state.environment.fields = ctx.state.environment.fields.filter((id) => id !== payload.entityId); ctx.emit('endwell.entity_destroyed', { type: 'entity_destroyed', entityId: payload.entityId, kind: entity.kind, reason: 'expired' } satisfies GameEvent); } },
  },
  systems: [{ runOn: 'authority', intervalMs: 100, update(ctx, dt = .1) { const now = ctx.now(), step = Math.min(.2, Math.max(.001, dt)); ctx.state.worldTime = now; updateAttachedDirections(ctx.state, step); for (const target of Object.values(ctx.state.players).filter((p) => p.alive)) integrateForceMotion(ctx.state, target, step); for (const entity of Object.values(ctx.state.entities).filter((e) => e.kind === 'monster')) integrateForceMotion(ctx.state, entity, step); for (const [id, entity] of Object.entries(ctx.state.entities)) if (entity.expiresAt != null && entity.expiresAt <= now) ctx.dispatch('entity.expire', { entityId: id }, ctx.host.id); const environment = ctx.state.environment.global; if (environment && environment.endsAt <= now) ctx.dispatch('internal.environmentExpire', { environmentId: environment.id }, ctx.host.id); else if (environment && environment.nextTickAt <= now) ctx.dispatch('internal.environmentTick', { environmentId: environment.id }, ctx.host.id); for (const target of [...Object.values(ctx.state.players), ...Object.values(ctx.state.entities)]) for (const [key, instance] of Object.entries(target.statuses)) if (instance && instance.endsAt <= now) delete target.statuses[key as ElementStatusType]; if (ctx.state.phase === 'running') { updateEncounters(ctx.state, now); updateBoss(ctx.state, now); updateMonsterCasts(ctx.state, now); updateMonsterAi(ctx.state, now, step); updateMonsterHitSources(ctx, now); updateTerrain(ctx.state, now); advancePortal(ctx.state, now); if (onlineLivingPlayers(ctx.state.players).length === 0 && Object.values(ctx.state.players).some((player) => player.connected)) { ctx.state.phase = 'gameover'; ctx.state.message = '远征失败'; } } } }],
});
