import type { BossState, EncounterState, EntityState, MapCorridor, MapRoom, MerchantState, ObjectiveState, PlayerState, RoomTemplateKind, SpellSpec, StageBlueprint, TerrainState, ThemeId, Vec2 } from './contracts';
import { createCatalyst, generateEquipment } from './rules/equipment';

export const GENERATION_VERSION = 1;
export const WORLD_WIDTH = 7800;
export const WORLD_HEIGHT = 5100;
const COLS = 6, ROWS = 5, CELL_W = 1250, CELL_H = 950, MARGIN_X = 150, MARGIN_Y = 150, ROOM_COUNT = 14;

export type ThemeDefinition = { id: ThemeId; roomTemplates: RoomTemplateKind[]; terrainKinds: TerrainState['kind'][]; monsterPool: string[]; eventPool: ObjectiveState['kind'][]; equipmentPool: string; visual: { floor: string; wall: string; accent: string }; audioKey: string };
export type MonsterAbilityDefinition = { id: string; spell: SpellSpec; minRange: number; maxRange: number; preferredRange: number; priority: number };
export type MonsterDefinition = { id: string; health: number; radius: number; speed: number; ai: 'chaser' | 'shooter' | 'guardian'; abilities: MonsterAbilityDefinition[]; resistances: EntityState['resistances']; dropClass: 'normal' | 'elite' | 'boss' };
export type BossDefinition = { id: string; monsterId: string; phaseThresholds: number[]; mechanicIntervalMs: number; addDefinitionId: string; baseAddCap: number; rewardClass: 'boss' };
export type StageDefinition = { index: number; themeId: ThemeId; bossId: string; requiredObjectives: number; difficulty: number; rewardMultiplier: number; mechanicSpeed: number; addBonus: number };

export const THEMES: Record<ThemeId, ThemeDefinition> = { ruins: { id: 'ruins', roomTemplates: ['standard', 'wide', 'tall'], terrainKinds: ['falling-rock', 'rune-wall', 'rune', 'safe-zone', 'obstacle'], monsterPool: ['ruins.chaser', 'ruins.shooter', 'ruins.guardian'], eventPool: ['elite', 'altar', 'puzzle'], equipmentPool: 'ruins', visual: { floor: '#171827', wall: '#625c64', accent: '#d6b56f' }, audioKey: 'theme.ruins' } };
const monsterSpell = (id: string, name: string, delivery: SpellSpec['delivery'], values: { element: 'rock' | 'fire' | 'lightning'; damage: number; chant: number; recovery: number; range: number; radius: number; lifetime: number; speed?: number; buildup?: number; warning?: number; knockback?: number }): SpellSpec => ({ id, name, elements: [values.element], elementVector: { rock: 0, fire: 0, ice: 0, life: 0, lightning: 0, water: 0, shield: 0, [values.element]: 1 }, delivery, payload: { damage: { [values.element]: values.damage }, statusBuildup: values.buildup ? { [values.element === 'fire' ? 'burning' : values.element === 'lightning' ? 'shocked' : 'chilled']: values.buildup } : undefined, effects: values.knockback ? [{ type: 'knockback', force: values.knockback }] : undefined }, chantMs: values.chant, recoveryMs: values.recovery, detached: true, channelled: false, lifetimeMs: values.lifetime, speed: values.speed, tickMs: 0, range: values.range, radius: values.radius, coneAngle: delivery === 'spray' ? Math.PI * .48 : undefined, area: delivery === 'area' ? { warningMs: values.warning ?? 800, impactDelay: values.warning ?? 800 } : undefined, targeting: { canHitSelf: false, canHitAllies: false, canHitEnemies: true, canHitNeutral: true }, blocking: { blockBySelf: false, blockByAllies: true, blockByEnemies: true, blockByNeutral: true, blockByWalls: true, blockBySummons: true }, tags: ['monster-ability', values.element], visualKey: `monster.${id}` });
const CLAW = monsterSpell('ruins-claw', '岩爪', 'spray', { element: 'rock', damage: 10.4, chant: 470, recovery: 805, range: 68, radius: 24, lifetime: 160, knockback: 45 });
const RUNE_BOLT = monsterSpell('ruins-rune-bolt', '雷纹弹', 'projectile', { element: 'lightning', damage: 8.5, chant: 675, recovery: 990, range: 410, radius: 13, lifetime: 1800, speed: 260, buildup: 45 });
const GUARDIAN_WAVE = monsterSpell('ruins-guardian-wave', '守卫震波', 'spray', { element: 'rock', damage: 15, chant: 805, recovery: 1170, range: 115, radius: 34, lifetime: 180, knockback: 90 });
const BOSS_FLAME = monsterSpell('ruins-boss-flame', '遗迹烈焰', 'area', { element: 'fire', damage: 25.5, chant: 485, recovery: 1125, range: 440, radius: 95, lifetime: 180, warning: 1000, buildup: 55 });
export const MONSTERS: Record<string, MonsterDefinition> = {
  'ruins.chaser': { id: 'ruins.chaser', health: 78, radius: 25, speed: 94, ai: 'chaser', abilities: [{ id: 'claw', spell: CLAW, minRange: 0, maxRange: 74, preferredRange: 52, priority: 1 }], resistances: {}, dropClass: 'normal' },
  'ruins.shooter': { id: 'ruins.shooter', health: 59, radius: 23, speed: 66, ai: 'shooter', abilities: [{ id: 'rune-bolt', spell: RUNE_BOLT, minRange: 95, maxRange: 390, preferredRange: 245, priority: 1 }], resistances: { lightning: .1 }, dropClass: 'normal' },
  'ruins.guardian': { id: 'ruins.guardian', health: 120, radius: 31, speed: 58, ai: 'guardian', abilities: [{ id: 'guardian-wave', spell: GUARDIAN_WAVE, minRange: 0, maxRange: 125, preferredRange: 78, priority: 1 }], resistances: { physical: .2 }, dropClass: 'elite' },
  'ruins.boss': { id: 'ruins.boss', health: 765, radius: 58, speed: 52, ai: 'guardian', abilities: [{ id: 'boss-flame', spell: BOSS_FLAME, minRange: 80, maxRange: 430, preferredRange: 210, priority: 2 }, { id: 'guardian-wave', spell: GUARDIAN_WAVE, minRange: 0, maxRange: 145, preferredRange: 90, priority: 3 }, { id: 'rune-bolt', spell: RUNE_BOLT, minRange: 120, maxRange: 390, preferredRange: 240, priority: 1 }], resistances: { physical: .15 }, dropClass: 'boss' },
};
export const BOSSES: Record<string, BossDefinition> = { 'ruins.guardian': { id: 'ruins.guardian', monsterId: 'ruins.boss', phaseThresholds: [.66, .33], mechanicIntervalMs: 8000, addDefinitionId: 'ruins.chaser', baseAddCap: 3, rewardClass: 'boss' } };
export const STAGES: StageDefinition[] = [
  { index: 0, themeId: 'ruins', bossId: 'ruins.guardian', requiredObjectives: 2, difficulty: 1, rewardMultiplier: 1, mechanicSpeed: 1, addBonus: 0 },
  { index: 1, themeId: 'ruins', bossId: 'ruins.guardian', requiredObjectives: 2, difficulty: 1.28, rewardMultiplier: 1.25, mechanicSpeed: .86, addBonus: 1 },
  { index: 2, themeId: 'ruins', bossId: 'ruins.guardian', requiredObjectives: 2, difficulty: 1.62, rewardMultiplier: 1.55, mechanicSpeed: .72, addBonus: 2 },
];

export function createRng(seed: number) { let state = (seed >>> 0) || 0x6d2b79f5; return () => { state = (state + 0x6d2b79f5) | 0; let t = state; t = Math.imul(t ^ t >>> 15, t | 1); t ^= t + Math.imul(t ^ t >>> 7, t | 61); return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
export function hashText(value: string) { let hash = 2166136261; for (let i = 0; i < value.length; i++) { hash ^= value.charCodeAt(i); hash = Math.imul(hash, 16777619); } return hash >>> 0; }
export function deriveSeed(seed: number, domain: string) { return (Math.imul((seed ^ hashText(domain)) >>> 0, 0x9e3779b1) + 0x85ebca6b) >>> 0; }
export function deriveStageSeed(runSeed: number, stageIndex: number) { return deriveSeed(runSeed, `stage:${stageIndex}`); }

type Placement = { gridX: number; gridY: number; gridWidth: number; gridHeight: number; template: RoomTemplateKind; neighbors: string[] };
export function generateStage(runSeed: number, stageIndex: number): StageBlueprint {
  const definition = STAGES[stageIndex] ?? STAGES[STAGES.length - 1]!, stageSeed = deriveStageSeed(runSeed, stageIndex), map = generateMap(deriveSeed(stageSeed, 'map'));
  const terrain = generateTerrain(map.rooms, deriveSeed(stageSeed, 'terrain')), progress = generateProgress(map.rooms, map.spawn, stageIndex, deriveSeed(stageSeed, 'progress'));
  const encounters = generateEncounters(map.rooms, progress, deriveSeed(stageSeed, 'encounters')), merchant = generateMerchant(map.rooms, progress, terrain, deriveSeed(stageSeed, 'merchant'), stageIndex), forgeRoom = map.rooms.find((room) => !progress.used.has(room.id) && room.id !== 'room-0') ?? map.rooms[1]!;
  const blueprint: Omit<StageBlueprint, 'fingerprint'> = { generationVersion: GENERATION_VERSION, index: stageIndex, stageSeed, themeId: definition.themeId, bossDefinitionId: definition.bossId, difficulty: definition.difficulty, rewardMultiplier: definition.rewardMultiplier, world: { width: WORLD_WIDTH, height: WORLD_HEIGHT, spawn: map.spawn, rooms: map.rooms, corridors: map.corridors }, terrains: terrain, encounters, objectives: progress.objectives, boss: progress.boss, merchant, forge: { id: `forge:${stageIndex}`, position: safeEconomyPosition(forgeRoom, terrain, 64), radius: 64 }, rewardSeeds: Object.fromEntries(encounters.map((encounter) => [encounter.id, deriveSeed(stageSeed, `reward:${encounter.id}`)])) };
  return { ...blueprint, fingerprint: fingerprint(blueprint) };
}

function generateMap(seed: number) {
  const random = createRng(seed), rooms: MapRoom[] = [makeRoom('room-0', { gridX: 2, gridY: 2, gridWidth: 1, gridHeight: 1, template: 'standard', neighbors: [] }, random)], occupied = new Map<string, string>([['2,2', 'room-0']]), edges: Array<[string, string]> = [];
  for (let index = 1; index < ROOM_COUNT; index++) { const preferred: RoomTemplateKind = index % 5 === 2 ? 'wide' : index % 5 === 4 ? 'tall' : 'standard', candidates = placements(preferred, occupied), fallback = candidates.length ? candidates : placements('standard', occupied), selected = fallback[Math.floor(random() * fallback.length)]!; const room = makeRoom(`room-${index}`, selected, random); rooms.push(room); for (let y = selected.gridY; y < selected.gridY + selected.gridHeight; y++) for (let x = selected.gridX; x < selected.gridX + selected.gridWidth; x++) occupied.set(`${x},${y}`, room.id); edges.push([selected.neighbors[Math.floor(random() * selected.neighbors.length)]!, room.id]); }
  const connected = new Set(edges.map(([a, b]) => edgeKey(a, b))), loops: Array<[string, string]> = []; for (const room of rooms) for (const other of rooms) if (room.id < other.id && touches(room, other) && !connected.has(edgeKey(room.id, other.id))) loops.push([room.id, other.id]); shuffle(loops, random); edges.push(...loops.slice(0, 3));
  const byId = new Map(rooms.map((room) => [room.id, room])), corridors = edges.map(([a, b], index) => { const from = byId.get(a)!, to = byId.get(b)!; if (!from.connections.includes(to.id)) from.connections.push(to.id); if (!to.connections.includes(from.id)) to.connections.push(from.id); return corridor(`corridor-${index}`, from, to); });
  return { rooms, corridors, spawn: center(rooms[0]!) };
}
function placements(template: RoomTemplateKind, occupied: Map<string, string>): Placement[] { const [gridWidth, gridHeight] = template === 'wide' ? [2, 1] : template === 'tall' ? [1, 2] : [1, 1], result: Placement[] = []; for (let gridY = 0; gridY <= ROWS - gridHeight; gridY++) for (let gridX = 0; gridX <= COLS - gridWidth; gridX++) { let free = true; const neighbors = new Set<string>(); for (let y = gridY; y < gridY + gridHeight; y++) for (let x = gridX; x < gridX + gridWidth; x++) { if (occupied.has(`${x},${y}`)) free = false; for (const [nx, ny] of [[x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]]) { const id = occupied.get(`${nx},${ny}`); if (id) neighbors.add(id); } } if (free && neighbors.size) result.push({ gridX, gridY, gridWidth, gridHeight, template, neighbors: [...neighbors] }); } return result; }
function makeRoom(id: string, p: Placement, random: () => number): MapRoom { const footprintW = p.gridWidth * CELL_W, footprintH = p.gridHeight * CELL_H, width = Math.min(footprintW - 40, p.template === 'wide' ? 2100 + Math.floor(random() * 4) * 50 : 980 + Math.floor(random() * 4) * 50), height = Math.min(footprintH - 40, p.template === 'tall' ? 1700 + Math.floor(random() * 3) * 50 : 700 + Math.floor(random() * 4) * 50); return { id, gridX: p.gridX, gridY: p.gridY, gridWidth: p.gridWidth, gridHeight: p.gridHeight, template: p.template, position: { x: MARGIN_X + p.gridX * CELL_W + (footprintW - width) / 2, y: MARGIN_Y + p.gridY * CELL_H + (footprintH - height) / 2 }, width, height, connections: [] }; }
function corridor(id: string, a: MapRoom, b: MapRoom): MapCorridor { const ac = center(a), bc = center(b); if (Math.abs(ac.x - bc.x) > Math.abs(ac.y - bc.y)) return { id, fromRoomId: a.id, toRoomId: b.id, position: { x: Math.min(ac.x, bc.x), y: (ac.y + bc.y) / 2 - 60 }, width: Math.abs(ac.x - bc.x), height: 120 }; return { id, fromRoomId: a.id, toRoomId: b.id, position: { x: (ac.x + bc.x) / 2 - 60, y: Math.min(ac.y, bc.y) }, width: 120, height: Math.abs(ac.y - bc.y) }; }
function touches(a: MapRoom, b: MapRoom) { const row = Math.max(a.gridY, b.gridY) < Math.min(a.gridY + a.gridHeight, b.gridY + b.gridHeight), col = Math.max(a.gridX, b.gridX) < Math.min(a.gridX + a.gridWidth, b.gridX + b.gridWidth); return row && (a.gridX + a.gridWidth === b.gridX || b.gridX + b.gridWidth === a.gridX) || col && (a.gridY + a.gridHeight === b.gridY || b.gridY + b.gridHeight === a.gridY); }

function generateTerrain(rooms: MapRoom[], seed: number): TerrainState[] { const random = createRng(seed), result: TerrainState[] = [{ id: 'terrain:safe-spawn', roomId: 'room-0', kind: 'safe-zone', position: center(rooms[0]!), radius: 135, blocksMovement: false, active: true, warningAt: null, activatesAt: null, endsAt: null }]; for (const room of rooms.slice(1)) { const roll = random(), kind: TerrainState['kind'] = roll < .26 ? 'falling-rock' : roll < .48 ? 'rune-wall' : roll < .67 ? 'rune' : 'obstacle', position = { x: room.position.x + room.width * (.28 + random() * .44), y: room.position.y + room.height * (.28 + random() * .44) }, radius = kind === 'rune-wall' ? 52 : 55 + Math.floor(random() * 55); result.push({ id: `terrain:${room.id}:0`, roomId: room.id, kind, position, radius, width: kind === 'rune-wall' ? 42 : undefined, height: kind === 'rune-wall' ? Math.min(220, room.height * .35) : undefined, blocksMovement: kind === 'rune-wall' || kind === 'obstacle', active: true, warningAt: null, activatesAt: null, endsAt: null }); } return result; }
function generateProgress(rooms: MapRoom[], spawn: Vec2, stageIndex: number, seed: number) { const distances = roomDistances(rooms, 'room-0'), ranked = rooms.slice(1).sort((a, b) => (distances.get(b.id) ?? 0) - (distances.get(a.id) ?? 0) || a.id.localeCompare(b.id)), bossRoom = ranked.find((room) => room.gridWidth * room.gridHeight > 1) ?? ranked[0]!, used = new Set([bossRoom.id]), take = () => { const room = ranked.find((candidate) => !used.has(candidate.id))!; used.add(room.id); return room; }, kinds: ObjectiveState['kind'][] = ['elite', 'altar', 'puzzle'], objectives = kinds.map((kind) => ({ id: `objective:${stageIndex}:${kind}`, roomId: take().id, kind, status: 'dormant' as const, progress: 0, target: kind === 'altar' ? 2 : kind === 'puzzle' ? 3 : 1 })); const c = center(bossRoom), runes = Array.from({ length: 4 }, (_, index) => ({ id: `boss-rune:${stageIndex}:${index}`, position: { x: c.x + Math.cos(index / 4 * Math.PI * 2) * 210, y: c.y + Math.sin(index / 4 * Math.PI * 2) * 155 }, active: index < 2 })); const boss: BossState = { definitionId: 'ruins.guardian', roomId: bossRoom.id, status: 'locked', entityId: null, phase: 0, nextMechanicAt: 0, runes, shielded: true }; return { objectives, boss, used, spawn, random: createRng(seed) }; }
export function encounterWaves(roomId: string, playerCount: number, cycle = 0) { const bonus = (Math.max(1, playerCount) - 1) * 2; return [4, 6, 8].map((base, wave) => Array.from({ length: base + bonus }, (_, index) => `monster:${roomId}:cycle:${cycle}:wave:${wave}:${index}`)); }
function generateEncounters(rooms: MapRoom[], progress: ReturnType<typeof generateProgress>, seed: number): EncounterState[] { const random = createRng(seed), objectiveRooms = new Set(progress.objectives.map((objective) => objective.roomId)); return rooms.slice(1).filter((room) => room.id !== progress.boss.roomId).map((room, index) => { const waves = encounterWaves(room.id, 1), monsterIds = waves.flat(); return { id: `encounter:${room.id}`, roomId: room.id, kind: objectiveRooms.has(room.id) || index % 4 === 2 || random() < .2 ? 'sealed' : 'roaming', status: 'dormant', monsterIds, waves, currentWave: 0, totalWaves: waves.length, nextWaveAt: null, scaledForPlayers: null, activatedAt: null, clearedAt: null }; }); }
function safeEconomyPosition(room: MapRoom, terrains: TerrainState[], radius: number) { const c = center(room), offsets = [[0, 0], [-.22, 0], [.22, 0], [0, -.22], [0, .22], [-.22, -.22], [.22, .22], [-.22, .22], [.22, -.22]]; for (const [ox, oy] of offsets) { const point = { x: c.x + room.width * ox!, y: c.y + room.height * oy! }; if (point.x - radius < room.position.x || point.x + radius > room.position.x + room.width || point.y - radius < room.position.y || point.y + radius > room.position.y + room.height) continue; if (!terrains.some((terrain) => terrain.active && terrain.blocksMovement && terrainBlocks(terrain, point, radius + 12))) return point; } return c; }
function generateMerchant(rooms: MapRoom[], progress: ReturnType<typeof generateProgress>, terrains: TerrainState[], seed: number, stageIndex: number): MerchantState { const room = rooms.find((candidate) => candidate.id !== 'room-0' && !progress.used.has(candidate.id)) ?? rooms[1]!; progress.used.add(room.id); const stock: MerchantState['stock'] = [0, 1, 2, 3].map((index) => { const item = generateEquipment(deriveSeed(seed, 'equipment'), stageIndex * 10 + index); return { item, price: Math.round(item.value * (1 + stageIndex * .12)) }; }); if (createRng(deriveSeed(seed, 'catalyst'))() < .3) stock.push({ item: createCatalyst(seed, `merchant:${stageIndex}`), price: 80 }); return { id: `merchant:${stageIndex}`, position: safeEconomyPosition(room, terrains, 56), radius: 56, stock }; }

export function roomAt(stage: StageBlueprint, point: Vec2, inset = 0) { return stage.world.rooms.find((room) => contains(room.position, room.width, room.height, point, inset)); }
export function isWalkable(stage: StageBlueprint, point: Vec2, radius = 24) { const floor = stage.world.rooms.some((room) => contains(room.position, room.width, room.height, point, radius)) || stage.world.corridors.some((corridor) => contains(corridor.position, corridor.width, corridor.height, point, radius)); if (!floor) return false; return !stage.terrains.some((terrain) => terrain.active && terrain.blocksMovement && terrainBlocks(terrain, point, radius)); }
export function moveWithinStage(stage: StageBlueprint, from: Vec2, to: Vec2, radius = 24) { const currentRoom = roomAt(stage, from), sealed = currentRoom && (stage.encounters.some((encounter) => encounter.roomId === currentRoom.id && encounter.kind === 'sealed' && encounter.status === 'active') || stage.boss.roomId === currentRoom.id && stage.boss.status === 'active'); if (sealed && roomAt(stage, to)?.id !== currentRoom.id) return { ...from }; if (isWalkable(stage, to, radius)) return to; const x = { x: to.x, y: from.y }; if (isWalkable(stage, x, radius)) return x; const y = { x: from.x, y: to.y }; return isWalkable(stage, y, radius) ? y : { ...from }; }
export function onlineLivingPlayers(players: Record<string, PlayerState>) { return Object.values(players).filter((player) => player.connected && player.alive); }
export function allPlayersInRoom(players: Record<string, PlayerState>, stage: StageBlueprint, roomId: string) { const party = onlineLivingPlayers(players); return party.length > 0 && party.every((player) => roomAt(stage, player.position)?.id === roomId); }
export function completedObjectives(stage: StageBlueprint) { return stage.objectives.filter((objective) => objective.status === 'completed').length; }
export function stageDefinition(index: number) { return STAGES[index] ?? STAGES[STAGES.length - 1]!; }
export function monsterDefinition(id: string) { return MONSTERS[id] ?? MONSTERS['ruins.chaser']!; }
export function bossDefinition(id: string) { return BOSSES[id] ?? BOSSES['ruins.guardian']!; }
export function monsterEntity(id: string, definitionId: string, roomId: string, position: Vec2, difficulty: number, now: number, elite = false, boss = false): EntityState { const definition = monsterDefinition(definitionId), health = Math.round(definition.health * difficulty * (elite ? 1.45 : 1)); return { id, kind: 'monster', monsterDefinitionId: definition.id, roomId, elite, boss, position, radius: definition.radius, createdAt: now, expiresAt: null, detached: true, health: { current: health, max: health }, damageable: { canReceiveDamage: true, canReceiveHeal: true }, faction: { id: 'monsters', team: 'monster' }, statuses: {}, buildup: {}, buffs: [], shields: [], resistances: { ...definition.resistances }, cast: { phase: 'idle', castId: null, spell: null, startedAt: 0, phaseEndsAt: null, aim: { x: 1, y: 0 }, target: { ...position } }, ai: { targetId: null, currentAbilityId: null, nextThinkAt: now + 500, movement: 'hold', phase: 1 } }; }

function roomDistances(rooms: MapRoom[], start: string) { const result = new Map<string, number>([[start, 0]]), queue = [start]; while (queue.length) { const id = queue.shift()!, room = rooms.find((candidate) => candidate.id === id); if (!room) continue; for (const next of room.connections) if (!result.has(next)) { result.set(next, result.get(room.id)! + 1); queue.push(next); } } return result; }
function center(room: MapRoom): Vec2 { return { x: room.position.x + room.width / 2, y: room.position.y + room.height / 2 }; }
function contains(position: Vec2, width: number, height: number, point: Vec2, inset: number) { return point.x >= position.x + inset && point.x <= position.x + width - inset && point.y >= position.y + inset && point.y <= position.y + height - inset; }
function terrainBlocks(terrain: TerrainState, point: Vec2, radius: number) { if (terrain.width && terrain.height) return Math.abs(point.x - terrain.position.x) <= terrain.width / 2 + radius && Math.abs(point.y - terrain.position.y) <= terrain.height / 2 + radius; return Math.hypot(point.x - terrain.position.x, point.y - terrain.position.y) <= terrain.radius + radius; }
function edgeKey(a: string, b: string) { return a < b ? `${a}|${b}` : `${b}|${a}`; }
function shuffle<T>(values: T[], random: () => number) { for (let i = values.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [values[i], values[j]] = [values[j]!, values[i]!]; } return values; }
function fingerprint(value: unknown) { return hashText(JSON.stringify(value)).toString(16).padStart(8, '0'); }
