import { useEffect, useMemo, useState } from 'react';
import { DrawingBoard } from './DrawingBoard';
import { renderableClassicStrokes } from './canvas-view';
import { categoryDialogRole, drawingPermissions } from './ui-logic';
import { useParti } from './useParti';
import type { Message, RevealChain, RoomState } from './types';

function Countdown({ end }: { end: number | null }) { const [now, setNow] = useState(Date.now()); useEffect(() => { const id = setInterval(() => setNow(Date.now()), 250); return () => clearInterval(id); }, []); if (!end) return <span className="timer">--</span>; const seconds = Math.max(0, Math.ceil((end - now) / 1000)); return <span className={`timer ${seconds <= 10 ? 'urgent' : ''}`}>{seconds}s</span>; }
function CategoryPicker({ categories, onPick, pending }: { categories: RoomState['categories']; onPick: (id: string) => void; pending: boolean }) { return <div className="category-grid">{categories.map((category) => <button key={category.id} disabled={pending} onClick={() => onPick(category.id)}><b>{category.icon} {category.name}</b><small>{category.description}</small></button>)}</div>; }
function Modal({ children, wide = false }: { children: React.ReactNode; wide?: boolean }) { return <div className="modal-backdrop"><section className={`modal ${wide ? 'wide' : ''}`} role="dialog" aria-modal="true">{children}</section></div>; }

function PlayerStrip({ state, playerId }: { state: RoomState; playerId: string }) { const players = Object.values(state.players); return <section className="player-strip"><header><b>玩家</b><span>{players.filter((p) => p.connected).length}/8</span></header><ul>{players.map((player) => <li key={player.id} className={!player.connected ? 'offline' : ''} title={player.name}><span>{player.name.slice(0, 1)}</span><small>{player.id === state.drawerId ? '画' : player.ready ? '✓' : state.guessedIds.includes(player.id) ? '中' : !player.connected ? '离' : state.scores[player.id] ?? 0}</small>{player.id === playerId && <i>你</i>}</li>)}</ul></section>; }
function ChatPanel({ messages, enabled, placeholder }: { messages: Message[]; enabled: boolean; placeholder: string }) { const [text, setText] = useState(''); return <section className="chat-panel"><div className="chat-head"><b>聊天与猜词</b><small>最近 {Math.min(messages.length, 60)} 条</small></div><div className="messages">{messages.slice(-60).map((message, index) => <p key={message.id ?? index} className={`message-${message.type}`}><b>{message.name ? `${message.name}：` : ''}</b>{message.text}</p>)}</div><form className="guess-box" onSubmit={(event) => { event.preventDefault(); if (!enabled || !text.trim()) return; void parti.action('submitGuess', { text }); setText(''); }}><input value={text} disabled={!enabled} maxLength={40} placeholder={placeholder} onChange={(event) => setText(event.target.value)} /><button className="primary" disabled={!enabled}>发送</button></form></section>; }
function Reveal({ chain }: { chain: RevealChain }) { return <div className="reveal"><header><p className="eyebrow">接力画册</p><h2>原题：{chain.word}</h2></header><div className="reveal-track">{chain.items.map((item, index) => <article key={`${item.playerId}-${index}`}>{item.kind === 'drawing' ? <DrawingBoard strokes={item.strokes} sessionKey={`reveal:${chain.id}:${index}`} canvasRevision={0} editable={false} /> : <blockquote>“{item.text}”</blockquote>}<small>玩家 {item.playerId.slice(0, 6)}</small></article>)}</div></div>; }

function PhaseModal({ state, playerId }: { state: RoomState; playerId: string }) {
  const [pending, setPending] = useState(false); const isHost = state.hostId === playerId; const me = state.players[playerId];
  const dialogRole = categoryDialogRole(state.phase, state.drawerId, playerId, state.relayParticipants, state.relaySubmittedIds);
  useEffect(() => setPending(false), [state.phase, state.relaySubmittedIds.length]);
  const pick = (categoryId: string) => { setPending(true); void parti.action('chooseCategory', { categoryId }); };
  if (state.phase === 'choosing') return <Modal><p className="eyebrow">经典模式 · 第 {state.roundNumber} 轮</p>{dialogRole === 'classic-picker' ? <><h2>选择题目分类</h2><p>选定后只有你会看到秘密题目。</p><CategoryPicker categories={state.categories} onPick={pick} pending={pending} /></> : <div className="waiting"><span className="waiting-orbit" /><h2>等待画手选词</h2><p>{state.players[state.drawerId ?? '']?.name ?? '画手'} 正在选择题目分类。</p></div>}</Modal>;
  if (state.phase === 'relay-choosing') return <Modal>{dialogRole === 'relay-waiting' ? <div className="waiting"><span className="waiting-orbit" /><h2>题目已经选好</h2><p>等待其他玩家完成选择。</p></div> : <><p className="eyebrow">接力模式</p><h2>选择你的秘密题目分类</h2><p>每位玩家都会获得不同的私密题目。</p><CategoryPicker categories={state.categories} onPick={pick} pending={pending} /></>}</Modal>;
  if (state.phase === 'round-result') return <Modal><p className="eyebrow">本轮结束</p><h2>答案：{state.roundResult?.answer ?? '—'}</h2><div className="result-points">{Object.entries(state.roundPoints).map(([id, score]) => <span key={id}>{state.players[id]?.name ?? id} +{score}</span>)}</div><p>5 秒后自动进入下一轮。</p></Modal>;
  if (state.phase === 'relay-reveal' && state.relayReveal) return <Modal wide><Reveal chain={state.relayReveal.current} />{isHost ? <button className="primary modal-action" onClick={() => void parti.action('advanceReveal')}>继续揭晓</button> : <p>等待房主继续揭晓</p>}</Modal>;
  if (state.phase === 'lobby' || state.phase === 'game-over') return <Modal wide><div className="setup-head"><div><p className="eyebrow">{state.phase === 'lobby' ? 'PARTI DRAW ROOM' : '再来一局'}</p><h2>{state.phase === 'game-over' ? '最终积分' : '准备开始'}</h2></div>{isHost && <div className="mode-tabs"><button className={state.mode === 'classic' ? 'active' : ''} onClick={() => void parti.action('selectMode', { mode: 'classic' })}>经典模式</button><button className={state.mode === 'relay' ? 'active' : ''} onClick={() => void parti.action('selectMode', { mode: 'relay' })}>接力模式</button></div>}</div><div className="ready-list">{Object.values(state.players).map((player) => <span key={player.id}>{player.name}<b>{player.ready ? '已准备' : '未准备'}</b></span>)}</div><button className="ready primary" onClick={() => void parti.action('toggleReady')}>{me?.ready ? '取消准备' : '准备开始'}</button><p className="modal-note">至少两人，所有在线玩家准备后自动开始。</p></Modal>;
  if (state.phase === 'relay-gallery' && state.relayReveal?.gallery) return <Modal wide><div className="gallery-list">{state.relayReveal.gallery.map((chain) => <Reveal key={chain.id} chain={chain} />)}</div><button className="ready primary" onClick={() => void parti.action('toggleReady')}>{me?.ready ? '取消准备' : '准备下一局'}</button></Modal>;
  return null;
}

export function App() {
  const { state, playerId, word, relayTask, notice } = useParti();
  const players = useMemo(() => Object.values(state?.players ?? {}), [state?.players]);
  if (!state || !playerId) return <main className="loading">正在加入画室…</main>;
  const { canDraw } = drawingPermissions(state.phase, state.drawerId, playerId);
  const relayDrawing = (state.phase === 'relay-initial-drawing' || state.phase === 'relay-redrawing') && relayTask?.kind === 'draw' && !state.relaySubmittedIds.includes(playerId);
  const relayGuessing = (state.phase === 'relay-guessing' || state.phase === 'relay-final-guess') && (relayTask?.kind === 'guess' || relayTask?.kind === 'final-guess') && !state.relaySubmittedIds.includes(playerId);
  const boardStrokes = relayTask && 'strokes' in relayTask ? relayTask.strokes : renderableClassicStrokes(state.strokes, state.activeStroke, canDraw);
  const deadline = state.phase === 'choosing' ? state.pickEndsAt : state.phase.startsWith('relay-') ? state.relayDeadline : state.roundEndsAt;
  const sessionKey = `${state.canvasRevision}:${state.drawerId ?? 'relay'}:${relayTask?.taskId ?? 'classic'}`;
  const chatEnabled = (state.phase === 'drawing' && !canDraw) || relayGuessing;
  const chatPlaceholder = relayTask?.kind === 'final-guess' ? '写下最终答案' : relayGuessing ? '这幅画是什么？' : state.phase === 'drawing' && !canDraw ? '输入答案或聊天' : '当前阶段不能发送';
  return <main className="app-shell"><header className="topbar"><div className="brand"><span>✎</span><div><small>PARTI SKETCH ROOM</small><h1>你画我猜</h1></div></div><div className="phase-chip">{phaseLabel(state.phase)}</div><Countdown end={deadline} /></header><section className="game-grid"><div className="workspace"><div className="board-overlay"><div>{canDraw && word && <span className="secret">题目：{word}</span>}{relayDrawing && <span className="secret">请画：{relayTask.prompt}</span>}{relayTask?.kind === 'final-guess' && <span className="final-tag">最后一棒 · 猜完直接揭晓</span>}</div><div className="hints">{state.revealedHints.map((hint) => <span key={hint}>{hint}</span>)}</div></div><DrawingBoard strokes={boardStrokes} sessionKey={sessionKey} canvasRevision={state.canvasRevision} taskId={relayTask?.kind === 'draw' ? relayTask.taskId : undefined} editable={canDraw || relayDrawing} canSubmit={relayDrawing} onSubmit={() => void parti.action('relaySubmitDrawing')} /></div><aside className="side-column"><PlayerStrip state={state} playerId={playerId} /><ChatPanel messages={state.messages} enabled={chatEnabled} placeholder={chatPlaceholder} /></aside></section><PhaseModal state={state} playerId={playerId} />{notice && <div className="toast">{notice}</div>}<span className="sr-only">{players.length} 名玩家</span></main>;
}

function phaseLabel(phase: string) { return ({ lobby: '等待准备', choosing: '选择题目', drawing: '正在绘画', 'round-result': '本轮结算', 'game-over': '游戏结算', 'relay-choosing': '接力选题', 'relay-initial-drawing': '初始作画', 'relay-guessing': '看画猜词', 'relay-redrawing': '按词重画', 'relay-final-guess': '最终猜测', 'relay-reveal': '逐步揭晓', 'relay-gallery': '画册总览' } as Record<string, string>)[phase] ?? phase; }
