export const CATEGORY_DEFS = [
  { id: 'daily', name: '日常生活', icon: '☀️', description: '熟悉的物品与场景' },
  { id: 'animals', name: '动物世界', icon: '🐾', description: '天上、地上和水里' },
  { id: 'imagination', name: '脑洞趣味', icon: '✨', description: '动作、状态与奇妙组合' },
  { id: 'food', name: '美食天地', icon: '🍜', description: '主食、甜点与饮品' },
  { id: 'sports', name: '运动时刻', icon: '⚽', description: '球类、户外与竞技' },
  { id: 'places', name: '地点场景', icon: '🏙️', description: '建筑、交通与旅行' },
  { id: 'jobs', name: '职业人物', icon: '🧑‍🚀', description: '熟悉的职业与角色' },
  { id: 'culture', name: '文化节庆', icon: '🏮', description: '成语、节日与传统' },
];

// 添加分类时同步增加 CATEGORY_DEFS；添加词语只需继续追加相同结构的条目。
export const WORD_BANK = {
  daily: [
    { id: 'daily-umbrella', word: '雨伞', hints: ['下雨天常常用到', '它会在头顶撑开'] },
    { id: 'daily-toothbrush', word: '牙刷', hints: ['每天早晚都可能用到', '它和牙膏是搭档'] },
    { id: 'daily-fridge', word: '冰箱', hints: ['厨房里的大型电器', '能让食物保持低温'] },
    { id: 'daily-slippers', word: '拖鞋', hints: ['回到家常常换上它', '穿脱很方便的鞋'] },
    { id: 'daily-alarm', word: '闹钟', hints: ['它和时间有关', '早晨会把人叫醒'] },
    { id: 'daily-key', word: '钥匙', hints: ['出门时别忘了带', '能打开一把锁'] },
    { id: 'daily-backpack', word: '书包', hints: ['学生经常携带', '里面可以装课本'] },
    { id: 'daily-mirror', word: '镜子', hints: ['房间里常见的物品', '能看到自己的样子'] },
    { id: 'daily-kettle', word: '烧水壶', hints: ['喝水前可能用到', '可以把冷水加热'] },
    { id: 'daily-headphones', word: '耳机', hints: ['常和电子设备一起使用', '戴在耳朵上听声音'] },
    { id: 'daily-traffic-light', word: '红绿灯', hints: ['马路上很常见', '用颜色指挥通行'] },
    { id: 'daily-elevator', word: '电梯', hints: ['高楼里经常见到', '载着人上下楼'] },
    { id: 'daily-tissue', word: '纸巾', hints: ['轻薄的一次性用品', '可以用来擦拭'] },
    { id: 'daily-sofa', word: '沙发', hints: ['客厅里的家具', '可以坐下或躺下'] },
    { id: 'daily-lamp', word: '台灯', hints: ['常摆在桌面上', '夜里提供一小片光'] },
    { id: 'daily-suitcase', word: '行李箱', hints: ['旅行时常常出现', '有轮子并能装衣物'] },
    { id: 'daily-washing-machine', word: '洗衣机', hints: ['家中的电器', '衣服在里面旋转清洗'] },
    { id: 'daily-microwave', word: '微波炉', hints: ['厨房里的电器', '能很快加热食物'] },
    { id: 'daily-bicycle', word: '自行车', hints: ['常见的交通工具', '有两个轮子并靠脚踩'] },
    { id: 'daily-fire-extinguisher', word: '灭火器', hints: ['公共场所的安全设备', '着火时用它喷射灭火'] },
    { id: 'daily-vacuum', word: '吸尘器', hints: ['打扫房间时使用', '长管吸走地面的灰尘'] },
    { id: 'daily-hairdryer', word: '吹风机', hints: ['洗头后常用', '从前端吹出热风'] },
    { id: 'daily-rice-cooker', word: '电饭煲', hints: ['厨房里的小家电', '盖上盖子把米煮成熟饭'] },
    { id: 'daily-fan', word: '电风扇', hints: ['天气热时使用', '几片扇叶旋转送风'] },
    { id: 'daily-sweeping', word: '扫地', hints: ['一种家务劳动', '拿着扫把清理地面'] },
    { id: 'daily-laundry', word: '晾衣服', hints: ['洗衣之后进行', '把湿衣服挂到长杆上'] },
    { id: 'daily-charging', word: '手机充电', hints: ['电子设备没电时需要', '用一根线连接手机和插座'] },
    { id: 'daily-shopping-cart', word: '购物车', hints: ['商店里常见', '有篮筐和轮子供顾客推动'] },
    { id: 'daily-doorbell', word: '按门铃', hints: ['到别人家门口时可能做', '用手指按下门边按钮'] },
    { id: 'daily-taking-photo', word: '拍照', hints: ['记录眼前画面', '举起相机或手机按下快门'] },
  ],
  animals: [
    { id: 'animal-elephant', word: '大象', hints: ['生活在陆地上的大型动物', '有很长的鼻子'] },
    { id: 'animal-giraffe', word: '长颈鹿', hints: ['来自草原的动物', '脖子特别长'] },
    { id: 'animal-penguin', word: '企鹅', hints: ['生活在寒冷地区', '穿着黑白色外衣走路摇摆'] },
    { id: 'animal-octopus', word: '章鱼', hints: ['生活在海里', '有八条腕足'] },
    { id: 'animal-kangaroo', word: '袋鼠', hints: ['来自澳大利亚', '肚子前面有育儿袋'] },
    { id: 'animal-hedgehog', word: '刺猬', hints: ['体型不大的陆地动物', '遇到危险会蜷成刺球'] },
    { id: 'animal-flamingo', word: '火烈鸟', hints: ['生活在湿地的鸟类', '羽毛粉红且常单脚站立'] },
    { id: 'animal-camel', word: '骆驼', hints: ['适应干旱环境', '背上有驼峰'] },
    { id: 'animal-peacock', word: '孔雀', hints: ['色彩鲜艳的鸟', '雄鸟会展开扇形尾羽'] },
    { id: 'animal-snail', word: '蜗牛', hints: ['移动得很慢', '背着螺旋形的壳'] },
    { id: 'animal-bat', word: '蝙蝠', hints: ['常在夜间活动', '会飞但不是鸟'] },
    { id: 'animal-dolphin', word: '海豚', hints: ['聪明的海洋动物', '会跃出水面并发出哨声'] },
    { id: 'animal-crocodile', word: '鳄鱼', hints: ['常潜伏在水边', '有长嘴和锋利牙齿'] },
    { id: 'animal-panda', word: '熊猫', hints: ['爱吃植物的大型动物', '黑白相间并爱吃竹子'] },
    { id: 'animal-squirrel', word: '松鼠', hints: ['常在树上活动', '有蓬松大尾巴并爱存坚果'] },
    { id: 'animal-owl', word: '猫头鹰', hints: ['夜间活动的鸟', '眼睛很大且头能转很远'] },
    { id: 'animal-turtle', word: '乌龟', hints: ['行动通常比较缓慢', '身体藏在坚硬的壳里'] },
    { id: 'animal-zebra', word: '斑马', hints: ['生活在非洲草原', '全身有黑白条纹'] },
    { id: 'animal-crab', word: '螃蟹', hints: ['常生活在水边', '横着走并有一对钳子'] },
    { id: 'animal-chameleon', word: '变色龙', hints: ['常待在树枝上', '身体颜色会随环境变化'] },
    { id: 'animal-lion', word: '狮子', hints: ['生活在草原的大型动物', '雄性脖子周围有浓密鬃毛'] },
    { id: 'animal-rabbit', word: '兔子', hints: ['常见的小动物', '有长耳朵并爱吃胡萝卜'] },
    { id: 'animal-frog', word: '青蛙', hints: ['常出现在池塘边', '后腿有力会跳也会呱呱叫'] },
    { id: 'animal-seahorse', word: '海马', hints: ['生活在海里', '头像小马并竖着游泳'] },
    { id: 'animal-jellyfish', word: '水母', hints: ['透明的海洋生物', '伞状身体下垂着许多触手'] },
    { id: 'animal-polar-bear', word: '北极熊', hints: ['生活在冰雪地区', '全身白色的大型熊类'] },
    { id: 'animal-woodpecker', word: '啄木鸟', hints: ['一种会飞的动物', '用尖嘴反复敲击树干'] },
    { id: 'animal-butterfly', word: '蝴蝶', hints: ['常在花丛出现', '有两对色彩漂亮的翅膀'] },
    { id: 'animal-ant', word: '蚂蚁搬家', hints: ['许多小动物共同行动', '排成长队搬运食物'] },
    { id: 'animal-cat-fishing', word: '小猫钓鱼', hints: ['动物进行人类活动', '猫拿着鱼竿坐在水边'] },
  ],
  imagination: [
    { id: 'idea-daydream', word: '白日梦', hints: ['一种走神的状态', '醒着的时候展开幻想'] },
    { id: 'idea-time-travel', word: '穿越时空', hints: ['科幻故事中常见', '从现在去往过去或未来'] },
    { id: 'idea-invisible', word: '隐身', hints: ['一种超能力', '让别人无法看见自己'] },
    { id: 'idea-moon-fishing', word: '海底捞月', hints: ['和水中的影像有关', '想从水底捞起月亮'] },
    { id: 'idea-head-clouds', word: '腾云驾雾', hints: ['神话里的移动方式', '乘着云雾在空中飞行'] },
    { id: 'idea-cold-sweat', word: '冒冷汗', hints: ['紧张时可能发生', '额头出现汗珠'] },
    { id: 'idea-star-eyes', word: '眼冒金星', hints: ['受到撞击后可能出现', '眼前仿佛有星星旋转'] },
    { id: 'idea-cat-computer', word: '猫咪敲键盘', hints: ['动物和电子设备的组合', '爪子在按一排按键'] },
    { id: 'idea-flying-pig', word: '会飞的猪', hints: ['一种不寻常的动物', '它长出了翅膀'] },
    { id: 'idea-rain-candy', word: '糖果雨', hints: ['天气和零食的组合', '从天空落下甜食'] },
    { id: 'idea-sleepwalking', word: '梦游', hints: ['发生在睡眠期间', '闭着眼睛下床活动'] },
    { id: 'idea-rocket-schoolbag', word: '火箭书包', hints: ['学习用品和航天器的组合', '背在身后喷火升空'] },
    { id: 'idea-frozen', word: '冻成冰块', hints: ['温度非常低的结果', '整个人被透明方块包住'] },
    { id: 'idea-face-change', word: '瞬间变脸', hints: ['情绪或表演发生变化', '一眨眼换了另一张脸'] },
    { id: 'idea-mountain-food', word: '堆积如山', hints: ['形容数量特别多', '物品堆得像一座山'] },
    { id: 'idea-lightbulb', word: '灵光一闪', hints: ['想到办法时的感觉', '脑袋旁突然亮起灯泡'] },
    { id: 'idea-chicken-dance', word: '闻鸡起舞', hints: ['和清晨及练习有关', '听见鸡叫就起床舞剑'] },
    { id: 'idea-fire-eyes', word: '火眼金睛', hints: ['神话角色的特殊本领', '眼睛发光并能识破伪装'] },
    { id: 'idea-laugh-floor', word: '笑到打滚', hints: ['非常开心的表现', '躺在地上一边笑一边翻滚'] },
    { id: 'idea-brainstorm', word: '脑洞大开', hints: ['形容想法很有创意', '脑袋打开并冒出奇妙事物'] },
    { id: 'idea-walking-on-air', word: '飘飘然', hints: ['一种轻盈得意的状态', '整个人像气球一样离开地面'] },
    { id: 'idea-head-fire', word: '怒火冲天', hints: ['形容非常生气', '头顶冒出直冲天空的火焰'] },
    { id: 'idea-rainbow-bridge', word: '彩虹桥', hints: ['自然景象和建筑的组合', '七彩弧线连接天空两端'] },
    { id: 'idea-fish-bicycle', word: '骑车的鱼', hints: ['奇妙的动物组合', '鱼坐在自行车上踩踏板'] },
    { id: 'idea-cloud-bed', word: '云朵床', hints: ['柔软的幻想物品', '人在天空的白云上睡觉'] },
    { id: 'idea-pocket-moon', word: '口袋月亮', hints: ['不可能的收藏', '从衣服口袋掏出发光月牙'] },
    { id: 'idea-tree-house', word: '树上城堡', hints: ['建筑与植物的组合', '高大树冠上建着塔楼'] },
    { id: 'idea-frozen-time', word: '时间静止', hints: ['科幻能力', '钟表和周围动作全部停住'] },
    { id: 'idea-shadow-run', word: '影子逃跑', hints: ['不寻常的现象', '地上的黑影离开主人奔跑'] },
    { id: 'idea-mouse-giant', word: '巨型老鼠', hints: ['尺寸颠倒的场景', '老鼠比旁边的房子还大'] },
  ],
  food: [
    { id: 'food-hotpot', word: '火锅', hints: ['大家常围坐着吃', '食材放进滚烫汤底'] },
    { id: 'food-dumpling', word: '饺子', hints: ['常见的面食', '面皮包着馅并捏出褶边'] },
    { id: 'food-baozi', word: '包子', hints: ['蒸笼里常见', '圆鼓鼓的面皮里面有馅'] },
    { id: 'food-noodles', word: '拉面', hints: ['一种条状主食', '师傅会把面团反复拉长'] },
    { id: 'food-rice-roll', word: '寿司', hints: ['常见的冷食', '米饭和配料卷在一起'] },
    { id: 'food-pizza', word: '披萨', hints: ['通常切成三角形分享', '圆饼上铺着芝士和配料'] },
    { id: 'food-hamburger', word: '汉堡', hints: ['常用双手拿着吃', '两片圆面包夹着肉和蔬菜'] },
    { id: 'food-cake', word: '生日蛋糕', hints: ['庆祝时常出现', '上面通常插着蜡烛'] },
    { id: 'food-icecream', word: '冰淇淋', hints: ['天气热时很受欢迎', '冰凉甜品常装在脆筒上'] },
    { id: 'food-popcorn', word: '爆米花', hints: ['看电影时常吃', '玉米粒加热后膨胀开花'] },
    { id: 'food-milk-tea', word: '珍珠奶茶', hints: ['一种甜饮料', '杯底有许多黑色小圆球'] },
    { id: 'food-coffee', word: '咖啡', hints: ['常用杯子盛装', '深色饮品带有烘焙香气'] },
    { id: 'food-watermelon', word: '西瓜', hints: ['夏天常见的水果', '绿色外皮里有红色果肉'] },
    { id: 'food-pineapple', word: '菠萝', hints: ['一种热带水果', '外皮粗糙且顶部有叶冠'] },
    { id: 'food-strawberry', word: '草莓', hints: ['体型不大的水果', '红色表面布满小籽'] },
    { id: 'food-corn', word: '玉米', hints: ['长在高高的秆上', '剥开叶子是一排排黄色颗粒'] },
    { id: 'food-fried-egg', word: '煎鸡蛋', hints: ['早餐里常见', '白色圆面中间有黄色蛋黄'] },
    { id: 'food-kebab', word: '烤串', hints: ['夜市里常见', '食材穿在细签上加热'] },
    { id: 'food-lollipop', word: '棒棒糖', hints: ['小朋友熟悉的甜食', '糖块下面连着一根小棍'] },
    { id: 'food-french-fries', word: '薯条', hints: ['常装在纸盒里', '一根根金黄色的土豆条'] },
    { id: 'food-hot-dog', word: '热狗', hints: ['常见的街头食品', '长面包中夹着一根香肠'] },
    { id: 'food-cupcake', word: '纸杯蛋糕', hints: ['小巧的甜点', '蛋糕装在纸托里并顶着奶油'] },
    { id: 'food-cookie', word: '曲奇饼干', hints: ['酥脆的小零食', '圆形饼上常有巧克力豆'] },
    { id: 'food-bubble-tea', word: '水果茶', hints: ['装在透明杯中的饮料', '水里能看到水果切片'] },
    { id: 'food-banana', word: '香蕉', hints: ['常见水果', '黄色弯弯的外形像月牙'] },
    { id: 'food-cherry', word: '樱桃', hints: ['小巧的红色水果', '两个圆果常由细梗连在一起'] },
    { id: 'food-mushroom', word: '蘑菇', hints: ['可食用也有野生种类', '顶部像一把圆圆的小伞'] },
    { id: 'food-bento', word: '盒饭', hints: ['方便携带的一餐', '格子餐盒里装着饭和菜'] },
    { id: 'food-steamed-fish', word: '清蒸鱼', hints: ['一道完整鱼形的菜', '盘子里有鱼、葱丝和热气'] },
    { id: 'food-toast', word: '烤面包', hints: ['早餐常见动作', '面包片从机器里弹出来'] },
  ],
  sports: [
    { id: 'sport-football', word: '踢足球', hints: ['在草地球场进行', '用脚把球送进球门'] },
    { id: 'sport-basketball', word: '打篮球', hints: ['一种团队球类运动', '把球投进高处的篮筐'] },
    { id: 'sport-badminton', word: '打羽毛球', hints: ['隔着球网进行', '球拍击打一只带羽毛的球'] },
    { id: 'sport-table-tennis', word: '打乒乓球', hints: ['在桌子两边进行', '用小球拍击打白色小球'] },
    { id: 'sport-swimming', word: '游泳', hints: ['在水中进行', '挥动四肢向前移动'] },
    { id: 'sport-skiing', word: '滑雪', hints: ['冬季户外运动', '踩着两块长板从雪坡滑下'] },
    { id: 'sport-skating', word: '滑冰', hints: ['在光滑冰面上进行', '鞋底装有细长冰刀'] },
    { id: 'sport-boxing', word: '拳击', hints: ['双方在擂台较量', '戴着厚手套挥拳进攻'] },
    { id: 'sport-archery', word: '射箭', hints: ['需要瞄准远处目标', '拉开弓弦让箭飞向靶心'] },
    { id: 'sport-weightlifting', word: '举重', hints: ['力量型比赛项目', '把带圆盘的杠铃举过头顶'] },
    { id: 'sport-high-jump', word: '跳高', hints: ['田径比赛项目', '助跑后越过一根横杆'] },
    { id: 'sport-marathon', word: '马拉松', hints: ['长距离耐力项目', '许多人沿公路长时间奔跑'] },
    { id: 'sport-relay', word: '接力赛', hints: ['多人组队完成', '跑动时把一根短棒交给队友'] },
    { id: 'sport-surfing', word: '冲浪', hints: ['在海面进行', '站在板上追逐海浪'] },
    { id: 'sport-climbing', word: '攀岩', hints: ['需要手脚并用', '沿着陡峭岩壁向上爬'] },
    { id: 'sport-cycling', word: '骑自行车', hints: ['常见的户外活动', '握住车把并用双脚踩踏板'] },
    { id: 'sport-tug-war', word: '拔河', hints: ['两队共同参与', '大家抓住长绳向相反方向拉'] },
    { id: 'sport-gymnastics', word: '体操', hints: ['强调柔韧与平衡', '运动员会翻腾和旋转'] },
    { id: 'sport-fencing', word: '击剑', hints: ['两人穿着护具比赛', '手持细剑互相刺击得分'] },
    { id: 'sport-bowling', word: '保龄球', hints: ['在室内长球道进行', '滚出重球撞倒一排瓶状物'] },
    { id: 'sport-tennis', word: '打网球', hints: ['隔网进行的球类运动', '用球拍击打绿色小球'] },
    { id: 'sport-volleyball', word: '打排球', hints: ['多人团队运动', '双手把球垫过高网'] },
    { id: 'sport-diving', word: '跳水', hints: ['从高处进入水中', '运动员翻转后笔直落入泳池'] },
    { id: 'sport-skateboard', word: '滑滑板', hints: ['街头运动', '站在带四个轮子的短板上'] },
    { id: 'sport-hula-hoop', word: '转呼啦圈', hints: ['休闲健身活动', '让圆环绕着腰部旋转'] },
    { id: 'sport-jump-rope', word: '跳绳', hints: ['一人就能进行', '双手摇绳并连续跳过'] },
    { id: 'sport-golf', word: '打高尔夫', hints: ['在大片草地进行', '挥杆把小球打进远处洞中'] },
    { id: 'sport-rowing', word: '划船', hints: ['在水面进行', '坐在船上用桨推动前进'] },
    { id: 'sport-parachute', word: '跳伞', hints: ['从很高处开始', '背后张开巨大伞面缓慢下降'] },
    { id: 'sport-medal', word: '领奖牌', hints: ['比赛结束后的场景', '站在领奖台让人挂上奖牌'] },
  ],
  places: [
    { id: 'place-airport', word: '机场', hints: ['旅行时可能经过', '飞机在长跑道上起降'] },
    { id: 'place-station', word: '火车站', hints: ['交通枢纽', '乘客在站台等待列车'] },
    { id: 'place-subway', word: '地铁站', hints: ['城市交通场所', '列车多在地下隧道中停靠'] },
    { id: 'place-school', word: '学校', hints: ['许多人在这里成长', '有教室、操场和老师'] },
    { id: 'place-hospital', word: '医院', hints: ['身体不舒服时会去', '医生和护士在这里工作'] },
    { id: 'place-library', word: '图书馆', hints: ['需要保持安静', '一排排书架供人阅读借阅'] },
    { id: 'place-supermarket', word: '超市', hints: ['日常购物场所', '推着购物车从货架挑选商品'] },
    { id: 'place-cinema', word: '电影院', hints: ['休闲娱乐场所', '人们面对大银幕坐成很多排'] },
    { id: 'place-amusement-park', word: '游乐园', hints: ['充满欢笑的场所', '有过山车和旋转木马'] },
    { id: 'place-zoo', word: '动物园', hints: ['适合观察动物', '不同动物住在各自园区'] },
    { id: 'place-aquarium', word: '海洋馆', hints: ['室内参观场所', '隔着巨大玻璃看鱼群游过'] },
    { id: 'place-museum', word: '博物馆', hints: ['收藏和展示物品', '展柜里陈列历史或艺术展品'] },
    { id: 'place-lighthouse', word: '灯塔', hints: ['常建在海岸附近', '高塔顶端发光为船只指路'] },
    { id: 'place-castle', word: '城堡', hints: ['故事里常出现', '高墙、塔楼和大门组成建筑'] },
    { id: 'place-bridge', word: '大桥', hints: ['跨越障碍的建筑', '把河流两岸连接起来'] },
    { id: 'place-tunnel', word: '隧道', hints: ['交通线路的一部分', '车辆从山体或地下穿过'] },
    { id: 'place-campsite', word: '露营地', hints: ['户外过夜的地方', '草地上搭着帐篷和篝火'] },
    { id: 'place-beach', word: '海滩', hints: ['度假场景', '海浪拍打大片沙子'] },
    { id: 'place-farm', word: '农场', hints: ['远离城市的生产场所', '有田地、谷仓和牲畜'] },
    { id: 'place-restaurant', word: '餐厅', hints: ['人们在这里用餐', '桌椅之间有服务员端菜'] },
    { id: 'place-post-office', word: '邮局', hints: ['办理寄送业务', '柜台旁有信封、邮票和包裹'] },
    { id: 'place-bank', word: '银行', hints: ['办理钱款业务', '柜台和取款机都能在这里见到'] },
    { id: 'place-gas-station', word: '加油站', hints: ['车辆途中会停靠', '油枪从机器连接到汽车'] },
    { id: 'place-playground', word: '操场', hints: ['学校里常见', '有跑道、球场和旗杆'] },
    { id: 'place-bus-stop', word: '公交站', hints: ['路边等车的地方', '站牌旁有人排队等候'] },
    { id: 'place-temple', word: '寺庙', hints: ['传统建筑场所', '屋檐翘起并有香炉'] },
    { id: 'place-waterfall', word: '瀑布', hints: ['自然景观', '大片水流从高处落下'] },
    { id: 'place-volcano', word: '火山', hints: ['一种特殊山体', '山顶喷出岩浆和烟雾'] },
    { id: 'place-space-station', word: '空间站', hints: ['位于地球之外', '大型舱体带着太阳能板绕行'] },
    { id: 'place-treehouse', word: '树屋', hints: ['建在特殊位置的小屋', '房子架在粗大树枝之间'] },
  ],
  jobs: [
    { id: 'job-doctor', word: '医生', hints: ['帮助生病的人', '常穿白大褂并使用听诊器'] },
    { id: 'job-firefighter', word: '消防员', hints: ['处理危险现场', '穿防护服拿水枪扑灭火焰'] },
    { id: 'job-police', word: '警察', hints: ['维护公共安全', '穿制服并佩戴警徽'] },
    { id: 'job-teacher', word: '老师', hints: ['在学校工作', '站在讲台前给学生上课'] },
    { id: 'job-chef', word: '厨师', hints: ['在厨房工作', '戴高帽拿锅铲烹饪食物'] },
    { id: 'job-pilot', word: '飞行员', hints: ['在高空工作', '坐在驾驶舱操纵飞机'] },
    { id: 'job-astronaut', word: '宇航员', hints: ['探索地球之外', '穿厚重航天服漂浮在太空'] },
    { id: 'job-farmer', word: '农民', hints: ['在田地里劳作', '使用农具播种和收获庄稼'] },
    { id: 'job-photographer', word: '摄影师', hints: ['记录画面的人', '举着相机寻找合适角度'] },
    { id: 'job-painter', word: '画家', hints: ['从事艺术创作', '拿画笔在画布上涂色'] },
    { id: 'job-singer', word: '歌手', hints: ['用声音表演', '站在舞台上拿着麦克风'] },
    { id: 'job-magician', word: '魔术师', hints: ['带来神奇表演', '从帽子里变出意外的东西'] },
    { id: 'job-barber', word: '理发师', hints: ['改变客人的发型', '手拿剪刀在镜子前工作'] },
    { id: 'job-postman', word: '快递员', hints: ['穿梭在街道社区', '骑车把包裹送到收件人手中'] },
    { id: 'job-builder', word: '建筑工人', hints: ['在工地工作', '戴安全帽使用工具建造房屋'] },
    { id: 'job-scientist', word: '科学家', hints: ['研究未知问题', '常在实验室观察和记录'] },
    { id: 'job-dentist', word: '牙医', hints: ['一种医疗职业', '使用小工具检查人的牙齿'] },
    { id: 'job-diver', word: '潜水员', hints: ['在水下活动', '背氧气瓶戴面镜探索海底'] },
    { id: 'job-sailor', word: '船员', hints: ['长期在水上工作', '站在甲板操控船只'] },
    { id: 'job-conductor', word: '交警', hints: ['在道路上工作', '站在路口用手势指挥车辆'] },
    { id: 'job-nurse', word: '护士', hints: ['在医疗场所工作', '照顾病人并协助医生'] },
    { id: 'job-vet', word: '兽医', hints: ['特殊的医疗职业', '拿听诊器为小动物检查身体'] },
    { id: 'job-baker', word: '面包师', hints: ['在烘焙房工作', '把面团送进烤炉变成面包'] },
    { id: 'job-waiter', word: '服务员', hints: ['在餐厅常见', '端着托盘把菜送到桌边'] },
    { id: 'job-programmer', word: '程序员', hints: ['常使用电子设备工作', '面对多块屏幕敲键盘写代码'] },
    { id: 'job-reporter', word: '记者', hints: ['记录和传播新闻', '拿着话筒在现场采访'] },
    { id: 'job-librarian', word: '图书管理员', hints: ['在安静场所工作', '整理书架并办理借书'] },
    { id: 'job-train-driver', word: '火车司机', hints: ['驾驶大型交通工具', '坐在车头控制列车前进'] },
    { id: 'job-gardener', word: '园丁', hints: ['照料植物的人', '拿水壶和剪刀修整花园'] },
    { id: 'job-courier', word: '外卖员', hints: ['在城市街道穿行', '骑车带着餐箱送食物'] },
  ],
  culture: [
    { id: 'culture-new-year', word: '贴春联', hints: ['新年习俗', '把红色对联贴在大门两边'] },
    { id: 'culture-lantern', word: '猜灯谜', hints: ['节日活动', '看着灯笼下的谜面思考答案'] },
    { id: 'culture-dragon-boat', word: '赛龙舟', hints: ['传统节日活动', '多人划着长船竞速前进'] },
    { id: 'culture-mooncake', word: '吃月饼', hints: ['秋天的节日习俗', '一家人分享圆形点心'] },
    { id: 'culture-dumpling', word: '包饺子', hints: ['家庭聚餐活动', '把馅放进圆面皮并捏紧'] },
    { id: 'culture-lion-dance', word: '舞狮', hints: ['热闹的传统表演', '两人钻进彩色狮子服跳跃'] },
    { id: 'culture-kite', word: '放风筝', hints: ['有风时适合进行', '牵着长线让彩色物体飞上天'] },
    { id: 'culture-paper-cut', word: '剪纸', hints: ['传统手工艺', '红纸折叠后剪出花纹'] },
    { id: 'culture-calligraphy', word: '写毛笔字', hints: ['传统书写方式', '手握毛笔蘸墨在宣纸落笔'] },
    { id: 'culture-opera', word: '唱戏', hints: ['传统舞台表演', '演员穿戏服化浓妆亮相'] },
    { id: 'culture-chess', word: '下象棋', hints: ['两人对弈活动', '棋盘上有将帅车马炮'] },
    { id: 'culture-tea', word: '泡茶', hints: ['和饮品有关', '把热水倒入装有茶叶的壶'] },
    { id: 'culture-cover-ears', word: '掩耳盗铃', hints: ['一个成语故事', '捂住耳朵去偷会响的铃铛'] },
    { id: 'culture-seedling', word: '拔苗助长', hints: ['一个成语故事', '把田里的幼苗向上拔高'] },
    { id: 'culture-boat-sword', word: '刻舟求剑', hints: ['一个成语故事', '在船边做记号寻找落水的剑'] },
    { id: 'culture-rabbit-stump', word: '守株待兔', hints: ['一个成语故事', '农夫守着树桩等待兔子'] },
    { id: 'culture-paint-snake', word: '画蛇添足', hints: ['比喻做了多余的事', '画完蛇又给它添上脚'] },
    { id: 'culture-blind-elephant', word: '盲人摸象', hints: ['和片面认识有关', '几个人摸着大象不同部位'] },
    { id: 'culture-frog-well', word: '井底之蛙', hints: ['形容眼界有限', '青蛙坐在井底仰望小片天空'] },
    { id: 'culture-fox-tiger', word: '狐假虎威', hints: ['和借势吓人有关', '狐狸走在老虎前面吓跑动物'] },
    { id: 'culture-firecracker', word: '放鞭炮', hints: ['节庆时的热闹活动', '红色长串在地面炸出火花'] },
    { id: 'culture-red-envelope', word: '发红包', hints: ['节庆或祝福时进行', '把红色信封递给别人'] },
    { id: 'culture-tangyuan', word: '煮汤圆', hints: ['传统节日食俗', '圆圆的白色食物漂在锅里'] },
    { id: 'culture-tomb-sweep', word: '扫墓', hints: ['纪念先人的传统活动', '在墓碑前献花并清理周围'] },
    { id: 'culture-chang-e', word: '嫦娥奔月', hints: ['神话故事', '女子飞向天空中的圆月'] },
    { id: 'culture-houyi', word: '后羿射日', hints: ['神话故事', '弓箭手瞄准天空多个太阳'] },
    { id: 'culture-jingwei', word: '精卫填海', hints: ['神话传说', '小鸟衔石头投入大海'] },
    { id: 'culture-crow-water', word: '乌鸦喝水', hints: ['熟悉的寓言故事', '鸟向瓶里放石子让水升高'] },
    { id: 'culture-snow-coal', word: '雪中送炭', hints: ['比喻及时给予帮助', '大雪天把一筐木炭送给别人'] },
    { id: 'culture-book-sleep', word: '废寝忘食', hints: ['形容非常专注', '趴在书桌读书忘记吃饭睡觉'] },
  ],
};
