import type { Element,MapManifest,StageProgress } from './contracts';
import {createRng} from './map';

export function createStageProgress(map:MapManifest,index:number):StageProgress{
 const distances=roomDistances(map,'room-0'),ranked=map.rooms.slice(1).sort((a,b)=>(distances.get(b.id)??0)-(distances.get(a.id)??0)||a.id.localeCompare(b.id)),large=ranked.filter(room=>room.gridWidth*room.gridHeight>1),bossRoom=large[0]??ranked[0]!,used=new Set([bossRoom.id]),take=(preferLarge:boolean)=>{const room=(preferLarge?large:ranked).find(candidate=>!used.has(candidate.id))??ranked.find(candidate=>!used.has(candidate.id))!;used.add(room.id);return room;},objectiveRooms=[take(true),take(true),take(false)],kinds=['elite','altar','puzzle'] as const;
 const center={x:bossRoom.x+bossRoom.width/2,y:bossRoom.y+bossRoom.height/2},mechanicKind=index===0?'rune-pillar':index===1?'purifier':'cooling-rune',count=index===1?3:4;
 const random=createRng(map.stageSeed^0x6368616c),elements:Exclude<Element,'shield'>[]=['rock','fire','ice','life','lightning','water'],challenge=random()<.35?{element:elements[Math.floor(random()*elements.length)]!,active:false}:null;
 return{index,biome:map.biome,status:'exploring',startedAt:Date.now(),completedAt:null,requiredSigils:2,objectives:objectiveRooms.map((room,i)=>({id:`objective-${index}-${kinds[i]}`,roomId:room.id,kind:kinds[i]!,status:'dormant',progress:0,target:kinds[i]==='altar'?2:kinds[i]==='puzzle'?3:1,startedAt:null})),boss:{roomId:bossRoom.id,status:'locked',enemyId:null,phase:0,nextMechanicAt:0,arena:{phase:'idle',warningStartsAt:0,activeStartsAt:0,endsAt:0},mechanics:Array.from({length:count},(_,i)=>({id:`boss-mechanic-${index}-${i}`,kind:mechanicKind,x:center.x+Math.cos(i/count*Math.PI*2)*Math.min(220,bossRoom.width*.3),y:center.y+Math.sin(i/count*Math.PI*2)*Math.min(180,bossRoom.height*.3),progress:0,target:1,active:i<(index===1?count:2)})),challenge},portal:null};
}

export function completedSigils(stage:StageProgress){return stage.objectives.filter(o=>o.status==='completed').length;}
export function roomDistances(map:MapManifest,startId:string){const result=new Map<string,number>([[startId,0]]),queue=[startId];while(queue.length){const id=queue.shift()!,room=map.rooms.find(r=>r.id===id);if(!room)continue;for(const next of room.connections)if(!result.has(next)){result.set(next,result.get(id)!+1);queue.push(next);}}return result;}
export function puzzleRunes(map:MapManifest,roomId:string){const room=map.rooms.find(r=>r.id===roomId);if(!room)return[];return[-1,0,1].map((offset,index)=>({index,x:room.x+room.width/2+offset*room.width*.25,y:room.y+room.height/2+(index%2?room.height*.18:-room.height*.18)}));}
export function bossAddCap(stageIndex:number,partySize:number){const players=Math.max(1,Math.min(4,Math.floor(partySize)));return stageIndex===0?Math.max(3,Math.min(5,players+1)):stageIndex===1?Math.max(3,Math.min(6,players+2)):Math.max(4,Math.min(6,players+2));}
export function bossAddSlots(stageIndex:number,partySize:number,currentAdds:number,requested:number){return Math.max(0,Math.min(Math.max(0,Math.floor(requested)),bossAddCap(stageIndex,partySize)-Math.max(0,Math.floor(currentAdds))));}
