import { describe, expect, it } from 'vitest';
import type { EntityState, HitEvent } from '../contracts';
import { applyHit, canTarget } from './combat';
import { initialState, player, trainingMonster } from './state';
import { resolveSpell } from './spells';

function setup(element: 'fire' | 'water' | 'lightning') { const state = initialState(); const owner = state.players.p1 = player('p1', 'one', 0); const target = trainingMonster(0); state.entities[target.id] = target; const spell = resolveSpell([element])!; const source: EntityState = { ...trainingMonster(0), id: 's', kind: 'field', ownerId: owner.id, detached: false, source: { spell, tickMs: 150, nextTickAt: 0 }, faction: owner.faction }; state.entities[source.id] = source; const hit: HitEvent = { hitId: `hit:${element}`, sourceId: source.id, ownerId: owner.id, targetId: target.id, payload: spell.payload, delivery: spell.delivery, detached: false, tags: spell.tags }; return { state, owner, target, hit }; }
describe('unified combat pipeline', () => {
  it('filters allies for attached spells', () => { const { owner } = setup('fire'); const ally = player('p2', 'two', 1); expect(canTarget(owner.id, ally.id, owner, ally, resolveSpell(['fire'])!.targeting)).toBe(false); });
  it('deduplicates hits', () => { const { state, target, hit } = setup('fire'); const hp = target.health.current; applyHit(state, hit, 100); const after = target.health.current; applyHit(state, hit, 100); expect(after).toBeLessThan(hp); expect(target.health.current).toBe(after); });
  it('vaporizes wet targets and consumes wet', () => { const { state, target, hit } = setup('fire'); target.statuses.wet = { type: 'wet', endsAt: 5000, potency: 1, stacks: 1, tags: [] }; const result = applyHit(state, hit, 100); expect(result.events).toContainEqual({ type: 'reaction_triggered', id: 'vaporize', targetId: target.id }); expect(target.statuses.wet).toBeUndefined(); expect(target.health.current).toBeCloseTo(488.8); });
  it('electrocutes and interrupts wet casters', () => { const { state, target, hit } = setup('lightning'); target.statuses.wet = { type: 'wet', endsAt: 5000, potency: 1, stacks: 1, tags: [] }; target.cast.phase = 'chanting'; const result = applyHit(state, hit, 100); expect(result.events).toContainEqual({ type: 'reaction_triggered', id: 'electro-charged', targetId: target.id }); expect(target.cast.phase).toBe('interrupted'); });
  it('absorbs configured damage through shield layers', () => { const { state, target, hit } = setup('fire'); target.shields.push({ id: 'fire', amount: 100, maxAmount: 100, absorbElements: { fire: .8 }, priority: 1, tags: [] }); applyHit(state, hit, 100); expect(target.health.current).toBeCloseTo(498.4); expect(target.shields[0].amount).toBeCloseTo(93.6); });
  it('reports rejected targeting without consuming the source', () => { const { state, owner, hit } = setup('fire'), ally = state.players.p2 = player('p2', 'two', 1); hit.targetId = ally.id; const result = applyHit(state, hit, 100); expect(result).toEqual({ accepted: false, events: [] }); expect(state.seen.hits[hit.hitId]).toBeUndefined(); expect(owner.health.current).toBe(100); });
  it('freezes wet targets with ice and shatters them with rock', () => { const ice = setup('water'); ice.target.statuses.wet = { type: 'wet', endsAt: 5000, potency: 1, stacks: 1, tags: [] }; ice.hit.payload = resolveSpell(['ice']).payload; let result = applyHit(ice.state, ice.hit, 100); expect(result.events).toContainEqual({ type: 'reaction_triggered', id: 'freeze', targetId: ice.target.id }); expect(ice.target.statuses.frozen).toBeDefined(); const rock = resolveSpell(['rock']); const shatter = { ...ice.hit, hitId: 'shatter', payload: rock.payload }; result = applyHit(ice.state, shatter, 200); expect(result.events).toContainEqual({ type: 'reaction_triggered', id: 'shatter', targetId: ice.target.id }); expect(ice.target.statuses.frozen).toBeUndefined(); });
  it('heals allies up to maximum health', () => { const state = initialState(), owner = state.players.p1 = player('p1', 'one', 0), ally = state.players.p2 = player('p2', 'two', 1), spell = resolveSpell(['life']); ally.health.current = 95; const source: EntityState = { ...trainingMonster(0), id: 'life-source', kind: 'field', ownerId: owner.id, faction: owner.faction, source: { spell, tickMs: 140, nextTickAt: 0 } }; state.entities[source.id] = source; const result = applyHit(state, { hitId: 'heal', sourceId: source.id, ownerId: owner.id, targetId: ally.id, payload: spell.payload, delivery: 'beam', detached: false, tags: spell.tags }, 100); expect(result.events).toContainEqual({ type: 'heal_applied', targetId: ally.id, amount: 5 }); expect(ally.health.current).toBe(100); });
});
