import { describe, expect, it } from 'vitest';
import type { EntityState, HitEvent } from '../contracts';
import { applyHit, canTarget } from './combat';
import { initialState, player, testMonster } from './state';
import { resolveSpell } from './spells';

function setup(element: 'fire' | 'water' | 'lightning') { const state = initialState(); const owner = state.players.p1 = player('p1', 'one', 0); const target = testMonster(0); state.entities[target.id] = target; const spell = resolveSpell([element])!; const source: EntityState = { ...testMonster(0), id: 's', kind: 'field', ownerId: owner.id, detached: false, source: { spell, tickMs: 150, nextTickAt: 0 }, faction: owner.faction }; state.entities[source.id] = source; const hit: HitEvent = { hitId: `hit:${element}`, sourceId: source.id, ownerId: owner.id, targetId: target.id, payload: spell.payload, delivery: spell.delivery, detached: false, tags: spell.tags }; return { state, owner, target, hit }; }
function forceSetup(targetId = 'monster:test') { const state = initialState(), owner = state.players.p1 = player('p1', 'one', 0), spell = resolveSpell(['rock', 'shield', 'lightning', 'rock']); const source: EntityState = { ...testMonster(0), id: 'force-source', kind: 'field', position: { x: 400, y: 360 }, radius: 200, ownerId: owner.id, detached: true, faction: owner.faction, source: { spell, tickMs: 350, nextTickAt: 0 } }; state.entities[source.id] = source; const hit: HitEvent = { hitId: `force:${targetId}`, sourceId: source.id, ownerId: owner.id, targetId, payload: { effects: [{ type: 'knockback', force: 100 }] }, delivery: 'summon', detached: true, tags: spell.tags }; return { state, owner, source, hit }; }
describe('unified combat pipeline', () => {
  it('filters allies for attached spells', () => { const { owner } = setup('fire'); const ally = player('p2', 'two', 1); expect(canTarget(owner.id, ally.id, owner, ally, resolveSpell(['fire'])!.targeting)).toBe(false); });
  it('deduplicates hits', () => { const { state, target, hit } = setup('fire'); const hp = target.health.current; applyHit(state, hit, 100); const after = target.health.current; applyHit(state, hit, 100); expect(after).toBeLessThan(hp); expect(target.health.current).toBe(after); });
  it('vaporizes wet targets and consumes wet', () => { const { state, target, hit } = setup('fire'); target.statuses.wet = { type: 'wet', endsAt: 5000, potency: 1, stacks: 1, tags: [] }; const result = applyHit(state, hit, 100); expect(result.events).toContainEqual({ type: 'reaction_triggered', id: 'vaporize', targetId: target.id }); expect(target.statuses.wet).toBeUndefined(); expect(target.health.current).toBeCloseTo(488.8); });
  it('electrocutes and interrupts wet casters', () => { const { state, target, hit } = setup('lightning'); target.statuses.wet = { type: 'wet', endsAt: 5000, potency: 1, stacks: 1, tags: [] }; target.cast.phase = 'chanting'; const result = applyHit(state, hit, 100); expect(result.events).toContainEqual({ type: 'reaction_triggered', id: 'electro-charged', targetId: target.id }); expect(target.cast.phase).toBe('interrupted'); });
  it('absorbs configured damage through shield layers', () => { const { state, target, hit } = setup('fire'); target.shields.push({ id: 'fire', amount: 100, maxAmount: 100, absorbElements: { fire: .8 }, priority: 1, tags: [] }); applyHit(state, hit, 100); expect(target.health.current).toBeCloseTo(498.4); expect(target.shields[0].amount).toBeCloseTo(93.6); });
  it('reports zero damage when a shield fully absorbs an element', () => { const { state, target, hit } = setup('fire'); target.shields.push({ id: 'fire', amount: 100, maxAmount: 100, absorbElements: { fire: 1 }, priority: 1, tags: [] }); const result = applyHit(state, hit, 100); expect(result.events).toContainEqual({ type: 'damage_applied', targetId: target.id, amount: 0, element: 'fire', sourceId: 's', largeImpact: false }); });
  it('marks damage from large-impact spell sources', () => { const { state, target, hit } = setup('fire'); hit.tags.push('large-impact'); const result = applyHit(state, hit, 100); expect(result.events).toContainEqual(expect.objectContaining({ type: 'damage_applied', targetId: target.id, sourceId: 's', largeImpact: true })); });
  it('reports immunity for invincible targets while consuming the hit', () => { const { state, target, hit } = setup('fire'); target.damageable.invincible = true; const result = applyHit(state, hit, 100); expect(result).toMatchObject({ accepted: true, events: [{ type: 'damage_immune', targetId: target.id, reason: 'invincible' }] }); expect(state.seen.hits[hit.hitId]).toBe(true); });
  it('prevents warded elemental buildup', () => { const { state, target, hit } = setup('fire'); target.statuses.fireWard = { type: 'fireWard', endsAt: 5000, potency: 1, stacks: 1, tags: [] }; hit.payload.statusBuildup = { burning: 120 }; applyHit(state, hit, 100); expect(target.statuses.burning).toBeUndefined(); expect(target.buildup.burning).toBe(0); });
  it('reports rejected targeting without consuming the source', () => { const { state, owner, hit } = setup('fire'), ally = state.players.p2 = player('p2', 'two', 1); hit.targetId = ally.id; const result = applyHit(state, hit, 100); expect(result).toEqual({ accepted: false, events: [] }); expect(state.seen.hits[hit.hitId]).toBeUndefined(); expect(owner.health.current).toBe(100); });
  it('freezes wet targets with ice and shatters them with rock', () => { const ice = setup('water'); ice.target.statuses.wet = { type: 'wet', endsAt: 5000, potency: 1, stacks: 1, tags: [] }; ice.hit.payload = resolveSpell(['ice']).payload; let result = applyHit(ice.state, ice.hit, 100); expect(result.events).toContainEqual({ type: 'reaction_triggered', id: 'freeze', targetId: ice.target.id }); expect(ice.target.statuses.frozen).toBeDefined(); const rock = resolveSpell(['rock']); const shatter = { ...ice.hit, hitId: 'shatter', payload: rock.payload }; result = applyHit(ice.state, shatter, 200); expect(result.events).toContainEqual({ type: 'reaction_triggered', id: 'shatter', targetId: ice.target.id }); expect(ice.target.statuses.frozen).toBeUndefined(); });
  it('heals allies up to maximum health', () => { const state = initialState(), owner = state.players.p1 = player('p1', 'one', 0), ally = state.players.p2 = player('p2', 'two', 1), spell = resolveSpell(['life', 'life']); ally.health.current = 95; const source: EntityState = { ...testMonster(0), id: 'life-source', kind: 'field', ownerId: owner.id, faction: owner.faction, source: { spell, tickMs: 140, nextTickAt: 0 } }; state.entities[source.id] = source; const result = applyHit(state, { hitId: 'heal', sourceId: source.id, ownerId: owner.id, targetId: ally.id, payload: spell.payload, delivery: 'beam', detached: false, tags: spell.tags }, 100); expect(result.events).toContainEqual({ type: 'heal_applied', targetId: ally.id, amount: 5 }); expect(ally.health.current).toBe(100); });
  it('pushes movable monsters by adding force velocity', () => { const test = forceSetup(), target = test.state.entities['monster:test'] = testMonster(0); target.position = { x: 500, y: 360 }; applyHit(test.state, test.hit, 100); expect(target.position).toEqual({ x: 500, y: 360 }); expect(target.forceVelocity?.x).toBeCloseTo(17.5); expect(target.forceVelocity?.y).toBeCloseTo(0); });
  it('pulls movable targets toward the hit source with negative force velocity', () => { const test = forceSetup(), target = test.state.entities['monster:test'] = testMonster(0); target.position = { x: 500, y: 360 }; test.hit.hitId = 'force:pull'; test.hit.payload = { effects: [{ type: 'knockback', force: -80 }] }; applyHit(test.state, test.hit, 100); expect(target.position).toEqual({ x: 500, y: 360 }); expect(target.forceVelocity?.x).toBeCloseTo(-14); });
  it('adds force velocity to players without immediately bumping position epochs', () => { const test = forceSetup('p2'), target = test.state.players.p2 = player('p2', 'two', 1); target.position = { x: 500, y: 360 }; const epoch = target.positionEpoch; applyHit(test.state, test.hit, 100); expect(target.position.x).toBe(500); expect(target.positionEpoch).toBe(epoch); expect(target.forceVelocity?.x).toBeCloseTo(17.5); });
  it('does not add force velocity to non-monster entities such as walls', () => { const test = forceSetup('wall'), wall: EntityState = { ...testMonster(0), id: 'wall', kind: 'wall', position: { x: 500, y: 360 }, faction: { id: 'neutral', team: 'neutral' }, obstacle: { blocksMovement: true, blocksProjectile: true, blocksBeam: true, blocksSpray: false, material: 'stone' } }; test.state.entities[wall.id] = wall; applyHit(test.state, test.hit, 100); expect(wall.position).toEqual({ x: 500, y: 360 }); expect(wall.forceVelocity).toBeUndefined(); });
  it('accumulates channelled water force gradually away from the caster', () => { const test = forceSetup(), target = test.state.entities['monster:test'] = testMonster(0); target.position = { x: 500, y: 360 }; test.source.kind = 'projectile'; test.source.source!.tickMs = 140; test.hit.payload = { effects: [{ type: 'knockback', force: 80 }] }; for (let tick = 0; tick < 3; tick++) { test.hit.hitId = `water-beam:${tick}`; applyHit(test.state, test.hit, 100 + tick * 140); } expect(target.position).toEqual({ x: 500, y: 360 }); expect(target.forceVelocity?.x).toBeCloseTo(33.6); expect(target.forceVelocity?.y).toBeCloseTo(0); });
});
