import type { EntityState, GameState, PlayerState, SpellSpec, Vec2 } from '../contracts';
import { combatant } from './state';

function add(state: GameState, entity: EntityState) { state.entities[entity.id] = entity; state.seen.spawns[entity.id] = true; if (entity.kind === 'field' && entity.source?.spell.delivery === 'summon') state.environment.fields.push(entity.id); return entity; }
export function spawnSpellEntity(state: GameState, caster: PlayerState, spell: SpellSpec, now: number): EntityState {
  const castId = caster.cast.castId!, aim = caster.cast.aim, target = caster.cast.target, projectile = spell.delivery === 'projectile', summon = spell.delivery === 'summon', attached = spell.delivery === 'spray' || spell.delivery === 'beam', wall = spell.summon?.archetype === 'rock-wall' || spell.summon?.archetype === 'ice-wall';
  const position: Vec2 = summon ? spell.summon?.positionMode === 'self' ? { ...caster.position } : spell.summon?.positionMode === 'casterFront' ? { x: caster.position.x + aim.x * 80, y: caster.position.y + aim.y * 80 } : target : projectile ? { x: caster.position.x + aim.x * 30, y: caster.position.y + aim.y * 30 } : { ...caster.position };
  const travelMs = projectile && spell.speed ? spell.range / spell.speed * 1000 : spell.lifetimeMs, tickMs = spell.tickMs ?? spell.beam?.tickInterval ?? (spell.delivery === 'spray' ? 150 : summon && !wall ? 350 : 0);
  const entity: EntityState = { id: `${castId}:${spell.delivery}:0`, kind: projectile ? 'projectile' : wall ? 'wall' : 'field', archetype: spell.summon?.archetype, ownerId: caster.id, position, velocity: projectile ? { x: aim.x * (spell.speed ?? 0), y: aim.y * (spell.speed ?? 0) } : undefined, direction: attached ? aim : undefined, radius: spell.radius, createdAt: now, expiresAt: now + Math.min(spell.lifetimeMs, travelMs), detached: spell.detached, source: { spell, tickMs, nextTickAt: now }, ...combatant(wall ? 'neutral' : 'player', caster.faction.id, wall ? spell.summon?.archetype === 'ice-wall' ? 130 : 180 : 1) };
  if (wall) entity.obstacle = { blocksMovement: true, blocksProjectile: true, blocksBeam: true, blocksSpray: false, material: spell.summon?.archetype === 'ice-wall' ? 'ice' : 'stone' };
  return add(state, entity);
}
export function spawnMeteorWarning(state: GameState, caster: PlayerState, spell: SpellSpec, now: number) { const entity: EntityState = { id: `${caster.cast.castId}:warning:0`, kind: 'warning', archetype: 'meteor-warning', ownerId: caster.id, position: { ...caster.cast.target }, radius: spell.radius, createdAt: now, expiresAt: now + (spell.area?.warningMs ?? 700), detached: true, ...combatant('environment', caster.faction.id, 1) }; entity.damageable.canReceiveDamage = false; return add(state, entity); }
export function spawnMeteorImpact(state: GameState, caster: PlayerState, spell: SpellSpec, now: number) { const entity: EntityState = { id: `${caster.cast.castId}:area:0`, kind: 'area', archetype: 'meteor-impact', ownerId: caster.id, position: { ...caster.cast.target }, radius: spell.radius, createdAt: now, expiresAt: now + spell.lifetimeMs, detached: true, source: { spell, tickMs: 0, nextTickAt: now }, ...combatant('environment', caster.faction.id, 1) }; return add(state, entity); }
export function positionAt(entity: EntityState, now: number) { if (!entity.velocity) return entity.position; const elapsed = Math.max(0, now - entity.createdAt) / 1000; return { x: entity.position.x + entity.velocity.x * elapsed, y: entity.position.y + entity.velocity.y * elapsed }; }
