import type { Combatant, EntityState, FactionTeam, GameState, PlayerState, Vec2 } from '../contracts';
import { idleCast } from './casting';

export { idleCast } from './casting';
export function combatant(team: FactionTeam, factionId: string, hp: number): Combatant { return { health: { current: hp, max: hp }, damageable: { canReceiveDamage: true, canReceiveHeal: true }, faction: { id: factionId, team }, statuses: {}, buildup: {}, buffs: [], shields: [], resistances: {}, cast: idleCast() }; }
export function player(id: string, name: string, index: number): PlayerState { return { id, name, connected: true, alive: true, position: { x: 0, y: index * 54 }, aim: { x: 1, y: 0 }, selectedElements: [], positionEpoch: 0, lastPoseSequence: 0, lastCastSequence: 0, gold: 50, inventory: [], equipment: {}, scrollCooldowns: {}, ...combatant('player', 'players', 100) }; }
export function testMonster(now: number): EntityState { return { id: 'monster:test', kind: 'monster', monsterDefinitionId: 'test', position: { x: 680, y: 360 }, radius: 34, createdAt: now, expiresAt: null, detached: true, obstacle: { blocksMovement: true, blocksProjectile: true, blocksBeam: true, blocksSpray: true, material: 'flesh' }, ...combatant('monster', 'monsters', 500) }; }
export function initialState(): GameState { return { schemaVersion: 5, phase: 'lobby', hostId: null, seed: 1, worldTime: 0, startedAt: null, run: { seed: 1, stageIndex: 0, stage: null, exploredRoomIds: [], discoveredSpellIds: ['resurrect'], completedRewardIds: [], portal: null, startedAt: null, completedAt: null }, players: {}, entities: {}, environment: { global: null, fields: [] }, loot: {}, merchant: null, forge: null, forgeUses: {}, seen: { hits: {}, spawns: {} }, message: '等待远征' }; }
export function normalize(value: Vec2): Vec2 { const length = Math.hypot(value.x, value.y); return length > .0001 ? { x: value.x / length, y: value.y / length } : { x: 1, y: 0 }; }
