import type { EntityState, GameState, Vec2 } from '../contracts';
import { isWalkable, moveWithinStage, roomAt } from '../roguelike';

function obstacleHalfSize(entity: EntityState) { return { x: (entity.obstacle?.width ?? entity.radius * 2) / 2, y: (entity.obstacle?.height ?? entity.radius * 2) / 2 }; }
function overlapsObstacle(point: Vec2, radius: number, entity: EntityState) { const half = obstacleHalfSize(entity), dx = Math.max(0, Math.abs(point.x - entity.position.x) - half.x), dy = Math.max(0, Math.abs(point.y - entity.position.y) - half.y); return Math.hypot(dx, dy) < radius; }
function movementObstacles(state: GameState, moverId?: string) { return Object.values(state.entities).filter((entity) => entity.id !== moverId && entity.obstacle?.blocksMovement && entity.expiresAt !== 0); }

export function isWorldPositionWalkable(state: GameState, point: Vec2, radius: number, moverId?: string) { const stage = state.run.stage; return Boolean(stage && isWalkable(stage, point, radius) && !movementObstacles(state, moverId).some((entity) => overlapsObstacle(point, radius, entity))); }

function resolveStep(state: GameState, from: Vec2, to: Vec2, radius: number, moverId?: string) { const stage = state.run.stage; if (!stage) return from; const mapResolved = moveWithinStage(stage, from, to, radius); if (isWorldPositionWalkable(state, mapResolved, radius, moverId)) return mapResolved; const x = moveWithinStage(stage, from, { x: to.x, y: from.y }, radius); if (isWorldPositionWalkable(state, x, radius, moverId)) return x; const y = moveWithinStage(stage, from, { x: from.x, y: to.y }, radius); return isWorldPositionWalkable(state, y, radius, moverId) ? y : from; }

export function resolveWorldMovement(state: GameState, from: Vec2, to: Vec2, radius: number, moverId?: string) { const distance = Math.hypot(to.x - from.x, to.y - from.y), steps = Math.max(1, Math.ceil(distance / Math.max(8, radius * .45))); let current = { ...from }; for (let index = 1; index <= steps; index++) { const target = { x: from.x + (to.x - from.x) * index / steps, y: from.y + (to.y - from.y) * index / steps }, next = resolveStep(state, current, target, radius, moverId); if (next.x === current.x && next.y === current.y) break; current = next; } return current; }

function roomIsSealed(state: GameState, roomId: string | undefined) { const stage = state.run.stage; return Boolean(stage && roomId && (stage.encounters.some((encounter) => encounter.roomId === roomId && encounter.kind === 'sealed' && encounter.status === 'active') || stage.boss.roomId === roomId && stage.boss.status === 'active')); }
export function resolveTeleportDestination(state: GameState, from: Vec2, target: Vec2, radius = 24, moverId?: string) {
  const stage = state.run.stage; if (!stage) return target; const dx = target.x - from.x, dy = target.y - from.y, distance = Math.hypot(dx, dy); if (distance < .001) return from; const direction = { x: dx / distance, y: dy / distance }, startRoom = roomAt(stage, from)?.id, startSealed = roomIsSealed(state, startRoom); let best = { ...from }, low = 0;
  for (let travelled = Math.min(8, distance); travelled <= distance; travelled += 8) { const point = { x: from.x + direction.x * travelled, y: from.y + direction.y * travelled }, roomId = roomAt(stage, point)?.id; if (startSealed && roomId !== startRoom || roomId !== startRoom && roomIsSealed(state, roomId) || !isWorldPositionWalkable(state, point, radius + 2, moverId)) break; best = point; low = travelled; }
  let high = Math.min(distance, low + 8); for (let index = 0; index < 7 && high > low; index++) { const middle = (low + high) / 2, point = { x: from.x + direction.x * middle, y: from.y + direction.y * middle }, roomId = roomAt(stage, point)?.id, allowed = !(startSealed && roomId !== startRoom) && !(roomId !== startRoom && roomIsSealed(state, roomId)) && isWorldPositionWalkable(state, point, radius + 2, moverId); if (allowed) { best = point; low = middle; } else high = middle; }
  return best;
}

export function canPlaceObstacle(state: GameState, position: Vec2, width: number, height: number, _ownerId: string) { const stage = state.run.stage; if (!stage) return true; const room = roomAt(stage, position, Math.max(width, height) / 2); if (!room) return false; const corners = [{ x: position.x - width / 2, y: position.y - height / 2 }, { x: position.x + width / 2, y: position.y - height / 2 }, { x: position.x - width / 2, y: position.y + height / 2 }, { x: position.x + width / 2, y: position.y + height / 2 }]; if (corners.some((corner) => !isWalkable(stage, corner, 8))) return false; if (Object.values(state.players).some((player) => player.alive && Math.abs(player.position.x - position.x) < width / 2 + 28 && Math.abs(player.position.y - position.y) < height / 2 + 28)) return false; return !movementObstacles(state).some((entity) => { const half = obstacleHalfSize(entity); return Math.abs(entity.position.x - position.x) < half.x + width / 2 && Math.abs(entity.position.y - position.y) < half.y + height / 2; }); }
