import { accept, defineGame, reject, type FlowReducerContext } from '@parti/flow';
import { bossStrategies, CONTENT_FINGERPRINT, pickupStrategies, platformStrategies } from '../content';
import { BOSS_TRIGGER_OFFSET, CHUNK_HEIGHT, SCHEMA_VERSION, WORLD_WIDTH, type ActiveEffect, type Enemy, type GameState, type PublicPlayer, type RuntimeContext, type RuntimeEffect } from './contracts';
import { canStartBoss } from './boss';
import { bossOrdinalForChunk, contextFor, findEntity, generateChunk, runtimeContext } from './generation';

const RESPAWN_MS = 4000, INVULNERABLE_MS = 2200;
type Ctx = FlowReducerContext<GameState>;
type LatestPose = { sequence: number; x: number; y: number; vy: number; cameraBottom: number; direction: number; persistedAt: number };
const latestPoses = new Map<string, LatestPose>();
const ok = <T>(payload: T) => accept(payload);

export const skywardGame = defineGame<GameState>({
  meta: { name: '云端远征 2', minPlayers: 1, maxPlayers: 4 }, initialState,
  lifecycle: {
    create(ctx) { latestPoses.clear(); ctx.state.hostId = ctx.host.id; },
    join(ctx, player) { ctx.state.hostId = ctx.host.id; if (ctx.state.phase !== 'lobby' && !ctx.state.players[player.id]) { ctx.kick(player.id, '远征已经开始'); return; } const current = ctx.state.players[player.id]; if (current) { current.connected = true; current.name = player.name; } else ctx.state.players[player.id] = createPlayer(player.id, player.name); },
    reconnect(ctx, player) { const current = ctx.state.players[player.id]; if (current) { current.connected = true; current.name = player.name; latestPoses.set(player.id, poseFrom(current, ctx.now())); } },
    leave(ctx, player) { const current = ctx.state.players[player.id]; if (!current) return; if (ctx.state.phase === 'lobby') delete ctx.state.players[player.id]; else { current.connected = false; current.direction = 0; updateVoid(ctx.state); checkWipe(ctx); } },
  },
  actions: {
    setReady: { sync: { mode: 'hostAuthoritative' }, validate(ctx, payload: any) { return ctx.state.phase === 'lobby' && ctx.state.players[ctx.actor.id] ? ok({ ready: Boolean(payload?.ready) }) : reject('not-in-lobby'); }, reduce(ctx, payload: any) { const player = ctx.state.players[ctx.actor.id]; player.ready = payload.ready; const all = Object.values(ctx.state.players); if (all.length && all.every((item) => item.ready && item.connected)) startRun(ctx); } },
    restart: { sync: { mode: 'hostAuthoritative' }, validate(ctx) { return ctx.state.phase === 'gameover' && ctx.actor.id === ctx.host.id ? ok(null) : reject('host-only'); }, reduce(ctx) { resetLobby(ctx.state); } },
    publishPose: { sync: { mode: 'hostRelay' }, validate(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id), sequence = Number(payload?.sequence), x = Number(payload?.x), y = Number(payload?.y), vy = Number(payload?.vy), cameraBottom = Number(payload?.cameraBottom), direction = Number(payload?.direction), previous = latestPoses.get(ctx.actor.id); if (!player?.alive || !Number.isInteger(sequence) || ![x, y, vy, cameraBottom, direction].every(Number.isFinite) || previous && sequence <= previous.sequence) return reject('invalid-pose'); return ok({ sequence, x: wrap(x), y, vy, cameraBottom, direction }); }, reduce(ctx, payload: any) { const now = ctx.now(), packet = { playerId: ctx.actor.id, sequence: payload.sequence, x: payload.x, y: payload.y, vy: payload.vy, direction: payload.direction, sentAt: now }; ctx.emit('skyward.pose', packet); const player = activePlayer(ctx.state, ctx.actor.id); if (!player) return; const previous = latestPoses.get(ctx.actor.id), pose = { ...payload, persistedAt: previous?.persistedAt ?? 0 }; latestPoses.set(ctx.actor.id, pose); if (now - pose.persistedAt >= 500) persistPose(ctx, player, pose, now); } },
    shoot: { sync: { mode: 'optimisticBroadcast' }, validate(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id), shotId = text(payload?.shotId, 96), x = Number(payload?.x), y = Number(payload?.y); if (!player?.alive || !shotId || !Number.isFinite(x) || !Number.isFinite(y)) return reject('invalid-shot'); return ok({ shotId, x, y, damage: effectActive(player, 'power', ctx.now()) ? 2 : 1, spread: effectActive(player, 'spread', ctx.now()), pierce: effectActive(player, 'pierce', ctx.now()) }); }, reduce(ctx, payload: any) { const player = ctx.state.players[ctx.actor.id], damage = payload.damage ?? (player && effectActive(player, 'power', ctx.now()) ? 2 : 1), spread = payload.spread ?? Boolean(player && effectActive(player, 'spread', ctx.now())), pierce = payload.pierce ?? Boolean(player && effectActive(player, 'pierce', ctx.now())); ctx.emit('skyward.shot', { ...payload, playerId: ctx.actor.id, damage, spread, pierce }); } },
    hitEnemy: { sync: { mode: 'hostRelay' }, validate(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id), sequence = Number(payload?.sequence), eventId = text(payload?.eventId, 120), enemyId = text(payload?.enemyId, 120), damage = Number(payload?.damage); if (!player?.alive || !eventId || !enemyId || !Number.isInteger(sequence) || sequence <= player.lastHitSequence || !Number.isFinite(damage)) return reject('invalid-hit'); return ok({ ...payload, eventId, enemyId, sequence, damage: Math.max(1, Math.min(3, Math.round(damage))) }); }, reduce(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id); if (!player) return; player.lastHitSequence = payload.sequence; damageEnemy(ctx, player, payload.enemyId, payload.damage); } },
    stompEnemy: { sync: { mode: 'hostRelay' }, validate(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id), sequence = Number(payload?.sequence), eventId = text(payload?.eventId, 120), enemyId = text(payload?.enemyId, 120), enemy = enemyById(ctx.state, enemyId); return player?.alive && eventId && Number.isInteger(sequence) && sequence > player.lastHitSequence && enemy?.stompable ? ok({ eventId, enemyId, sequence }) : reject('invalid-stomp'); }, reduce(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id); if (!player) return; player.lastHitSequence = payload.sequence; damageEnemy(ctx, player, payload.enemyId, 1); } },
    landPlatform: { sync: { mode: 'hostRelay' }, validate(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id), platformId = text(payload?.platformId, 120), sequence = Number(payload?.sequence), entity = findEntity(ctx.state.seed, ctx.state.startedPlayers.length, platformId); return player?.alive && platformId && Number.isInteger(sequence) && sequence > player.lastOutcomeSequence && entity && 'width' in entity ? ok({ platformId, sequence }) : reject('invalid-platform'); }, reduce(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id), entity = findEntity(ctx.state.seed, ctx.state.startedPlayers.length, payload.platformId); if (!player || !entity || !('width' in entity)) return; player.lastOutcomeSequence = payload.sequence; const now = ctx.now(), strategy = platformStrategies.require(entity.kind), runtime = runtimeFor(ctx.state, entity.id, now), transitioned = strategy.transition(entity, runtime, ctx.state.entities[entity.id]); if (transitioned) ctx.state.entities[entity.id] = transitioned; applyEffects(ctx, player, strategy.contact(entity, runtime, transitioned ?? undefined).effects); } },
    claimPickup: { sync: { mode: 'hostRelay' }, validate(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id), pickupId = text(payload?.pickupId, 120), sequence = Number(payload?.sequence), dynamic = ctx.state.entities[pickupId], generated = findEntity(ctx.state.seed, ctx.state.startedPlayers.length, pickupId), pickup = dynamic?.kind === 'pickup' && dynamic.pickup ? dynamic.pickup : generated && 'durationMs' in generated ? generated : null; return player?.alive && pickupId && Number.isInteger(sequence) && sequence > player.lastOutcomeSequence && !(dynamic?.kind === 'pickup' && dynamic.claimedBy) && pickup ? ok({ pickupId, sequence }) : reject('invalid-pickup'); }, reduce(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id), dynamic = ctx.state.entities[payload.pickupId], generated = findEntity(ctx.state.seed, ctx.state.startedPlayers.length, payload.pickupId), pickup = dynamic?.kind === 'pickup' && dynamic.pickup ? dynamic.pickup : generated && 'durationMs' in generated ? generated : null; if (!player || !pickup) return; player.lastOutcomeSequence = payload.sequence; const now = ctx.now(); ctx.state.entities[payload.pickupId] = { kind: 'pickup', pickup: dynamic?.kind === 'pickup' ? dynamic.pickup : undefined, claimedBy: player.id, claimedAt: now }; applyEffects(ctx, player, pickupStrategies.require(pickup.kind).claim(pickup, runtimeFor(ctx.state, payload.pickupId, now))); ctx.emit('skyward.pickup', { playerId: player.id, kind: pickup.kind }); } },
    playerOutcome: { sync: { mode: 'hostRelay' }, validate(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id), sequence = Number(payload?.sequence), eventId = text(payload?.eventId, 120), outcome = payload?.outcome; return player?.alive && eventId && Number.isInteger(sequence) && sequence > player.lastOutcomeSequence && (outcome === 'shield' || outcome === 'death') ? ok({ eventId, sequence, outcome, reason: text(payload?.reason, 40) || '危险' }) : reject('invalid-outcome'); }, reduce(ctx, payload: any) { const player = activePlayer(ctx.state, ctx.actor.id); if (!player) return; player.lastOutcomeSequence = payload.sequence; if (payload.outcome === 'shield' && player.effects.shield) { delete player.effects.shield; player.killStreak = 0; ctx.emit('skyward.outcome', { playerId: player.id, ...payload }); return; } kill(ctx, player.id, payload.reason); } },
    enableTilt: { sync: { mode: 'hostRelay' }, validate(_, payload: any) { return ok({ enabled: Boolean(payload?.enabled) }); }, reduce(ctx, payload: any) { const player = ctx.state.players[ctx.actor.id]; if (player) player.tilt = payload.enabled; } },
    'internal.respawn': { sync: { mode: 'hostAuthoritative' }, reduce(ctx, payload: any) { const player = ctx.state.players[payload.playerId]; if (!player || player.alive || ctx.state.phase !== 'running') return; player.alive = true; player.respawnAt = null; player.invulnerableUntil = ctx.now() + INVULNERABLE_MS; player.x = WORLD_WIDTH / 2; player.y = Math.max(ctx.state.teamVoidY + 180, player.cameraBottom + 180); player.vy = 760; player.positionEpoch += 1; } },
    'internal.bossTick': { sync: { mode: 'hostAuthoritative' }, reduce(ctx) { bossTick(ctx); } },
  },
});

export function initialState(): GameState { return { schemaVersion: SCHEMA_VERSION, contentFingerprint: CONTENT_FINGERPRINT, phase: 'lobby', hostId: null, seed: 0, startedAt: null, startedPlayers: [], players: {}, teamVoidY: 0, highestY: 0, completedBossCount: 0, entities: {}, boss: null, bestRun: { height: 0, bosses: 0, kills: 0, noDamageHeight: 0 }, message: '所有人准备后开始' }; }
function createPlayer(id: string, name: string): PublicPlayer { return { id, name, ready: false, connected: true, alive: true, respawnAt: null, invulnerableUntil: 0, x: WORLD_WIDTH / 2, y: 120, vy: 0, cameraBottom: 0, direction: 0, positionEpoch: 0, kills: 0, deaths: 0, shots: 0, killStreak: 0, noDamageHeight: 0, tilt: false, lastHitSequence: 0, lastOutcomeSequence: 0, effects: {} }; }
function poseFrom(player: PublicPlayer, now: number): LatestPose { return { sequence: -1, x: player.x, y: player.y, vy: player.vy, cameraBottom: player.cameraBottom, direction: player.direction, persistedAt: now }; }
function text(value: unknown, max: number) { return typeof value === 'string' ? value.slice(0, max) : ''; }
function wrap(x: number) { return (x % WORLD_WIDTH + WORLD_WIDTH) % WORLD_WIDTH; }
function activePlayer(state: GameState, id: string) { return state.phase === 'running' && state.startedPlayers.includes(id) ? state.players[id] : undefined; }
function startRun(ctx: Ctx) { const state = ctx.state; Object.assign(state, { phase: 'running', seed: Math.floor(ctx.random() * 0xffffffff) >>> 0, startedAt: ctx.now(), startedPlayers: Object.keys(state.players), teamVoidY: 0, highestY: 0, completedBossCount: 0, entities: {}, boss: null, message: '向上攀登' }); for (const player of Object.values(state.players)) { const epoch = player.positionEpoch + 1; Object.assign(player, createPlayer(player.id, player.name), { positionEpoch: epoch }); } ctx.emit('skyward.started', {}); }
function resetLobby(state: GameState) { for (const [id, player] of Object.entries(state.players)) { if (!player.connected) delete state.players[id]; else { const epoch = player.positionEpoch; Object.assign(player, createPlayer(id, player.name), { positionEpoch: epoch }); } } Object.assign(state, { phase: 'lobby', seed: 0, startedAt: null, startedPlayers: [], teamVoidY: 0, highestY: 0, completedBossCount: 0, entities: {}, boss: null, message: '所有人准备后开始' }); }
function runtimeFor(state: GameState, entityId: string, now: number): RuntimeContext { return runtimeContext(contextFor(state.seed, Number(entityId.split(':')[0]), Math.max(1, state.startedPlayers.length)), state.startedAt ?? now, now); }
function effectActive(player: PublicPlayer, id: keyof PublicPlayer['effects'], now: number) { const effect = player.effects[id]; return Boolean(effect && (effect.endsAt == null || effect.endsAt > now)); }
function applyEffects(ctx: Ctx, player: PublicPlayer, effects: RuntimeEffect[]) { for (const effect of effects) { if (effect.kind === 'entity-state') ctx.state.entities[effect.entityId] = effect.state; else if (effect.kind === 'apply-effect') applyEffect(player, effect.effect); else if (effect.kind === 'remove-effect') delete player.effects[effect.effectId]; else if (effect.kind === 'stat') { if (effect.stat === 'kills') player.kills += effect.amount; else player.noDamageHeight = Math.max(player.noDamageHeight, effect.amount); } else if (effect.kind === 'message') ctx.state.message = effect.text; else if (effect.kind === 'spawn-enemy') ctx.state.entities[effect.enemy.id] = { kind: 'summon', enemy: effect.enemy, hp: effect.enemy.hp, defeated: false, changedAt: ctx.now() }; else if (effect.kind === 'spawn-hazard') ctx.state.entities[`hazard:${effect.hazard.activeAt}:${Object.keys(ctx.state.entities).length}`] = effect.hazard; } }
function applyEffect(player: PublicPlayer, effect: ActiveEffect) { if (effect.id === 'rocket') delete player.effects.propeller; if (effect.id === 'propeller') delete player.effects.rocket; player.effects[effect.id] = { ...effect, stacks: 1 }; }
function updateVoid(state: GameState) { const alive = state.startedPlayers.map((id) => state.players[id]).filter((player) => player?.connected && player.alive); if (alive.length) state.teamVoidY = Math.max(state.teamVoidY, Math.min(...alive.map((player) => player.cameraBottom))); }
function kill(ctx: Ctx, id: string, reason: string) { const player = ctx.state.players[id]; if (!player?.alive || ctx.state.phase !== 'running') return; player.alive = false; player.deaths += 1; player.killStreak = 0; player.respawnAt = ctx.now() + RESPAWN_MS; player.vy = 0; ctx.emit('skyward.death', { playerId: id, reason }); if (!checkWipe(ctx)) ctx.timers.dispatch(`respawn:${id}`, RESPAWN_MS, 'internal.respawn', { playerId: id }, id); }
function checkWipe(ctx: Ctx) { if (ctx.state.startedPlayers.some((id) => ctx.state.players[id]?.connected && ctx.state.players[id].alive)) return false; const kills = Math.max(0, ...Object.values(ctx.state.players).map((player) => player.kills)), height = Math.max(0, ...Object.values(ctx.state.players).map((player) => player.noDamageHeight)); ctx.state.bestRun = { height: Math.max(ctx.state.bestRun.height, ctx.state.highestY), bosses: Math.max(ctx.state.bestRun.bosses, ctx.state.completedBossCount), kills: Math.max(ctx.state.bestRun.kills, kills), noDamageHeight: Math.max(ctx.state.bestRun.noDamageHeight, height) }; ctx.state.phase = 'gameover'; ctx.state.boss = null; ctx.state.message = '远征结束'; for (const id of ctx.state.startedPlayers) ctx.timers.clear(`respawn:${id}`); return true; }
function enemyById(state: GameState, id: string): Enemy | null { const dynamic = state.entities[id]; if (dynamic?.kind === 'summon') return dynamic.enemy; const entity = findEntity(state.seed, state.startedPlayers.length, id); return entity && 'hp' in entity ? entity : null; }
function damageEnemy(ctx: Ctx, player: PublicPlayer, id: string, damage: number) { const enemy = enemyById(ctx.state, id); if (!enemy || enemy.boss && ctx.state.boss?.enemyId !== id) return; if (ctx.state.boss?.enemyId === id) { const strategy = bossStrategies.require(ctx.state.boss.bossId), phase = strategy.phases.find((item) => ctx.state.boss!.hp / ctx.state.boss!.maxHp >= item.minHpRatio)!; const applied = strategy.id === 'mechanical-core' && !phase.weak && phase.id !== 'phase-3' ? Math.max(1, Math.floor(damage / 2)) : damage; ctx.state.boss.hp = Math.max(0, ctx.state.boss.hp - applied); if (!ctx.state.boss.hp) defeatBoss(ctx); return; } const current = ctx.state.entities[id], hp = (current?.kind === 'enemy' || current?.kind === 'summon' ? current.hp : enemy.hp) - damage; if (current?.kind === 'summon') ctx.state.entities[id] = { ...current, hp, defeated: hp <= 0, changedAt: ctx.now() }; else ctx.state.entities[id] = { kind: 'enemy', hp, defeated: hp <= 0, changedAt: ctx.now() }; if (hp <= 0) { player.kills += 1; player.killStreak += 1; spawnDrop(ctx.state, enemy, ctx.now()); ctx.emit('skyward.enemyDefeated', { enemyId: id, playerId: player.id }); } }
function spawnDrop(state: GameState, enemy: Enemy, now: number) { const runtime = runtimeFor(state, enemy.id, now), roll = runtime.rng(`drop:${enemy.id}`).float(); if (roll >= .35 || !enemy.drops.length) return; const total = enemy.drops.reduce((sum, item) => sum + item.weight, 0); let cursor = runtime.rng(`drop-kind:${enemy.id}`).float() * total, chosen = enemy.drops[0]!; for (const item of enemy.drops) { cursor -= item.weight; if (cursor <= 0) { chosen = item; break; } } const id = `${enemy.id}:drop`; state.entities[id] = { kind: 'pickup', pickup: { id, kind: chosen.pickup, x: enemy.x, y: enemy.y, durationMs: pickupStrategies.require(chosen.pickup).durationMs, sourceId: enemy.id } }; }
function startBoss(ctx: Ctx, chunkIndex: number) { if (!canStartBoss(ctx.state, chunkIndex)) return; const chunk = generateChunk(ctx.state.seed, chunkIndex, ctx.state.startedPlayers.length), enemy = chunk.enemies.find((item) => item.boss); if (!enemy) return; const now = ctx.now(); ctx.state.boss = { enemyId: enemy.id, bossId: enemy.kind as NonNullable<GameState['boss']>['bossId'], ordinal: bossOrdinalForChunk(chunkIndex), chunkIndex, hp: enemy.hp, maxHp: enemy.hp, phaseId: 'phase-1', startedAt: now, nextAttackAt: now + 3000, sequence: 0, attacks: [], summons: [] }; ctx.state.message = `${enemy.kind} 封锁了上行通路`; ctx.timers.dispatch('boss:tick', 200, 'internal.bossTick'); }
function bossTick(ctx: Ctx) { const boss = ctx.state.boss; if (!boss || ctx.state.phase !== 'running') return; const now = ctx.now(), strategy = bossStrategies.require(boss.bossId), generated = findEntity(ctx.state.seed, ctx.state.startedPlayers.length, boss.enemyId); if (!generated || !('hp' in generated)) return; boss.attacks = boss.attacks.filter((attack) => attack.endsAt > now); const ratio = boss.hp / boss.maxHp, phase = strategy.phases.find((item) => ratio >= item.minHpRatio) ?? strategy.phases.at(-1)!; boss.phaseId = phase.id; if (now >= boss.nextAttackAt) { const targets = ctx.state.startedPlayers.map((id) => ctx.state.players[id]).filter((player) => player?.connected && player.alive), target = targets[boss.sequence % Math.max(1, targets.length)], runtime = runtimeFor(ctx.state, boss.enemyId, now), attack = strategy.selectAttack(generated, runtime, phase, boss.sequence, target); if (attack.kind === 'platform-hazard' || attack.kind === 'platform-toggle' || attack.kind === 'slam') { const arena = generateChunk(ctx.state.seed, boss.chunkIndex, ctx.state.startedPlayers.length).platforms.filter((platform) => platform.kind !== 'boss-exit'); attack.platformId = arena[boss.sequence % arena.length]?.id; } boss.attacks.push(attack); if (attack.kind !== 'summon') ctx.state.entities[attack.id] = { kind: 'hazard', hazardKind: attack.kind, x: attack.x, y: attack.y, radius: attack.radius, activeAt: attack.activeAt, endsAt: attack.endsAt, platformId: attack.platformId, direction: attack.direction }; else { const summons = strategy.summons(generated, runtime, boss.sequence); boss.summons.push(...summons); for (const summon of summons) ctx.state.entities[summon.id] = { kind: 'summon', enemy: summon, hp: summon.hp, defeated: false, changedAt: now }; } boss.sequence += 1; boss.nextAttackAt = now + Math.round(4400 * phase.cooldownScale); } ctx.timers.dispatch('boss:tick', 200, 'internal.bossTick'); }
function defeatBoss(ctx: Ctx) { const boss = ctx.state.boss; if (!boss) return; ctx.timers.clear('boss:tick'); for (const summon of boss.summons) delete ctx.state.entities[summon.id]; ctx.state.completedBossCount = Math.max(ctx.state.completedBossCount, boss.ordinal); ctx.state.boss = null; ctx.state.message = '通路恢复，继续向上'; ctx.emit('skyward.bossDefeated', { chunkIndex: boss.chunkIndex, ordinal: boss.ordinal }); }
function persistPose(ctx: Ctx, player: PublicPlayer, pose: LatestPose, now: number) { player.x = pose.x; player.y = pose.y; player.vy = pose.vy; player.direction = pose.direction; player.cameraBottom = Math.max(player.cameraBottom, Math.min(pose.cameraBottom, pose.y - 140)); player.noDamageHeight = Math.max(player.noDamageHeight, pose.y); pose.persistedAt = now; ctx.state.highestY = Math.max(ctx.state.highestY, pose.y); for (const [id, effect] of Object.entries(player.effects)) if (effect?.endsAt != null && effect.endsAt <= now) delete player.effects[id as keyof PublicPlayer['effects']]; updateVoid(ctx.state); const below = Math.floor(ctx.state.teamVoidY / CHUNK_HEIGHT) - 2; for (const [id, value] of Object.entries(ctx.state.entities)) { const chunk = Number(id.split(':')[0]); if (value.kind === 'hazard' && value.endsAt <= now || Number.isInteger(chunk) && chunk < below) delete ctx.state.entities[id]; } const chunk = Math.floor(pose.y / CHUNK_HEIGHT), triggerY = chunk * CHUNK_HEIGHT + BOSS_TRIGGER_OFFSET; if (pose.y >= triggerY && !ctx.state.boss) { const allArrived = ctx.state.startedPlayers.map((id) => ctx.state.players[id]).filter((p) => p?.connected).every((p) => p!.y >= triggerY - 100); if (allArrived) startBoss(ctx, chunk); } }
