import { describe, expect, it } from 'vitest';
import { player, trainingMonster } from '../game/rules/state';
import { spawnSpellEntity } from '../game/rules/entities';
import { resolveSpell } from '../game/rules/spells';
import { initialState } from '../game/rules/state';
import { collisionCandidates, intersectsSource } from './collision';

describe('client collision candidates', () => {
  it('moves projectile from creation time', () => { const state = initialState(), caster = player('p1', 'one', 0); caster.cast.castId = 'p1:cast:1'; caster.cast.spell = resolveSpell(['fire', 'rock']); const source = spawnSpellEntity(state, caster, caster.cast.spell!, 1000); expect(intersectsSource(source, { position: { x: source.position.x + 430, y: source.position.y }, radius: 20 }, 2000)).toBe(true); });
  it('uses a forward cone for spray', () => { const state = initialState(), caster = player('p1', 'one', 0); caster.cast.castId = 'p1:cast:1'; caster.cast.aim = { x: 1, y: 0 }; caster.cast.spell = resolveSpell(['water']); const source = spawnSpellEntity(state, caster, caster.cast.spell!, 1000); expect(intersectsSource(source, { position: { x: caster.position.x + 120, y: caster.position.y }, radius: 10 }, 1000)).toBe(true); expect(intersectsSource(source, { position: { x: caster.position.x - 120, y: caster.position.y }, radius: 10 }, 1000)).toBe(false); });
  it('does not collide with its owner at spawn', () => { const state = initialState(), caster = state.players.p1 = player('p1', 'one', 0); caster.cast.castId = 'p1:cast:1'; caster.cast.spell = resolveSpell(['fire', 'rock']); const source = spawnSpellEntity(state, caster, caster.cast.spell!, 1000); expect(collisionCandidates(state, source, 1000)).toEqual([]); });
  it('sweeps the projectile path so fast shots cannot skip targets', () => { const state = initialState(), caster = state.players.p1 = player('p1', 'one', 0); caster.cast.castId = 'p1:cast:1'; caster.cast.spell = resolveSpell(['fire', 'rock']); const source = spawnSpellEntity(state, caster, caster.cast.spell!, 1000), monster = trainingMonster(0); monster.position = { x: 420, y: source.position.y }; state.entities[monster.id] = monster; expect(collisionCandidates(state, source, 2000, source.position).map((candidate) => candidate.target.id)).toEqual([monster.id]); });
  it('limits normal beams to the nearest target and lets walls stop healing beams', () => { const state = initialState(), caster = state.players.p1 = player('p1', 'one', 0), ally = state.players.p2 = player('p2', 'two', 1); caster.cast.castId = 'p1:cast:1'; caster.cast.aim = { x: 1, y: 0 }; caster.cast.spell = resolveSpell(['life']); const source = spawnSpellEntity(state, caster, caster.cast.spell, 1000); ally.position = { x: 500, y: caster.position.y }; const wall = spawnSpellEntity(state, { ...caster, cast: { ...caster.cast, castId: 'wall', spell: resolveSpell(['rock', 'rock', 'shield']), target: { x: 350, y: caster.position.y } } }, resolveSpell(['rock', 'rock', 'shield']), 1000); expect(collisionCandidates(state, source, 1000)).toMatchObject([{ target: { id: wall.id }, reason: 'blocked' }]); });
});
