import { createGameRuntime, createPartiSyncPlugin, PARTI_FLOW_REJECT_EVENT, type GameRuntime, type StateAdapter } from '@parti/flow';
import type { CastAimPayload, Element, GameEvent, GameState, HitRequestPayload, PartiApi, PosePayload, Vec2 } from '../game/contracts';
import { endwellGame } from '../game/definition';
import { positionAt } from '../game/rules/entities';
import { acceptRemoteFrame, needsHardCorrection, remotePosition, type RemoteMotion, type RemotePoseFrame } from './remoteMotion';

export type EndwellFlow = { game: GameRuntime; pose(payload: PosePayload): string; cast(sequence: number, elements: Element[], aim: Vec2, target: Vec2): { castId: string; actionId: string }; activate(castId: string): string; aim(payload: CastAimPayload): string; release(castId: string): string; hit(payload: HitRequestPayload): string; equip(itemId: string): void; unequip(itemId: string): void; drop(itemId: string): void; pickup(lootId: string): void; buy(merchantId: string, itemId: string): void; sell(merchantId: string, itemId: string): void; fuse(forgeId: string, itemIds: string[]): void; start(): void; finish(): void };
export type EndwellHandlers = { state(state: GameState): void; event(event: GameEvent): void; rejected?(actionId: string): void };

type PendingPrediction =
  | { kind: 'cast'; castId: string; sequence: number; createdAt: number }
  | { kind: 'activate' | 'release'; castId: string; sequence: number; createdAt: number }
  | { kind: 'hit'; hitId: string; targetId: string; createdAt: number }
  | { kind: 'equip' | 'unequip'; itemId: string; createdAt: number }
  | { kind: 'pickup'; lootId: string; createdAt: number };
const combatKeys = ['health', 'statuses', 'buildup', 'buffs', 'shields', 'cast', 'forceVelocity'] as const;

export function createEndwellFlowWhenReady(api: PartiApi, handlers: EndwellHandlers, ready: (flow: EndwellFlow) => void): () => void {
  let waiting = true, unsubscribe = () => {};
  const start = () => {
    if (!waiting || !api.playerId || api.getState() == null) return false;
    waiting = false;
    ready(createEndwellFlow(api, handlers));
    return true;
  };
  if (start()) return () => {};
  unsubscribe = api.onState(() => { if (start()) unsubscribe(); });
  return () => { waiting = false; unsubscribe(); };
}

export function createEndwellFlow(api: PartiApi, handlers: EndwellHandlers): EndwellFlow {
  let runtime: GameRuntime | null = null, presentedPhase: GameState['phase'] | undefined; const synced = new Set<string>(), motions = new Map<string, RemoteMotion>(), pending = new Map<string, PendingPrediction>();
  const playerId = api.playerId ?? 'pending';
  const reconcile = (incoming: unknown): GameState => { if (!incoming || typeof incoming !== 'object') return incoming as GameState; const state = structuredClone(incoming) as GameState, confirmed = structuredClone(incoming) as GameState, local = runtime?.state.get<GameState>(''), now = Date.now(); if (!local) return state;
    for (const [actionId, prediction] of pending) {
      if (now - prediction.createdAt > 8000) { pending.delete(actionId); continue; }
      if (prediction.kind === 'hit') { if (confirmed.seen.hits[prediction.hitId]) { pending.delete(actionId); continue; } const predictedPlayer = local.players[prediction.targetId], authorityPlayer = state.players[prediction.targetId], predictedEntity = local.entities[prediction.targetId], authorityEntity = state.entities[prediction.targetId]; if (predictedPlayer && authorityPlayer) { for (const key of combatKeys) if (key in predictedPlayer) (authorityPlayer as any)[key] = structuredClone((predictedPlayer as any)[key]); } else if (predictedEntity && authorityEntity) { for (const key of combatKeys) if (key in predictedEntity) (authorityEntity as any)[key] = structuredClone((predictedEntity as any)[key]); } else if (!predictedEntity && authorityEntity) delete state.entities[prediction.targetId]; state.seen.hits[prediction.hitId] = true; continue; }
      if (prediction.kind === 'equip' || prediction.kind === 'unequip' || prediction.kind === 'pickup') { const authoritative = confirmed.players[playerId], predicted = local.players[playerId], authority = state.players[playerId]; if (!authoritative || !predicted || !authority) { pending.delete(actionId); continue; } let confirmedAction = false; if (prediction.kind === 'pickup') confirmedAction = !confirmed.loot[prediction.lootId]; else { const equipped = Object.values(authoritative.equipment).some((item) => item?.id === prediction.itemId), inInventory = authoritative.inventory.some((item) => item.id === prediction.itemId); confirmedAction = prediction.kind === 'equip' ? equipped && !inInventory : !equipped && inInventory; } if (confirmedAction) { pending.delete(actionId); continue; } authority.inventory = structuredClone(predicted.inventory); authority.equipment = structuredClone(predicted.equipment); if (prediction.kind === 'pickup') delete state.loot[prediction.lootId]; continue; }
      if (prediction.kind !== 'cast' && prediction.kind !== 'activate' && prediction.kind !== 'release') continue;
      const authority = state.players[playerId], authoritative = confirmed.players[playerId], predicted = local.players[playerId]; if (!authority || !authoritative || !predicted) { pending.delete(actionId); continue; }
      if (prediction.kind === 'cast') { if (authoritative.lastCastSequence >= prediction.sequence) { pending.delete(actionId); continue; } authority.lastCastSequence = predicted.lastCastSequence; authority.cast = structuredClone(predicted.cast); continue; }
      const authoritativeFinished = authoritative.lastCastSequence >= prediction.sequence && (authoritative.cast.castId !== prediction.castId || prediction.kind === 'activate' && authoritative.cast.phase !== 'chanting' || prediction.kind === 'release' && authoritative.cast.phase !== 'chanting' && authoritative.cast.phase !== 'active');
      if (authoritativeFinished) { pending.delete(actionId); continue; }
      authority.cast = structuredClone(predicted.cast); authority.aim = { ...predicted.aim };
      for (const [id, entity] of Object.entries(local.entities)) if (entity.ownerId === playerId && id.startsWith(`${prediction.castId}:`)) state.entities[id] = structuredClone(entity);
      if (prediction.kind === 'release') for (const id of Object.keys(state.entities)) if (state.entities[id]?.ownerId === playerId && id.startsWith(`${prediction.castId}:`) && !state.entities[id]!.detached) delete state.entities[id];
    }
    return state;
  };
  const syncApi: PartiApi = { ...api, getState: () => reconcile(api.getState()), onState(handler) { return api.onState((state) => handler(reconcile(state))); }, onEvent(event, handler) { return api.onEvent(event, (payload) => { if (event === PARTI_FLOW_REJECT_EVENT) { const actionId = (payload as { actionId?: string } | null)?.actionId, prediction = actionId ? pending.get(actionId) : undefined; if (actionId) pending.delete(actionId); if (actionId && prediction?.kind === 'hit') handlers.rejected?.(actionId); } handler(payload); }); } };
  const adapter: StateAdapter = { get: () => undefined, set(path, value) { if (path !== '' || !runtime) return; const state = runtime.state.get<GameState>('') ?? value as GameState; const active = new Set<string>();
    for (const p of Object.values(state.players)) { active.add(p.id); if (!runtime.world.has(p.id)) runtime.world.spawn({ id: p.id, type: 'player', components: { Transform: p.position, Radius: 24, PlayerState: p, PositionEpoch: p.positionEpoch } }); else { const epoch = runtime.world.getComponent<number>(p.id, 'PositionEpoch') ?? -1, current = runtime.world.getComponent<Vec2>(p.id, 'Transform') ?? p.position; runtime.world.setComponent(p.id, 'PlayerState', p); if (epoch !== p.positionEpoch || p.id !== runtime.playerId && needsHardCorrection(current, p.position)) { runtime.world.setComponent(p.id, 'Transform', p.position); runtime.world.setComponent(p.id, 'PositionEpoch', p.positionEpoch); if (p.id !== runtime.playerId) { const frame: RemotePoseFrame = { playerId: p.id, sequence: p.lastPoseSequence, sentAt: Date.now(), position: p.position, aim: p.aim }; motions.set(p.id, acceptRemoteFrame(undefined, frame, performance.now())); } } } }
    for (const entity of Object.values(state.entities)) { active.add(entity.id); const position = positionAt(entity, Date.now()); if (!runtime.world.has(entity.id)) runtime.world.spawn({ id: entity.id, type: entity.kind, components: { Transform: position, RemoteTarget: position, Radius: entity.radius, EntityState: entity, Velocity: entity.velocity, Lifetime: entity.expiresAt } }); else { runtime.world.setComponent(entity.id, 'EntityState', entity); runtime.world.setComponent(entity.id, 'RemoteTarget', position); runtime.world.setComponent(entity.id, 'Velocity', entity.velocity); runtime.world.setComponent(entity.id, 'Lifetime', entity.expiresAt); } }
    for (const id of synced) if (!active.has(id) && runtime.world.has(id)) runtime.world.destroy(id); synced.clear(); for (const id of active) synced.add(id); handlers.state(structuredClone(state));
  } };
  const game = runtime = createGameRuntime(endwellGame, { role: 'client', playerId: api.playerId ?? 'pending', stateAdapter: adapter });
  const eventTypes = ['damage_applied', 'damage_immune', 'heal_applied', 'status_applied', 'reaction_triggered', 'cast_started', 'cast_interrupted', 'entity_spawned', 'entity_destroyed'] as const;
  for (const type of eventTypes) game.events.on<GameEvent>(`endwell.${type}`, handlers.event);
  game.events.on<RemotePoseFrame>('endwell.player_pose', (frame) => { if (frame.playerId === game.playerId) return; motions.set(frame.playerId, acceptRemoteFrame(motions.get(frame.playerId), frame, performance.now())); });
  game.use(createPartiSyncPlugin(syncApi));
  game.addSystem({ update(ctx) { const now = performance.now(), state = ctx.state.get<GameState>(''), phaseChanged = state?.phase !== presentedPhase; if (state) { for (const p of Object.values(state.players)) { if (!ctx.world.has(p.id)) ctx.world.spawn({ id: p.id, type: 'player', components: { Transform: p.position, Radius: 24, PlayerState: p, PositionEpoch: p.positionEpoch } }); const epoch = ctx.world.getComponent<number>(p.id, 'PositionEpoch') ?? -1; ctx.world.setComponent(p.id, 'PlayerState', p); if (phaseChanged || epoch !== p.positionEpoch) { ctx.world.setComponent(p.id, 'Transform', p.position); ctx.world.setComponent(p.id, 'PositionEpoch', p.positionEpoch); if (p.id !== ctx.playerId) { const frame: RemotePoseFrame = { playerId: p.id, sequence: p.lastPoseSequence, sentAt: Date.now(), position: p.position, aim: p.aim }; motions.set(p.id, acceptRemoteFrame(undefined, frame, now)); } } } presentedPhase = state.phase; } for (const [id, motion] of motions) if (ctx.world.has(id)) ctx.world.setComponent(id, 'Transform', remotePosition(motion, now)); } });
  const remember = (actionId: string, prediction: PendingPrediction) => { pending.set(actionId, prediction); return actionId; };
  return { game, pose: (payload) => game.action('player.pose', payload).id, cast: (sequence, elements, aim, target) => { const castId = `${game.playerId}:cast:${sequence}`, action = game.action('cast.request', { castId, sequence, elements, aim, target }); remember(action.id, { kind: 'cast', castId, sequence, createdAt: Date.now() }); return { castId, actionId: action.id }; }, activate: (castId) => { const sequence = Number(castId.split(':').at(-1)) || 0, action = game.action('cast.activate', { castId }); return remember(action.id, { kind: 'activate', castId, sequence, createdAt: Date.now() }); }, aim: (payload) => game.action('cast.aim', payload).id, release: (castId) => { const sequence = Number(castId.split(':').at(-1)) || 0, action = game.action('cast.release', { castId }); return remember(action.id, { kind: 'release', castId, sequence, createdAt: Date.now() }); }, hit: (payload) => { const action = game.action('combat.hit', payload); return remember(action.id, { kind: 'hit', hitId: payload.hitId, targetId: payload.targetId, createdAt: Date.now() }); }, equip: (itemId) => { const action = game.action('inventory.equip', { itemId }), p = game.state.get<GameState>('')?.players[playerId]; if (p && Object.values(p.equipment).some((item) => item?.id === itemId)) remember(action.id, { kind: 'equip', itemId, createdAt: Date.now() }); }, unequip: (itemId) => { const action = game.action('inventory.unequip', { itemId }), p = game.state.get<GameState>('')?.players[playerId]; if (p?.inventory.some((item) => item.id === itemId)) remember(action.id, { kind: 'unequip', itemId, createdAt: Date.now() }); }, drop: (itemId) => { game.action('inventory.drop', { itemId }); }, pickup: (lootId) => { const action = game.action('inventory.pickup', { lootId }), state = game.state.get<GameState>(''); if (state && !state.loot[lootId]) remember(action.id, { kind: 'pickup', lootId, createdAt: Date.now() }); }, buy: (merchantId, itemId) => { game.action('merchant.buy', { merchantId, itemId }); }, sell: (merchantId, itemId) => { game.action('merchant.sell', { merchantId, itemId }); }, fuse: (forgeId, itemIds) => { game.action('forge.fuse', { forgeId, itemIds }); }, start: () => { game.action('game.start', null); }, finish: () => { game.action('game.finish', null); } };
}
