import { describe, expect, it } from 'vitest';
import { createMonsterDeathEffect, createMonsterHitSnapshot, monsterDeathFinished, sampleMonsterDeathEffect, type MonsterHitSnapshot } from './monsterDeathEffect';
import { testMonster } from '../game/rules/state';

const snapshot = (damage: number, direction = { x: 1, y: 0 }): MonsterHitSnapshot => ({ monsterId: 'monster:test', position: { x: 100, y: 100 }, direction, damage, maxHealth: 100, radius: 25, element: 'fire', elite: false, boss: false, visual: 'chaser', flip: false });
describe('local monster death fragments', () => {
  it('is deterministic per seed and varies across seeds', () => { expect(createMonsterDeathEffect(snapshot(40), 7, 1000)).toEqual(createMonsterDeathEffect(snapshot(40), 7, 1000)); expect(createMonsterDeathEffect(snapshot(40), 8, 1000).fragments).not.toEqual(createMonsterDeathEffect(snapshot(40), 7, 1000).fragments); });
  it('biases fragments along the incoming hit direction', () => { const effect = createMonsterDeathEffect(snapshot(60, { x: 1, y: 0 }), 7, 0), averageX = effect.fragments.reduce((sum, fragment) => sum + fragment.velocity.x, 0) / effect.fragments.length; expect(averageX).toBeGreaterThan(80); });
  it('scales fragmentation with damage while respecting the cap', () => { const light = createMonsterDeathEffect(snapshot(15), 7, 0), heavy = createMonsterDeathEffect(snapshot(240), 7, 0), boss = createMonsterDeathEffect({ ...snapshot(500), boss: true, radius: 58 }, 7, 0); expect(heavy.fragments.length).toBeGreaterThan(light.fragments.length); expect(heavy.fragments.reduce((sum, fragment) => sum + Math.hypot(fragment.velocity.x, fragment.velocity.y), 0)).toBeGreaterThan(light.fragments.reduce((sum, fragment) => sum + Math.hypot(fragment.velocity.x, fragment.velocity.y), 0)); expect(boss.fragments.length).toBeLessThanOrEqual(20); });
  it('cuts fragments across the full original monster sprite instead of tiny central particles', () => { const effect = createMonsterDeathEffect(snapshot(40), 7, 0), xs = effect.fragments.map((fragment) => fragment.offset.x), ys = effect.fragments.map((fragment) => fragment.offset.y); expect(Math.max(...xs) - Math.min(...xs)).toBeGreaterThan(35); expect(Math.max(...ys) - Math.min(...ys)).toBeGreaterThan(30); expect(effect.fragments.reduce((sum, fragment) => sum + fragment.size * fragment.size * Math.PI, 0)).toBeGreaterThan(70 * 62 * .65); });
  it('flies and spins before settling on the floor, then stays still while fading', () => { const effect = createMonsterDeathEffect(snapshot(80), 7, 1000), fragment = effect.fragments[0]!, airborne = sampleMonsterDeathEffect(effect, 1000 + fragment.flightTime * 500)[0]!, landed = sampleMonsterDeathEffect(effect, 1000 + fragment.flightTime * 1000 + 20)[0]!, resting = sampleMonsterDeathEffect(effect, 1000 + fragment.flightTime * 1000 + 240)[0]!; expect(airborne.position).not.toEqual({ x: effect.position.x + fragment.offset.x, y: effect.position.y + fragment.offset.y }); expect(resting.position).toEqual(landed.position); expect(resting.rotation).toBe(landed.rotation); });
  it('shrinks and fades near completion, then reports finished', () => { const effect = createMonsterDeathEffect(snapshot(80), 7, 1000), middle = sampleMonsterDeathEffect(effect, 1000 + effect.duration * .5)[0]!, ending = sampleMonsterDeathEffect(effect, 1000 + effect.duration * .9)[0]!; expect(ending.alpha).toBeLessThan(middle.alpha); expect(ending.size).toBeLessThan(middle.size); expect(monsterDeathFinished(effect, 1000 + effect.duration - 1)).toBe(false); expect(monsterDeathFinished(effect, 1000 + effect.duration)).toBe(true); });
  it('builds directional snapshots with deterministic fallback jitter', () => { const monster = testMonster(0), event = { type: 'damage_applied', targetId: monster.id, amount: 30, element: 'fire', sourceId: 'source', largeImpact: false } as const, sourced = createMonsterHitSnapshot(monster, { x: -100, y: 0 }, { x: 0, y: 0 }, event), fallbackA = createMonsterHitSnapshot(monster, null, { x: 0, y: 0 }, event), fallbackB = createMonsterHitSnapshot(monster, null, { x: 0, y: 0 }, event); expect(sourced.direction.x).toBeCloseTo(1); expect(fallbackA.direction).toEqual(fallbackB.direction); expect(Math.hypot(fallbackA.direction.x, fallbackA.direction.y)).toBeCloseTo(1); });
});
