import type { BlockingSpec, DamageElement, Element, ElementStatusType, ElementVector, HitPayload, ShieldSpec, SpellSpec, SummonArchetype, TargetingSpec } from '../game/contracts';

export const ELEMENTS: readonly Element[] = ['rock', 'fire', 'ice', 'life', 'lightning', 'water', 'shield'];
const attachedTargeting: TargetingSpec = { canHitSelf: false, canHitAllies: false, canHitEnemies: true, canHitNeutral: true };
const projectileTargeting: TargetingSpec = { canHitSelf: false, canHitAllies: true, canHitEnemies: true, canHitNeutral: true };
const hostileAreaTargeting: TargetingSpec = { canHitSelf: true, canHitAllies: true, canHitEnemies: true, canHitNeutral: true };
const hostileFieldTargeting: TargetingSpec = hostileAreaTargeting;
const detachedTargeting: TargetingSpec = hostileAreaTargeting;
const allTargeting: TargetingSpec = { canHitSelf: true, canHitAllies: true, canHitEnemies: true, canHitNeutral: true };
const healingTargeting: TargetingSpec = { canHitSelf: false, canHitAllies: true, canHitEnemies: false, canHitNeutral: false, beneficial: true };
const fieldHealingTargeting: TargetingSpec = { ...healingTargeting, canHitSelf: true };
const attachedBlocking: BlockingSpec = { blockBySelf: false, blockByAllies: false, blockByEnemies: true, blockByNeutral: true, blockByWalls: false, blockBySummons: true };
const beamBlocking: BlockingSpec = { ...attachedBlocking, blockByWalls: true };
const detachedBlocking: BlockingSpec = { blockBySelf: false, blockByAllies: true, blockByEnemies: true, blockByNeutral: true, blockByWalls: true, blockBySummons: true };
const selfTargeting: TargetingSpec = { canHitSelf: true, canHitAllies: false, canHitEnemies: false, canHitNeutral: false, beneficial: true };
const noBlocking: BlockingSpec = { blockBySelf: false, blockByAllies: false, blockByEnemies: false, blockByNeutral: false, blockByWalls: false, blockBySummons: false };
const names: Record<Element, string> = { rock: '岩', fire: '火', ice: '冰', life: '生命', lightning: '雷', water: '水', shield: '盾' };

export function elementVector(elements: readonly Element[]): ElementVector { const vector = Object.fromEntries(ELEMENTS.map((element) => [element, 0])) as ElementVector; for (const element of elements) vector[element] += 1; return vector; }
function offensive(elements: readonly Element[]) { return elements.filter((element): element is Exclude<Element, 'life' | 'shield'> => element !== 'life' && element !== 'shield'); }
export function hitPayload(elements: readonly Element[], allowHeal = true): HitPayload { const vector = elementVector(elements), attack = offensive(elements), damage: Partial<Record<DamageElement, number>> = {}, statusBuildup: HitPayload['statusBuildup'] = {}, effects: NonNullable<HitPayload['effects']> = [];
  if (!attack.length && vector.life && allowHeal) return { heal: 12 * vector.life };
  if (vector.fire) { damage.fire = 8 * vector.fire; statusBuildup.burning = 30 * vector.fire; }
  if (vector.water) { damage.water = 5 * vector.water; statusBuildup.wet = 38 * vector.water; effects.push({ type: 'knockback', force: 120 + vector.water * 35 }); }
  if (vector.lightning) { damage.lightning = 7 * vector.lightning; statusBuildup.shocked = 28 * vector.lightning; effects.push({ type: 'interrupt', power: 18 + vector.lightning * 8 }); }
  if (vector.ice) { damage.ice = 6 * vector.ice; statusBuildup.chilled = 45 * vector.ice; }
  if (vector.rock) { damage.rock = 10 * vector.rock; damage.physical = 3 * vector.rock; effects.push({ type: 'knockback', force: 180 + vector.rock * 55 }); }
  return { damage, statusBuildup, effects };
}
function base(elements: Element[], delivery: SpellSpec['delivery'], values: Partial<SpellSpec>): SpellSpec { const count = elements.length; return { id: `${delivery}:${elements.join('-')}`, name: `${elements.map((element) => names[element]).join('·')}${{ spray: '喷射', beam: '射线', projectile: '弹', summon: '召唤', area: '陨石', environment: '降雨', shield: '护盾', instant: '秘术' }[delivery]}`, elements: [...elements], elementVector: elementVector(elements), delivery, payload: hitPayload(elements), chantMs: 160 + Math.max(0, count - 1) * 120, recoveryMs: 240 + count * 45, detached: false, channelled: false, lifetimeMs: 4000, range: 240, radius: 42, targeting: attachedTargeting, blocking: attachedBlocking, tags: ['spell', ...new Set(elements)], visualKey: `${delivery}.${elements.join('-')}`, ...values };
}
function payload(values: HitPayload): HitPayload { return values; }
const largeImpactTags = (elements: Element[]) => ['spell', 'large-impact', ...new Set(elements)];
function instantSpec(elements: Element[], id: string, name: string, instant: NonNullable<SpellSpec['instant']>, values: Partial<SpellSpec> = {}) { return base(elements, 'instant', { id, name, instant, payload: {}, detached: true, channelled: false, targeting: selfTargeting, blocking: noBlocking, range: 0, radius: instant.radius ?? 0, lifetimeMs: 0, chantMs: 420, recoveryMs: 300, visualKey: `instant.${id}`, ...values }); }
function specialShieldSpec(elements: Element[], id: string, name: string, shield: ShieldSpec, ward?: ElementStatusType) { return base(elements, 'shield', { id, name, payload: {}, shield, targeting: selfTargeting, blocking: noBlocking, range: 0, radius: 30, lifetimeMs: 9000, chantMs: 300, recoveryMs: 360, tags: ['spell', 'shield', ...(ward ? [ward] : []), ...new Set(elements)], visualKey: `shield.${id}` }); }
function fieldSpec(elements: Element[], id: string, name: string, archetype: NonNullable<SpellSpec['summon']>['archetype'], values: Partial<SpellSpec>) { return base(elements, 'summon', { id, name, detached: true, lifetimeMs: 6000, range: 460, radius: 120, summon: { archetype, positionMode: 'targetPoint' }, targeting: hostileFieldTargeting, blocking: detachedBlocking, chantMs: 520, recoveryMs: 450, visualKey: `summon.${archetype}`, ...values }); }
export function spraySpec(elements: Element[]) { return base(elements, 'spray', { channelled: true, lifetimeMs: 5000, range: 230 + elements.length * 15, radius: 54, coneAngle: Math.PI / 3, targeting: attachedTargeting, blocking: attachedBlocking }); }
export function beamSpec(elements: Element[]) { const healing = offensive(elements).length === 0, beamPayload = hitPayload(elements, true); if (elements.includes('water')) beamPayload.effects = [...(beamPayload.effects ?? []).filter((effect) => effect.type !== 'knockback'), { type: 'knockback', force: 80 }]; return base(elements, 'beam', { payload: beamPayload, channelled: true, lifetimeMs: 5000, range: 820, radius: 14, beam: { width: 14, tickInterval: 140, mode: 'normal', maxBounces: 0, turnSpeed: Math.PI * 1.5 }, targeting: healing ? healingTargeting : attachedTargeting, blocking: beamBlocking, chantMs: 260 + elements.length * 120 }); }
export function selfHealSpec(elements: Element[]) { return instantSpec(elements, 'self-heal', '生命治愈', { kind: 'selfHeal', amount: 20 }, { range: 0, radius: 0, targeting: healingTargeting, chantMs: 180, recoveryMs: 260 }); }
export function projectileSpec(elements: Element[]) { return base(elements, 'projectile', { detached: true, lifetimeMs: 2400, speed: 460, range: 920, radius: 16 + elements.length * 2, targeting: projectileTargeting, blocking: detachedBlocking, chantMs: 320 + elements.length * 110 }); }
function summonArchetype(elements: Element[]): SummonArchetype { const shaped = elements.slice(0, -1).filter((element) => element !== 'rock' && element !== 'shield').at(-1); if (shaped === 'ice') return 'ice-wall'; if (shaped === 'fire') return 'fire-field'; if (shaped === 'lightning') return 'lightning-field'; if (shaped === 'water') return 'water-pool'; if (shaped === 'life') return 'healing-field'; return 'rock-wall'; }
export function summonSpec(elements: Element[]) { const archetype = summonArchetype(elements), wall = archetype === 'rock-wall' || archetype === 'ice-wall', healing = archetype === 'healing-field'; return base(elements, 'summon', { payload: healing ? { heal: 10 + elements.length * 4 } : hitPayload(elements.filter((element) => element !== 'shield')), detached: true, lifetimeMs: wall ? 9000 : 6500, range: 430, radius: wall ? 44 : 105, summon: { archetype, positionMode: 'targetPoint' }, targeting: healing ? fieldHealingTargeting : hostileFieldTargeting, blocking: detachedBlocking, chantMs: 430 + elements.length * 120, visualKey: `summon.${archetype}` }); }
function shieldValues(elements: Element[]): ShieldSpec { const vector = elementVector(elements), absorbElements: ShieldSpec['absorbElements'] = { physical: .2 }; for (const element of ELEMENTS) if (vector[element] && element !== 'life' && element !== 'shield') absorbElements[element] = .8; if (Object.keys(absorbElements).length === 1) for (const element of ['fire', 'water', 'ice', 'lightning', 'rock'] as const) absorbElements[element] = .35; return { amount: 55 + elements.length * 20, absorbElements }; }
export function shieldSpec(elements: Element[]) { return base(elements, 'shield', { payload: {}, shield: shieldValues(elements), targeting: selfTargeting, blocking: noBlocking, range: 0, radius: 30, lifetimeMs: 10000, chantMs: 180 + elements.length * 70 }); }
export function meteorSpec(elements: Element[]) { return base(elements, 'area', { id: 'meteor', name: '陨石', payload: hitPayload(elements), detached: true, range: 720, radius: 125, lifetimeMs: 500, area: { warningMs: 700, impactDelay: 700 }, targeting: hostileAreaTargeting, blocking: noBlocking, chantMs: 850, recoveryMs: 650, tags: largeImpactTags(elements), visualKey: 'area.meteor' }); }
export function rainSpec(elements: Element[]) { return base(elements, 'environment', { id: 'rain', name: '全场降雨', payload: {}, detached: true, range: 0, radius: 0, lifetimeMs: 8000, environment: { kind: 'rain', duration: 8000, tickInterval: 500 }, targeting: selfTargeting, blocking: noBlocking, chantMs: 900, recoveryMs: 700, visualKey: 'environment.rain' }); }
export function resurrectSpec(elements: Element[]) { return instantSpec(elements, 'resurrect', '复活术', { kind: 'resurrect', radius: 150, amount: .25 }, { range: 520, radius: 150, targeting: healingTargeting, chantMs: 650, recoveryMs: 520 }); }
export function teleportSpec(elements: Element[]) { return instantSpec(elements, 'teleport', '瞬间移动', { kind: 'teleport' }, { range: 600, chantMs: 280, recoveryMs: 220 }); }
export function cleanseSpec(elements: Element[]) { return instantSpec(elements, 'cleanse', '消除术', { kind: 'cleanse', radius: 150 }, { range: 520, radius: 150, targeting: allTargeting, chantMs: 520, recoveryMs: 380 }); }
export function hasteSpec(elements: Element[]) { return instantSpec(elements, 'haste', '加速', { kind: 'haste', durationMs: 6000 }, { chantMs: 360, recoveryMs: 280 }); }
export function lifeSpringSpec(elements: Element[]) { return fieldSpec(elements, 'life-spring', '生命之泉', 'healing-field', { payload: payload({ heal: 35, statusBuildup: { wet: 100 } }), lifetimeMs: 700, radius: 130, targeting: fieldHealingTargeting, blocking: noBlocking, chantMs: 420, recoveryMs: 360 }); }
export function chainHealSpec(elements: Element[]) { return fieldSpec(elements, 'chain-heal', '连锁治疗', 'healing-field', { payload: payload({ heal: 32 }), lifetimeMs: 700, radius: 165, targeting: fieldHealingTargeting, blocking: noBlocking, chantMs: 520, recoveryMs: 420 }); }
export function rockShieldSpec(elements: Element[]) { return specialShieldSpec(elements, 'rock-shield', '岩石护盾', { amount: 95, absorbElements: { physical: .75, rock: .8, fire: .25, ice: .25, lightning: .25, water: .25 } }); }
export function fireShieldSpec(elements: Element[]) { return specialShieldSpec(elements, 'fire-shield', '火焰护盾', { amount: 75, absorbElements: { physical: .25, fire: .9, ice: .35 } }, 'fireWard'); }
export function frostShieldSpec(elements: Element[]) { return specialShieldSpec(elements, 'frost-shield', '寒冰护盾', { amount: 75, absorbElements: { physical: .25, ice: .9, fire: .2 } }, 'frostWard'); }
export function groundingShieldSpec(elements: Element[]) { return specialShieldSpec(elements, 'grounding-shield', '接地护盾', { amount: 75, absorbElements: { physical: .25, lightning: .9, water: .35 } }, 'grounded'); }
export function waterShieldSpec(elements: Element[]) { return specialShieldSpec(elements, 'water-shield', '流水护盾', { amount: 75, absorbElements: { physical: .25, water: .9, fire: .35 } }, 'waterWard'); }
export function lifeFlameSpec(elements: Element[]) { return base(elements, 'beam', { id: 'life-flame', name: '生命烈焰', payload: payload({ damage: { fire: 9 }, statusBuildup: { burning: 45 } }), channelled: true, lifetimeMs: 5000, range: 820, radius: 14, beam: { width: 14, tickInterval: 140, mode: 'normal' }, targeting: attachedTargeting, blocking: beamBlocking, chantMs: 420, recoveryMs: 360, visualKey: 'beam.life-flame' }); }
export function frostStreamSpec(elements: Element[]) { return base(elements, 'beam', { id: 'frost-stream', name: '冻结水流', payload: payload({ damage: { ice: 7, water: 2 }, statusBuildup: { wet: 45, chilled: 45 }, effects: [{ type: 'knockback', force: 70 }] }), channelled: true, lifetimeMs: 5000, range: 760, radius: 16, beam: { width: 16, tickInterval: 140, mode: 'normal' }, targeting: attachedTargeting, blocking: beamBlocking, chantMs: 420, recoveryMs: 360, visualKey: 'beam.frost-stream' }); }
export function lavaBoltSpec(elements: Element[]) { return base(elements, 'projectile', { id: 'lava-bolt', name: '熔岩弹', payload: payload({ damage: { rock: 34, fire: 26 }, statusBuildup: { burning: 70 }, effects: [{ type: 'knockback', force: 190 }] }), detached: true, lifetimeMs: 2400, speed: 430, range: 860, radius: 20, targeting: projectileTargeting, blocking: detachedBlocking, chantMs: 430, recoveryMs: 380, visualKey: 'projectile.lava-bolt' }); }
export function shatterIceBoltSpec(elements: Element[]) { return base(elements, 'projectile', { id: 'shatter-ice-bolt', name: '碎冰岩弹', payload: payload({ damage: { rock: 40, ice: 18 }, statusBuildup: { chilled: 70 }, effects: [{ type: 'knockback', force: 240 }] }), detached: true, lifetimeMs: 2400, speed: 480, range: 900, radius: 18, targeting: projectileTargeting, blocking: detachedBlocking, chantMs: 430, recoveryMs: 380, visualKey: 'projectile.shatter-ice-bolt' }); }
export function conductiveWaterSpec(elements: Element[]) { return base(elements, 'area', { id: 'conductive-water-chain', name: '导电水链', payload: payload({ damage: { lightning: 42, water: 4 }, statusBuildup: { wet: 100, shocked: 85 }, effects: [{ type: 'interrupt', power: 45 }] }), detached: true, range: 620, radius: 130, lifetimeMs: 350, area: { warningMs: 0, impactDelay: 0 }, targeting: detachedTargeting, blocking: noBlocking, chantMs: 500, recoveryMs: 430, visualKey: 'area.conductive-water-chain' }); }
export function flameJetSpec(elements: Element[]) { return base(elements, 'spray', { id: 'flame-jet', name: '烈焰喷射', payload: payload({ damage: { fire: 40 }, statusBuildup: { burning: 90 } }), channelled: true, lifetimeMs: 4200, range: 280, radius: 64, coneAngle: Math.PI * 70 / 180, targeting: attachedTargeting, blocking: attachedBlocking, chantMs: 320, recoveryMs: 320, visualKey: 'spray.flame-jet' }); }
export function iceLanceSpec(elements: Element[]) { return base(elements, 'projectile', { id: 'ice-lance', name: '寒冰长矛', payload: payload({ damage: { ice: 52 }, statusBuildup: { chilled: 90 } }), detached: true, lifetimeMs: 2600, speed: 620, range: 1050, radius: 12, targeting: projectileTargeting, blocking: detachedBlocking, chantMs: 520, recoveryMs: 460, tags: ['spell', 'ice', 'rock', 'pierce'], visualKey: 'projectile.ice-lance' }); }
export function tidalImpactSpec(elements: Element[]) { return fieldSpec(elements, 'tidal-impact', '潮汐冲击', 'water-pool', { payload: payload({ damage: { water: 30 }, statusBuildup: { wet: 100 }, effects: [{ type: 'knockback', force: 280 }] }), lifetimeMs: 4200, radius: 135, targeting: allTargeting, blocking: noBlocking, chantMs: 500, recoveryMs: 420 }); }
export function lightningStrikeSpec(elements: Element[]) { return fieldSpec(elements, 'lightning-strike', '雷击术', 'lightning-storm', { payload: payload({ damage: { lightning: 24 }, statusBuildup: { shocked: 60 }, effects: [{ type: 'interrupt', power: 35 }] }), lifetimeMs: 3000, radius: 145, targeting: detachedTargeting, blocking: noBlocking, chantMs: 760, recoveryMs: 520, tags: largeImpactTags(elements) }); }
export function blizzardSpec(elements: Element[]) { return base(elements, 'environment', { id: 'blizzard', name: '暴风雪', payload: {}, detached: true, range: 0, radius: 0, lifetimeMs: 10000, environment: { kind: 'blizzard', duration: 10000, tickInterval: 500 }, targeting: selfTargeting, blocking: noBlocking, chantMs: 900, recoveryMs: 700, visualKey: 'environment.blizzard' }); }
export function steamCloudSpec(elements: Element[]) { return fieldSpec(elements, 'steam-cloud', '蒸汽云', 'steam-cloud', { payload: payload({ damage: { fire: 18, water: 3 }, statusBuildup: { wet: 25 } }), lifetimeMs: 5500, radius: 125, targeting: detachedTargeting, blocking: noBlocking, chantMs: 420, recoveryMs: 360 }); }
export function magickaIceWallSpec(elements: Element[]) { return fieldSpec(elements, 'magicka-ice-wall', '冰墙', 'ice-wall', { payload: payload({ damage: { ice: 3 }, statusBuildup: { chilled: 55 } }), lifetimeMs: 6500, radius: 110, targeting: detachedTargeting, blocking: detachedBlocking, chantMs: 620, recoveryMs: 520 }); }
export function thunderstormSpec(elements: Element[]) { return fieldSpec(elements, 'thunderstorm', '雷暴领域', 'lightning-field', { payload: payload({ damage: { lightning: 12 }, statusBuildup: { shocked: 42 }, effects: [{ type: 'interrupt', power: 24 }] }), lifetimeMs: 6000, radius: 155, targeting: detachedTargeting, blocking: noBlocking, chantMs: 700, recoveryMs: 520 }); }
export function gravityWellSpec(elements: Element[]) { return fieldSpec(elements, 'gravity-well', '重力井', 'gravity-well', { payload: payload({ damage: { rock: 35 }, effects: [{ type: 'knockback', force: -120 }] }), lifetimeMs: 4200, radius: 170, targeting: detachedTargeting, blocking: noBlocking, chantMs: 720, recoveryMs: 560, tags: largeImpactTags(elements) }); }
export function fireRingSpec(elements: Element[]) { return fieldSpec(elements, 'fire-ring', '火焰环', 'fire-ring', { payload: payload({ damage: { fire: 8 }, statusBuildup: { burning: 40 } }), lifetimeMs: 5000, range: 0, radius: 135, summon: { archetype: 'fire-ring', positionMode: 'self' }, targeting: detachedTargeting, blocking: noBlocking, chantMs: 450, recoveryMs: 360 }); }
export function lifeBarrierSpec(elements: Element[]) { return fieldSpec(elements, 'life-barrier', '生命屏障', 'life-barrier', { payload: payload({ heal: 6 }), lifetimeMs: 6500, radius: 145, targeting: fieldHealingTargeting, blocking: noBlocking, chantMs: 650, recoveryMs: 500 }); }
export function supernovaSpec(elements: Element[]) { return instantSpec(elements, 'supernova', '超新星爆发', { kind: 'supernova', amount: .5 }, { chantMs: 650, recoveryMs: 700, targeting: allTargeting, tags: largeImpactTags(elements), visualKey: 'scroll.supernova' }); }
export function equilibriumSpec(elements: Element[]) { return instantSpec(elements, 'equilibrium', '均衡术', { kind: 'equilibrium', amount: .5 }, { chantMs: 650, recoveryMs: 650, targeting: allTargeting, visualKey: 'scroll.equilibrium' }); }
export function annihilationSpec(elements: Element[]) { return instantSpec(elements, 'annihilation', '湮灭术', { kind: 'annihilation', radius: 120, amount: .99 }, { range: 620, radius: 120, chantMs: 650, recoveryMs: 760, targeting: detachedTargeting, visualKey: 'scroll.annihilation' }); }
export function blackHoleSpec(elements: Element[]) { return fieldSpec(elements, 'black-hole', '黑洞', 'black-hole', { payload: payload({ damage: { pure: 8 }, effects: [{ type: 'knockback', force: -160 }] }), lifetimeMs: 8000, tickMs: 500, range: 680, radius: 340, targeting: allTargeting, blocking: noBlocking, chantMs: 650, recoveryMs: 760, tags: largeImpactTags(elements), visualKey: 'scroll.black-hole' }); }
