import type { BlockingSpec, DamageElement, Element, ElementVector, HitPayload, ShieldSpec, SpellSpec, SummonArchetype, TargetingSpec } from '../game/contracts';

export const ELEMENTS: readonly Element[] = ['rock', 'fire', 'ice', 'life', 'lightning', 'water', 'shield'];
const attachedTargeting: TargetingSpec = { canHitSelf: false, canHitAllies: false, canHitEnemies: true, canHitNeutral: true };
const detachedTargeting: TargetingSpec = { canHitSelf: false, canHitAllies: true, canHitEnemies: true, canHitNeutral: true };
const healingTargeting: TargetingSpec = { canHitSelf: false, canHitAllies: true, canHitEnemies: false, canHitNeutral: false, beneficial: true };
const fieldHealingTargeting: TargetingSpec = { ...healingTargeting, canHitSelf: true };
const attachedBlocking: BlockingSpec = { blockBySelf: false, blockByAllies: false, blockByEnemies: true, blockByNeutral: true, blockByWalls: false, blockBySummons: true };
const beamBlocking: BlockingSpec = { ...attachedBlocking, blockByWalls: true };
const detachedBlocking: BlockingSpec = { blockBySelf: false, blockByAllies: true, blockByEnemies: true, blockByNeutral: true, blockByWalls: true, blockBySummons: true };
const selfTargeting: TargetingSpec = { canHitSelf: true, canHitAllies: false, canHitEnemies: false, canHitNeutral: false, beneficial: true };
const noBlocking: BlockingSpec = { blockBySelf: false, blockByAllies: false, blockByEnemies: false, blockByNeutral: false, blockByWalls: false, blockBySummons: false };
const names: Record<Element, string> = { rock: '岩', fire: '火', ice: '冰', life: '生命', lightning: '雷', water: '水', shield: '盾' };

export function elementVector(elements: readonly Element[]): ElementVector { const vector = Object.fromEntries(ELEMENTS.map((element) => [element, 0])) as ElementVector; for (const element of elements) vector[element] += 1; return vector; }
function offensive(elements: readonly Element[]) { return elements.filter((element): element is Exclude<Element, 'life' | 'shield'> => element !== 'life' && element !== 'shield'); }
export function hitPayload(elements: readonly Element[], allowHeal = true): HitPayload { const vector = elementVector(elements), attack = offensive(elements), damage: Partial<Record<DamageElement, number>> = {}, statusBuildup: HitPayload['statusBuildup'] = {}, effects: NonNullable<HitPayload['effects']> = [];
  if (!attack.length && vector.life && allowHeal) return { heal: 12 * vector.life };
  if (vector.fire) { damage.fire = 8 * vector.fire; statusBuildup.burning = 30 * vector.fire; }
  if (vector.water) { damage.water = 5 * vector.water; statusBuildup.wet = 38 * vector.water; effects.push({ type: 'knockback', force: 80 + vector.water * 25 }); }
  if (vector.lightning) { damage.lightning = 7 * vector.lightning; statusBuildup.shocked = 28 * vector.lightning; effects.push({ type: 'interrupt', power: 18 + vector.lightning * 8 }); }
  if (vector.ice) { damage.ice = 6 * vector.ice; statusBuildup.chilled = 35 * vector.ice; }
  if (vector.rock) { damage.rock = 10 * vector.rock; damage.physical = 3 * vector.rock; effects.push({ type: 'knockback', force: 130 + vector.rock * 45 }); }
  return { damage, statusBuildup, effects };
}
function base(elements: Element[], delivery: SpellSpec['delivery'], values: Partial<SpellSpec>): SpellSpec { const count = elements.length; return { id: `${delivery}:${elements.join('-')}`, name: `${elements.map((element) => names[element]).join('·')}${{ spray: '喷射', beam: '射线', projectile: '弹', summon: '召唤', area: '陨石', environment: '降雨', shield: '护盾' }[delivery]}`, elements: [...elements], elementVector: elementVector(elements), delivery, payload: hitPayload(elements), chantMs: 160 + Math.max(0, count - 1) * 120, recoveryMs: 240 + count * 45, detached: false, channelled: false, lifetimeMs: 4000, range: 240, radius: 42, targeting: attachedTargeting, blocking: attachedBlocking, tags: ['spell', ...new Set(elements)], visualKey: `${delivery}.${elements.join('-')}`, ...values };
}
export function spraySpec(elements: Element[]) { return base(elements, 'spray', { channelled: true, lifetimeMs: 5000, range: 230 + elements.length * 15, radius: 54, coneAngle: Math.PI * .5, targeting: attachedTargeting, blocking: attachedBlocking }); }
export function beamSpec(elements: Element[]) { const healing = offensive(elements).length === 0; return base(elements, 'beam', { payload: hitPayload(elements, true), channelled: true, lifetimeMs: 5000, range: 820, radius: 14, beam: { width: 14, tickInterval: 140, mode: 'normal' }, targeting: healing ? healingTargeting : attachedTargeting, blocking: beamBlocking, chantMs: 260 + elements.length * 120 }); }
export function projectileSpec(elements: Element[]) { return base(elements, 'projectile', { detached: true, lifetimeMs: 2400, speed: 460, range: 920, radius: 16 + elements.length * 2, targeting: detachedTargeting, blocking: detachedBlocking, chantMs: 320 + elements.length * 110 }); }
function summonArchetype(elements: Element[]): SummonArchetype { const shaped = elements.slice(0, -1).filter((element) => element !== 'rock' && element !== 'shield').at(-1); if (shaped === 'ice') return 'ice-wall'; if (shaped === 'fire') return 'fire-field'; if (shaped === 'lightning') return 'lightning-field'; if (shaped === 'water') return 'water-pool'; if (shaped === 'life') return 'healing-field'; return 'rock-wall'; }
export function summonSpec(elements: Element[]) { const archetype = summonArchetype(elements), wall = archetype === 'rock-wall' || archetype === 'ice-wall', healing = archetype === 'healing-field'; return base(elements, 'summon', { payload: healing ? { heal: 10 + elements.length * 4 } : hitPayload(elements.filter((element) => element !== 'shield')), detached: true, lifetimeMs: wall ? 9000 : 6500, range: 430, radius: wall ? 44 : 105, summon: { archetype, positionMode: 'targetPoint' }, targeting: healing ? fieldHealingTargeting : detachedTargeting, blocking: detachedBlocking, chantMs: 430 + elements.length * 120, visualKey: `summon.${archetype}` }); }
function shieldValues(elements: Element[]): ShieldSpec { const vector = elementVector(elements), absorbElements: ShieldSpec['absorbElements'] = { physical: .2 }; for (const element of ELEMENTS) if (vector[element] && element !== 'life' && element !== 'shield') absorbElements[element] = .8; if (Object.keys(absorbElements).length === 1) for (const element of ['fire', 'water', 'ice', 'lightning', 'rock'] as const) absorbElements[element] = .35; return { amount: 55 + elements.length * 20, absorbElements }; }
export function shieldSpec(elements: Element[]) { return base(elements, 'shield', { payload: {}, shield: shieldValues(elements), targeting: selfTargeting, blocking: noBlocking, range: 0, radius: 30, lifetimeMs: 10000, chantMs: 180 + elements.length * 70 }); }
export function meteorSpec(elements: Element[]) { return base(elements, 'area', { id: 'meteor', name: '陨石', payload: hitPayload(elements), detached: true, range: 720, radius: 125, lifetimeMs: 500, area: { warningMs: 700, impactDelay: 700 }, targeting: detachedTargeting, blocking: noBlocking, chantMs: 850, recoveryMs: 650, visualKey: 'area.meteor' }); }
export function rainSpec(elements: Element[]) { return base(elements, 'environment', { id: 'rain', name: '全场降雨', payload: {}, detached: true, range: 0, radius: 0, lifetimeMs: 8000, environment: { kind: 'rain', duration: 8000, tickInterval: 500 }, targeting: selfTargeting, blocking: noBlocking, chantMs: 900, recoveryMs: 700, visualKey: 'environment.rain' }); }
