import type { GameState, Vec2 } from '../game/contracts';
import { roomAt } from '../game/roguelike';
import type { Rect } from './hud';

export type MinimapRoom = Rect & { id: string; current: boolean; boss: boolean };
export type MinimapLine = { from: Vec2; to: Vec2; frontier: boolean };
export type MinimapMarker = { kind: 'self' | 'ally' | 'objective' | 'merchant' | 'forge' | 'boss' | 'portal'; position: Vec2; state?: string };
export type MinimapModel = { rooms: MinimapRoom[]; lines: MinimapLine[]; markers: MinimapMarker[] };

export function buildMinimapModel(state: GameState, playerId: string, rect: Rect): MinimapModel {
  const stage = state.run.stage; if (!stage) return { rooms: [], lines: [], markers: [] }; const explored = new Set(state.run.exploredRoomIds), padding = 9, scale = Math.min((rect.w - padding * 2) / stage.world.width, (rect.h - padding * 2) / stage.world.height), ox = rect.x + (rect.w - stage.world.width * scale) / 2, oy = rect.y + (rect.h - stage.world.height * scale) / 2, point = (value: Vec2) => ({ x: ox + value.x * scale, y: oy + value.y * scale }), center = (id: string) => { const room = stage.world.rooms.find((candidate) => candidate.id === id)!; return point({ x: room.position.x + room.width / 2, y: room.position.y + room.height / 2 }); }, me = state.players[playerId], currentId = me ? roomAt(stage, me.position)?.id : undefined;
  const rooms = stage.world.rooms.filter((room) => explored.has(room.id)).map((room) => ({ id: room.id, x: ox + room.position.x * scale, y: oy + room.position.y * scale, w: Math.max(4, room.width * scale), h: Math.max(3, room.height * scale), current: room.id === currentId, boss: room.id === stage.boss.roomId }));
  const lines: MinimapLine[] = []; for (const room of stage.world.rooms.filter((candidate) => explored.has(candidate.id))) for (const next of room.connections) { if (explored.has(next)) { if (room.id < next) lines.push({ from: center(room.id), to: center(next), frontier: false }); } else { const from = center(room.id), hidden = stage.world.rooms.find((candidate) => candidate.id === next)! , hiddenCenter = { x: hidden.position.x + hidden.width / 2, y: hidden.position.y + hidden.height / 2 }, roomCenter = { x: room.position.x + room.width / 2, y: room.position.y + room.height / 2 }, dx = hiddenCenter.x - roomCenter.x, dy = hiddenCenter.y - roomCenter.y, scaleToEdge = Math.abs(dx) > Math.abs(dy) ? hidden.width / 2 / Math.abs(dx) : hidden.height / 2 / Math.abs(dy), entrance = point({ x: hiddenCenter.x - dx * scaleToEdge, y: hiddenCenter.y - dy * scaleToEdge }); lines.push({ from, to: entrance, frontier: true }); } }
  const markers: MinimapMarker[] = []; for (const player of Object.values(state.players)) { const room = roomAt(stage, player.position); if (!player.connected || !room || !explored.has(room.id)) continue; markers.push({ kind: player.id === playerId ? 'self' : 'ally', position: point(player.position), state: player.alive ? 'alive' : 'dead' }); }
  for (const objective of stage.objectives) if (explored.has(objective.roomId) && objective.status !== 'completed') markers.push({ kind: 'objective', position: center(objective.roomId), state: objective.kind });
  const located = (position: Vec2) => { const room = roomAt(stage, position); return room && explored.has(room.id); }; if (state.merchant && located(state.merchant.position)) markers.push({ kind: 'merchant', position: point(state.merchant.position) }); if (state.forge && located(state.forge.position)) markers.push({ kind: 'forge', position: point(state.forge.position) }); if (explored.has(stage.boss.roomId)) markers.push({ kind: 'boss', position: center(stage.boss.roomId), state: stage.boss.status }); if (state.run.portal?.active) markers.push({ kind: 'portal', position: point(state.run.portal.position) });
  return { rooms, lines, markers };
}
